Cpp/pathfinding/src/boost_graph.h File Reference
Header file for BoostGraph.
#include <boost/graph/graph_traits.hpp>
#include <boost/graph/adjacency_matrix.hpp>
#include <boost/graph/directed_graph.hpp>
#include <boost/graph/compressed_sparse_row_graph.hpp>
#include <boost/graph/adjacency_list.hpp>
Classes
struct std::hash< std::array< float, 3 > >
Template specialization of std::hash, using std::array<float, 3> as type.
struct HF::Pathfinding::Edge_Cost
Represents the weight of an edge within a graph, used by graph_t More...
struct HF::Pathfinding::vertex_data
Represents a vertex descriptor, used by graph_t More...
class HF::Pathfinding::BoostGraph
Holds the necessary state for the Boost pathfinding algorithm
Namespaces
 boost
 HF
Output CSR for interop with other languages
 HF::SpatialStructures
 HF::Pathfinding
Typedefs
using HF::Pathfinding::pair = std::pair< int, int >
Alias for std::pair<int, int>
typedef boost::compressed_sparse_row_graph< boost::directedS, vertex_data, Edge_Cost > HF::Pathfinding::graph_t
Alias for a graph type, a directed Compressed Sparse Row (CSR) graph See struct vertex_data and struct Edge_Cost
typedef boost::graph_traits< graph_t >::vertex_descriptor HF::Pathfinding::vertex_descriptor
Alias for a vertex_descriptor See graph_t
Functions
template<typename SizeT >
void std::array_hash_combine_impl (SizeT &seed, SizeT value)
Used to create a seed
Detailed Description
Header file for BoostGraph.
Author
TBA
Date
17 Jun 2020
Class Documentation
struct HF::Pathfinding::Edge_Cost
Represents the weight of an edge within a graph, used by graph_t
Definition at line 87 of file boost_graph.h.
Class Members
float
weight
weight/cost of an edge
struct HF::Pathfinding::vertex_data
Represents a vertex descriptor, used by graph_t
Definition at line 94 of file boost_graph.h.
Class Members
double
d
graph_traits< compressed_sparse_row_graph< directedS > >::vertex_descriptor
p
A vertex_descriptor for a directed Boost CSR graph.
Function Documentation
array_hash_combine_impl()
template<typename SizeT >
void std::array_hash_combine_impl (SizeT & seed, SizeT value) [inline]
Used to create a seed
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Definition at line 32 of file meshinfo.h.
References std::array_hash_combine_impl().
Referenced by std::array_hash_combine_impl(), and std::hash< std::array< float, 3 > >::operator()().