Cpp/objloader/src/meshinfo.h File Reference
Source file for MeshInfo.
#include <Dense>
#include <array>
Classes
struct std::hash< std::array< float, 3 > >
Template specialization of std::hash, using std::array<float, 3> as type.
class HF::Geometry::MeshInfo
Holds vertices and some other information about a specific mesh
Namespaces
 HF
Output CSR for interop with other languages
 HF::Geometry
Functions
template<typename SizeT >
void std::array_hash_combine_impl (SizeT &seed, SizeT value)
Used to create a seed
Detailed Description
Source file for MeshInfo.
Header file for MeshInfo.
Author
TBA
Date
16 Jun 2020
Function Documentation
array_hash_combine_impl()
template<typename SizeT >
void std::array_hash_combine_impl (SizeT & seed, SizeT value) [inline]
Used to create a seed
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Definition at line 32 of file meshinfo.h.
References std::array_hash_combine_impl().
Referenced by std::array_hash_combine_impl(), and std::hash< std::array< float, 3 > >::operator()().