Cpp/pathfinding/src/path_finder.cpp File Reference
Source file for BoostGraph, BoostGraphDeleter, as well as DistPred, and miscellaneous procedures.
#include <path_finder.h>
#include <vector>
#include <robin_hood.h>
#include <omp.h>
#include <thread>
#include <math.h>
#include <execution>
#include <memory>
#include <boost/graph/dijkstra_shortest_paths.hpp>
#include <boost/graph/breadth_first_search.hpp>
#include <boost/graph/dijkstra_shortest_paths_no_color_map.hpp>
#include <boost/exception/exception.hpp>
#include <boost_graph.h>
#include <path.h>
Classes
struct DistPred
Holds a distance and predecessor matrix for the boost pathfinding algorithm
Namespaces
 HF
Output CSR for interop with other languages
 HF::Pathfinding
Functions
Path ConstructShortestPathFromPred (int start, int end, const std::vector< size_t > &pred, const std::vector< float > &distances)
Construct the shortest path from start to end using the given predecessor and distance vectors
Path ConstructShortestPathFromPred (int start, int end, const DistPred &dist_pred)
DistPred BuildDistanceAndPredecessor (const graph_t &g, int id)
Build a row of the distance and predecessor matrices for the given node ID
Path HF::Pathfinding::FindPath (BoostGraph *bg, int start_id, int end_id)
Find a path between points A and B
vector< Path > HF::Pathfinding::FindPaths (BoostGraph *bg, const std::vector< int > &start_points, const std::vector< int > &end_points)
More efficient than calling FindPath manually. Organises paths by starting point, calculates only one predecessor matrix per unique starting point, then finds a path for every pair.
void HF::Pathfinding::InsertPathsIntoArray (const BoostGraph *bg, const std::vector< int > &start_points, const std::vector< int > &end_points, HF::SpatialStructures::Path **out_paths, HF::SpatialStructures::PathMember **out_path_members, int *out_sizes)
Runs Dijkstra's Shortest Path Algorithm on a (BoostGraph *) bg, and inserts the constructed paths into an array of (HF::SpatialStructures::Path *), as well as the PathMembers into an array of (HF::SpatialStructures::PathMember *).
std::unique_ptr< BoostGraph, BoostGraphDeleter > HF::Pathfinding::CreateBoostGraph (const HF::SpatialStructures::Graph &g)
Create a new boost graph from the given HFGraph
Parameters
g The desired Graph used to create a BoostGraph
Detailed Description
Source file for BoostGraph, BoostGraphDeleter, as well as DistPred, and miscellaneous procedures.
Author
TBA
Date
17 Jun 2020
Function Documentation
BuildDistanceAndPredecessor()
DistPred BuildDistanceAndPredecessor (const graph_t & g, int id) [inline]
Build a row of the distance and predecessor matrices for the given node ID
Definition at line 88 of file path_finder.cpp.
References DistPred::distance, and DistPred::predecessor.
Referenced by HF::Pathfinding::FindPath(), HF::Pathfinding::FindPaths(), and HF::Pathfinding::InsertPathsIntoArray().
ConstructShortestPathFromPred() [1/2]
Path ConstructShortestPathFromPred (int start, int end, const DistPred & dist_pred) [inline]
Definition at line 81 of file path_finder.cpp.
References ConstructShortestPathFromPred(), DistPred::distance, and DistPred::predecessor.
ConstructShortestPathFromPred() [2/2]
Path ConstructShortestPathFromPred (int start, int end, const std::vector< size_t > & pred, const std::vector< float > & distances) [inline]
Construct the shortest path from start to end using the given predecessor and distance vectors
Definition at line 51 of file path_finder.cpp.
References HF::SpatialStructures::Path::AddNode(), HF::SpatialStructures::Path::Reverse(), and HF::SpatialStructures::Path::size().
Referenced by ConstructShortestPathFromPred(), HF::Pathfinding::FindPath(), HF::Pathfinding::FindPaths(), and HF::Pathfinding::InsertPathsIntoArray().