Cpp/objloader/src/meshinfo.h File Reference
Contains definitions for the MeshInfo class.
#include <Dense>
#include <array>
Classes
struct std::hash< std::array< float, 3 > >
Template specialization of std::hash for using std::array<float, 3>.
class HF::Geometry::MeshInfo
A collection of vertices and indices representing geometry.
Namespaces
 HF
Output CSR for interop with other languages
 HF::Geometry
Manipulate and load geometry from disk.
Functions
template<typename SizeT >
void std::array_hash_combine_impl (SizeT &seed, SizeT value)
Combine the hash of value into seed.
Detailed Description
Contains definitions for the MeshInfo class.
Author
TBA
Date
16 Jun 2020
Function Documentation
array_hash_combine_impl()
template<typename SizeT >
void std::array_hash_combine_impl (SizeT & seed, SizeT value) [inline]
Combine the hash of value into seed.
Combine hashes for multiple floats.
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
// be sure to #include "meshinfo.h"
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Definition at line 32 of file meshinfo.h.
References std::array_hash_combine_impl().
Referenced by std::array_hash_combine_impl(), and std::hash< std::array< float, 3 > >::operator()().