RayTracer
Perform efficient ray intersections using Intel's Embree Library.
Classes
struct RayResult
The result of firing a ray at an object. Contains distance to the hitpoint and the ID of the mesh.
Functions
C_INTERFACE CreateRaytracer (std::vector< HF::Geometry::MeshInfo > *mesh, HF::RayTracer::EmbreeRayTracer **out_raytracer)
Create a new raytracer using several meshes.
C_INTERFACE DestroyRayTracer (HF::RayTracer::EmbreeRayTracer *rt_to_destroy)
Delete an existing raytracer.
C_INTERFACE FireRaysDistance (HF::RayTracer::EmbreeRayTracer *ert, float *origins, int num_origins, float *directions, int num_directions, std::vector< RayResult > **out_results, RayResult **results_data)
Fire rays for each node in origins/directions as ordered pairs and get distance back as a result.
C_INTERFACE FireSingleRayDistance (HF::RayTracer::EmbreeRayTracer *ert, const float *origin, const float *direction, const float max_distance, float *out_distance, int *out_meshid)
Fire a single ray and get the distance to its hit and the meshID if it hit anything. If it missed, then distance and meshid will both be -1.
C_INTERFACE FireRay (HF::RayTracer::EmbreeRayTracer *ert, float &x, float &y, float &z, float dx, float dy, float dz, float max_distance, bool &result)
Fire a single ray from the raytracer and recieve a point in return.
C_INTERFACE FireMultipleRays (HF::RayTracer::EmbreeRayTracer *ert, float *origins, const float *directions, int size, float max_distance, bool *result_array)
Fire multiple rays at once in parallel and recieve their hitpoints in return. The number of directions must be equal to the number of origins.
C_INTERFACE FireMultipleOriginsOneDirection (HF::RayTracer::EmbreeRayTracer *ert, float *origins, const float *direction, int size, float max_distance, bool *result_array)
Fire rays from each origin point in the given direction.
C_INTERFACE FireMultipleDirectionsOneOrigin (HF::RayTracer::EmbreeRayTracer *ert, const float *origin, float *directions, int size, float max_distance, bool *result_array)
Fire rays from a single origin point in multiple directions and get a the points where they intersected the geometry.
C_INTERFACE FireOcclusionRays (HF::RayTracer::EmbreeRayTracer *ert, const float *origins, const float *directions, int origin_size, int direction_size, float max_distance, bool *result_array)
Fire one or more occlusion rays in parallel.
C_INTERFACE DestroyRayResultVector (std::vector< RayResult > *analysis)
Destroy a vector of rayresults.
Detailed Description
Perform efficient ray intersections using Intel's Embree Library.
Function Documentation
CreateRaytracer()
C_INTERFACE CreateRaytracer (std::vector< HF::Geometry::MeshInfo > * mesh, HF::RayTracer::EmbreeRayTracer ** out_raytracer)
#include <Cinterface/raytracer_C.h>
Create a new raytracer using several meshes.
Parameters
mesh The meshes to add to raytracer's BVH.
out_raytracer Output parameter for the new raytracer.
Returns
HF_STATUS::MISSING_DEPEND if Embree's dll couldn't be found. HF_STATUS::GENERIC_ERROR if mesh is null.
Definition at line 15 of file raytracer_C.cpp.
References HF::Exceptions::GENERIC_ERROR, HF::Exceptions::MISSING_DEPEND, and HF::Exceptions::OK.
DestroyRayResultVector()
C_INTERFACE DestroyRayResultVector (std::vector< RayResult > * analysis)
#include <Cinterface/raytracer_C.h>
Destroy a vector of rayresults.
Parameters
analysis The ray results to destroy.
Definition at line 222 of file raytracer_C.cpp.
References DeleteRawPtr(), and HF::Exceptions::OK.
DestroyRayTracer()
C_INTERFACE DestroyRayTracer (HF::RayTracer::EmbreeRayTracer * rt_to_destroy)
#include <Cinterface/raytracer_C.h>
Delete an existing raytracer.
Parameters
rt_to_destroy Raytracer to destroy.
Returns
HF::OK on completion.
Definition at line 32 of file raytracer_C.cpp.
References HF::Exceptions::OK.
FireMultipleDirectionsOneOrigin()
C_INTERFACE FireMultipleDirectionsOneOrigin (HF::RayTracer::EmbreeRayTracer * ert, const float * origin, float * directions, int size, float max_distance, bool * result_array)
#include <Cinterface/raytracer_C.h>
Fire rays from a single origin point in multiple directions and get a the points where they intersected the geometry.
Parameters
ert A pointer to a valid embree raytracer.
origin An array of 3 floats representing the X, Y, and Z coordinates of the origin to fire from respectively.
directions A list of floats representing directions, with each 3 floats representing one direction. If a ray fired in a direction resulted in a hit, that directionwill be overwritten to the hitpoint.
size Number of points and directions, equal to the total number of floats in one array / 3
max_distance Maximum distance a ray can travel and still hit a target
result_array Output parameter conatining an ordered list of booleans set to true if the their rays hit, and false if their rays did not.
Definition at line 190 of file raytracer_C.cpp.
References ConvertRawFloatArrayToPoints(), HF::RayTracer::EmbreeRayTracer::FireRays(), and HF::Exceptions::OK.
FireMultipleOriginsOneDirection()
C_INTERFACE FireMultipleOriginsOneDirection (HF::RayTracer::EmbreeRayTracer * ert, float * origins, const float * direction, int size, float max_distance, bool * result_array)
#include <Cinterface/raytracer_C.h>
Fire rays from each origin point in the given direction.
Parameters
ert The raytracer to fire each ray from.
origins A list of floats representing origin points, with each 3 floats representing one point.
direction An array of 3 floats representing the X, Y, and Z coordinates respectively.
size Number of points and directions, equal to the total number of floats in one array / 3.
max_distance Maximum distance a ray can travel and still hit a target.
result_array Output parameter conatining an ordered list of booleans set to true if the their rays hit, and false if their rays did not.
Definition at line 168 of file raytracer_C.cpp.
References ConvertRawFloatArrayToPoints(), HF::RayTracer::EmbreeRayTracer::FireRays(), and HF::Exceptions::OK.
FireMultipleRays()
C_INTERFACE FireMultipleRays (HF::RayTracer::EmbreeRayTracer * ert, float * origins, const float * directions, int size, float max_distance, bool * result_array)
#include <Cinterface/raytracer_C.h>
Fire multiple rays at once in parallel and recieve their hitpoints in return. The number of directions must be equal to the number of origins.
Parameters
ert Raytracer to fire each ray from.
origins A list of floats representing origin points, with each 3 floats representing one point. If the ray fired from a point is successful, said point will be overwritten with the place it hit.
directions A list of floats representing ray directions, with each 3 floats representing one direction.
size Number of points and directions, equal to the total number of floats in one array / 3.
max_distance Maximum distance a ray can travel and still hit a target. Any hits beyond this point will not be recorded.
result_array Output parameter conatining an ordered list of booleans set to true if the their rays hit, and false if their rays did not.
Returns
HF_STATUS::OK on completion.
Definition at line 140 of file raytracer_C.cpp.
References ConvertRawFloatArrayToPoints(), HF::RayTracer::EmbreeRayTracer::FireRays(), and HF::Exceptions::OK.
FireOcclusionRays()
C_INTERFACE FireOcclusionRays (HF::RayTracer::EmbreeRayTracer * ert, const float * origins, const float * directions, int origin_size, int direction_size, float max_distance, bool * result_array)
#include <Cinterface/raytracer_C.h>
Fire one or more occlusion rays in parallel.
Parameters
ert A pointer to a valid embree raytracer
origins A list of floats representing origin points, with each 3 floats representing one point
directions a list of floats representing ray directions, with each 3 floats representing one direction
origin_size How many origins points are included are included. Note that a single origin point is 3 floats, so this should equal the length of the origin array/3. This must match direction_size or be equal to one.
direction_size How many directions are included. Note that a single direction is 3 floats, so this should equal the length of the origin array/3. This must match origin_size or be equal to one.
max_distance Maximum distance a ray can travel and still hit a target.
result_array Output array booleans
Occlusion rays are noticably faster than standard rays but are only capable of returning whether they hit something or not. This makes them good for line of sight checks.
Definition at line 212 of file raytracer_C.cpp.
References ConvertRawFloatArrayToPoints(), HF::RayTracer::EmbreeRayTracer::FireOcclusionRays(), and HF::Exceptions::OK.
FireRay()
C_INTERFACE FireRay (HF::RayTracer::EmbreeRayTracer * ert, float & x, float & y, float & z, float dx, float dy, float dz, float max_distance, bool & result)
#include <Cinterface/raytracer_C.h>
Fire a single ray from the raytracer and recieve a point in return.
Parameters
ert Raytracer to fire each ray from.
x x coordinate of the ray's origin. Will be set to the hit point's x coordinate if the ray something.
y y coordinate of the ray's origin. Will be set to the hit point's y coordinate if the ray something.
z z coordinate of the ray's origin. Will be set to the hit point's z coordinate if the ray something.
dx x coordinate of the ray's direction.
dy y coordinate of the ray's direction.
dz z coordinate of the ray's direction.
max_distance Maximum distance to record a hit within. Any hits beyond this distance will not be counted.
result Set to true if the ray hits, false otherwise
Returns
HF::OK on completion.
Definition at line 134 of file raytracer_C.cpp.
References HF::RayTracer::EmbreeRayTracer::FireRay(), and HF::Exceptions::OK.
FireRaysDistance()
C_INTERFACE FireRaysDistance (HF::RayTracer::EmbreeRayTracer * ert, float * origins, int num_origins, float * directions, int num_directions, std::vector< RayResult > ** out_results, RayResult ** results_data)
#include <Cinterface/raytracer_C.h>
Fire rays for each node in origins/directions as ordered pairs and get distance back as a result.
Parameters
ert The raytracer to use for firing every ray.
origins An array of origin points to fire rays from. Should be an array of floats with every 3 floats representing a new origin point.
num_origins The number of points in origins. NOTE: This should be equal to the length of origins/3, since every 3 floats in origins equals a single point.
directions An array of directions points to fire rays from. Should be an array of floats with every 3 floats representing a new direction.
num_directions The number of directions in directions. NOTE: This should be equal to the length of directions/3, since every 3 floats in directions equals a single direction.
out_results Output parameter for ray results.
results_data Output parameter for the data of the array held by out_results
Returns
HF_STATUS::OK on completion. HF::GENERICE_ERROR if the input parameters didn't meet atleast one of the required cases below.
Can be fired in 3 configurations:
<font color=`#2a2a2a`> Equal amount of directions/origins: Fire a ray for every pair of origin/direction in order. i.e. (origin[0], direction[0]), (origin[1], direction[1]). </font>
<font color=`#2a2a2a`> One direction, multiple origins: Fire a ray in the given direction from each origin point in origins. </font>
<font color=`#2a2a2a`> One origin, multiple directions: Fire a ray from the origin point in each direction in directions. </font>
Definition at line 52 of file raytracer_C.cpp.
References ConvertRawFloatArrayToPoints(), HF::RayTracer::EmbreeRayTracer::FireAnyRay(), HF::Exceptions::GENERIC_ERROR, and HF::Exceptions::OK.
FireSingleRayDistance()
C_INTERFACE FireSingleRayDistance (HF::RayTracer::EmbreeRayTracer * ert, const float * origin, const float * direction, const float max_distance, float * out_distance, int * out_meshid)
#include <Cinterface/raytracer_C.h>
Fire a single ray and get the distance to its hit and the meshID if it hit anything. If it missed, then distance and meshid will both be -1.
Parameters
ert The ray tracer to fire from.
origin The origin point to fire from.
direction The direction to fire the ray in.
max_distance Maximum distance to record a hit within. Any hits beyond this distance will not be counted.
out_distance Out parameter for Distance to the hitpoint. Will be set to -1 if the ray didn't hit anything.
out_meshid Out parameter for the ID of the hit mesh. Will be set to -1 if the ray didn't hit anything.
Returns
HF_STATUS::OK on success.
Definition at line 39 of file raytracer_C.cpp.
References HF::RayTracer::EmbreeRayTracer::FireAnyRay(), and HF::Exceptions::OK.