HF::SpatialStructures Namespace Reference
Classes
struct CSRPtrs
TODO summary
struct Edge
Indicates a connection between two nodes
struct EdgeSet
A collection of edges for a specific node More...
class Graph
A HF Graph similar to the one stored in python Invariants: 1) Always stores a valid graph 2) Every node added will be assigned a unique ID
struct IntEdge
Like an edge, but without the node attached since that isn't always relevant. More...
struct Node
A point in space with an ID
struct Path
A point in space with an ID
struct PathMember
Enumerations
enum STEP {
NOT_CONNECTED = 0,
NONE = 1,
UP = 2,
DOWN = 3,
OVER = 4
 }
Describes the type of step an edge connects to
enum COST_AGGREGATE : int { COST_AGGREGATE::SUM = 0,
COST_AGGREGATE::AVERAGE = 1,
COST_AGGREGATE::COUNT = 2
 }
TODO summary
enum NODE_TYPE { GRAPH = 0,
POI = 1,
OTHER = 2
 }
Functions
float roundhf (float f)
Round a float using std::round
void Aggregate (float &out_total, float new_value, const COST_AGGREGATE agg_type, int &count)
void Normalize (std::array< float, 3 > &vector)
Variables
constexpr float ROUNDING_PRECISION = 0.0001f
Class Documentation
struct HF::SpatialStructures::EdgeSet
A collection of edges for a specific node
Definition at line 67 of file Edge.h.
Class Members
vector< IntEdge >
children
vector of IntEdge (children)
int
parent
Identifier of parent node.
struct HF::SpatialStructures::IntEdge
Like an edge, but without the node attached since that isn't always relevant.
Definition at line 59 of file Edge.h.
Class Members
int
child
Identifier of child node.
float
weight
Weight of edge.
Enumeration Type Documentation
COST_AGGREGATE
enum HF::SpatialStructures::COST_AGGREGATE : int [strong]
TODO summary
Enumerator
SUM
AVERAGE
COUNT
Definition at line 29 of file graph.h.
NODE_TYPE
enum HF::SpatialStructures::NODE_TYPE
Enumerator
GRAPH
POI POI is 'point of interest'.
OTHER
Definition at line 19 of file node.h.
STEP
enum HF::SpatialStructures::STEP
Describes the type of step an edge connects to
Enumerator
NOT_CONNECTED
NONE
UP
DOWN
OVER
Definition at line 18 of file Edge.h.
Function Documentation
Aggregate()
void HF::SpatialStructures::Aggregate (float & out_total, float new_value, const COST_AGGREGATE agg_type, int & count) [inline]
Definition at line 91 of file graph.cpp.
Referenced by HF::SpatialStructures::Graph::AggregateGraph().
Normalize()
void HF::SpatialStructures::Normalize (std::array< float, 3 > & vector)
Definition at line 122 of file node.cpp.
Referenced by HF::SpatialStructures::Node::directionTo().
roundhf()
float HF::SpatialStructures::roundhf (float f)
Round a float using std::round
Parameters
f The desired float to round
Returns
A rounded floating-point value using std::round and ROUNDING_PRECISION
// be sure to #include "Constants.h"
// std::round from the cmath library is used in roundhf.
// Precision is to the nearest ten-thousandth
const float my_pi = 3.141592653589793238462643383279502884197169399375105820974944592307816406286;
float rounded = HF::SpatialStructures::roundhf(my_pi); // rounded == 3.1416
Definition at line 13 of file Constants.cpp.
References ROUNDING_PRECISION.
Referenced by HF::AnalysisMethods::GraphGeneratorPrivate::BuildNetwork(), and HF::AnalysisMethods::GraphGeneratorPrivate::GeneratePotentialChildren().
Variable Documentation
ROUNDING_PRECISION
constexpr float HF::SpatialStructures::ROUNDING_PRECISION = 0.0001f [constexpr]
Definition at line 14 of file Constants.h.
Referenced by HF::SpatialStructures::PathMember::operator==(), HF::SpatialStructures::Node::operator==(), and roundhf().