Cpp/spatialstructures/src/node.h File Reference
Header file for a node data structure, used in a graph ADT.
#include <array>
#include <ostream>
Classes
struct HF::SpatialStructures::Node
A point in space with an ID
struct std::hash< HF::SpatialStructures::Node >
Namespaces
 HF
Output CSR for interop with other languages
 HF::SpatialStructures
Macros
#define HF_NODE
Enumerations
enum HF::SpatialStructures::NODE_TYPE { HF::SpatialStructures::GRAPH = 0,
HF::SpatialStructures::POI = 1,
HF::SpatialStructures::OTHER = 2
 }
Functions
template<typename SizeT >
void std::hash_combine_impl (SizeT &seed, SizeT value) noexcept
ostream & std::operator<< (ostream &os, const HF::SpatialStructures::Node n)
ostream & std::operator<< (ostream &os, const std::array< float, 3 > n)
Detailed Description
Header file for a node data structure, used in a graph ADT.
Author
TBA
Date
06 Jun 2020
Macro Definition Documentation
HF_NODE
#define HF_NODE
Definition at line 12 of file node.h.
Function Documentation
hash_combine_impl()
template<typename SizeT >
void std::hash_combine_impl (SizeT & seed, SizeT value) [inline], [noexcept]
Definition at line 415 of file node.h.
References std::hash_combine_impl().
Referenced by std::hash_combine_impl(), and std::hash< HF::SpatialStructures::Node >::operator()().
operator<<() [1/2]
ostream& std::operator<< (ostream & os, const HF::SpatialStructures::Node n) [inline]
Definition at line 432 of file node.h.
References std::operator<<(), HF::SpatialStructures::Node::x, HF::SpatialStructures::Node::y, and HF::SpatialStructures::Node::z.
Referenced by std::operator<<().
operator<<() [2/2]
ostream& std::operator<< (ostream & os, const std::array< float, 3 > n) [inline]
Definition at line 437 of file node.h.
References std::operator<<().