Cpp/spatialstructures/src/CInterface.cpp File Reference
Contains implementation for the CInterface.
#include <spatialstructures_C.h>
#include <iostream>
#include <Constants.h>
#include <HFExceptions.h>
#include <graph.h>
#include <node.h>
#include <edge.h>
Functions
std::vector< std::array< float, 3 > > ConvertRawFloatArrayToPoints (const float *raw_array, int size)
Convert a raw array from an external caller to an organized vector of points
std::vector< std::array< int, 3 > > ConvertRawIntArrayToPoints (const int *raw_array, int size)
C_INTERFACE GetEdgesForNode (const Graph *graph, const Node *Node, vector< Edge > **out_vector_ptr, Edge **out_edge_list_ptr, int *out_edge_list_size)
C_INTERFACE GetSizeOfNodeVector (const std::vector< HF::SpatialStructures::Node > *node_list, int *out_size)
Get the size of a node vector.
C_INTERFACE GetSizeOfEdgeVector (const std::vector< HF::SpatialStructures::Edge > *edge_list, int *out_size)
C_INTERFACE DestroyNodes (std::vector< HF::SpatialStructures::Node > *nodelist_to_destroy)
Delete the vector of nodes at the given pointer.
C_INTERFACE DestroyEdges (std::vector< HF::SpatialStructures::Edge > *edgelist_to_destroy)
Delete the vector of edges at the given pointer.
C_INTERFACE DestroyGraph (HF::SpatialStructures::Graph *graph_to_destroy)
Delete a graph.
Detailed Description
Contains implementation for the CInterface.
Author
TBA
Date
06 Jun 2020
Function Documentation
ConvertRawFloatArrayToPoints()
std::vector<std::array<float, 3> > ConvertRawFloatArrayToPoints (const float * raw_array, int size)
Convert a raw array from an external caller to an organized vector of points
Parameters
raw_array Pointer to the external array
size The number of points stored in the raw array, equal to the total number of floats / 3
Returns
Definition at line 24 of file CInterface.cpp.
Referenced by CreateVisibilityGraphAllToAll(), CreateVisibilityGraphAllToAllUndirected(), CreateVisibilityGraphGroupToGroup(), FireMultipleDirectionsOneOrigin(), FireMultipleOriginsOneDirection(), FireMultipleRays(), FireOcclusionRays(), FireRaysDistance(), SphereicalViewAnalysisAggregateFlat(), and SphericalViewAnalysisNoAggregateFlat().
ConvertRawIntArrayToPoints()
std::vector<std::array<int, 3> > ConvertRawIntArrayToPoints (const int * raw_array, int size)
Definition at line 35 of file CInterface.cpp.
GetEdgesForNode()
C_INTERFACE GetEdgesForNode (const Graph * graph, const Node * Node, vector< Edge > ** out_vector_ptr, Edge ** out_edge_list_ptr, int * out_edge_list_size)
Definition at line 46 of file CInterface.cpp.
References HF::Exceptions::OK, and HF::Exceptions::OUT_OF_RANGE.