Cpp/pathfinding/src/boost_graph.h File Reference
Contains definitions for the BoostGraph class.
#include <boost/graph/graph_traits.hpp>
#include <boost/graph/adjacency_matrix.hpp>
#include <boost/graph/directed_graph.hpp>
#include <boost/graph/compressed_sparse_row_graph.hpp>
#include <boost/graph/adjacency_list.hpp>
Classes
struct std::hash< std::array< float, 3 > >
Template specialization of std::hash for using std::array<float, 3>.
struct HF::Pathfinding::Edge_Cost
Data stored for every edge in the BoostGraph. More...
struct HF::Pathfinding::vertex_data
Data stored for every vertex in the BoostGraph. More...
class HF::Pathfinding::BoostGraph
A graph usable with the BoostGraphLibrary.
Namespaces
 boost
The Boost C++ library. https://www.boost.org/.
 HF
Output CSR for interop with other languages
 HF::SpatialStructures
Contains standard fundamental data structures for representing space used throughout HumanFactors.
 HF::Pathfinding
Algorithms to find the shortest path between nodes in a HF::SpatialStructures::Graph.
Typedefs
typedef boost::compressed_sparse_row_graph< boost::directedS, vertex_data, Edge_Cost > HF::Pathfinding::graph_t
Type of graph held by the BoostGraph.
typedef boost::graph_traits< graph_t >::vertex_descriptor HF::Pathfinding::vertex_descriptor
Quick alias to shorten the typename of vertex descriptors for our graph_t type. /summary>
typedef std::pair< int, int > HF::Pathfinding::pair
Shorten std::pair to simplify graph construction.
Functions
template<typename SizeT >
void std::array_hash_combine_impl (SizeT &seed, SizeT value)
Combine the hash of value into seed.
Detailed Description
Contains definitions for the BoostGraph class.
Author
TBA
Date
17 Jun 2020
Class Documentation
struct HF::Pathfinding::Edge_Cost
Data stored for every edge in the BoostGraph.
Each edge in the graph only stores its weight as a float.
Definition at line 99 of file boost_graph.h.
Class Members
float
weight
Cost of traversing this edge.
struct HF::Pathfinding::vertex_data
Data stored for every vertex in the BoostGraph.
Every vertex stores in the graph stores it's index p and a unique double d.
Todo
Todo Is the double d needed?
Definition at line 111 of file boost_graph.h.
Class Members
double
d
Unknown may have been used for the colormap.
graph_traits< compressed_sparse_row_graph< directedS > >::vertex_descriptor
p
The index of a vertex in the CSR.
Function Documentation
array_hash_combine_impl()
template<typename SizeT >
void std::array_hash_combine_impl (SizeT & seed, SizeT value) [inline]
Combine the hash of value into seed.
Combine hashes for multiple floats.
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
// be sure to #include "meshinfo.h"
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Definition at line 32 of file meshinfo.h.
References std::array_hash_combine_impl().
Referenced by std::array_hash_combine_impl(), and std::hash< std::array< float, 3 > >::operator()().