HF::Pathfinding Namespace Reference
Classes
class BoostGraph
Holds the necessary state for the Boost pathfinding algorithm
struct BoostGraphDeleter
Forward declared to prevent clients from importing boost.
struct Edge_Cost
Represents the weight of an edge within a graph, used by graph_t More...
struct vertex_data
Represents a vertex descriptor, used by graph_t More...
Typedefs
using pair = std::pair< int, int >
Alias for std::pair<int, int>
typedef boost::compressed_sparse_row_graph< boost::directedS, vertex_data, Edge_Cost > graph_t
Alias for a graph type, a directed Compressed Sparse Row (CSR) graph See struct vertex_data and struct Edge_Cost
typedef boost::graph_traits< graph_t >::vertex_descriptor vertex_descriptor
Alias for a vertex_descriptor See graph_t
Functions
Path FindPath (BoostGraph *bg, int start_id, int end_id)
Find a path between points A and B
vector< Path > FindPaths (BoostGraph *bg, const std::vector< int > &start_points, const std::vector< int > &end_points)
More efficient than calling FindPath manually. Organises paths by starting point, calculates only one predecessor matrix per unique starting point, then finds a path for every pair.
void InsertPathsIntoArray (const BoostGraph *bg, const std::vector< int > &start_points, const std::vector< int > &end_points, HF::SpatialStructures::Path **out_paths, HF::SpatialStructures::PathMember **out_path_members, int *out_sizes)
Runs Dijkstra's Shortest Path Algorithm on a (BoostGraph *) bg, and inserts the constructed paths into an array of (HF::SpatialStructures::Path *), as well as the PathMembers into an array of (HF::SpatialStructures::PathMember *).
std::unique_ptr< BoostGraph, BoostGraphDeleter > CreateBoostGraph (const HF::SpatialStructures::Graph &g)
Create a new boost graph from the given HFGraph
Parameters
g The desired Graph used to create a BoostGraph
std::vector< HF::SpatialStructures::Path > FindAllPaths (BoostGraph *bg, int start_id, int end_id)
Find a path from every node to every node (NOTE: Not implemented yet.)
Class Documentation
struct HF::Pathfinding::Edge_Cost
Represents the weight of an edge within a graph, used by graph_t
Definition at line 87 of file boost_graph.h.
Class Members
float
weight
weight/cost of an edge
struct HF::Pathfinding::vertex_data
Represents a vertex descriptor, used by graph_t
Definition at line 94 of file boost_graph.h.
Class Members
double
d
graph_traits< compressed_sparse_row_graph< directedS > >::vertex_descriptor
p
A vertex_descriptor for a directed Boost CSR graph.
Typedef Documentation
graph_t
typedef boost::compressed_sparse_row_graph< boost::directedS, vertex_data, Edge_Cost > HF::Pathfinding::graph_t
Alias for a graph type, a directed Compressed Sparse Row (CSR) graph See struct vertex_data and struct Edge_Cost
Definition at line 109 of file boost_graph.h.
pair
typedef std::pair< int, int > HF::Pathfinding::pair
Alias for std::pair<int, int>
Definition at line 82 of file boost_graph.h.
vertex_descriptor
typedef boost::graph_traits< graph_t >::vertex_descriptor HF::Pathfinding::vertex_descriptor
Alias for a vertex_descriptor See graph_t
Definition at line 115 of file boost_graph.h.
Function Documentation
CreateBoostGraph()
std::unique_ptr< BoostGraph, BoostGraphDeleter > HF::Pathfinding::CreateBoostGraph (const HF::SpatialStructures::Graph & g)
Create a new boost graph from the given HFGraph
Parameters
g The desired Graph used to create a BoostGraph
Returns
A smart pointer (unique_ptr) of type BoostGraph, created from the HFGraph
We must first have a HF::SpatialStructures::Graph instance first.
using HF::SpatialStructures::Node; // for Node
using HF::SpatialStructures::Graph; // for Graph
// Create the nodes
Node node_0(12.0, 23.1, 34.2, 456);
Node node_1(45.3, 56.4, 67.5, 789);
Node node_2(55.5, 25.1, 85.2, 940);
   // Create a container (vector) of nodes
std::vector<Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
   std::vector<std::vector<int>> edges = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9 } };
std::vector<std::vector<float>> distances = { {12.0, 23.1, 45.2}, {67.3, 89.4, 98.5}, {76.6, 54.7, 32.8} };
   // Create a Graph - note that nodes, edges, and distances are passed by reference
Graph g(edges, distances, nodes);
// Now we can create a BoostGraph - note that Graph g is passed by reference
std::unique_ptr<BoostGraph, BoostGraphDeleter> boostGraph = CreateBoostGraph(g);
Definition at line 185 of file path_finder.cpp.
Referenced by CreatePath(), and CreatePaths().
FindAllPaths()
std::vector<HF::SpatialStructures::Path> HF::Pathfinding::FindAllPaths (BoostGraph * bg, int start_id, int end_id)
Find a path from every node to every node (NOTE: Not implemented yet.)
Parameters
bg A BoostGraph for the desired traversal
start_id Identifier for the starting node (start point)
end_id Identifier for the ending node (end point)
Returns
A std::vector of Path
using HF::SpatialStructures::Path; // for Path
using HF::SpatialStructures::Graph; // for Graph
   // Build a Graph g with the following edges, then compress g
Graph g;
g.addEdge(0, 1, 100);
g.addEdge(0, 2, 50);
g.addEdge(1, 3, 10);
g.addEdge(2, 3, 10);
g.Compress();
// Create a std::unique_ptr<BoostGraph, BoostGraphDeleter> from an HF::SpatialStructures::Graph g
   std::unique_ptr<BoostGraph, BoostGraphDeleter> boostGraph = CreateBoostGraph(g);
   
   // Prepare range of IDs
   int begin_id = 0;
int end_id = 3;
   // Use std::unique_ptr's get member function to retrieve a raw pointer
std::vector<Path> found_paths = FindAllPaths(boostGraph.get(), begin_id, end_id);
FindPath()
HF::SpatialStructures::Path HF::Pathfinding::FindPath (BoostGraph * bg, int start_id, int end_id)
Find a path between points A and B
Parameters
bg The boost graph containing edges/nodes
start_id ID of the starting node
end_id ID of the ending node
Returns
A Path constructed using Dijkstra's Shortest Path algorithm
// We must first have a HF::SpatialStructures::Graph instance first.
using HF::SpatialStructures::Node; // for Node
using HF::SpatialStructures::Graph; // for Graph
   using HF::SpatialStructures::Path; // for Path
// Create the nodes
Node node_0(12.0, 23.1, 34.2, 456);
Node node_1(45.3, 56.4, 67.5, 789);
Node node_2(55.5, 25.1, 85.2, 940);
   // Create a container (vector) of nodes
std::vector<Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
   std::vector<std::vector<int>> edges = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9 } };
std::vector<std::vector<float>> distances = { {12.0, 23.1, 45.2}, {67.3, 89.4, 98.5}, {76.6, 54.7, 32.8} };
   // Create a Graph - note that nodes, edges, and distances are passed by reference
Graph g(edges, distances, nodes);
// Now we can create a BoostGraph - note that Graph g is passed by reference
std::unique_ptr<BoostGraph, BoostGraphDeleter> boostGraph = CreateBoostGraph(g);
// Prepare the range of IDs (from Nodes)
int id_begin = node_0.id; // id_begin == 456
int id_end = node_2.id; // id_end == 940
   // Use the std::unique_ptr::get function to retrieve a raw pointer for FindPath
   Path found_path = FindPath(boostGraph.get(), id_begin, id_end);
Definition at line 102 of file path_finder.cpp.
References BuildDistanceAndPredecessor(), ConstructShortestPathFromPred(), and HF::Pathfinding::BoostGraph::g.
Referenced by CreatePath().
FindPaths()
std::vector< HF::SpatialStructures::Path > HF::Pathfinding::FindPaths (BoostGraph * bg, const std::vector< int > & start_points, const std::vector< int > & end_points)
More efficient than calling FindPath manually. Organises paths by starting point, calculates only one predecessor matrix per unique starting point, then finds a path for every pair.
Parameters
graph The boost graph containing edges/nodes
start_points Ordered list of starting points
end_points Ordered list of ending points
Returns
a std::vector of Path, constructed using Dijkstra's Shortest Path algorithm
using HF::SpatialStructures::Path; // for Path
using HF::SpatialStructures::Graph; // for Graph
   // Build a Graph g with the following edges, then compress g
Graph g;
g.addEdge(0, 1, 100);
g.addEdge(0, 2, 50);
g.addEdge(1, 3, 10);
g.addEdge(2, 3, 10);
g.Compress();
// Create a std::unique_ptr<BoostGraph, BoostGraphDeleter> from an HF::SpatialStructures::Graph g
   std::unique_ptr<BoostGraph, BoostGraphDeleter> boostGraph = CreateBoostGraph(g);
   
   // Create a vector of 100 int, initialized to value 0
   std::vector<int> start_vec(100, 0);
// Create a vector of 100 int, initialized to value 3
   std::vector<int> end_vec(100, 3);
   // Use std::unique_ptr's get member function to retrieve a raw pointer
std::vector<Path> found_paths = FindPaths(boostGraph.get(), start_vec, end_vec);
Definition at line 109 of file path_finder.cpp.
References BuildDistanceAndPredecessor(), ConstructShortestPathFromPred(), and HF::Pathfinding::BoostGraph::g.
InsertPathsIntoArray()
void HF::Pathfinding::InsertPathsIntoArray (const BoostGraph * bg, const std::vector< int > & start_points, const std::vector< int > & end_points, HF::SpatialStructures::Path ** out_paths, HF::SpatialStructures::PathMember ** out_path_members, int * out_sizes)
Runs Dijkstra's Shortest Path Algorithm on a (BoostGraph *) bg, and inserts the constructed paths into an array of (HF::SpatialStructures::Path *), as well as the PathMembers into an array of (HF::SpatialStructures::PathMember *).
Parameters
bg Address of a BoostGraph
start_points Vector of starting points
end_points Vector of ending points
out_paths Pointer to dynamically allocated array of HF::SpatialStructures::Path
out_path_members Pointer to dynamically allocated array of HF::SpatialStructures::PathMember
using HF::SpatialStructures::Path; // for Path
using HF::SpatialStructures::PathMember; // for PathMember
using HF::SpatialStructures::Graph; // for Graph
   // Build a Graph g with the following edges, then compress g
Graph g;
g.addEdge(0, 1, 100);
g.addEdge(0, 2, 50);
g.addEdge(1, 3, 10);
g.addEdge(2, 3, 10);
g.Compress();
// Create a std::unique_ptr<BoostGraph, BoostGraphDeleter> from an HF::SpatialStructures::Graph g
   std::unique_ptr<BoostGraph, BoostGraphDeleter> boostGraph = CreateBoostGraph(g);
   
   // Create a vector of 100 int, initialized to value 0
   std::vector<int> start_vec(100, 0);
// Create a vector of 100 int, initialized to value 3
   std::vector<int> end_vec(100, 3);
   // Create smart pointers to hold Paths, PathMembers, and the sizes
std::unique_ptr<Path[]> result_paths(new Path[MAX_SIZE]);
std::unique_ptr<PathMember[]> result_path_members(new PathMember[MAX_SIZE]);
std::unique_ptr<int[]> result_sizes(new int[MAX_SIZE]);
   // Retrieve raw pointers so their addresses can be passed to InsertPathsIntoArray
   Path* ppath = result_paths.get();
   PathMember* pmembers = result_path_members.get();
int* psizes = result_sizes.get();
   // Call InsertPathsIntoArray
   InsertPathsIntoArray(boostGraph.get(), start_vec, end_vec, &ppath, &pmembers, psizes);
// No need to call operator delete on result_paths, result_path_members, or result_sizes,
// as their memory resources are handled by std::unique_ptr
Definition at line 132 of file path_finder.cpp.
References BuildDistanceAndPredecessor(), ConstructShortestPathFromPred(), HF::Pathfinding::BoostGraph::g, HF::SpatialStructures::Path::GetPMPointer(), and HF::SpatialStructures::Path::size().
Referenced by CreatePaths().