HF::AnalysisMethods::VisibilityGraph Namespace Reference
Functions
bool HeightCheck (const Node &Node, float height, EmbreeRayTracer &ert)
std::vector< int > HeightCheckAllNodes (const std::vector< Node > &nodes_to_filter, float height, EmbreeRayTracer &ert)
bool IsOcclusionBetween (const Node &node_a, const Node &node_b, EmbreeRayTracer &ert, float height=1.7f, float pre_calculated_distance=0.0f)
Checks to see if there's an occlusion between two nodes at height level
Graph AllToAll (HF::RayTracer::EmbreeRayTracer &ert, const std::vector< HF::SpatialStructures::Node > &input_nodes, float height=1.7f)
All variations for generating the visibility graph
Graph GroupToGroup (HF::RayTracer::EmbreeRayTracer &ert, const std::vector< HF::SpatialStructures::Node > &from, const std::vector< HF::SpatialStructures::Node > &to, float height=1.7f)
Generate a visibility graph between every node in set a and every node in set b
Graph AllToAllUndirected (HF::RayTracer::EmbreeRayTracer &ert, const std::vector< HF::SpatialStructures::Node > &nodes, float height, int cores=-1)
Parallel AllToAll Algorithm for an undirected visibility graph
Function Documentation
AllToAll()
HF::SpatialStructures::Graph HF::AnalysisMethods::VisibilityGraph::AllToAll (HF::RayTracer::EmbreeRayTracer & ert, const std::vector< HF::SpatialStructures::Node > & input_nodes, float height = 1.7f)
All variations for generating the visibility graph
Generate a visibility graph between all nodes in input nodes
Parameters
ert reference to EmbreeRayTracer for the VisibilityGraph
input_nodes reference to vector of Node for VisibilityGraph
height Desired height for the VisibilityGraph
using HF::RayTracer::EmbreeRayTracer; // needed for EmbreeRayTracer
using HF::SpatialStructures::Node; // needed for Node
using HF::Geometry::LoadMeshObjects; // needed for LoadMeshObjects
using HF::Geometry::Graph; // needed for Graph
std::string plane_path = "plane.obj"; // path to an OBJ file for a flat plane
// Create an EmbreeRayTracer.
// Note that LoadMeshObjects has two more arguments after plane_path -
   // an enum HF::Geometry::GROUP_METHOD (defaults to GROUP_METHOD::ONLY_FILE)
// a bool (defaults to true, used to convert OBJ coordinate system to Rhino coordinates)
EmbreeRayTracer tracer(LoadMeshObjects(plane_path));
   std::vector<Node> node_vec; // Container of nodes
const int reserve_count = 100; // Pre-defined reserve size
node_vec.reserve(reserve_count); // Reserve reserve_count blocks for node_vec
// Construct reserve_count Node and insert each of them into node_vec
for (float i = -5.0; i < 5.0; i++) {
    // runs 10 times
    for (float j = -5; j < 5.0; j++) {
        // runs 10 times
        node_vec.emplace_back(Node(i, j, 0.0f)); // all Node ID default to -1
    }
}
   // AllToAll constructs and returns a Graph
// consisting of Node (from node_vec) that do not occlude each other
float desired_height = 2.0f; // Height of graph
Graph graph = AllToAll(tracer, node_vec, desired_height);
Definition at line 70 of file visibility_graph.cpp.
References HF::SpatialStructures::Node::distanceTo(), HeightCheckAllNodes(), and IsOcclusionBetween().
Referenced by CreateVisibilityGraphAllToAll().
AllToAllUndirected()
HF::SpatialStructures::Graph HF::AnalysisMethods::VisibilityGraph::AllToAllUndirected (HF::RayTracer::EmbreeRayTracer & ert, const std::vector< HF::SpatialStructures::Node > & nodes, float height, int cores = -1)
Parallel AllToAll Algorithm for an undirected visibility graph
Parameters
ert reference to EmbreeRayTracer for the VisibilityGraph
input_nodes reference to vector of Node for VisibilityGraph
height Desired height for the VisibilityGraph
cores Core count for the graph
using HF::RayTracer::EmbreeRayTracer; // needed for EmbreeRayTracer
using HF::SpatialStructures::Node; // needed for Node
using HF::Geometry::LoadMeshObjects; // needed for LoadMeshObjects
using HF::Geometry::Graph; // needed for Graph
std::string plane_path = "plane.obj"; // path to an OBJ file for a flat plane
// Create an EmbreeRayTracer.
// Note that LoadMeshObjects has two more arguments after plane_path -
   // an enum HF::Geometry::GROUP_METHOD (defaults to GROUP_METHOD::ONLY_FILE)
// a bool (defaults to true, used to convert OBJ coordinate system to Rhino coordinates)
EmbreeRayTracer tracer(LoadMeshObjects(plane_path));
   std::vector<Node> node_vec; // Container of nodes
const int reserve_count = 100; // Pre-defined reserve size
node_vec.reserve(reserve_count); // Reserve reserve_count blocks for node_vec
// Construct reserve_count Node and insert each of them into node_vec
for (float i = -5.0; i < 5.0; i++) {
    // runs 10 times
    for (float j = -5; j < 5.0; j++) {
        // runs 10 times
        node_vec.emplace_back(Node(i, j, 0.0f)); // all Node ID default to -1
    }
}
   // AllToAllUndirected constructs and returns a Graph
// consisting of Node (from node_vec) that do not occlude each other
float desired_height = 2.0f; // Height of graph
int core_count = 4; // For omp_set_num_threads(int num_threads), CPU core count
Graph graph = AllToAllUndirected(tracer, node_vec, desired_height, core_count);
Definition at line 150 of file visibility_graph.cpp.
References HF::SpatialStructures::Node::distanceTo(), HeightCheckAllNodes(), and IsOcclusionBetween().
Referenced by CreateVisibilityGraphAllToAllUndirected().
GroupToGroup()
HF::SpatialStructures::Graph HF::AnalysisMethods::VisibilityGraph::GroupToGroup (HF::RayTracer::EmbreeRayTracer & ert, const std::vector< HF::SpatialStructures::Node > & from, const std::vector< HF::SpatialStructures::Node > & to, float height = 1.7f)
Generate a visibility graph between every node in set a and every node in set b
Parameters
ert reference to EmbreeRayTracer for the VisibilityGraph
input_nodes reference to vector of Node for VisibilityGraph
height Desired height for the VisibilityGraph
using HF::RayTracer::EmbreeRayTracer; // needed for EmbreeRayTracer
using HF::SpatialStructures::Node; // needed for Node
using HF::Geometry::LoadMeshObjects; // needed for LoadMeshObjects
using HF::Geometry::Graph; // needed for Graph
std::string plane_path = "plane.obj"; // path to an OBJ file for a flat plane
// Create an EmbreeRayTracer.
// Note that LoadMeshObjects has two more arguments after plane_path -
   // an enum HF::Geometry::GROUP_METHOD (defaults to GROUP_METHOD::ONLY_FILE)
// a bool (defaults to true, used to convert OBJ coordinate system to Rhino coordinates)
EmbreeRayTracer tracer(LoadMeshObjects(plane_path));
   std::vector<Node> node_vec_0; // First container of Node
std::vector<Node> node_vec_1; // Second container of Node
const int reserve_count = 100; // Pre-defined reserve size
node_vec_0.reserve(reserve_count); // Reserve reserve_count blocks for both vectors
node_vec_1.reserve(reserve_count);
// 0) Construct reserve_count Node and insert each of them into node_vec_0
for (float i = -5.0; i < 5.0; i++) {
    // runs 10 times
    for (float j = -5.0; j < 5.0; j++) {
        // runs 10 times
        node_vec_0.emplace_back(Node(i, j, 0.0f)); // all Node ID default to -1
    }
}
// 1) Construct reserve_count Node and insert each of them into node_vec_1
for (float i = 0.0; i < 10.0; i++) {
    for (float j = 0.0; j < 10.0; j++) {
        node_vec_1.emplace_back(Node(i, j, 0.0f)); // all Node ID default to -1
    }
   // GroupToGroup constructs and returns a Graph consisting of Node
// (between node_vec_0 and node_vec_1) such that the nodes do not occlude each other
float desired_height = 2.0f; // Height of graph
Graph graph = GroupToGroup(tracer, node_vec_0, node_vec_1, desired_height);
Definition at line 107 of file visibility_graph.cpp.
References HF::SpatialStructures::Node::distanceTo(), HeightCheckAllNodes(), and IsOcclusionBetween().
Referenced by CreateVisibilityGraphGroupToGroup().
HeightCheck()
bool HF::AnalysisMethods::VisibilityGraph::HeightCheck (const Node & Node, float height, EmbreeRayTracer & ert) [inline]
Definition at line 27 of file visibility_graph.cpp.
References HF::RayTracer::EmbreeRayTracer::FireAnyOcclusionRay().
Referenced by HeightCheckAllNodes().
HeightCheckAllNodes()
std::vector<int> HF::AnalysisMethods::VisibilityGraph::HeightCheckAllNodes (const std::vector< Node > & nodes_to_filter, float height, EmbreeRayTracer & ert)
Definition at line 33 of file visibility_graph.cpp.
References HeightCheck().
Referenced by AllToAll(), AllToAllUndirected(), and GroupToGroup().
IsOcclusionBetween()
bool HF::AnalysisMethods::VisibilityGraph::IsOcclusionBetween (const Node & node_a, const Node & node_b, EmbreeRayTracer & ert, float height = 1.7f, float pre_calculated_distance = 0.0f) [inline]
Checks to see if there's an occlusion between two nodes at height level
Returns
True if there is an obstacle between nodes a and b, false otherwise
Definition at line 48 of file visibility_graph.cpp.
References HF::SpatialStructures::Node::directionTo(), HF::SpatialStructures::Node::distanceTo(), and HF::RayTracer::EmbreeRayTracer::FireAnyOcclusionRay().
Referenced by AllToAll(), AllToAllUndirected(), and GroupToGroup().