HF::Geometry Namespace Reference
Classes
class MeshInfo
Holds vertices and some other information about a specific mesh
Enumerations
enum GROUP_METHOD { ONLY_FILE = 0,
BY_GROUP = 1,
BY_MATERIAL = 2,
MATERIAL_AND_FILE = 3
 }
Functions
void IndexRawVertices (const std::vector< std::array< float, 3 >> &vertices, std::vector< int > &mapped_indexes, std::vector< float > &mapped_vertices)
float arrayDist (const std::array< float, 3 > from, const std::array< float, 3 > &to)
void IndexShape (const tinyobj::shape_t &shape, const std::vector< tinyobj::real_t > &verts, std::vector< int > out_indices, std::vector< float > out_vertexes)
Create an indexed array of vertices from a tinyobj::shape and list of verts
std::vector< MeshInfo > LoadMeshObjects (std::string path, GROUP_METHOD gm=ONLY_FILE, bool change_coords=true)
Load obj file into mesh info instances
std::vector< std::array< float, 3 > > LoadRawVertices (std::string path)
Load a list of vertices raw from the specified file.
Parameters
path The path for the desired file from which vertices will be loaded
std::vector< MeshInfo > LoadMeshObjects (std::vector< std::string > &path, GROUP_METHOD gm=ONLY_FILE, bool change_coords=true)
Load obj file into mesh info instances
Enumeration Type Documentation
GROUP_METHOD
enum HF::Geometry::GROUP_METHOD
Enumerator
ONLY_FILE
BY_GROUP
BY_MATERIAL
MATERIAL_AND_FILE
Definition at line 18 of file objloader.h.
Function Documentation
arrayDist()
float HF::Geometry::arrayDist (const std::array< float, 3 > from, const std::array< float, 3 > & to)
Definition at line 216 of file meshinfo.cpp.
Referenced by HF::Geometry::MeshInfo::operator==().
IndexRawVertices()
void HF::Geometry::IndexRawVertices (const std::vector< std::array< float, 3 >> & vertices, std::vector< int > & mapped_indexes, std::vector< float > & mapped_vertices)
Definition at line 41 of file meshinfo.cpp.
Referenced by HF::Geometry::MeshInfo::VectorsToBuffers().
IndexShape()
void HF::Geometry::IndexShape (const tinyobj::shape_t & shape, const std::vector< tinyobj::real_t > & verts, std::vector< int > out_indices, std::vector< float > out_vertexes)
Create an indexed array of vertices from a tinyobj::shape and list of verts
Parameters
shape Shape to index
verts Vertex array from tinyobjloader
out_indices Output array for indexes
out_vertexes Output array for vertices
Definition at line 28 of file objloader.cpp.
LoadMeshObjects() [1/2]
std::vector< MeshInfo > HF::Geometry::LoadMeshObjects (std::string path, GROUP_METHOD gm = ONLY_FILE, bool change_coords = true)
Load obj file into mesh info instances
Parameters
path The path to a valid OBJ file
gm How to divide the mesh into subobjects
change_coords Convert OBJ coordinate system to Rhino's coordinates
Returns
A vector of meshinfo from the given file
Exceptions
HF::Exceptions::InvalidOBJ Thrown if the obj at path fails to load
std::string file_path = "directory/filename.obj";
// if file_path is not a path to a valid OBJ file, HF::Exceptions::FileNotFound is thrown
std::vector<MeshInfo> meshvec = Geometry::LoadMeshObjects(file_path, GROUP_METHOD::BY_MATERIAL, false);
// meshvec is a vector of meshinfo from file_path
Definition at line 68 of file objloader.cpp.
References BY_GROUP, BY_MATERIAL, and ONLY_FILE.
Referenced by LoadMeshObjects(), and LoadOBJ().
LoadMeshObjects() [2/2]
std::vector< MeshInfo > HF::Geometry::LoadMeshObjects (std::vector< std::string > & path, GROUP_METHOD gm = ONLY_FILE, bool change_coords = true)
Load obj file into mesh info instances
Parameters
path The path to a valid OBJ file
gm How to divide the mesh into subobjects
change_coords Convert OBJ coordinate system to Rhino's coordinates
Returns
A vector of meshinfo from the given file
Exceptions
HF::Exceptions::InvalidOBJ Thrown if the obj at path fails to load
std::vector<std::string> pathvec = { PATH_0, PATH_1, PATH_2 };
// PATH_0, PATH_1, and PATH_2 each represent a path to an OBJ file.
// Note that if any path in pathvec is invalid, HF::Exceptions::FileNotFound will be thrown
// when LoadMeshObjects is called
std::vector<MeshInfo> meshvec = Geometry::LoadMeshObjects(pathvec, GROUP_METHOD::MATERIAL_AND_FILE, false);
// The overload for LoadMeshObjects is called for each member (which is an OBJ file path) in pathvec,
// then IDs are reassigned for each MeshInfo object within the std::vector<MeshInfo> that is returned
Definition at line 245 of file objloader.cpp.
References LoadMeshObjects().
LoadRawVertices()
std::vector< std::array< float, 3 > > HF::Geometry::LoadRawVertices (std::string path)
Load a list of vertices raw from the specified file.
Parameters
path The path for the desired file from which vertices will be loaded
Returns
a vector of array (type float, size 3) that represents the vertices from the file specified at path
std::string filepath = PATH_TO_FILE;
// Note that filepath must lead to a valid OBJ file, or
// HF::Exceptions::InvalidOBJ will be thrown when Geometry::LoadMeshObjects is called
std::vector<std::array<float, 3>> vertices = Geometry::LoadRawVertices(filepath);
// vertices now contains the raw vertices loaded from the OBJ file specified at filepath
Definition at line 214 of file objloader.cpp.