Cinterface/cinterface_utils.h File Reference
#include <vector>
#include <array>
Macros
#define C_INTERFACE extern `C` __declspec(dllexport) int
Functions
std::vector< std::array< float, 3 > > ConvertRawFloatArrayToPoints (const float *raw_array, int size)
Convert a raw array from an external caller to an organized vector of points
std::vector< std::array< int, 3 > > ConvertRawIntArrayToPoints (const int *raw_array, int size)
C_INTERFACE DestroyFloatVector (std::vector< float > *float_vector)
Delete a float vector that's pointed to by float_vector
template<typename T >
void DeleteRawPtr (T *ptr)
Delete some object pointed to by ptr
Macro Definition Documentation
C_INTERFACE
#define C_INTERFACE extern `C` __declspec(dllexport) int
Definition at line 7 of file cinterface_utils.h.
Function Documentation
ConvertRawFloatArrayToPoints()
std::vector<std::array<float, 3> > ConvertRawFloatArrayToPoints (const float * raw_array, int size)
Convert a raw array from an external caller to an organized vector of points
Parameters
raw_array Pointer to the external array
size The number of points stored in the raw array, equal to the total number of floats / 3
Returns
A list of points
Parameters
raw_array Pointer to the external array
size The number of points stored in the raw array, equal to the total number of floats / 3
Returns
Definition at line 24 of file CInterface.cpp.
Referenced by CreateVisibilityGraphAllToAll(), CreateVisibilityGraphAllToAllUndirected(), CreateVisibilityGraphGroupToGroup(), FireMultipleDirectionsOneOrigin(), FireMultipleOriginsOneDirection(), FireMultipleRays(), FireOcclusionRays(), FireRaysDistance(), SphereicalViewAnalysisAggregateFlat(), and SphericalViewAnalysisNoAggregateFlat().
ConvertRawIntArrayToPoints()
std::vector<std::array<int, 3> > ConvertRawIntArrayToPoints (const int * raw_array, int size)
Definition at line 35 of file CInterface.cpp.
DeleteRawPtr()
template<typename T >
void DeleteRawPtr (T * ptr)
Delete some object pointed to by ptr
Definition at line 25 of file cinterface_utils.h.
Referenced by DestroyFloatVector(), DestroyPath(), and DestroyRayResultVector().
DestroyFloatVector()
C_INTERFACE DestroyFloatVector (std::vector< float > * float_vector)
Delete a float vector that's pointed to by float_vector
Definition at line 27 of file cinterface_utils.cpp.
References DeleteRawPtr(), and HF::Exceptions::OK.