HF::RayTracer Namespace Reference
Cast rays to determine if and where they intersect geometry.
Classes
class EmbreeRayTracer
A wrapper for Intel's Embree Library.
struct FullRayRequest
struct HitStruct
A simple hit struct to carry all relevant information about hits.
struct Triangle
A triangle. Used internally in Embree. More...
struct Vertex
A vertex. Used internally in Embree. More...
Functions
void CheckState (RTCDevice &device)
Check an embree device for errors.
void vectorsToBuffers (const std::vector< std::array< float, 3 >> &vertices, std::vector< Triangle > &Tribuffer, std::vector< Vertex > &Vbuffer)
Index a list of verticies and place them into a triangle and vertex buffer.
void buffersToStructs (std::vector< float > &in_vertices, std::vector< int > &in_indices, std::vector< Vertex > &out_vertices, std::vector< Triangle > &out_triangles)
Package raw arrays of floats and indices in buffers to the required Embree types.
Detailed Description
Cast rays to determine if and where they intersect geometry.
The basics of raytracing entail casting a ray from an origin point in a specific direction and determining whether or not it intersects with a set of geometry. Certain functions can even determine where the intersection occured. Generally, every RayTracer will contain a set of geometry and provide functions for casting rays from an origin point in a specific direciton. Some generate an accelerated structure from geometry called a Bounding Volume Hierarchy, or BVH. A BVH can drastically decrease the time it takes to calculate ray intersections, but can be more complicated to manage compared to standard buffers of geometry.
See also
EmbreeRayTracer For an implementation of a raytracer using Intel's Embree library as a backend.
Class Documentation
struct HF::RayTracer::Triangle
A triangle. Used internally in Embree.
Definition at line 43 of file embree_raytracer.cpp.
Class Members
int
v0
int
v1
int
v2
struct HF::RayTracer::Vertex
A vertex. Used internally in Embree.
Definition at line 38 of file embree_raytracer.cpp.
Class Members
float
x
float
y
float
z
Function Documentation
buffersToStructs()
void HF::RayTracer::buffersToStructs (std::vector< float > & in_vertices, std::vector< int > & in_indices, std::vector< Vertex > & out_vertices, std::vector< Triangle > & out_triangles) [inline]
Package raw arrays of floats and indices in buffers to the required Embree types.
Parameters
in_vertices An array of floats in which every 3 floats represents a vertex.
in_indices An array of integers in which every 3 integers represents a triangle.
out_vertices Output array for vertexes.
out_triangles Output array for triangles.
Todo
Todo May be faster as a std::move or std::copy.
Definition at line 103 of file embree_raytracer.cpp.
CheckState()
void HF::RayTracer::CheckState (RTCDevice & device)
Check an embree device for errors.
Parameters
device Device to check for errors
Exceptions
std::exception Some error is found while casting rays.
Definition at line 29 of file embree_raytracer.cpp.
Referenced by HF::RayTracer::EmbreeRayTracer::FireRay().
vectorsToBuffers()
void HF::RayTracer::vectorsToBuffers (const std::vector< std::array< float, 3 >> & vertices, std::vector< Triangle > & Tribuffer, std::vector< Vertex > & Vbuffer) [inline]
Index a list of verticies and place them into a triangle and vertex buffer.
Parameters
vertices Mesh vertices.
Tribuffer Output triangle buffer.
Vbuffer Output Vertex Buffer.
Internally, this uses a hashmap to create an index map of vertices.
Todo
Todo Performance here can be improved by using indexing.
Definition at line 53 of file embree_raytracer.cpp.
Referenced by HF::RayTracer::EmbreeRayTracer::EmbreeRayTracer(), and HF::RayTracer::EmbreeRayTracer::InsertNewMesh().