HF::RayTracer Namespace Reference
Classes
class EmbreeRayTracer
A wrapper for Intel's Embree Library.
struct FullRayRequest
struct HitInfo
Contains no information about the ray itself, More...
struct HitStruct
A simple hit struct to carry all relevant information about hits.
class RayRequestCollection
Holds a set of ray requests, reusing memory where possible
struct RayRequestLite
A ray request, that depends on RayRequestLiteHolder
struct Triangle
A triangle. Used internally in Embree. More...
struct Vertex
A vertex. Used internally in Embree. More...
Functions
template<typename P , typename D >
P CalculateHitPoint (const P &origin, const D &direction, float distance)
Calculate the hitpoint of a ray from its origin, direction and distance
void CheckState (RTCDevice &device)
Check an embree device for errors.
static double getRandomNumber ()
static float myradians (float angle)
static unsigned long mix (unsigned long a, unsigned long b, unsigned long c)
static std::vector< std::array< float, 3 > > genSphereRays (int step)
Generate a vector of directions to distribute rays in 360 degrees.
std::vector< std::array< float, 3 > > genFibbonacciRays (int numrays)
Generate a set of equally distributed directions in sphere.
void vectorsToBuffers (const std::vector< std::array< float, 3 >> &vertices, std::vector< Triangle > &Tribuffer, std::vector< Vertex > &Vbuffer)
Index a list of verticies and place them into a triangle and vertex buffer.
void buffersToStructs (std::vector< float > &in_vertices, std::vector< int > &in_indices, std::vector< Vertex > &out_vertices, std::vector< Triangle > &out_triangles)
Package raw arrays of floats and indices in buffers to the required Embree types.
void Fire8Rays (std::vector< std::reference_wrapper< FullRayRequest >> &requests, const RTCScene &scene, RTCIntersectContext &context)
Fire 8 rays and update the requests based on results
Class Documentation
struct HF::RayTracer::HitInfo
Contains no information about the ray itself,
Deprecated
Deprecated Never used. Leftover from partially implemented experimental feature. This eventually became the RayResult struct seen in the C-interface. Moving the RayResult struct to the C interface was far more useful than what could be accomplished here, since it allowed the Cinterface and its clients to define their own RayRequest structs that could be filled through templates.
Definition at line 119 of file RayRequest.h.
struct HF::RayTracer::Triangle
A triangle. Used internally in Embree.
Definition at line 55 of file embree_raytracer.cpp.
Class Members
int
v0
int
v1
int
v2
struct HF::RayTracer::Vertex
A vertex. Used internally in Embree.
Definition at line 50 of file embree_raytracer.cpp.
Class Members
float
x
float
y
float
z
Function Documentation
buffersToStructs()
void HF::RayTracer::buffersToStructs (std::vector< float > & in_vertices, std::vector< int > & in_indices, std::vector< Vertex > & out_vertices, std::vector< Triangle > & out_triangles) [inline]
Package raw arrays of floats and indices in buffers to the required Embree types.
Parameters
in_vertices An array of floats in which every 3 floats represents a vertex.
in_indices An array of integers in which every 3 integers represents a triangle.
out_vertices Output array for vertexes.
out_triangles Output array for triangles.
Todo
Todo May be faster as a std::move or std::copy.
Definition at line 201 of file embree_raytracer.cpp.
CalculateHitPoint()
template<typename P , typename D >
P HF::RayTracer::CalculateHitPoint (const P & origin, const D & direction, float distance)
Calculate the hitpoint of a ray from its origin, direction and distance
Deprecated
Deprecated Unused.
Definition at line 27 of file embree_raytracer.cpp.
CheckState()
void HF::RayTracer::CheckState (RTCDevice & device)
Check an embree device for errors.
Parameters
device Device to check for errors
Exceptions
std::exception Some error is found while casting rays.
Definition at line 41 of file embree_raytracer.cpp.
Referenced by HF::RayTracer::EmbreeRayTracer::FireRay().
Fire8Rays()
void HF::RayTracer::Fire8Rays (std::vector< std::reference_wrapper< FullRayRequest >> & requests, const RTCScene & scene, RTCIntersectContext & context) [inline]
Fire 8 rays and update the requests based on results
Definition at line 480 of file embree_raytracer.cpp.
Referenced by HF::RayTracer::EmbreeRayTracer::FireRequests().
genFibbonacciRays()
std::vector< std::array< float, 3 > > HF::RayTracer::genFibbonacciRays (int numrays)
Generate a set of equally distributed directions in sphere.
Deprecated
Deprecated Use the version in view analysis
The directions from this function are better distributed than those of genSphereRays. The implementation of this function is based on https://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere.
Parameters
numrays The number of directions to generate.
Returns
An array of equally spaced directions.
Deprecated
Deprecated Use the version in ViewAnalysis
Definition at line 114 of file embree_raytracer.cpp.
References myradians().
genSphereRays()
std::vector< std::array< float, 3 > > HF::RayTracer::genSphereRays (int step) [inline], [static]
Generate a vector of directions to distribute rays in 360 degrees.
Deprecated
Deprecated Use the version in ViewAnalysis.
This algorithm is from the old python codebase.
Parameters
step The stepsize to use for distributing directions. Lower step sizes yield better coverage, but more rays.
Returns
An array of directions distributed in a sphere.
Deprecated
Deprecated Use the version in ViewAnalysis
Definition at line 87 of file embree_raytracer.cpp.
References myradians().
getRandomNumber()
static double HF::RayTracer::getRandomNumber () [inline], [static]
Deprecated
Deprecated Use the version in ViewAnalysis.
Definition at line 59 of file embree_raytracer.cpp.
mix()
static unsigned long HF::RayTracer::mix (unsigned long a, unsigned long b, unsigned long c) [inline], [static]
Deprecated
Deprecated Use the version in ViewAnalysis.
Definition at line 71 of file embree_raytracer.cpp.
myradians()
static float HF::RayTracer::myradians (float angle) [inline], [static]
Deprecated
Deprecated Use the version in ViewAnalysis.
Definition at line 65 of file embree_raytracer.cpp.
Referenced by genFibbonacciRays(), and genSphereRays().
vectorsToBuffers()
void HF::RayTracer::vectorsToBuffers (const std::vector< std::array< float, 3 >> & vertices, std::vector< Triangle > & Tribuffer, std::vector< Vertex > & Vbuffer) [inline]
Index a list of verticies and place them into a triangle and vertex buffer.
Parameters
vertices Mesh vertices.
Tribuffer Output triangle buffer.
Vbuffer Output Vertex Buffer.
Internally, this uses a hashmap to create an index map of vertices.
Todo
Todo Performance here can be improved by using indexing.
Definition at line 151 of file embree_raytracer.cpp.
Referenced by HF::RayTracer::EmbreeRayTracer::EmbreeRayTracer(), and HF::RayTracer::EmbreeRayTracer::InsertNewMesh().