ViewAnalysis
Analyze the view from from points in the environment.
Functions
vector< std::array< float, 3 > > HF::AnalysisMethods::ViewAnalysis::FibbonacciDistributePoints (int num_points, float upwards_fov=50.0f, float downward_fov=70.0f)
Evenly distribute a set of points around a sphere centered at the origin.
template<typename RES , typename RT , typename N >
std::vector< RES > HF::AnalysisMethods::ViewAnalysis::SphericalViewAnalysis (RT &ray_tracer, const std::vector< N > &Nodes, int num_rays, float upward_limit=50.0f, float downward_limit=70.0f, float height=1.7f)
Conduct view analysis with any Raytracer in parallel.
template<typename RT , typename N >
std::vector< float > HF::AnalysisMethods::ViewAnalysis::SphericalRayshootWithAnyRTForDistance (RT &ray_tracer, const std::vector< N > &Nodes, int num_rays, float upward_limit=50.0f, float downward_limit=70.0f, float height=1.7f, const AGGREGATE_TYPE aggregation=AGGREGATE_TYPE::SUM)
Conduct view analysis and recieve a summarized set of results for each node.
C_INTERFACE SphereicalViewAnalysisAggregate (HF::RayTracer::EmbreeRayTracer *ERT, HF::SpatialStructures::Node *node_ptr, int node_size, int max_rays, float upward_fov, float downward_fov, float height, AGGREGATE_TYPE AT, std::vector< float > **out_scores, float **out_scores_ptr, int *out_scores_size)
Perform view analysis from a list of points and aggregate the results into an ordered list of scores. Scores are aggregated by the aggregation specified in AT aggregation method.
C_INTERFACE SphereicalViewAnalysisAggregateFlat (HF::RayTracer::EmbreeRayTracer *ERT, const float *node_ptr, int node_size, int max_rays, float upward_fov, float downward_fov, float height, AGGREGATE_TYPE AT, std::vector< float > **out_scores, float **out_scores_ptr, int *out_scores_size)
Perform view analysis from a list of points and aggregate the results into an ordered list of scores. Scores are aggregated by the aggregation specified in AT aggregation method.
C_INTERFACE SphericalViewAnalysisNoAggregate (HF::RayTracer::EmbreeRayTracer *ERT, const HF::SpatialStructures::Node *node_ptr, int node_size, int *max_rays, float upward_fov, float downward_fov, float height, std::vector< RayResult > **out_results, RayResult **out_results_ptr)
Perform view analysis and recieve the distance and meshid for each individual ray.
C_INTERFACE SphericalViewAnalysisNoAggregateFlat (HF::RayTracer::EmbreeRayTracer *ERT, const float *node_ptr, int node_size, int *max_rays, float upward_fov, float downward_fov, float height, std::vector< RayResult > **out_results, RayResult **out_results_ptr)
Perform view analysis and recieve the distance and meshid for each individual ray.
C_INTERFACE SphericalDistribute (int *num_rays, std::vector< float > **out_direction_vector, float **out_direction_data, float upward_fov, float downward_fov)
Distribute directions in a sphere
Detailed Description
Analyze the view from from points in the environment.
Function Documentation
FibbonacciDistributePoints()
std::vector< std::array< float, 3 > > HF::AnalysisMethods::ViewAnalysis::FibbonacciDistributePoints (int num_points, float upwards_fov = 50.0f, float downward_fov = 70.0f)
#include <Cpp/analysismethods/src/view_analysis.cpp>
Evenly distribute a set of points around a sphere centered at the origin.
Parameters
num_points Maximum number of points to distribute.
upward_limit Maximum angle in degrees to cast rays above the viewpoint.
downward_limit Maximum angle in degrees to cast rays below the viewpoint. ///
Returns
A vector of arrays containing the x, y, and z coordinates of each point on the sphere.
Note
The number of points returned by this function will not exactly equal the amount of points specified by num_points depending on the values of upwards_fov and downward fov. More information is available below.
How FOV is implemented
Every point is equally distributed on a sphere using a formula based on this stack overflow answer: https://stackoverflow.com/questions/9600801/evenly-distributing-n-points-on-a-sphere. This formula cannot easily be mapped to a specific vertical fov or cone, so instead this function will remove points that don't meet the constraints. Discarding points causes the number of points generated to be less than the num_rays argument, so the percentage of points discarded is calculated and a second run is performed with an adjusted num_rays value to get as close as possible to the value specified in the argument. This approach will not result in an exact match to the num_rays argument, and will run FibbonacciDist twice.
Example
// Requires #include "view_analysis.h"
// For brevity
using HF::AnalysisMethods::ViewAnalysis::FibbonacciDistributePoints;
// Prepare maximum number of points to distribute
int size = 8;
// Generate points without any limitations on fov
auto points = FibbonacciDistributePoints(size, 90.0f, 90.0f);
// Print number of points
std::cout << "Number of Points:" << points.size() << std::endl;
// Iterate through results and print every point.
std::cout << "[";
for (int i = 0; i < size; i++) {
    const auto& point = points[i];
    std::cout << "(" << point[0] << ", " << point[1] << ", " << point[2] << ")";
    if (i != size - 1) std::cout << ", ";
}
std::cout << "]" << std::endl;
>>> Number of Points:8
>>> [(-0, -1, 0), (-0.304862, -0.75, -0.586992), (0.813476, -0.5, 0.29708), (-0.894994, -0.25, 0.369441), (0.423846, 0, -0.905734), (0.289781, 0.25, 0.923865), (-0.749296, 0.5, -0.43423), (0.64601, 0.75, -0.142025)]
Definition at line 158 of file view_analysis.cpp.
References HF::AnalysisMethods::ViewAnalysis::FibbonacciDist().
Referenced by SphericalDistribute(), HF::AnalysisMethods::ViewAnalysis::SphericalRayshootWithAnyRTForDistance(), HF::AnalysisMethods::ViewAnalysis::SphericalViewAnalysis(), and HF::AnalysisMethods::ViewAnalysis::SphericalViewAnalysisFromRayRequests().
SphereicalViewAnalysisAggregate()
C_INTERFACE SphereicalViewAnalysisAggregate (HF::RayTracer::EmbreeRayTracer * ERT, HF::SpatialStructures::Node * node_ptr, int node_size, int max_rays, float upward_fov, float downward_fov, float height, AGGREGATE_TYPE AT, std::vector< float > ** out_scores, float ** out_scores_ptr, int * out_scores_size)
#include <Cinterface/view_analysis_C.h>
Perform view analysis from a list of points and aggregate the results into an ordered list of scores. Scores are aggregated by the aggregation specified in AT aggregation method.
Parameters
ERT Raytracer to fire all rays from.
node_ptr Positions to perform view analysis from.
node_size Number of nodes in the array pointed at by node_ptr.
max_rays Number of rays to evenly distribute in a sphere.
height Height to offset nodes from the ground.
AT Type of aggregation method to use on distance values.
out_scores Output parameter for score vector.
out_scores_ptr Output parameter for the score vector's underlying data.
out_scores_size Number of elements in the output vector..
Returns
HF_STATUS::OK on completion.
Definition at line 17 of file view_analysis_C.cpp.
References HF::Exceptions::OK, and HF::AnalysisMethods::ViewAnalysis::SphericalRayshootWithAnyRTForDistance().
SphereicalViewAnalysisAggregateFlat()
C_INTERFACE SphereicalViewAnalysisAggregateFlat (HF::RayTracer::EmbreeRayTracer * ERT, const float * node_ptr, int node_size, int max_rays, float upward_fov, float downward_fov, float height, AGGREGATE_TYPE AT, std::vector< float > ** out_scores, float ** out_scores_ptr, int * out_scores_size)
#include <Cinterface/view_analysis_C.h>
Perform view analysis from a list of points and aggregate the results into an ordered list of scores. Scores are aggregated by the aggregation specified in AT aggregation method.
Parameters
ERT Raytracer to fire all rays from.
node_ptr Positions to perform view analysis from as a flat array of floats. Each 3 floats should represent a new point.
node_size Number of nodes in the array pointed at by node_ptr. Should be equal to the length of node_ptr/3.
max_rays Number of rays to evenly distribute in a sphere.
upward_fov Maximum degrees upward from the viewer's eye level to consider.
downward_fov Maximum degrees downward from the viewer's eye level to consider.
height Height to offset nodes from the ground.
AT Type of aggregation method to use on distance values.
out_scores Output parameter for score vector.
out_scores_ptr Output parameter for the score vector's underlying data.
out_scores_size Number of elements in the output vector..
Returns
HF_STATUS::OK on completion.
Definition at line 50 of file view_analysis_C.cpp.
References ConvertRawFloatArrayToPoints(), HF::Exceptions::OK, and HF::AnalysisMethods::ViewAnalysis::SphericalRayshootWithAnyRTForDistance().
SphericalDistribute()
C_INTERFACE SphericalDistribute (int * num_rays, std::vector< float > ** out_direction_vector, float ** out_direction_data, float upward_fov, float downward_fov)
#include <Cinterface/view_analysis_C.h>
Distribute directions in a sphere
Parameters
num_rays The number of directions to generate.
out_direction_vector Output parameter for the resulting directions.
upward_fov Maximum degrees upward from the viewer's eye level to consider.
downward_fov Maximum degrees downward from the viewer's eye level to consider.
Returns
HF_STATUS::OK On success.
Definition at line 125 of file view_analysis_C.cpp.
References HF::AnalysisMethods::ViewAnalysis::FibbonacciDistributePoints(), and HF::Exceptions::OK.
SphericalRayshootWithAnyRTForDistance()
template<typename RT , typename N >
std::vector<float> HF::AnalysisMethods::ViewAnalysis::SphericalRayshootWithAnyRTForDistance (RT & ray_tracer, const std::vector< N > & Nodes, int num_rays, float upward_limit = 50.0f, float downward_limit = 70.0f, float height = 1.7f, const AGGREGATE_TYPE aggregation = AGGREGATE_TYPE::SUM)
#include <Cpp/analysismethods/src/view_analysis.h>
Conduct view analysis and recieve a summarized set of results for each node.
Parameters
ray_tracer A valid raytracer that already has the geometry loaded.
Nodes Points to perform analysis from.
num_rays The number of rays to cast from each point in nodes. The actual amount of rays cast may be less or more than this number.
Parameters
upward_limit Maximum angle in degrees to cast rays above the viewpoint.
downward_limit Maximum angle in degrees to cast rays below the viewpoint.
height Height off the ground to cast from. All points in Nodes will be offset this distance from the ground (+Z) before calculations are performed
aggregation The type of aggregation to use.
Template Parameters
RT A Raytracer with FireAnyRay defined for the type of N.
N A point that overloads [] for 0, 1 and 2.
Returns
A Nodes.size() long array of results for each node in Nodes.
The analysis performed by this function is identical to that described in SphericalViewAnalysis, but results are summarized over the course of the analysis for every observer point instead of recording each individual intersection. The memory usage for this function is drastically lower than that of SphericalViewAnalysis, resulting in lower execution times at the cost of being restricted to a set of predefined aggregation methods.
Exceptions
std::bad_array_new_length The number of rays is larger than that which can be stored in a std::vector.
See also
FibbonacciDistributePoints For details on how the directions are calculated from num_rays.
SphericalViewAnalysis to get the result of every ray fired instead of summarizing the results.
AGGREGATE_TYPE for a list of aggregation methods.
Aggregate for the implementation of all aggregation methods.
Example
// Requires #include "view_analysis.h"
// Use this so we can fit within 80 characters
using HF::AnalysisMethods::ViewAnalysis::SphericalRayshootWithAnyRTForDistance;
using HF::AnalysisMethods::ViewAnalysis::AGGREGATE_TYPE;
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{
    MeshInfo(plane_vertices, plane_indices, 0, " ")}
);
// Define observer points
std::vector<std::array<float, 3>> points{
    {0,0,0}, {10,10,0}, {20,20,0}, {30, 30, 0}
};
// Perform View Analysis and sum the distance to all intersections
// for every node
int num_rays = 2000;
auto results = SphericalRayshootWithAnyRTForDistance(
    ert, points, num_rays, 90.0f, 90.0f, 1.7f, AGGREGATE_TYPE::SUM
);
// Print Results
std::cerr << "(";
for (int i = 0; i < results.size(); i++) {
    std::cerr << results[i];
    if (i != results.size() - 1) std::cerr << ", ";
}
std::cerr << ")" << std::endl;
>>> (2746.72, 932.565, 170.858, 76.8413)
Todo
Todo Should this have a height check like the one in the VisibilityGraph?
Todo
Todo Rename this to ViewAnalysisAggregate.
Todo
Todo Potential speed up here by using a Raytracer function that doesn't return the point of intersection.
Definition at line 489 of file view_analysis.h.
References HF::AnalysisMethods::ViewAnalysis::Aggregate(), and HF::AnalysisMethods::ViewAnalysis::FibbonacciDistributePoints().
Referenced by SphereicalViewAnalysisAggregate(), and SphereicalViewAnalysisAggregateFlat().
SphericalViewAnalysis()
template<typename RES , typename RT , typename N >
std::vector<RES> HF::AnalysisMethods::ViewAnalysis::SphericalViewAnalysis (RT & ray_tracer, const std::vector< N > & Nodes, int num_rays, float upward_limit = 50.0f, float downward_limit = 70.0f, float height = 1.7f)
#include <Cpp/analysismethods/src/view_analysis.h>
Conduct view analysis with any Raytracer in parallel.
Parameters
ray_tracer A valid raytracer that already has the geometry loaded.
Nodes Points to perform analysis from.
num_rays The number of rays to cast from each point in nodes. The actual amount of rays cast may be less or more than this number.
upward_limit Maximum angle in degrees to cast rays above the viewpoint.
downward_limit Maximum angle in degrees to cast rays below the viewpoint.
height Height off the ground to cast from. All points in Nodes will be offset this distance from the ground (+Z) before calculations are performed
Template Parameters
RES A class or struct that has a .SetHit() function. This function will be called with the node, direction, distance to intersection, and MeshID intersected for every ray that intersects geometry.
RT A Raytracer with FireAnyRay defined for the type of N.
N A point that overloads [] for 0, 1 and 2.
Returns
An approximately num_rays * Nodes.size() long vector of RES with one element for every ray fired. Results will be laid out in order with the first node's results first, then the second, etc. Every ray that intersected something, and all elements that didn't result in an intersection will left at their default values.
ViewAnalysis is calculated by casting a series of rays equally distributed in a sphere from each point in Nodes. This function will run in parallel using all available cores. Depending on RES, this function's complexity and results can vary.
Exceptions
std::bad_array_new_length The number of rays is larger than that which can be stored in a std::vector.
See also
FibbonacciDistributePoints For details on how the directions are calculated from num_rays.
SphericalRayshootWithAnyRTForDistance for a more efficent method of getting a summary of the results.
Example
// Requires #include "view_analysis.h"
// Use this so we can fit within 80 characters
using HF::AnalysisMethods::ViewAnalysis::SphericalViewAnalysis;
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{
    MeshInfo(plane_vertices, plane_indices, 0, " ")}
);
// Define a struct that only stores the distance when sethit is called.
struct SampleResults {
    float dist = -1.0f;
    inline void SetHit(
        const std::array<float, 3> & node,
        const std::array<float, 3> & direction,
        float distance,
        int meshID
    ) {
        dist = distance;
    }
};
// Define observer points
std::vector<std::array<float, 3>> points{
    {0,0,0}, {1,1,0}, {1,2,0}, {1000, 1000, 0}
};
// Perform View Analysis
int num_rays = 50;
auto results = SphericalViewAnalysis<SampleResults>(ert, points, num_rays);
// Determine how many directions there were since there may have been less than
// what we specified
int num_directions = results.size() / points.size();
// Construct a vector from the results of the first node
std::vector<SampleResults> first_results(
    results.begin(), results.begin() + num_directions
);
// Print Results
std::cerr << "(";
for (int i = 0; i < first_results.size(); i++) {
    const auto & result = first_results[i];
    std::cerr << result.dist;
    if (i != first_results.size() - 1) std::cerr << ", ";
}
std::cerr << ")" << std::endl;
>>> (-1, 7.35812, -1, -1, 3.70356, -1, 5.56647, 12.1517, -1, 2.36725, -1, -1, 2.97477, 2.58713, -1, -1, 1.91404, 5.95885, 4.26368, 1.86167, -1, -1, 2.0406, 2.78304, -1, -1, -1, -1, 2.83909, 2.05302, -1, -1, 1.90724, 4.29017, 6.3381, 1.98544, -1, -1, 2.75554, 3.15929, -1, -1, 2.6345, -1, -1, 6.80486, -1, 5.12012, -1)
Todo
Todo Should this have a height check like the one in the VisibilityGraph?
Definition at line 357 of file view_analysis.h.
References HF::AnalysisMethods::ViewAnalysis::FibbonacciDistributePoints().
SphericalViewAnalysisNoAggregate()
C_INTERFACE SphericalViewAnalysisNoAggregate (HF::RayTracer::EmbreeRayTracer * ERT, const HF::SpatialStructures::Node * node_ptr, int node_size, int * max_rays, float upward_fov, float downward_fov, float height, std::vector< RayResult > ** out_results, RayResult ** out_results_ptr)
#include <Cinterface/view_analysis_C.h>
Perform view analysis and recieve the distance and meshid for each individual ray.
Parameters
ERT Raytracer to fire rays from.
node_ptr Positions to perform view analysis from .
node_size Number of nodes in node_ptr.
max_rays Number of rays to fire per node.
upward_fov Maximum degrees upward from the viewer's eye level to consider.
downward_fov Maximum degrees downward from the viewer's eye level to consider.
height Height to offset nodes to.
out_results Vector to store results in.
out_results_ptr Pointer to the result vector's data.
Returns
HF_STATUS::OK on vomplryion.
Definition at line 73 of file view_analysis_C.cpp.
References HF::Exceptions::OK.
SphericalViewAnalysisNoAggregateFlat()
C_INTERFACE SphericalViewAnalysisNoAggregateFlat (HF::RayTracer::EmbreeRayTracer * ERT, const float * node_ptr, int node_size, int * max_rays, float upward_fov, float downward_fov, float height, std::vector< RayResult > ** out_results, RayResult ** out_results_ptr)
#include <Cinterface/view_analysis_C.h>
Perform view analysis and recieve the distance and meshid for each individual ray.
Parameters
ERT Raytracer to fire all rays from.
node_ptr Positions to perform view analysis from as a flat array of floats. Each 3 floats should represent a new point.
node_size Number of nodes in the array pointed at by node_ptr. Should be equal to the length of node_ptr/3.
max_rays Number of rays to evenly distribute in a sphere.
upward_fov Maximum degrees upward from the viewer's eye level to consider.
downward_fov Maximum degrees downward from the viewer's eye level to consider.
height Height to offset nodes from the ground.
out_scores Output parameter for score vector.
out_scores_ptr Output parameter for the score vector's underlying data.
out_scores_size Number of elements in the output vector.
Returns
HF_STATUS::OK on completion.
Definition at line 105 of file view_analysis_C.cpp.
References ConvertRawFloatArrayToPoints(), and HF::Exceptions::OK.