Pathfinding
Find paths between differnt points in a graph.
Functions
C_INTERFACE CreatePath (const HF::SpatialStructures::Graph *g, int start, int end, int *out_size, HF::SpatialStructures::Path **out_path, HF::SpatialStructures::PathMember **out_data)
Create a path from start to end in C++. If no path exists, the NO_PATH error code will be returned, and both pointers will be left as they were before the function was called.
C_INTERFACE CreatePaths (const HF::SpatialStructures::Graph *g, const int *start, const int *end, HF::SpatialStructures::Path **out_path_ptr_holder, HF::SpatialStructures::PathMember **out_path_member_ptr_holder, int *out_sizes, int num_paths)
Create multiple paths from start to end in C++. both out_ members return as arrays of pointers, with one for each element. Sizes of zero represent non-existant paths, and will be set to null pointers
C_INTERFACE GetPathInfo (HF::SpatialStructures::Path *p, HF::SpatialStructures::PathMember **out_member_ptr, int *out_size)
Get the size of a path and a pointer to its path members.
C_INTERFACE DestroyPath (HF::SpatialStructures::Path *path_to_destroy)
Delete a path.
Detailed Description
Find paths between differnt points in a graph.
Function Documentation
CreatePath()
C_INTERFACE CreatePath (const HF::SpatialStructures::Graph * g, int start, int end, int * out_size, HF::SpatialStructures::Path ** out_path, HF::SpatialStructures::PathMember ** out_data)
#include <Cinterface/pathfinder_C.h>
Create a path from start to end in C++. If no path exists, the NO_PATH error code will be returned, and both pointers will be left as they were before the function was called.
Parameters
g The graph to conduct the search on.
start The id of the node for the starting point of the path. The ID must belong to a node already within the graph!
end The id of the node for the end point of the path. The ID must belong to a node already within the graph!
out_path Return parameter for the path object.
out_data Return parameter for the path's members.
Returns
HF_STATUS::NO_PATH if a path could not be generated. HF_STATUS::OK if a path was generated.
Uses the Boost Graph Library to perform Dijkstra's shortest path algorithm. For multiple paths, use CreatePaths for multiple paths at once.
// Requires #include "pathfinder_C.h", #include "graph.h", #include "path.h", #include "path_finder.h"
// Create a Graph g, and compress it.
HF::SpatialStructures::Graph g;
g.addEdge(0, 1, 1);
g.addEdge(0, 2, 2);
g.addEdge(1, 3, 3);
g.addEdge(2, 4, 1);
g.addEdge(3, 4, 5);
g.Compress();
// Create a boostGraph from g
auto boostGraph = HF::Pathfinding::CreateBoostGraph(g);
// Prepare parameters for CreatePath
HF::SpatialStructures::Path* out_path = nullptr;
HF::SpatialStructures::PathMember* out_path_member = nullptr;
int out_size = -1;
CreatePath(&g, 0, 4, &out_size, &out_path, &out_path_member);
// Use out_path, out_path_member
// Remember to free resources when finished
DestroyPath(out_path);
// At this point, out_path_member has also been destroyed, so we set this to nullptr
out_path_member = nullptr;
Definition at line 20 of file pathfinder_C.cpp.
References HF::Pathfinding::CreateBoostGraph(), HF::SpatialStructures::Path::empty(), HF::Pathfinding::FindPath(), HF::SpatialStructures::Path::GetPMPointer(), HF::Exceptions::NO_PATH, HF::Exceptions::OK, and HF::SpatialStructures::Path::size().
CreatePaths()
C_INTERFACE CreatePaths (const HF::SpatialStructures::Graph * g, const int * start, const int * end, HF::SpatialStructures::Path ** out_path_ptr_holder, HF::SpatialStructures::PathMember ** out_path_member_ptr_holder, int * out_sizes, int num_paths)
#include <Cinterface/pathfinder_C.h>
Create multiple paths from start to end in C++. both out_ members return as arrays of pointers, with one for each element. Sizes of zero represent non-existant paths, and will be set to null pointers
Parameters
g The graph to conduct the search on.
start An array of ids for starting nodes. Length must match that of end and all the IDS must belong to nodes that already exist within the graph.
end An array of ids for ending nodes. Length must match that of end and all the IDS must belong to nodes that already exist within the graph.
out_path_ptr_holder Return parameter for path objects.
out_data Return parameter for pointers to the path objects' underlying data.
out_sizes Output array of integers representing the length of of each path in out_data's arrays. Sizes of 0 indicate that no path could be generated.
num_paths Size of start and end arrays
Returns
HF::OK on completion.
// Requires #include "pathfinder_C.h", #include "graph.h", #include "path.h", #include "path_finder.h"
// Create a Graph g, and compress it.
HF::SpatialStructures::Graph g;
g.addEdge(0, 1, 1);
g.addEdge(0, 2, 2);
g.addEdge(1, 3, 3);
g.addEdge(2, 4, 1);
g.addEdge(3, 4, 5);
g.Compress();
// Create a boostGraph from g
auto boostGraph = HF::Pathfinding::CreateBoostGraph(g);
// Prepare starting and ending nodes
int start_nodes[] = { 0 };
int end_nodes[] = { 4 };
// Prepare parameters for CreatePaths
HF::SpatialStructures::Path* out_path = nullptr;
HF::SpatialStructures::PathMember* out_path_member = nullptr;
int out_size = -1;
const int path_size = 5;
// Sizes of paths
const int MAX_SIZE = 16;
int out_sizes[MAX_SIZE];
CreatePaths(&g, start_nodes, end_nodes, &out_path, &out_path_member, out_sizes, path_size);
// Use out_path, out_path_member
// Remember to free resources when finished
DestroyPath(out_path);
// At this point, out_path_member has also been destroyed, so we set this to nullptr
out_path_member = nullptr;
Definition at line 46 of file pathfinder_C.cpp.
References HF::Pathfinding::CreateBoostGraph(), HF::Pathfinding::InsertPathsIntoArray(), and HF::Exceptions::OK.
DestroyPath()
C_INTERFACE DestroyPath (HF::SpatialStructures::Path * path_to_destroy)
#include <Cinterface/pathfinder_C.h>
Delete a path.
Parameters
path_to_destroy Pointer to the path to delete.
// Requires #include "pathfinder_C.h", #include "graph.h", #include "path.h", #include "path_finder.h"
// Create a Graph g, and compress it.
HF::SpatialStructures::Graph g;
g.addEdge(0, 1, 1);
g.addEdge(0, 2, 2);
g.addEdge(1, 3, 3);
g.addEdge(2, 4, 1);
g.addEdge(3, 4, 5);
g.Compress();
// Create a boostGraph from g
auto boostGraph = HF::Pathfinding::CreateBoostGraph(g);
HF::SpatialStructures::Path* out_path = nullptr;
HF::SpatialStructures::PathMember* out_path_member = nullptr;
int out_size = -1;
CreatePath(&g, 0, 4, &out_size, &out_path, &out_path_member);
// Use out_path, out_path_member
// Remember to free resources when finished
DestroyPath(out_path);
// At this point, out_path_member has also been destroyed, so we set this to nullptr
out_path_member = nullptr;
Definition at line 93 of file pathfinder_C.cpp.
References DeleteRawPtr(), and HF::Exceptions::OK.
GetPathInfo()
C_INTERFACE GetPathInfo (HF::SpatialStructures::Path * p, PathMember ** out_member_ptr, int * out_size)
#include <Cinterface/pathfinder_C.h>
Get the size of a path and a pointer to its path members.
Parameters
p Pointer to the path to get information from. This can handle null values.
out_member_ptr Pointer to the path to get information from. Should not be null.
out_size The number of path members in the path.
Returns
HF_STATUS::NO_PATH if the path is not valid. HF_OK otherwise.
// Requires #include "pathfinder_C.h", #include "path.h"
// Create a Graph g, and compress it.
HF::SpatialStructures::Graph g;
g.addEdge(0, 1, 1);
g.addEdge(0, 2, 2);
g.addEdge(1, 3, 3);
g.addEdge(2, 4, 1);
g.addEdge(3, 4, 5);
g.Compress();
// Create a boostGraph from g
auto boostGraph = HF::Pathfinding::CreateBoostGraph(g);
HF::SpatialStructures::Path* out_path = nullptr;
HF::SpatialStructures::PathMember* out_path_member = nullptr;
int out_size = -1;
CreatePath(&g, 0, 4, &out_size, &out_path, &out_path_member);
// Get p's info, store results in out_path_member and out_size
GetPathInfo(p, &out_path_member, &out_size);
// Remember to free resources when finished
DestroyPath(out_path);
// At this point, out_path_member has also been destroyed, so we set this to nullptr
out_path_member = nullptr;
Get the size of a path and a pointer to its path members.
Definition at line 75 of file pathfinder_C.cpp.
References HF::SpatialStructures::Path::GetPMPointer(), HF::Exceptions::NO_PATH, HF::Exceptions::OK, and HF::SpatialStructures::Path::size().