HF::GraphGenerator Namespace Reference
Generate a graph of accessible space from a given start point.
Classes
class GraphGenerator
Generate a graph of accessible space from a given start point.
class GraphGeneratorPrivate
Contains the private implementation of the GraphGenerator to insulate the clients from the implementation.
class UniqueQueue
A queue that remembers every object inserted, and prevents the addition of nodes that have already been inserted even if they've been popped.
Typedefs
using v3 = std::array< float, 3 >
Enumerations
enum HIT_FLAG { FLOORS = 1,
OBSTACLES = 2,
BOTH = 3
 }
Determines which geometry the ray will collide with.
Functions
std::set< std::pair< int, int > > permutations (int limit)
Create a set of every permutation for all numbers between 0 and limit.
vector< pair > CreateDirecs (int max_step_connections)
Create the set of directions to offset nodes in.
Variables
constexpr v3 down { 0, 0, -1 }
static const vector< pair > init_directs
Detailed Description
Generate a graph of accessible space from a given start point.
See also
GraphGenerator for more details.
Typedef Documentation
v3
using HF::GraphGenerator::v3 = typedef std::array<float, 3>
Definition at line 21 of file graph_generator.h.
Enumeration Type Documentation
HIT_FLAG
enum HF::GraphGenerator::HIT_FLAG
Determines which geometry the ray will collide with.
Remarks
Used internally by the GraphGenerator to determine which type of geometry to collide with when casting a ray.
Enumerator
FLOORS Floors only.
OBSTACLES Obstacles only.
BOTH Collide with floors and obstacles.
Definition at line 33 of file graph_generator.h.
Function Documentation
CreateDirecs()
vector<pair> HF::GraphGenerator::CreateDirecs (int max_step_connections) [inline]
Create the set of directions to offset nodes in.
Parameters
max_step_connections value of MaxStepConnections to generate directions for.
Copies init_direcs then appends the output of permutations to it. If max_step_connections is 1, only init_direcs is returned.
Returns
Set of directions for the given max_step_connections.
See also
permutations to see how the value of max_step_connections influences generated steps.
Definition at line 78 of file graph_generator_private.cpp.
References init_directs, and permutations().
Referenced by HF::GraphGenerator::GraphGeneratorPrivate::CrawlGeom(), and HF::GraphGenerator::GraphGeneratorPrivate::CrawlGeomParallel().
permutations()
std::set< std::pair< int, int > > HF::GraphGenerator::permutations (int limit)
Create a set of every permutation for all numbers between 0 and limit.
Calculate P(n,r) as an array with each unique permutaton of 2 values being a pair.
Parameters
limit Highest number in the set
Returns
A list of all permutations for numbers 0 to limit.
Todo
Todo This can be optimized by using indexing instead of pushback.
Definition at line 43 of file graph_generator_private.cpp.
Referenced by CreateDirecs().
Variable Documentation
down
constexpr v3 HF::GraphGenerator::down { 0, 0, -1 } [constexpr]
Definition at line 27 of file graph_generator_private.cpp.
Referenced by HF::GraphGenerator::GraphGeneratorPrivate::CheckChildren(), HF::GraphGenerator::GraphGeneratorPrivate::CheckStart(), and HF::GraphGenerator::GraphGeneratorPrivate::WalkableCheck().
init_directs
const vector<pair> HF::GraphGenerator::init_directs [static]
Initial value:
= {
        pair(-1, -1), pair(-1, 0), pair(-1, 1),
        pair(0, -1), pair(0, 1), pair(1, -1),
        pair(1, 0), pair(1, 1)
    }
Definition at line 30 of file graph_generator_private.cpp.
Referenced by CreateDirecs().