HF::SpatialStructures::CostAlgorithms Namespace Reference
Functions
bool is_floating_type (std::string value)
double to_radians (double degrees)
double to_degrees (double radians)
std::vector< EdgeSet > CalculateEnergyExpenditure (Graph &g)
float calculate_magnitude (std::array< float, 3 > dir_a, std::array< float, 3 > dir_b)
float calculate_dot_product (std::array< float, 3 > dir_a, std::array< float, 3 > dir_b)
bool is_perpendicular (std::array< float, 3 > dir_a, std::array< float, 3 > dir_b)
Determines if dir_a and dir_b (vectors) are perpendicular, or not
Function Documentation
calculate_dot_product()
float HF::SpatialStructures::CostAlgorithms::calculate_dot_product (std::array< float, 3 > dir_a, std::array< float, 3 > dir_b)
Definition at line 42 of file cost_algorithms.cpp.
Referenced by is_perpendicular().
calculate_magnitude()
float HF::SpatialStructures::CostAlgorithms::calculate_magnitude (std::array< float, 3 > dir_a, std::array< float, 3 > dir_b)
Definition at line 38 of file cost_algorithms.cpp.
CalculateEnergyExpenditure()
std::vector<EdgeSet> HF::SpatialStructures::CostAlgorithms::CalculateEnergyExpenditure (Graph & g)
is_floating_type()
bool HF::SpatialStructures::CostAlgorithms::is_floating_type (std::string value)
Definition at line 24 of file cost_algorithms.cpp.
Referenced by HF::SpatialStructures::Graph::AddNodeAttribute().
is_perpendicular()
bool HF::SpatialStructures::CostAlgorithms::is_perpendicular (std::array< float, 3 > dir_a, std::array< float, 3 > dir_b)
Determines if dir_a and dir_b (vectors) are perpendicular, or not
Parameters
dir_a The starting position
dir_b The ending position
Returns
True, if dir_a and and dir_b have a dot product close to 0, false otherwise
// TODO example
Definition at line 46 of file cost_algorithms.cpp.
References calculate_dot_product(), and HF::SpatialStructures::ROUNDING_PRECISION.
to_degrees()
double HF::SpatialStructures::CostAlgorithms::to_degrees (double radians)
Definition at line 34 of file cost_algorithms.cpp.
to_radians()
double HF::SpatialStructures::CostAlgorithms::to_radians (double degrees)
Definition at line 30 of file cost_algorithms.cpp.