HF::Geometry Namespace Reference
Manipulate and load geometry from disk.
Classes
class MeshInfo
A collection of vertices and indices representing geometry.
Enumerations
enum GROUP_METHOD { ONLY_FILE = 0,
BY_GROUP = 1,
BY_MATERIAL = 2,
MATERIAL_AND_FILE = 3
 }
Method of grouping submeshes in OBJ files.
Functions
void IndexRawVertices (const vector< array< float, 3 >> &vertices, vector< int > &mapped_indexes, vector< float > &mapped_vertices)
Index an array of vertices.
float arrayDist (const array< float, 3 > from, const array< float, 3 > &to)
Calculate the distance between from and to.
vector< MeshInfo > LoadMeshObjects (std::string path, GROUP_METHOD gm=ONLY_FILE, bool change_coords=false)
Create MeshInfo instances from the OBJ at path.
vector< array< float, 3 > > LoadRawVertices (std::string path)
Load a list of vertices directly from an OBJ file.
std::string GetTestOBJPath (std::string key)
Get the path to the OBJ with the given key.
vector< MeshInfo > LoadMeshObjects (std::vector< std::string > &path, GROUP_METHOD gm=ONLY_FILE, bool change_coords=false)
Create MeshInfo instances from the OBJ files in path.
Variables
static robin_hood::unordered_map< string, string > test_model_paths
Detailed Description
Manipulate and load geometry from disk.
HF::Geometry contains all functionality in HumanFactors for dealing with mesh Geometry. The fundamental datatype of HF::Geometry is MeshInfo, which stores the vertices and indices of meshes as matricies in Eigen.
Remarks
Right now only OBJ files are supported for loading geometry from disk, however MeshInfo offers multiple constructors that accept arrays of vertices and indices so support for more formats can be developed.
See also
LoadMeshObjects to load OBJ files from disk.
MeshInfo for details on how HumanFactors represents Mesh geometry.
Enumeration Type Documentation
GROUP_METHOD
enum HF::Geometry::GROUP_METHOD
Method of grouping submeshes in OBJ files.
See also
LoadMeshObjects to use this enum.
Enumerator
ONLY_FILE Treat all the geometry in the file as a single mesh.
BY_GROUP Create a new MeshInfo instance for every OBJ group in the file.
BY_MATERIAL Create a new MeshInfo instance for every different material in the file.
MATERIAL_AND_FILE UNIMPLEMENTED.
Definition at line 53 of file objloader.h.
Function Documentation
arrayDist()
float HF::Geometry::arrayDist (const array< float, 3 > from, const array< float, 3 > & to)
Calculate the distance between from and to.
Parameters
from x,y,z position to calculate distance from.
to x,y,z position to calculate distance to.
Returns
The distance between from and to.
Definition at line 286 of file meshinfo.cpp.
Referenced by HF::Geometry::MeshInfo::operator==().
GetTestOBJPath()
std::string HF::Geometry::GetTestOBJPath (std::string key)
Get the path to the OBJ with the given key.
Parameters
key The name of the obj to get the path of
Returns
The path to the obj in key.
Exceptions
std::out_of_range if the given key couldn't be found
Definition at line 233 of file objloader.cpp.
References test_model_paths.
IndexRawVertices()
void HF::Geometry::IndexRawVertices (const vector< array< float, 3 >> & vertices, vector< int > & mapped_indexes, vector< float > & mapped_vertices)
Index an array of vertices.
Parameters
vertices An array of vertices for a mesh organized so every 3 vertices represents a triangle on the mesh.
mapped_indexes Output parameter for array of indicies
mapped_vertices Output parameter for vertex array.
Iterate through every array in vertices. If the x,y,z location in the array hasn't been seen yet, add its coordinates to mapped_vertices, assign it a unique ID in a an index hashmap, then add its id to mapped_indexes. IF it has been seen add the existing ID in the index hashmap to mapped_indexes.
Precondition
mapped_indexes and mapped_vertices are empty vectors of integers and floats respectively.
Postcondition
1) mapped_indexes contains an array of indexes for mapped_vertices where every 3 indices represents a different triangle on the mesh.
2) mapped_vertices contains an array of floats with each 3 vertices represent the x,y, and z coordinates for a different vertex in the mesh with no repeats.
Definition at line 70 of file meshinfo.cpp.
Referenced by HF::Geometry::MeshInfo::VectorsToBuffers().
LoadMeshObjects() [1/2]
std::vector< MeshInfo > HF::Geometry::LoadMeshObjects (std::string path, GROUP_METHOD gm = ONLY_FILE, bool change_coords = false)
Create MeshInfo instances from the OBJ at path.
Parameters
path Path to the OBJ to load.
gm Method for dividing the mesh into subobjects.
change_coords Rotate the mesh from Y-up to Z-up.
Returns
A vector of meshinfo from the file at path.
Exceptions
HF::Exceptions::InvalidOBJ The file at path was not a valid OBJ file.
HF::Exceptions::FileNotFound No file could be found at path.
std::exception gm did not match any valid GROUP_METHOD.
Todo
Todo the name of the mesh should probably just be the filename if the group type is ONLY_FILE.
Definitely some areas for minor speed gains by using indexing instead of .push_bcaks
Change std::exception to std::out_of_range.
Refactor this to break out whatever code can be repeated or reused. This has a McCabe complexity of 25!!!!
See also
GROUP_METHOD for more information about every different group method.
// be sure to #include "objloader.h", and #include <vector>
// relative path begins where EXE file is located if file_path is not a path to a
// valid OBJ file, HF::Exceptions::FileNotFound is thrown
std::string file_path = "big_teapot.obj";
// meshvec is a vector of meshinfo from file_path
std::vector<HF::Geometry::MeshInfo> meshvec = HF::Geometry::LoadMeshObjects(file_path,
HF::Geometry::GROUP_METHOD::ONLY_FILE, false);
// retrieve the MeshInfo
HF::Geometry::MeshInfo info = meshvec[0];
Definition at line 33 of file objloader.cpp.
References BY_GROUP, BY_MATERIAL, and ONLY_FILE.
Referenced by LoadMeshObjects(), and LoadOBJ().
LoadMeshObjects() [2/2]
std::vector< MeshInfo > HF::Geometry::LoadMeshObjects (std::vector< std::string > & path, GROUP_METHOD gm = ONLY_FILE, bool change_coords = false)
Create MeshInfo instances from the OBJ files in path.
Parameters
path Path to the OBJ to load.
gm Method for dividing the mesh into subobjects.
change_coords Rotate the mesh from Y-up to Z-up.
Returns
A vector of meshinfo loaded from the files at path.
Exceptions
HF::Exceptions::InvalidOBJ One or more of the files in paths was not a valid OBJ file.
HF::Exceptions::FileNotFound Could not find one or more of the files at path.
std::exception gm did not match any valid GROUP_METHOD.
// be sure to #include "objloader.h", and #include <vector>
// Prepare the file paths
const auto PATH_0 = "big_teapot.obj";
const auto PATH_1 = "plane.obj";
const auto PATH_2 = "sibenik.obj";
// PATH_0, PATH_1, and PATH_2 each represent a path to an OBJ file. Note that if any
// path in pathvec is invalid, HF::Exceptions::FileNotFound will be thrown when
// LoadMeshObjects is called
std::vector<std::string> pathvec = { PATH_0, PATH_1, PATH_2 };
// The overload for LoadMeshObjects is called for each member (which is an OBJ file
// path) in pathvec, then IDs are reassigned for each MeshInfo object within the
// std::vector<MeshInfo> that is returned
std::vector<HF::Geometry::MeshInfo> meshvec = HF::Geometry::LoadMeshObjects(pathvec, HF::Geometry::GROUP_METHOD::ONLY_FILE, false);
std::cout << "Total loaded: " << meshvec.size() << std::endl;
// Print IDs of all mesh info
for (auto mesh_info : meshvec) {
    std::cout << "Mesh ID: " << mesh_info.GetMeshID() << std::endl;
}
Definition at line 238 of file objloader.cpp.
References LoadMeshObjects().
LoadRawVertices()
std::vector< std::array< float, 3 > > HF::Geometry::LoadRawVertices (std::string path)
Load a list of vertices directly from an OBJ file.
Parameters
path Location of the OBJ to load on disk.
Returns
A vector of x,y,z positions for each vertex of each face of the OBJ. Every 3 vertices form a single triangle. on the mesh.
Remarks
This is an alternative to the function that returns an instance of MeshInfo. Mostly for testing, since it uses a vertex array instead of an index array, making the end product take up more space in memory.
Exceptions
HF::Exceptions::InvalidOBJ path did not lead to a valid OBJ file.
Todo
Todo Check if the file exists then thow file not found exception instead of invalidobj.
// be sure to #include "objloader.h", and #include <vector>
// Note that filepath must lead to a valid OBJ file, or HF::Exceptions::InvalidOBJ will
// be thrown when Geometry::LoadMeshObjects is called
std::string filepath = "plane.obj";
// Vertices now contains the raw vertices loaded from the OBJ file specified at filepath
std::vector<std::array<float, 3>> vertices = HF::Geometry::LoadRawVertices(filepath);
// Display the vertices from filepath
std::cout << "Vertices from " << filepath << ": " << std::endl;
for (auto vertex : vertices) {
    std::cout << "(" << vertex[0] << ", " << vertex[1] << ", " << vertex[2] << ")" << std::endl;
}
Definition at line 197 of file objloader.cpp.
Variable Documentation
test_model_paths
robin_hood::unordered_map<string, string> HF::Geometry::test_model_paths [static]
Initial value:
{
        {"teapot", "teapot.obj"},
        {"plane", "plane.obj" },
        {"big teapot", "big_teapot.obj" },
        {"energy blob", "energy_blob.obj" },
        {"sibenik", "sibenik.obj" },
    }
Definition at line 25 of file objloader.cpp.
Referenced by GetTestOBJPath().