VisibilityGraph
Determine which points are visibile from other points in space.
Functions
C_INTERFACE CreateVisibilityGraphAllToAll (HF::RayTracer::EmbreeRayTracer *ert, const float *nodes, int num_nodes, HF::SpatialStructures::Graph **out_graph, float height)
Create a new directed visibility graph between all nodes in nodes.
C_INTERFACE CreateVisibilityGraphAllToAllUndirected (HF::RayTracer::EmbreeRayTracer *ert, const float *nodes, int num_nodes, HF::SpatialStructures::Graph **out_graph, float height, const int cores)
Create a new undirected visibility graph between all nodes in nodes.
C_INTERFACE CreateVisibilityGraphGroupToGroup (HF::RayTracer::EmbreeRayTracer *ert, const float *group_a, const int size_a, const float *group_b, const int size_b, HF::SpatialStructures::Graph **out_graph, float height)
Create a new visibility from the nodes in group_a to the nodes in group_b.
Detailed Description
Determine which points are visibile from other points in space.
Function Documentation
CreateVisibilityGraphAllToAll()
C_INTERFACE CreateVisibilityGraphAllToAll (HF::RayTracer::EmbreeRayTracer * ert, const float * nodes, int num_nodes, HF::SpatialStructures::Graph ** out_graph, float height)
#include <Cinterface/visibility_graph_C.h>
Create a new directed visibility graph between all nodes in nodes.
Parameters
ert The raytracer to fire rays from.
nodes Nodes to use in generating the visibility graph. Every 3 floats should represent a single point
num_nodes Nodes to use in generating the visibility graph. Should be equal to a the length of nodes/3 since every 3 floats represents a single point.
nodes Nodes to use in generating the visibility graph.
out_graph Output parameter for the completed graph.
height How far to offset nodes from the ground.
Returns
HS_STATUS::OK on completion.
Definition at line 16 of file visibility_graph_C.cpp.
References HF::VisibilityGraph::AllToAll(), ConvertRawFloatArrayToPoints(), and HF::Exceptions::OK.
CreateVisibilityGraphAllToAllUndirected()
C_INTERFACE CreateVisibilityGraphAllToAllUndirected (HF::RayTracer::EmbreeRayTracer * ert, const float * nodes, int num_nodes, HF::SpatialStructures::Graph ** out_graph, float height, const int cores)
#include <Cinterface/visibility_graph_C.h>
Create a new undirected visibility graph between all nodes in nodes.
Parameters
ert The raytracer to fire rays from.
nodes Nodes to use in generating the visibility graph. Every 3 floats should represent a single point
num_nodes Nodes to use in generating the visibility graph. Should be equal to a the length of nodes/3 since every 3 floats represents a single point.
nodes Nodes to use in generating the visibility graph.
out_graph Output parameter for the completed graph.
height How far to offset nodes from the ground.
Returns
HS_STATUS::OK on completion.
Definition at line 40 of file visibility_graph_C.cpp.
References HF::VisibilityGraph::AllToAllUndirected(), ConvertRawFloatArrayToPoints(), and HF::Exceptions::OK.
CreateVisibilityGraphGroupToGroup()
C_INTERFACE CreateVisibilityGraphGroupToGroup (HF::RayTracer::EmbreeRayTracer * ert, const float * group_a, const int size_a, const float * group_b, const int size_b, HF::SpatialStructures::Graph ** out_graph, float height)
#include <Cinterface/visibility_graph_C.h>
Create a new visibility from the nodes in group_a to the nodes in group_b.
Parameters
ert The raytracer to fire rays from.
group_a Nodes to fire from. Every 3 floats should represent a single point.
size_a Number of nodes in group_a. Should be equal to a the length of group_a/3 since every 3 floats represents a single point.
group_b Nodes to fire to. Every 3 floats should represent a single point.
size_b Number of nodes in group_b. Should be equal to a the length of group_b/3 since every 3 floats represents a single point.
out_graph Output parameter for the completed graph.
height How far to offset nodes from the ground.
Returns
HS_STATUS::OK on completion.
Definition at line 64 of file visibility_graph_C.cpp.
References ConvertRawFloatArrayToPoints(), HF::VisibilityGraph::GroupToGroup(), HF::Exceptions::NO_GRAPH, and HF::Exceptions::OK.