SpatialStructures
Contains the Graph and Node datatypes.
Functions
C_INTERFACE GetAllNodesFromGraph (const HF::SpatialStructures::Graph *graph, std::vector< HF::SpatialStructures::Node > **out_vector_ptr, HF::SpatialStructures::Node **out_data_ptr)
Get a vector of every node in the given graph pointer.
C_INTERFACE GetEdgesForNode (const HF::SpatialStructures::Graph *graph, const HF::SpatialStructures::Node *Node, std::vector< HF::SpatialStructures::Edge > **out_vector_ptr, HF::SpatialStructures::Edge **out_edge_list_ptr, int *out_edge_list_size)
C_INTERFACE GetSizeOfNodeVector (const std::vector< HF::SpatialStructures::Node > *node_list, int *out_size)
Get the size of a node vector.
C_INTERFACE GetSizeOfEdgeVector (const std::vector< HF::SpatialStructures::Edge > *edge_list, int *out_size)
C_INTERFACE AggregateCosts (const HF::SpatialStructures::Graph *graph, int agg, bool directed, std::vector< float > **out_vector_ptr, float **out_data_ptr)
Get an ordered array of costs for each node aggregatted by the desired method.
C_INTERFACE CreateGraph (const float *nodes, int num_nodes, HF::SpatialStructures::Graph **out_graph)
Create a new empty graph.
C_INTERFACE AddEdgeFromNodes (HF::SpatialStructures::Graph *graph, const float *parent, const float *child, float score)
Add an edge between parent and child. If parent or child doesn't already exist in the graph, they will be added and automatically assigned new IDS.
C_INTERFACE AddEdgeFromNodeIDs (HF::SpatialStructures::Graph *graph, int parent_id, int child_id, float score)
Create a new edge between parent_id and child_id. If these IDs don't yet exist in the graph they will be added.
C_INTERFACE GetCSRPointers (HF::SpatialStructures::Graph *graph, int *out_nnz, int *out_num_rows, int *out_num_cols, float **out_data_ptr, int **out_inner_indices_ptr, int **out_outer_indices_ptr)
Retrieve all information for a graph's CSR representation. This will compress the graph if it was not yet already compressed.
C_INTERFACE GetNodeID (HF::SpatialStructures::Graph *graph, const float *point, int *out_id)
Get the id of the given node in the graph. If the node does not exist, out_id will be set to -1.
C_INTERFACE Compress (HF::SpatialStructures::Graph *graph)
Compress the given graph into a csr representation.
C_INTERFACE ClearGraph (HF::SpatialStructures::Graph *graph)
Clear the nodes/edges for the given graph.
C_INTERFACE DestroyNodes (std::vector< HF::SpatialStructures::Node > *nodelist_to_destroy)
Delete the vector of nodes at the given pointer.
C_INTERFACE DestroyEdges (std::vector< HF::SpatialStructures::Edge > *edgelist_to_destroy)
Delete the vector of edges at the given pointer.
C_INTERFACE DestroyGraph (HF::SpatialStructures::Graph *graph_to_destroy)
Delete a graph.
C_INTERFACE AddNodeAttributes (HF::SpatialStructures::Graph *g, const int *ids, const char *attribute, const char **scores, int num_nodes)
Calculates and stores cross slope for all edges in Graph g
C_INTERFACE GetNodeAttributes (const HF::SpatialStructures::Graph *g, const char *attribute, char ***out_scores, int *out_score_size)
Attribute should be the name of the attribute to get from the graph. Memory shall be allocated in *out_scores to hold the char arrays. out_scores is a pointer to an array of pointers to char arrays, which will be allocated by the caller. The caller must call DeleteScores to deallocate these node scores. out_score_size should be updated to the length of the score array.
C_INTERFACE DeleteScoreArray (char ***scores_to_delete, int num_char_arrays)
Free the memory of every char array in scores_to_delete. The length of each contained char array should be determined by using strlen on the given array unless they are not delimited.
C_INTERFACE ClearAttributeType (HF::SpatialStructures::Graph *g, const char *s)
Deletes the contents of that attribute type in the graph
Detailed Description
Contains the Graph and Node datatypes.
Function Documentation
AddEdgeFromNodeIDs()
C_INTERFACE AddEdgeFromNodeIDs (HF::SpatialStructures::Graph * graph, int parent_id, int child_id, float score)
#include <Cinterface/spatialstructures_C.h>
Create a new edge between parent_id and child_id. If these IDs don't yet exist in the graph they will be added.
Parameters
graph Graph to create the new edge in.
parent The parent's id in the graph.
child The child's id in the graph.
score The cost from parent to child.
returns HF_STATUS::OK on completion.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
const int id0 = 0;
const int id1 = 1;
const float distance = 3;
AddEdgeFromNodeIDs(g, id0, id1, distance);
// Release memory for g after use
DestroyGraph(g);
Definition at line 99 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::addEdge(), and HF::Exceptions::OK.
AddEdgeFromNodes()
C_INTERFACE AddEdgeFromNodes (HF::SpatialStructures::Graph * graph, const float * parent, const float * child, float score)
#include <Cinterface/spatialstructures_C.h>
Add an edge between parent and child. If parent or child doesn't already exist in the graph, they will be added and automatically assigned new IDS.
Parameters
graph Graph to add the new edge to.
parent A 3 element float array containing the x, y, and z coordinate of the parent node.
child A 3 element float array containing the x, y, and z coordinate of the child node,
score The cost from parent to child
Returns
HF_STATUS::OK on success. HF_STATUS::INVALID_PTR on an invalidparent or child node.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
float n0[] = { 0, 0, 0 };
float n1[] = { 0, 1, 2 };
const float distance = 3;
AddEdgeFromNodes(g, n0, n1, distance);
// Release memory for g after use
DestroyGraph(g);
Definition at line 79 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::Exceptions::INVALID_PTR, and HF::Exceptions::OK.
AddNodeAttributes()
C_INTERFACE AddNodeAttributes (HF::SpatialStructures::Graph * g, const int * ids, const char * attribute, const char ** scores, int num_nodes)
#include <Cinterface/spatialstructures_C.h>
Calculates and stores cross slope for all edges in Graph g
Parameters
g The Graph to calculate and store cross slopes from
Returns
HF::STATUS::OK on completion
Add a new node attribute in the graph for the node at id. Returns an error code if the specified node doesn't exist in the graph. score and ids both point to arrays allocated by the caller which should be able to be passed to AddNodeAttributes.
Parameters
g The graph that will receive attributes
ids Array of int, allocated by caller, represents node IDs
attribute The attribute to add to the graph
scores Array of (char *), allocated by caller
num_nodes Block count of scores
Returns
HF_STATUS::OK on completion
Definition at line 167 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::AddNodeAttributes(), and HF::Exceptions::OK.
AggregateCosts()
C_INTERFACE AggregateCosts (const HF::SpatialStructures::Graph * graph, int agg, bool directed, std::vector< float > ** out_vector_ptr, float ** out_data_ptr)
#include <Cinterface/spatialstructures_C.h>
Get an ordered array of costs for each node aggregatted by the desired method.
Parameters
graph Graph to aggregare edges from.
agg Aggregation type to use.
directed If true, only count outgoing edges for a node, otherwise count both outgoing and incoming edges.
out_vector_ptr Output parameter for the vector.
out_vector_ptr Output parameter for the vector's held data.
Returns
HF_STATUS::OK if successful. If the graph wasn't valid HF_STATUS::NO_GRAPH.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
float n0[] = { 0, 0, 0 };
float n1[] = { 0, 1, 2 };
float n2[] = { 0, 1, 3 };
AddEdgeFromNodes(g, n0, n1, 1);
AddEdgeFromNodes(g, n0, n2, 2);
AddEdgeFromNodes(g, n1, n0, 3);
AddEdgeFromNodes(g, n1, n2, 4);
AddEdgeFromNodes(g, n2, n0, 5);
AddEdgeFromNodes(g, n2, n1, 6);
std::vector<float>* out_vector = nullptr;
float* out_data = nullptr;
int aggregation_type = 0;
AggregateCosts(g, aggregation_type, false, &out_vector, &out_data);
DestroyGraph(g);
Definition at line 50 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::AggregateGraph(), HF::Exceptions::NO_GRAPH, and HF::Exceptions::OK.
ClearAttributeType()
C_INTERFACE ClearAttributeType (HF::SpatialStructures::Graph * g, const char * s)
#include <Cinterface/spatialstructures_C.h>
Deletes the contents of that attribute type in the graph
Parameters
g The graph from which attributes of type s will be delete
s The attribute to be cleared from within g
Returns
HF_STATUS::OK on completion
Definition at line 266 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::ClearNodeAttributes(), and HF::Exceptions::OK.
ClearGraph()
C_INTERFACE ClearGraph (HF::SpatialStructures::Graph * graph)
#include <Cinterface/spatialstructures_C.h>
Clear the nodes/edges for the given graph.
Parameters
graph Graph to clear nodes from.
Returns
HF_STATUS::OK on completion.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
float n0[] = { 0, 0, 0 };
float n1[] = { 0, 1, 2 };
const float distance = 3;
AddEdgeFromNodes(g, n0, n1, distance);
ClearGraph(g);
// Release memory for g after use
DestroyGraph(g);
Definition at line 143 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::Clear(), and HF::Exceptions::OK.
Compress()
C_INTERFACE Compress (HF::SpatialStructures::Graph * graph)
#include <Cinterface/spatialstructures_C.h>
Compress the given graph into a csr representation.
Returns
HF_STATUS::OK on completion.
This will reduce the memory footprint of the graph, and invalidate all existing CSR representations of it. If the graph is already compressed, this will be a no-op.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
float n0[] = { 0, 0, 0 };
float n1[] = { 0, 1, 2 };
float n2[] = { 0, 1, 3 };
AddEdgeFromNodes(g, n0, n1, 1);
AddEdgeFromNodes(g, n0, n2, 2);
AddEdgeFromNodes(g, n1, n0, 3);
AddEdgeFromNodes(g, n1, n2, 4);
AddEdgeFromNodes(g, n2, n0, 5);
AddEdgeFromNodes(g, n2, n1, 6);
Compress(g);
// data = { 1, 2, 3, 4, 5, 6 }
// r = { 0, 2, 4 }
// c = { 1, 2, 0, 2, 0, 1 }
// Release memory for g after use
DestroyGraph(g);
Definition at line 137 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::Compress(), and HF::Exceptions::OK.
Referenced by HF::SpatialStructures::Graph::GetCSRPointers().
CreateGraph()
C_INTERFACE CreateGraph (const float * nodes, int num_nodes, HF::SpatialStructures::Graph ** out_graph)
#include <Cinterface/spatialstructures_C.h>
Create a new empty graph.
Parameters
nodes Unused.
num_nodes Unused.
out_graph Output parameter to store the graph in.
Returns
HF_STATUS::OK on completion.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
// use Graph
// Release memory for g after use
DestroyGraph(g);
Definition at line 68 of file spatialstructures_C.cpp.
References HF::Exceptions::OK.
DeleteScoreArray()
C_INTERFACE DeleteScoreArray (char *** scores_to_delete, int num_char_arrays)
#include <Cinterface/spatialstructures_C.h>
Free the memory of every char array in scores_to_delete. The length of each contained char array should be determined by using strlen on the given array unless they are not delimited.
Parameters
scores_to_delete Pointer to array of pointers to char arrays, allocated by caller
num_char_arrays Block count of scores_to_delete
Returns
HF_STATUS::OK on completion
Definition at line 245 of file spatialstructures_C.cpp.
References HF::Exceptions::OK.
DestroyEdges()
C_INTERFACE DestroyEdges (std::vector< HF::SpatialStructures::Edge > * edgelist_to_destroy)
#include <Cinterface/spatialstructures_C.h>
Delete the vector of edges at the given pointer.
Parameters
edgelist_to_destroy Vector of nodes to destroy.
Returns
HF_STATUS::OK on completion.
// Requires #include "node.h", #include <vector>
HF::SpatialStructures::Node n0(0, 0, 0);
HF::SpatialStructures::Node n1(0, 1, 1);
HF::SpatialStructures::Node n2(0, 1, 2);
HF::SpatialStructures::Node n3(1, 2, 3);
HF::SpatialStructures::Edge e0(n1); // parent is n0
HF::SpatialStructures::Edge e1(n3); // parent is n2
auto edge_vec = new std::vector<HF::SpatialStructures::Edge>{ e0, e1 };
// Use edge_vec
DestroyEdges(edge_vec);
Definition at line 75 of file CInterface.cpp.
References HF::Exceptions::OK.
DestroyGraph()
C_INTERFACE DestroyGraph (HF::SpatialStructures::Graph * graph_to_destroy)
#include <Cinterface/spatialstructures_C.h>
Delete a graph.
Parameters
graph_to_destroy Graph to delete.
Returns
HF_STATUS::OK on completion.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
// use Graph
// Release memory for g after use
DestroyGraph(g);
Definition at line 80 of file CInterface.cpp.
References HF::Exceptions::OK.
DestroyNodes()
C_INTERFACE DestroyNodes (std::vector< HF::SpatialStructures::Node > * nodelist_to_destroy)
#include <Cinterface/spatialstructures_C.h>
Delete the vector of nodes at the given pointer.
Parameters
nodelist_to_destroy Vector of nodes to destroy.
Returns
HF_STATUS::OK on completion.
// Requires #include "node.h", #include <vector>
HF::SpatialStructures::Node n0(0, 0, 0);
HF::SpatialStructures::Node n1(0, 1, 1);
HF::SpatialStructures::Node n2(0, 1, 2);
HF::SpatialStructures::Node n3(1, 2, 3);
auto node_vec = new std::vector<HF::SpatialStructures::Node>{ n0, n1, n2, n3 };
// Use node_vec
DestroyNodes(node_vec);
Definition at line 70 of file CInterface.cpp.
References HF::Exceptions::OK.
GetAllNodesFromGraph()
C_INTERFACE GetAllNodesFromGraph (const HF::SpatialStructures::Graph * graph, std::vector< HF::SpatialStructures::Node > ** out_vector_ptr, HF::SpatialStructures::Node ** out_data_ptr)
#include <Cinterface/spatialstructures_C.h>
Get a vector of every node in the given graph pointer.
Parameters
graph Graph to retrieve nodes from.
out_vector_ptr Output parameter for the new vector.
out_data_ptr Output parameter for the vector's data.
Returns
HF_STATUS::INVALID_PTR if the given pointer was invalid. HF::GENERIC_ERROR if the graph is not valid. HF::OK if successful.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
float n0[] = { 0, 0, 0 };
float n1[] = { 0, 1, 2 };
float n2[] = { 0, 1, 3 };
AddEdgeFromNodes(g, n0, n1, 1);
AddEdgeFromNodes(g, n0, n2, 2);
AddEdgeFromNodes(g, n1, n0, 3);
AddEdgeFromNodes(g, n1, n2, 4);
AddEdgeFromNodes(g, n2, n0, 5);
AddEdgeFromNodes(g, n2, n1, 6);
auto out_vec = new std::vector<HF::SpatialStructures::Node>;
HF::SpatialStructures::Node* out_data = nullptr;
GetAllNodesFromGraph(g, &out_vec, &out_data);
DestroyGraph(g);
Definition at line 16 of file spatialstructures_C.cpp.
References HF::Exceptions::GENERIC_ERROR, HF::Exceptions::INVALID_PTR, HF::SpatialStructures::Graph::Nodes(), and HF::Exceptions::OK.
GetCSRPointers()
C_INTERFACE GetCSRPointers (HF::SpatialStructures::Graph * graph, int * out_nnz, int * out_num_rows, int * out_num_cols, float ** out_data_ptr, int ** out_inner_indices_ptr, int ** out_outer_indices_ptr)
#include <Cinterface/spatialstructures_C.h>
Retrieve all information for a graph's CSR representation. This will compress the graph if it was not yet already compressed.
Parameters
out_nnz Number of non-zeros contained within the graph.
out_num_rows Number of rows contained within the graph.
out_num_rows Number of columns contained within the graph.
out_data_ptr Pointer to the graph's data array.
out_inner_indices_ptr Pointer to the graph's inner indices array.
out_inner_indices_ptr Pointer to the graph's outer indices array.
Returns
HF_STATUS::OK on completion.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
float n0[] = { 0, 0, 0 };
float n1[] = { 0, 1, 2 };
float n2[] = { 0, 1, 3 };
AddEdgeFromNodes(g, n0, n1, 1);
AddEdgeFromNodes(g, n0, n2, 2);
AddEdgeFromNodes(g, n1, n0, 3);
AddEdgeFromNodes(g, n1, n2, 4);
AddEdgeFromNodes(g, n2, n0, 5);
AddEdgeFromNodes(g, n2, n1, 6);
Compress(g);
// data = { 1, 2, 3, 4, 5, 6 }
// r = { 0, 2, 4 }
// c = { 1, 2, 0, 2, 0, 1 }
// Retrieve the CSR from the graph
CSRPtrs csr;
GetCSRPointers(g, &csr.nnz, &csr.rows, &csr.cols, &csr.data, &csr.inner_indices, &csr.outer_indices);
// Release memory for g after use
DestroyGraph(g);
Definition at line 104 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::GetCSRPointers(), HF::SpatialStructures::CSRPtrs::nnz, and HF::Exceptions::OK.
GetEdgesForNode()
C_INTERFACE GetEdgesForNode (const HF::SpatialStructures::Graph * graph, const HF::SpatialStructures::Node * Node, std::vector< HF::SpatialStructures::Edge > ** out_vector_ptr, HF::SpatialStructures::Edge ** out_edge_list_ptr, int * out_edge_list_size)
#include <Cinterface/spatialstructures_C.h>
GetNodeAttributes()
C_INTERFACE GetNodeAttributes (const HF::SpatialStructures::Graph * g, const char * attribute, char *** out_scores, int * out_score_size)
#include <Cinterface/spatialstructures_C.h>
Attribute should be the name of the attribute to get from the graph. Memory shall be allocated in *out_scores to hold the char arrays. out_scores is a pointer to an array of pointers to char arrays, which will be allocated by the caller. The caller must call DeleteScores to deallocate these node scores. out_score_size should be updated to the length of the score array.
Parameters
g The graph that will be used to retrieve attributes
attribute The attribute to retrieve from g
out_scores Pointer to array of pointers to char arrays, allocated by the caller
out_score_size Keeps track of the length of the out_scores buffer, updated as needed
Returns
HF_STATUS::OK on completion
Definition at line 186 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::GetNodeAttributes(), and HF::Exceptions::OK.
GetNodeID()
C_INTERFACE GetNodeID (HF::SpatialStructures::Graph * graph, const float * point, int * out_id)
#include <Cinterface/spatialstructures_C.h>
Get the id of the given node in the graph. If the node does not exist, out_id will be set to -1.
Parameters
graph The graph to get the ID from.
point A 3 float array containing the x,y, and z coordinates of the point to get the ID for.
out_id Output parameter for the id. Set to -1 if that point couldn't be found in graph
Returns
HF_STATUS::OK on completion.
// Requires #include "graph.h"
HF::SpatialStructures::Graph* g = nullptr;
// parameters nodes and num_nodes are unused, according to documentation
if (CreateGraph(nullptr, -1, &g)) {
    std::cout << "Graph creation successful";
}
else {
    std::cout << "Graph creation failed" << std::endl;
}
float n0[] = { 0, 0, 0 };
float n1[] = { 0, 1, 2 };
const float distance = 3;
AddEdgeFromNodes(g, n0, n1, distance);
float point[] = { 0, 1, 2 };
int result_id = -1;
GetNodeID(g, point, &result_id);
// Release memory for g after use
DestroyGraph(g);
Definition at line 126 of file spatialstructures_C.cpp.
References HF::SpatialStructures::Graph::getID(), and HF::Exceptions::OK.
GetSizeOfEdgeVector()
C_INTERFACE GetSizeOfEdgeVector (const std::vector< HF::SpatialStructures::Edge > * edge_list, int * out_size)
#include <Cinterface/spatialstructures_C.h>
Definition at line 65 of file CInterface.cpp.
References HF::Exceptions::OK.
GetSizeOfNodeVector()
C_INTERFACE GetSizeOfNodeVector (const std::vector< HF::SpatialStructures::Node > * node_list, int * out_size)
#include <Cinterface/spatialstructures_C.h>
Get the size of a node vector.
Parameters
node_list Node vector to get the size from.
out_size Size of the vector will be written to this int.
Returns
HF_STATUS::OK on completion.
// Requires #include "node.h", #include <vector>
HF::SpatialStructures::Node n0(0, 0, 0);
HF::SpatialStructures::Node n1(0, 1, 1);
HF::SpatialStructures::Node n2(0, 1, 2);
HF::SpatialStructures::Node n3(1, 2, 3);
std::vector<HF::SpatialStructures::Node> node_vec{ n0, n1, n2, n3 };
int node_vec_size = -1;
GetSizeOfNodeVector(&node_vec, &node_vec_size);
DestroyNodes(node_vec);
Definition at line 60 of file CInterface.cpp.
References HF::Exceptions::OK.