HF::SpatialStructures Namespace Reference
Contains standard fundamental data structures for representing space used throughout HumanFactors.
Namespaces
 CostAlgorithms
Classes
struct CSRPtrs
A struct to hold all necessary information for a CSR.
struct Edge
A connection to a child node.
struct EdgeSet
A collection of edges and a parent. More...
class Graph
A Graph of nodes connected by edges that supports both integers and HF::SpatialStructures::Node.
struct IntEdge
A lighter version of Edge that contains an ID instead of a full node object.. More...
struct Node
A point in space with an ID.
struct Path
A collection of nodes that form a path.
struct PathMember
The ID of a node, and the cost cost to the node after it.
Enumerations
enum STEP {
NOT_CONNECTED = 0,
NONE = 1,
UP = 2,
DOWN = 3,
OVER = 4
 }
Describes the type of step an edge connects to.
enum COST_AGGREGATE : int { COST_AGGREGATE::SUM = 0,
COST_AGGREGATE::AVERAGE = 1,
COST_AGGREGATE::COUNT = 2
 }
Methods of aggregating the costs for edges for each node in the graph.
enum NODE_TYPE { GRAPH = 0,
POI = 1,
OTHER = 2
 }
The type of node this is.
Functions
float roundhf (float f)
Round a a float to the nearest ROUNDING_PRECISION.
void Aggregate (float &out_total, float new_value, const COST_AGGREGATE agg_type, int &count)
Aggregate new_value into out_total using the method specified in agg_type.
void Normalize (std::array< float, 3 > &vector)
Variables
constexpr float ROUNDING_PRECISION = 0.0001f
Minimum value that can be represented in humanfactors.
Detailed Description
Contains standard fundamental data structures for representing space used throughout HumanFactors.
Remarks
The datatypes in the SpatialStructures Namespace are used throughout the HumanFactors library. For example, the HF::GraphGenerator and HF::VisibilityGraph both produce a Graph as output, allowing for the code to manage the Graph's internal CSR to be centralized in a single location.
Class Documentation
struct HF::SpatialStructures::EdgeSet
A collection of edges and a parent.
Remarks
This can to represent a node and its edges without repeating any information such as parent_id or node objects.
Definition at line 66 of file Edge.h.
Class Members
vector< IntEdge >
children
vector of IntEdge (children)
int
parent
Identifier of parent node.
struct HF::SpatialStructures::IntEdge
A lighter version of Edge that contains an ID instead of a full node object..
Definition at line 55 of file Edge.h.
Class Members
int
child
Identifier of child node.
float
weight
Cost to traverse to child.
Enumeration Type Documentation
COST_AGGREGATE
enum HF::SpatialStructures::COST_AGGREGATE : int [strong]
Methods of aggregating the costs for edges for each node in the graph.
See also
Graph.AggregateGraph() for details on how to use this enum.
Enumerator
SUM Add the cost of all edges.
AVERAGE Average the cost of all edges.
COUNT Count how many edges this node has.
Definition at line 23 of file graph.h.
NODE_TYPE
enum HF::SpatialStructures::NODE_TYPE
The type of node this is.
Remarks
This was primarially used in the previous codebase to differentiate the different types of nodes in the database. Since the database is not implemented here, this goes entirely unused.
Enumerator
GRAPH This node is a graph node.
POI POI is 'point of interest'.
OTHER This node doesn't belong in any other category.
Definition at line 29 of file node.h.
STEP
enum HF::SpatialStructures::STEP
Describes the type of step an edge connects to.
Enumerator
NOT_CONNECTED No connection between parent and child.
NONE Parent and child are on the same plane and no step is required.
UP A step up is required to get from parent to child.
DOWN A step down is required to get from parent to child.
OVER A step over something is required to get from parent to child.
Definition at line 15 of file Edge.h.
Function Documentation
Aggregate()
void HF::SpatialStructures::Aggregate (float & out_total, float new_value, const COST_AGGREGATE agg_type, int & count) [inline]
Aggregate new_value into out_total using the method specified in agg_type.
Parameters
out_total Total to aggregate new_value into.
new_value Value to aggregate into out_total.
agg_type Aggregation method to use.
count Number of elements. Incremented with each call.
Exceptions
std::out_of_range agg_type doesn't exist in COST_AGGREgATE
Remarks
This is similar to the function from ViewAnalysis but will increment count with each call.
See also
COST_AGGREGATE for more information on each aggregate type.
Definition at line 132 of file graph.cpp.
Referenced by HF::SpatialStructures::Graph::AggregateGraph().
Normalize()
void HF::SpatialStructures::Normalize (std::array< float, 3 > & vector)
Definition at line 123 of file node.cpp.
Referenced by HF::SpatialStructures::Node::directionTo().
roundhf()
float HF::SpatialStructures::roundhf (float f)
Round a a float to the nearest ROUNDING_PRECISION.
Parameters
f The desired float to round.
Returns
f rounded to the nearest rounding_precision.
// be sure to #include "Constants.h" std::round from the cmath library is used in
// roundhf. Precision is to the nearest ten-thousandth
const float my_pi = 3.141592653589793238462643383279502884197169399375105820974944592307816406286;
float rounded = HF::SpatialStructures::roundhf(my_pi); // rounded == 3.1416
Definition at line 13 of file Constants.cpp.
References ROUNDING_PRECISION.
Referenced by HF::GraphGenerator::GraphGeneratorPrivate::BuildNetwork(), and HF::GraphGenerator::GraphGeneratorPrivate::GeneratePotentialChildren().
Variable Documentation
ROUNDING_PRECISION
constexpr float HF::SpatialStructures::ROUNDING_PRECISION = 0.0001f [constexpr]
Minimum value that can be represented in humanfactors.
All rounding operations in HF::SpatialStructures will use this constant in rounding operations.
Definition at line 29 of file Constants.h.
Referenced by HF::VisibilityGraph::HeightCheck(), HF::SpatialStructures::CostAlgorithms::is_perpendicular(), HF::SpatialStructures::PathMember::operator==(), HF::SpatialStructures::Node::operator==(), and roundhf().