HF::AnalysisMethods::GraphGeneratorPrivate Class Reference
Contains the private implementation of the graph generator so clients aren't forced to recompile
#include <graph_generator_private.h>
Public Member Functions
GraphGeneratorPrivate (GraphGenerator &GG)
Default constructor
HF::SpatialStructures::Graph BuildNetwork ()
TODO description
Private Member Functions
bool WalkableCheck (const SpatialStructures::Node &position)
Invokes CheckRay using a temporary instance of v3 (named testpos), constructed from position
void Graphdirecs (const SpatialStructures::Node &parent, const std::vector< std::pair< int, int >> &directions, std::vector< SpatialStructures::Node > &out_children)
Calculate positions for every direction pair in directions, then deposit in out children
bool CheckStart (v3 &start)
void GeneratePotentialChildren (const HF::SpatialStructures::Node &parent, const std::vector< std::pair< int, int >> &directions, std::vector< HF::SpatialStructures::Node > &out_children)
Populate out_children with a potential child position for every direction in directions.
void CrawlGeom (UniqueQueue &todo)
Populate the graph with with nodes and edges
void CrawlGeomParallel (UniqueQueue &todo)
A parallel version of CrawlGeom
void ComputerParent (const HF::SpatialStructures::Node &parent, const std::vector< std::pair< int, int >> &directions, std::vector< HF::SpatialStructures::Edge > &out_relations)
Ranks children then stores relations?
bool CheckRay (HF::SpatialStructures::Node &position, const v3 &direction, HIT_FLAG flag=HIT_FLAG::BOTH)
Fire a ray using the Embree Ray Tracer
bool CheckRay (v3 &position, const v3 &direction, HIT_FLAG flag=HIT_FLAG::BOTH)
Fire a ray using the Embree Ray Tracer
bool OcclusionCheck (const SpatialStructures::Node &parent, const SpatialStructures::Node &child)
Check if parent has a line of sight to child within max_dist
bool CheckFloor (const HF::SpatialStructures::Node &parent, HF::SpatialStructures::Node &child)
Check the floor
bool isUpSlope (const HF::SpatialStructures::Node &n1, const HF::SpatialStructures::Node &n2)
Returns true if the slope is up, and false otherwise
void GetChildren (const HF::SpatialStructures::Node &parent, const std::vector< SpatialStructures::Node > &possible_children, std::vector< HF::SpatialStructures::Edge > &out_children)
Calculates children for parent and places them in out_children
std::vector< HF::SpatialStructures::Node > CheckChildren (const HF::SpatialStructures::Node &parent, std::vector< HF::SpatialStructures::Node > Children)
Fire a ray from the parent to each child node to see if it satisfies step requirements
bool IsConnected (const HF::SpatialStructures::Node &parent, const HF::SpatialStructures::Node &child)
Check if there is a connection between each node
float RayDist (const HF::SpatialStructures::Node &p1, const v3 &direction, HIT_FLAG flag=HIT_FLAG::BOTH)
Get the distance between the node and where the ray hits. If the ray doesn't hit return 0
HF::SpatialStructures::STEP CheckConnection (const HF::SpatialStructures::Node &parent, const HF::SpatialStructures::Node &child)
Private Attributes
HF::SpatialStructures::Graph G
An internal graph that is iterated upon as the program is executed ///<.
HF::AnalysisMethods::GraphGenerator & GG
The underlying graph generator; ///<.
Detailed Description
Contains the private implementation of the graph generator so clients aren't forced to recompile
Definition at line 12 of file graph_generator_private.h.
Constructor & Destructor Documentation
GraphGeneratorPrivate()
HF::AnalysisMethods::GraphGeneratorPrivate::GraphGeneratorPrivate (GraphGenerator & GG)
Default constructor
Parameters
GG The GraphGenerator used to create this instance
Definition at line 54 of file graph_generator_private.cpp.
Member Function Documentation
BuildNetwork()
Graph HF::AnalysisMethods::GraphGeneratorPrivate::BuildNetwork ()
TODO description
Returns
TODO returns
Definition at line 57 of file graph_generator_private.cpp.
References CheckStart(), HF::AnalysisMethods::GraphGenerator::core_count, CrawlGeom(), CrawlGeomParallel(), G, GG, HF::AnalysisMethods::UniqueQueue::push(), HF::SpatialStructures::roundhf(), and HF::AnalysisMethods::GraphGenerator::start.
Referenced by HF::AnalysisMethods::GraphGenerator::BuildNetwork().
CheckChildren()
std::vector< HF::SpatialStructures::Node > HF::AnalysisMethods::GraphGeneratorPrivate::CheckChildren (const HF::SpatialStructures::Node & parent, std::vector< HF::SpatialStructures::Node > Children) [private]
Fire a ray from the parent to each child node to see if it satisfies step requirements
Parameters
parent The parent node to fire the ray from
children A list of child nodes to check
Returns
A list of valid nodes
Definition at line 144 of file graph_generator_private.cpp.
References CheckRay(), HF::AnalysisMethods::down, HF::AnalysisMethods::GraphGenerator::downstep, GG, and HF::AnalysisMethods::GraphGenerator::upstep.
Referenced by GetChildren().
CheckConnection()
STEP HF::AnalysisMethods::GraphGeneratorPrivate::CheckConnection (const HF::SpatialStructures::Node & parent, const HF::SpatialStructures::Node & child) [private]
Definition at line 164 of file graph_generator_private.cpp.
References HF::SpatialStructures::DOWN, HF::AnalysisMethods::GraphGenerator::downstep, GG, isUpSlope(), HF::SpatialStructures::NONE, HF::SpatialStructures::NOT_CONNECTED, OcclusionCheck(), HF::SpatialStructures::OVER, HF::SpatialStructures::UP, and HF::AnalysisMethods::GraphGenerator::upstep.
Referenced by GetChildren().
CheckFloor()
bool HF::AnalysisMethods::GraphGeneratorPrivate::CheckFloor (const HF::SpatialStructures::Node & parent, HF::SpatialStructures::Node & child) [inline], [private]
Check the floor
Parameters
parent The desired parent
child The desired child
Returns
True if the child isn't lower than the maximum z coordinate offset, false otherwise
Definition at line 108 of file graph_generator_private.cpp.
References CheckRay(), HF::AnalysisMethods::down, HF::AnalysisMethods::GraphGenerator::downstep, HF::AnalysisMethods::FLOORS, GG, HF::AnalysisMethods::GraphGenerator::upstep, and HF::SpatialStructures::Node::z.
CheckRay() [1/2]
bool HF::AnalysisMethods::GraphGeneratorPrivate::CheckRay (HF::SpatialStructures::Node & position, const v3 & direction, HIT_FLAG flag = HIT_FLAG::BOTH) [private]
Fire a ray using the Embree Ray Tracer
Parameters
position Node to use as the origin. On Hit, this node's position will be overridden
direction Direction to fire the ray in
flag Fire at floors or obstacles
Returns
True on hit, false otherwise
Definition at line 338 of file graph_generator_private.cpp.
References HF::AnalysisMethods::BOTH, HF::RayTracer::EmbreeRayTracer::FireRay(), HF::AnalysisMethods::FLOORS, GG, HF::AnalysisMethods::OBSTACLES, HF::AnalysisMethods::GraphGenerator::ray_tracer, and HF::AnalysisMethods::GraphGenerator::walkable_surfaces.
Referenced by CheckChildren(), CheckFloor(), and CheckStart().
CheckRay() [2/2]
bool HF::AnalysisMethods::GraphGeneratorPrivate::CheckRay (v3 & position, const v3 & direction, HIT_FLAG flag = HIT_FLAG::BOTH) [private]
Fire a ray using the Embree Ray Tracer
Parameters
position Node to use as the origin. On Hit, this node's position will be overridden
direction Direction to fire the ray in
flag Fire at floors or obstacles
Returns
True on hit, false otherwise
Definition at line 322 of file graph_generator_private.cpp.
References HF::AnalysisMethods::BOTH, HF::RayTracer::EmbreeRayTracer::FireRay(), HF::AnalysisMethods::FLOORS, GG, HF::AnalysisMethods::OBSTACLES, and HF::AnalysisMethods::GraphGenerator::ray_tracer.
CheckStart()
bool HF::AnalysisMethods::GraphGeneratorPrivate::CheckStart (v3 & start) [private]
Definition at line 83 of file graph_generator_private.cpp.
References CheckRay(), and HF::AnalysisMethods::down.
Referenced by BuildNetwork().
ComputerParent()
void HF::AnalysisMethods::GraphGeneratorPrivate::ComputerParent (const HF::SpatialStructures::Node & parent, const std::vector< std::pair< int, int >> & directions, std::vector< HF::SpatialStructures::Edge > & out_relations) [inline], [private]
Ranks children then stores relations?
Parameters
parent The desired parent node
directions A reference to a vector of integer pairs, representing directions
out_relations A reference to a vector of Edge, representing relations
Definition at line 369 of file graph_generator_private.cpp.
References GeneratePotentialChildren(), and GetChildren().
Referenced by CrawlGeom(), and CrawlGeomParallel().
CrawlGeom()
void HF::AnalysisMethods::GraphGeneratorPrivate::CrawlGeom (UniqueQueue & todo) [private]
Populate the graph with with nodes and edges
Parameters
todo A unique queue with a single start point
Definition at line 213 of file graph_generator_private.cpp.
References HF::SpatialStructures::Graph::addEdge(), ComputerParent(), HF::AnalysisMethods::UniqueQueue::empty(), G, GG, HF::AnalysisMethods::GraphGenerator::max_nodes, HF::AnalysisMethods::GraphGenerator::max_step_connection, HF::AnalysisMethods::permutations(), HF::AnalysisMethods::UniqueQueue::pop(), and HF::AnalysisMethods::UniqueQueue::push().
Referenced by BuildNetwork().
CrawlGeomParallel()
void HF::AnalysisMethods::GraphGeneratorPrivate::CrawlGeomParallel (UniqueQueue & todo) [private]
A parallel version of CrawlGeom
Parameters
todo
Returns
Definition at line 245 of file graph_generator_private.cpp.
References HF::SpatialStructures::Graph::addEdge(), ComputerParent(), HF::AnalysisMethods::UniqueQueue::empty(), G, GG, HF::AnalysisMethods::GraphGenerator::max_nodes, HF::AnalysisMethods::GraphGenerator::max_step_connection, HF::AnalysisMethods::permutations(), HF::AnalysisMethods::UniqueQueue::pop(), HF::AnalysisMethods::UniqueQueue::popMany(), HF::AnalysisMethods::UniqueQueue::push(), and HF::AnalysisMethods::UniqueQueue::size().
Referenced by BuildNetwork().
GeneratePotentialChildren()
void HF::AnalysisMethods::GraphGeneratorPrivate::GeneratePotentialChildren (const HF::SpatialStructures::Node & parent, const std::vector< std::pair< int, int >> & directions, std::vector< HF::SpatialStructures::Node > & out_children) [inline], [private]
Populate out_children with a potential child position for every direction in directions.
Parameters
parent parent to start from
directions An array of pairs for the x and y direction
out_children Output array
Definition at line 87 of file graph_generator_private.cpp.
References GG, HF::SpatialStructures::roundhf(), and HF::AnalysisMethods::GraphGenerator::spacing.
Referenced by ComputerParent().
GetChildren()
void HF::AnalysisMethods::GraphGeneratorPrivate::GetChildren (const HF::SpatialStructures::Node & parent, const std::vector< SpatialStructures::Node > & possible_children, std::vector< HF::SpatialStructures::Edge > & out_children) [private]
Calculates children for parent and places them in out_children
Parameters
parent Reference to parent node
possible_children Reference to vector of node, representing possible children
out_children Reference to vector of Edge, representing edges of children
Definition at line 131 of file graph_generator_private.cpp.
References CheckChildren(), CheckConnection(), HF::SpatialStructures::Node::distanceTo(), and HF::SpatialStructures::NOT_CONNECTED.
Referenced by ComputerParent().
Graphdirecs()
void HF::AnalysisMethods::GraphGeneratorPrivate::Graphdirecs (const SpatialStructures::Node & parent, const std::vector< std::pair< int, int >> & directions, std::vector< SpatialStructures::Node > & out_children) [private]
Calculate positions for every direction pair in directions, then deposit in out children
Parameters
parent The parent node
directions A reference to a direction pair (coordinates)
out_children A reference to a vector of Node where children will be deposited
summary> Push point to the ground if there is ground beneath it and return true. Return false if it isn't on any walkable terrain. /summary>
Parameters
start Reference to v3 instance
Returns
Returns true if CheckRay(start, down) is true, false otherwise
IsConnected()
bool HF::AnalysisMethods::GraphGeneratorPrivate::IsConnected (const HF::SpatialStructures::Node & parent, const HF::SpatialStructures::Node & child) [private]
Check if there is a connection between each node
Parameters
parent The desired parent node
child The desired child node
Returns
True if parent and child are connected, false otherwise
isUpSlope()
bool HF::AnalysisMethods::GraphGeneratorPrivate::isUpSlope (const HF::SpatialStructures::Node & n1, const HF::SpatialStructures::Node & n2) [private]
Returns true if the slope is up, and false otherwise
Parameters
n1 The first node to compare
n2 The second node to compare
Returns
True, if the slope of n1 and n2 is positive (upward), false otherwise
Definition at line 121 of file graph_generator_private.cpp.
References HF::AnalysisMethods::GraphGenerator::downslope, GG, HF::AnalysisMethods::GraphGenerator::upslope, HF::SpatialStructures::Node::x, HF::SpatialStructures::Node::y, and HF::SpatialStructures::Node::z.
Referenced by CheckConnection().
OcclusionCheck()
bool HF::AnalysisMethods::GraphGeneratorPrivate::OcclusionCheck (const SpatialStructures::Node & parent, const SpatialStructures::Node & child) [inline], [private]
Check if parent has a line of sight to child within max_dist
Parameters
parent Node to shoot from
child Node to shoot to
Returns
True if there is an unobstructed path between parent and child
Definition at line 101 of file graph_generator_private.cpp.
References HF::SpatialStructures::Node::directionTo(), HF::SpatialStructures::Node::distanceTo(), HF::RayTracer::EmbreeRayTracer::FireOcclusionRay(), GG, HF::AnalysisMethods::GraphGenerator::ray_tracer, HF::SpatialStructures::Node::x, HF::SpatialStructures::Node::y, and HF::SpatialStructures::Node::z.
Referenced by CheckConnection().
RayDist()
float HF::AnalysisMethods::GraphGeneratorPrivate::RayDist (const HF::SpatialStructures::Node & p1, const v3 & direction, HIT_FLAG flag = HIT_FLAG::BOTH) [private]
Get the distance between the node and where the ray hits. If the ray doesn't hit return 0
Parameters
p1 The desired node to assess
direction The direction of the ray
flag Ray collision status, 1 = FLOORS, 2 = OBSTACLES, 3 = BOTH (the default)
Returns
Distance between the node and the ray collision -- 0.0f if ray does not hit
summary> Check if the parent and child have a connection between them. May move nodes around to fit on ground mesh. /summary>
WalkableCheck()
bool HF::AnalysisMethods::GraphGeneratorPrivate::WalkableCheck (const SpatialStructures::Node & position) [inline], [private]
Invokes CheckRay using a temporary instance of v3 (named testpos), constructed from position
Parameters
position The node to use for CheckRay
Returns
See CheckRay, returns value from CheckRay(testpos, down, FLOORS)
Definition at line 48 of file graph_generator_private.cpp.
References HF::AnalysisMethods::down, and HF::AnalysisMethods::FLOORS.
Member Data Documentation
G
HF::SpatialStructures::Graph HF::AnalysisMethods::GraphGeneratorPrivate::G [private]
An internal graph that is iterated upon as the program is executed ///<.
Definition at line 15 of file graph_generator_private.h.
Referenced by BuildNetwork(), CrawlGeom(), and CrawlGeomParallel().
GG
HF::AnalysisMethods::GraphGenerator& HF::AnalysisMethods::GraphGeneratorPrivate::GG [private]
The underlying graph generator; ///<.
Definition at line 16 of file graph_generator_private.h.
Referenced by BuildNetwork(), CheckChildren(), CheckConnection(), CheckFloor(), CheckRay(), CrawlGeom(), CrawlGeomParallel(), GeneratePotentialChildren(), isUpSlope(), and OcclusionCheck().
The documentation for this class was generated from the following files:
Cpp/analysismethods/src/graph_generator_private.h
Cpp/analysismethods/src/graph_generator_private.cpp