HF::Pathfinding::BoostGraph Class Reference
Holds the necessary state for the Boost pathfinding algorithm
#include <boost_graph.h>
Public Member Functions
BoostGraph (const HF::SpatialStructures::Graph &graph)
Create a new Boost graph from the given HF Graph
~BoostGraph ()
Destroy the current Boost graph (uses compiler-generated implementation via 'default')
Public Attributes
graph_t g
Directed CSR graph (Boost)
std::vector< vertex_descriptor > p
Container of vertex_descriptor.
std::vector< double > d
Container of double.
Detailed Description
Holds the necessary state for the Boost pathfinding algorithm
Definition at line 125 of file boost_graph.h.
Constructor & Destructor Documentation
BoostGraph()
HF::Pathfinding::BoostGraph::BoostGraph (const HF::SpatialStructures::Graph & graph)
Create a new Boost graph from the given HF Graph
// In order to create a Boost graph, we must first create a
// HF::SpatialStructures::Graph instance first.
using HF::SpatialStructures::Node;
using HF::SpatialStructures::Graph;
// Create the nodes
Node node_0(12.0, 23.1, 34.2, 456);
Node node_1(45.3, 56.4, 67.5, 789);
Node node_2(55.5, 25.1, 85.2, 940);
// Create a container (vector) of nodes
std::vector<Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { {1, 2, 3}, {4, 5, 6}, {7, 8, 9 } };
std::vector<std::vector<float>> distances = { {12.0, 23.1, 45.2}, {67.3, 89.4, 98.5}, {76.6, 54.7, 32.8} };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
Graph g(edges, distances, nodes);
// Passing Graph g to BoostGraph bg, by reference
BoostGraph bg(g);
Definition at line 20 of file boost_graph.cpp.
References d, g, HF::SpatialStructures::Graph::GetEdges(), HF::SpatialStructures::Graph::Nodes(), p, HF::SpatialStructures::Graph::size(), and HF::Pathfinding::Edge_Cost::weight.
 BoostGraph()
HF::Pathfinding::BoostGraph::~BoostGraph () [default]
Destroy the current Boost graph (uses compiler-generated implementation via 'default')
// Begin scope
{
    // Create a HF::SpatialStructures::Graph g here first.
    // Create a BoostGraph bg, from a Graph g (passing g by reference)
    BoostGraph bg(g);
}
// End scope
// When bg goes out of scope, BoostGraph::~BoostGraph is called
// An explicit call to BoostGraph::~BoostGraph is also made when
// invoking operator delete on a (BoostGraph *)
Member Data Documentation
d
std::vector<double> HF::Pathfinding::BoostGraph::d
Container of double.
Definition at line 129 of file boost_graph.h.
Referenced by BoostGraph().
g
graph_t HF::Pathfinding::BoostGraph::g
Directed CSR graph (Boost)
Definition at line 127 of file boost_graph.h.
Referenced by BoostGraph(), HF::Pathfinding::FindPath(), HF::Pathfinding::FindPaths(), and HF::Pathfinding::InsertPathsIntoArray().
p
std::vector<vertex_descriptor> HF::Pathfinding::BoostGraph::p
Container of vertex_descriptor.
Definition at line 128 of file boost_graph.h.
Referenced by BoostGraph().
The documentation for this class was generated from the following files:
Cpp/pathfinding/src/boost_graph.h
Cpp/pathfinding/src/boost_graph.cpp