HF::SpatialStructures::Graph Class Reference
A HF Graph similar to the one stored in python Invariants: 1) Always stores a valid graph 2) Every node added will be assigned a unique ID
#include <graph.h>
Public Member Functions
Graph (const std::vector< std::vector< int >> &edges, const std::vector< std::vector< float >> &distances, const std::vector< Node > &Nodes)
Construct a graph from a list of nodes and edges. This is faster than just using the addEdge method
Graph ()
bool HasEdge (const std::array< float, 3 > &parent, const std::array< float, 3 > &child, bool undirected=false) const
Determine if the graph has an edge with this parent and child, by constructing temporary Node (using the params parent and child) and calling the member function overload of HasEdge that accepts (const Node &).
bool HasEdge (const Node &parent, const Node &child, const bool undirected=false) const
Determine if the graph has an edge with this parent and child, using references to Node
bool HasEdge (int parent, int child, bool undirected=false) const
Determine if the graph has an edge with this parent and child, using the integer identifiers for nodes
std::vector< Node > Nodes () const
Get a list of nodes from the graph sorted by ID
std::vector< Edge > GetUndirectedEdges (const Node &N) const
Get a list of edges to and from node N
std::vector< EdgeSet > GetEdges () const
Get every edge/node in the given graph as IDs
std::vector< float > AggregateGraph (COST_AGGREGATE agg_type, bool directed=true) const
Generate an ordered list of scores for the graph
const std::vector< Edge > operator[] (const Node &n) const
Get a list of edges for the given node
void addEdge (const Node &parent, const Node &child, float score=1.0f)
Construct a new edge for the graph from parent and child pair. If the parent is not in the graph as a key then it will be added
void addEdge (int parent_id, int child_id, float score)
Construct a new edge for the graph using parent and child IDs. If the parent_id is not in the graph as a key, it will be added
bool hasKey (const Node &n) const
Tell whether or not the graph has the given node in it as a parent
std::vector< std::array< float, 3 > > NodesAsFloat3 () const
Get a list of nodes as arrays of floats
int size () const
Determine how many nodes are in the graph
int getID (const Node &node) const
Retrieve the ID for the given node.
void Compress ()
Compress the graph, significantly reducing memory usage, but disabling insertion.
CSRPtrs GetCSRPointers ()
Obtain pointers to the 3 arrays of the CSR, as well as any extra info that may be necesary to use the CSR in another language. This will automatically compress the graph if it isn't compressed already
Node NodeFromID (int id) const
Retrieve the node that corresponds to id
void Clear ()
Clear all nodes and edges in the graph.
void GenerateCrossSlope ()
Calculate cross slope for the given graph
void GenerateEnergy ()
Calculate energy for the given graph
Private Member Functions
int getOrAssignID (const Node &input_node)
Get the unique ID for this x, y, z position. If one does not exist yet for this node then assign it one.
int getOrAssignID (int input_int)
Get the unique ID for this x, y, z position. If one does not exist yet for this node then assign it one.
bool checkForEdge (int parent, int child) const
Iterate through every edge in parent to find child. Returns when child is found
void UpdateIDs (int new_id)
Add an empty node for this new id
Private Attributes
std::vector< Node > ordered_nodes
A ordered list of nodes with ids.
std::vector< int > id_to_nodes
a list that indexes ordered_nodes with ids
robin_hood::unordered_map< Node, int > idmap
Maps a list of X,Y,Z positions to ids.
Eigen::SparseMatrix< float, 1 > edge_matrix
Contains all edges between nodes.
int next_id = 0
The ID of the next unique node.
std::vector< Eigen::Triplet< float > > triplets
vector of Triplet, type float
bool needs_compression = true
The CSR is inaccurate and requires compression.
Detailed Description
A HF Graph similar to the one stored in python Invariants: 1) Always stores a valid graph 2) Every node added will be assigned a unique ID
Definition at line 80 of file graph.h.
Constructor & Destructor Documentation
Graph() [1/2]
HF::SpatialStructures::Graph::Graph (const std::vector< std::vector< int >> & edges, const std::vector< std::vector< float >> & distances, const std::vector< Node > & Nodes)
Construct a graph from a list of nodes and edges. This is faster than just using the addEdge method
Parameters
edges The desired edges for Graph, in the form of an adjacency matrix (reference)
distances The desired distances for Graph, following the form of param edges (reference)
Nodes A vector of Node for Graph (reference)
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
Definition at line 230 of file graph.cpp.
Graph() [2/2]
HF::SpatialStructures::Graph::Graph () [inline]
// be sure to #include "graph.h"
HF::SpatialStructures::Graph graph; // This represents an order-zero graph (null graph)
                                        // It lacks vertices and edges.
Definition at line 173 of file graph.h.
Member Function Documentation
addEdge() [1/2]
void HF::SpatialStructures::Graph::addEdge (const Node & parent, const Node & child, float score = 1.0f)
Construct a new edge for the graph from parent and child pair. If the parent is not in the graph as a key then it will be added
Parameters
parent The parent node to add to
child The child node to add as an edge
score The score for the given edge
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Create a pair of nodes
HF::SpatialStructures::Node n_parent(4.0f, 5.0f, 6.0f);
HF::SpatialStructures::Node n_child(7.0f, 8.0f, 9.0f);
graph.addEdge(n_parent, n_child); // default score is 1.0f
Definition at line 158 of file graph.cpp.
Referenced by AddEdgeFromNodeIDs(), AddEdgeFromNodes(), HF::AnalysisMethods::GraphGeneratorPrivate::CrawlGeom(), and HF::AnalysisMethods::GraphGeneratorPrivate::CrawlGeomParallel().
addEdge() [2/2]
void HF::SpatialStructures::Graph::addEdge (int parent_id, int child_id, float score)
Construct a new edge for the graph using parent and child IDs. If the parent_id is not in the graph as a key, it will be added
Parameters
parent_id The ID of the parent node for the edge to construct
child_id The ID of the child node for the edge to construct
score The score for the given edge
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
int parent = 1;
int child = 2;
graph.addEdge(parent, child, 1.0f);
graph.Compress();
Definition at line 169 of file graph.cpp.
AggregateGraph()
std::vector< float > HF::SpatialStructures::Graph::AggregateGraph (COST_AGGREGATE agg_type, bool directed = true) const
Generate an ordered list of scores for the graph
Parameters
agg_type 0 for SUM, 1 for AVERAGE, 2 for COUNT
directed if graph is directed or not, default is true
Returns
a vector of type float of the edge costs
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// graph must be compressed, or a exception will be thrown
HF::SpatialStructures::COST_AGGREGATE aggregate = HF::SpatialStructures::COST_AGGREGATE::AVERAGE; // aggregate == 1 in this case
// directed parameter may be true or false
std::vector<float> aggregate_graph = graph.AggregateGraph(aggregate, true);
Definition at line 115 of file graph.cpp.
References HF::SpatialStructures::Aggregate().
Referenced by AggregateCosts().
checkForEdge()
bool HF::SpatialStructures::Graph::checkForEdge (int parent, int child) const [private]
Iterate through every edge in parent to find child. Returns when child is found
TODO example
Definition at line 178 of file graph.cpp.
Clear()
void HF::SpatialStructures::Graph::Clear ()
Clear all nodes and edges in the graph.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// If we want to remove all nodes and edges from graph, we may do so with Clear:
graph.Clear(); // edge_matrix is zeroed out, buffer is squeezed,
                                    // triplets are also cleared, and needs_compression == true
Definition at line 305 of file graph.cpp.
Referenced by ClearGraph().
Compress()
void HF::SpatialStructures::Graph::Compress ()
Compress the graph, significantly reducing memory usage, but disabling insertion.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Create a pair of nodes
HF::SpatialStructures::Node n_parent(4.0f, 5.0f, 6.0f);
HF::SpatialStructures::Node n_child(7.0f, 8.0f, 9.0f);
graph.addEdge(n_parent, n_child); // default score is 1.0f
// In order to use GetEdges, or AggregateGraph, we must compress our graph instance
graph.Compress(); // GetEdges and AggregateGraph are now usable
Definition at line 295 of file graph.cpp.
Referenced by Compress().
GenerateCrossSlope()
void HF::SpatialStructures::Graph::GenerateCrossSlope ()
Calculate cross slope for the given graph
// TODO example - code commented out in graph.cpp
GenerateEnergy()
void HF::SpatialStructures::Graph::GenerateEnergy ()
Calculate energy for the given graph
// TODO example - code commented out in graph.cpp
GetCSRPointers()
CSRPtrs HF::SpatialStructures::Graph::GetCSRPointers ()
Obtain pointers to the 3 arrays of the CSR, as well as any extra info that may be necesary to use the CSR in another language. This will automatically compress the graph if it isn't compressed already
Returns
An instance of a struct CSRPtrs, using the member field edge_matrix
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Create a pair of nodes
HF::SpatialStructures::Node n_parent(4.0f, 5.0f, 6.0f);
HF::SpatialStructures::Node n_child(7.0f, 8.0f, 9.0f);
graph.addEdge(n_parent, n_child); // default score is 1.0f
// Graph will be compressed automatically be GetCSRPointers
CSRPtrs returned_csr = graph.GetCSRPointers();
Definition at line 30 of file graph.cpp.
References Compress().
Referenced by GetCSRPointers().
GetEdges()
std::vector< EdgeSet > HF::SpatialStructures::Graph::GetEdges () const
Get every edge/node in the given graph as IDs
Returns
A list of EdgeSet (Graph in the form of IDs)
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// graph must be compressed, or a exception will be thrown
// To brief, an EdgeSet has the following layout:
// struct EdgeSet {
// int parent;
// std::vector<IntEdge> children;
// };
//
// An IntEdge has the following layout:
// struct IntEdge {
// int child;
// float weight;
// };
// A std::vector<EdgeSet> is a Graph, in the form of IDs.
std::vector<HF::SpatialStructures::EdgeSet> edge_set = graph.GetEdges();
Definition at line 73 of file graph.cpp.
Referenced by HF::Pathfinding::BoostGraph::BoostGraph().
getID()
int HF::SpatialStructures::Graph::getID (const Node & node) const
Retrieve the ID for the given node.
Returns
The ID assigned to this node. -1 if it was not yet added to the graph
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
HF::SpatialStructures::Node other_node(55.0f, 66.1f, 15.5f, 9510); // Let's construct a Node we know is not in graph.
bool has_key = graph.hasKey(other_node); // other_node does not exist in graph, so has_key == false;
int ID = graph.getID(other_node); // ID will assigned -1, because other_node is not a part of graph.
// Likewise, if we pass a Node instance that indeed exists...
// Retrieve the nodes from the graph, or use the original instance of
// std::vector<Node> passed to Graph upon instantiation
std::vector<HF::SpatialStructures::Node> get_nodes = graph.Nodes();
// nodes[index] yields an instance of Node that we can pass to hasKey.
// Any node that exists with graph can be passed to this member function
// to determine if the graph has the node's key, or not.
int index = 2; // we assume for this example that index 2 is valid.
HF::SpatialStructures::Node good_node = get_nodes[index];
ID = graph.getID(good_node); // ID > -1, i.e. it is a Node instance that exists within this Graph.
Definition at line 22 of file graph.cpp.
Referenced by GetNodeID().
getOrAssignID() [1/2]
int HF::SpatialStructures::Graph::getOrAssignID (const Node & input_node) [private]
Get the unique ID for this x, y, z position. If one does not exist yet for this node then assign it one.
TODO example
Definition at line 203 of file graph.cpp.
getOrAssignID() [2/2]
int HF::SpatialStructures::Graph::getOrAssignID (int input_int) [private]
Get the unique ID for this x, y, z position. If one does not exist yet for this node then assign it one.
TODO example
Definition at line 217 of file graph.cpp.
GetUndirectedEdges()
vector< Edge > HF::SpatialStructures::Graph::GetUndirectedEdges (const Node & N) const
Get a list of edges to and from node N
Parameters
N The Node from which the list of edges will be derived
Returns
A list of edges to and from node N
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Retrieve the nodes from the graph, or use the original instance of
// std::vector<HF::SpatialStructures::Node> passed to Graph upon instantiation
std::vector<HF::SpatialStructures::Node> get_nodes = graph.Nodes();
// nodes[index] yields an instance of Node that we can pass to GetUndirectedEdges.
// Any node that exists with graph can be passed to this member function
// to retrieve a vector of undirected edges.
int index = 2;
std::vector<HF::SpatialStructures::Edge> undirected_edges = graph.GetUndirectedEdges(get_nodes[index]);
Definition at line 54 of file graph.cpp.
HasEdge() [1/3]
bool HF::SpatialStructures::Graph::HasEdge (const Node & parent, const Node & child, const bool undirected = false) const
Determine if the graph has an edge with this parent and child, using references to Node
Parameters
parent Parent node of edge; u to v, parent is u
child Child node of edge; u to v, child is v
undirected true if undirected, false otherwise
Returns
True if edge exists with parent and child (Node &), false otherwise
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// last argument can be true/false for undirected/directed graph respectively
bool has_edge = graph.HasEdge(node_1, node_2, true);
Definition at line 189 of file graph.cpp.
HasEdge() [2/3]
bool HF::SpatialStructures::Graph::HasEdge (const std::array< float, 3 > & parent, const std::array< float, 3 > & child, bool undirected = false) const
Determine if the graph has an edge with this parent and child, by constructing temporary Node (using the params parent and child) and calling the member function overload of HasEdge that accepts (const Node &).
Returns
See return for member function overload that accepts (const Node &)
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Prepare {x, y, z} coordinates (positions)
auto parent_pos = node_1.getArray(); // (2.0, 3.0, 4.0)
auto child_pos = node_2.getArray(); // (11.0, 22.0, 140.0)
// last argument can be true/false for undirected/directed graph respectively
bool has_edge = graph.HasEdge(parent_pos, child_pos, true);
Definition at line 260 of file graph.cpp.
HasEdge() [3/3]
bool HF::SpatialStructures::Graph::HasEdge (int parent, int child, bool undirected = false) const
Determine if the graph has an edge with this parent and child, using the integer identifiers for nodes
Parameters
parent Identifier for parent node (integer)
child Identifier for child node (integer)
undirected True if undirected graph, false otherwise. False by default.
Returns
True if checkForEdge(parent, child), or undirected && checkForEdge(child, parent), false otherwise
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// last argument can be true/false for undirected/directed graph respectively
bool has_edge = graph.HasEdge(0, 1, true);
Definition at line 185 of file graph.cpp.
hasKey()
bool HF::SpatialStructures::Graph::hasKey (const Node & n) const
Tell whether or not the graph has the given node in it as a parent
Parameters
n Node to check for
Returns
True if the node exists, false otherwise
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
HF::SpatialStructures::Node other_node(55.0f, 66.1f, 15.5f, 9510); // Let's construct a Node we know is not in graph.
bool has_key = graph.hasKey(other_node); // other_node does not exist in graph, so has_key == false;
// Likewise, if we pass a Node instance that indeed exists...
// Retrieve the nodes from the graph, or use the original instance of
// std::vector<Node> passed to Graph upon instantiation
std::vector<HF::SpatialStructures::Node> get_nodes = graph.Nodes();
// nodes[index] yields an instance of Node that we can pass to hasKey.
// Any node that exists with graph can be passed to this member function
// to determine if the graph has the node's key, or not.
int index = 2;
HF::SpatialStructures::Node good_node = get_nodes[index];
has_key = graph.hasKey(good_node); // now has_key is true
Definition at line 267 of file graph.cpp.
NodeFromID()
Node HF::SpatialStructures::Graph::NodeFromID (int id) const
Retrieve the node that corresponds to id
Parameters
id The id for the desired node
Returns
The node corresponding to id, by value
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Let's retrieve node_1.
int desired_node_id = 2;
HF::SpatialStructures::Node node_from_id = graph.NodeFromID(desired_node_id);
// Note that NodeFromID ceases to work if the id argument provided does not exist as an ID among
// the nodes within graph
Definition at line 48 of file graph.cpp.
Nodes()
std::vector< Node > HF::SpatialStructures::Graph::Nodes () const
Get a list of nodes from the graph sorted by ID
Returns
A sorted vector of nodes
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Nodes() returns a copy of the ordered_nodes field
std::vector<HF::SpatialStructures::Node> nodes_from_graph = graph.Nodes();
Definition at line 50 of file graph.cpp.
Referenced by HF::Pathfinding::BoostGraph::BoostGraph(), GenerateGraph(), and GetAllNodesFromGraph().
NodesAsFloat3()
std::vector< std::array< float, 3 > > HF::SpatialStructures::Graph::NodesAsFloat3 () const
Get a list of nodes as arrays of floats
Returns
A list of floats for each position of every node in the graph
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// A container of std::array<float, 3> is constructed and populated within
// NodesAsFloat3, and returned. Each array of 3 floats represents a Node's position
// within the Cartesian coordinate system. { x, y, z }
std::vector<std::array<float, 3>> nodes_as_floats = graph.NodesAsFloat3();
// The two loops below will yield the same output
for (auto n : graph.Nodes()) {
    std::cout << "(" << n.x << "," << n.y << "," << n.z << ")" << std::endl;
}
for (auto a : nodes_as_floats) {
    std::cout << a << std::endl;
}
 This yields the intended output
Definition at line 269 of file graph.cpp.
operator[]()
const std::vector< Edge > HF::SpatialStructures::Graph::operator[] (const Node & n) const
Get a list of edges for the given node
Parameters
n Node from which a list of edges will be derived
Returns
A copy of the graph's list
Exceptions
std::outofrange Thrown if the requested object is not in the dictionary
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Retrieve the nodes from the graph, or use the original instance of
// std::vector<Node> passed to Graph upon instantiation
std::vector<HF::SpatialStructures::Node> get_nodes = graph.Nodes();
// nodes[index] yields an instance of Node that we can pass to GetUndirectedEdges.
// Any node that exists with graph can be passed to this member function
// to retrieve a vector of edges.
int index = 2;
HF::SpatialStructures::Node node = get_nodes[index];
// Note that if node does not exist within graph, that an exception will be thrown.
std::vector<HF::SpatialStructures::Edge> undirected_edges = graph[node];
// See a (node)->(child_node_0, child_node_1, ... child_node_n)
std::cout << node.getArray() << "->";
for (auto e : undirected_edges) {
    std::cout << e.child.getArray() << ", ";
}
std::cout << std::endl;
Definition at line 143 of file graph.cpp.
size()
int HF::SpatialStructures::Graph::size () const
Determine how many nodes are in the graph
Returns
An int displaying how many nodes are in the graph (id_to_nodes.size())
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
int id_count = graph.size(); // We retrieve the size of the node id count within graph (3)
Definition at line 20 of file graph.cpp.
Referenced by HF::Pathfinding::BoostGraph::BoostGraph().
UpdateIDs()
void HF::SpatialStructures::Graph::UpdateIDs (int new_id) [private]
Add an empty node for this new id
TODO example
Member Data Documentation
edge_matrix
Eigen::SparseMatrix<float, 1> HF::SpatialStructures::Graph::edge_matrix [private]
Contains all edges between nodes.
Definition at line 86 of file graph.h.
id_to_nodes
std::vector<int> HF::SpatialStructures::Graph::id_to_nodes [private]
a list that indexes ordered_nodes with ids
Definition at line 84 of file graph.h.
idmap
robin_hood::unordered_map<Node, int> HF::SpatialStructures::Graph::idmap [private]
Maps a list of X,Y,Z positions to ids.
Definition at line 85 of file graph.h.
needs_compression
bool HF::SpatialStructures::Graph::needs_compression = true [private]
The CSR is inaccurate and requires compression.
Definition at line 89 of file graph.h.
next_id
int HF::SpatialStructures::Graph::next_id = 0 [private]
The ID of the next unique node.
Definition at line 87 of file graph.h.
ordered_nodes
std::vector<Node> HF::SpatialStructures::Graph::ordered_nodes [private]
A ordered list of nodes with ids.
Definition at line 83 of file graph.h.
triplets
std::vector<Eigen::Triplet<float> > HF::SpatialStructures::Graph::triplets [private]
vector of Triplet, type float
Definition at line 88 of file graph.h.
The documentation for this class was generated from the following files:
Cpp/spatialstructures/src/graph.h
Cpp/spatialstructures/src/graph.cpp