HF::Geometry::MeshInfo Class Reference
Holds vertices and some other information about a specific mesh
#include <meshinfo.h>
Public Member Functions
MeshInfo ()
Default constructor, all fields initialized except for member indices
MeshInfo (const std::vector< std::array< float, 3 >> &vertices, int id, std::string name=``)
Construct a new MeshInfo object from an unindexed vector of vertices, an ID, and a name
MeshInfo (const std::vector< float > &in_vertices, const std::vector< int > &in_indexes, int id, std::string name=``)
Construct a new MeshInfo object from an indexed vector of vertices
void AddVerts (const std::vector< std::array< float, 3 >> &verts)
Append a list of verts onto the end of the mesh. This will cause the array to be resized.
void AddVerts (const std::vector< float > &verts, std::vector< int > &indices)
Populate the mesh using only an array of floats and vertices corresponding to mesh x,y,z values and triangle indexes respectively.
int NumVerts () const
Get the number of vertices stored in this mesh info
int NumTris () const
Get the total number of triangles in the given mesh
void ConvertToRhinoCoordinates ()
Convert the internal coordinates of this mesh to rhino coordinates
void ConvertToOBJCoordinates ()
Convert the internal coordinates of this mesh to OBJ coordinates
void PerformRotation (float rx, float ry, float rz)
Rotate this mesh by x, y, z rotations in degrees (pitch, yaw, roll)
int GetMeshID () const
Return a copy of meshid
std::vector< float > getRawVertices () const
Retrieve a copy of the underlying vertex buffer. Helpful for filling other buffers
std::vector< int > getRawIndices () const
Retrieve a copy of the underlying index buffer. Useful for copying into other buffers
std::vector< std::array< float, 3 > > GetVertsAsArrays () const
Retrieve vertices as a vector of arrays of float.
void SetMeshID (int new_id)
Assigns the value of new_id to meshid
bool operator== (const MeshInfo &M2) const
Compare the vertices of two MeshInfo objects
std::array< float, 3 > operator[] (int i) const
Get vertex at a specific index in the mesh
Private Member Functions
void SetVert (int index, float x, float y, float z)
Set the specific coordinates at index to x, y, and z.
void VectorsToBuffers (const std::vector< std::array< float, 3 >> &vertices)
Insert an unindexed list of vertices into the triangle and vertex buffers using hashing.
Private Attributes
int meshid
Unique ID of this mesh in the Db ///<.
Eigen::Matrix3X< float > verts
A Matrix of vertices for this mesh ///<.
Eigen::Matrix3X< int > indices
A Matrix of triangle indices for this mesh ///<.
std::string name = ``
A name to help identify the mesh from other meshes ///<.
Detailed Description
Holds vertices and some other information about a specific mesh
Definition at line 75 of file meshinfo.h.
Constructor & Destructor Documentation
MeshInfo() [1/3]
HF::Geometry::MeshInfo::MeshInfo () [inline]
Default constructor, all fields initialized except for member indices
MeshInfo mesh; // meshid == 0; verts is given 3 rows, 0 cols; name == "INVALID"
Definition at line 118 of file meshinfo.h.
References meshid, name, and verts.
MeshInfo() [2/3]
HF::Geometry::MeshInfo::MeshInfo (const std::vector< std::array< float, 3 >> & vertices, int id, std::string name = ``)
Construct a new MeshInfo object from an unindexed vector of vertices, an ID, and a name
Parameters
vertices An ordered list of vertices, Every 3 vertices form a triangle in the mesh
id The id of this mesh
name The name of this mesh
// Prepare the vertices
std::array<float, 3> vertex_0 = { 34.1, 63.9, 16.5 };
std::array<float, 3> vertex_1 = { 23.5, 85.7, 45.2 };
std::array<float, 3> vertex_2 = { 12.0, 24.6, 99.4 };
// Create an array of vertices
std::vector<std::array<float, 3>> vertices(vertex_0, vertex_1, vertex_2);
// This mesh contains a triangle (due to having 3 vertices), id == 3451, name == "My Mesh"
// Note that vertices is passed by reference.
// Also, passing a std::vector<std::array<float, 3>> with (size < 1) will cause
// HF::Exceptions::InvalidOBJ to be thrown.
MeshInfo mesh(vertices, 3451, "My Mesh");
Definition at line 20 of file meshinfo.cpp.
References meshid, name, VectorsToBuffers(), and verts.
MeshInfo() [3/3]
HF::Geometry::MeshInfo::MeshInfo (const std::vector< float > & in_vertices, const std::vector< int > & in_indexes, int id, std::string name = ``)
Construct a new MeshInfo object from an indexed vector of vertices
Parameters
vertices An ordered list of floats with each 3 floats representing a single vertex.
indexes A vector of indexes with each index matching up with a vertex in vertices.
id The id of this mesh
name The name of this mesh
// Prepare the vertices. Every three floats represents one vertex.
std::vector<float> vertices = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 };
                                // 0 1 2 3 4 5 6 7 8
// Prepare indices - each member in indices must be the index representing the initial coordinate within a vertex.
// indices[0] refers to vertices[0] (beginning of vertex 0)
// indices[1] refers to vertices[3] (beginning of vertex 1)
// indices[2] refers to vertices[6] (beginning of vertex 2)
std::vector<int> indices = { 0, 3, 6 };
// Note that vertices and indices are passed by reference.
// Also, passing a std::vector<float> with a size that is not a multiple of 3,
// or passing a std::vector<int> with a size that is not a multiple of 3 --
// will cause HF::Exceptions::InvalidOBJ to be thrown.
// Also, indices.size() == (vertices.size() / 3), because all members of indices
// must correspond to the index of the first member representing the initial coordinate within a vertex.
MeshInfo mesh(vertices, indices, 5901, "This Mesh");
Definition at line 97 of file meshinfo.cpp.
References indices, meshid, name, and verts.
Member Function Documentation
AddVerts() [1/2]
void HF::Geometry::MeshInfo::AddVerts (const std::vector< float > & verts, std::vector< int > & indices)
Populate the mesh using only an array of floats and vertices corresponding to mesh x,y,z values and triangle indexes respectively.
Parameters
verts
indices
// TODO: needs implementation
// Prepare the vertices. Every three floats represents one vertex.
std::vector<float> vertices = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 };
                            // 0 1 2 3 4 5 6 7 8
// Prepare indices - each member in indices must be the index representing the initial coordinate within a vertex.
// indices[0] refers to vertices[0] (beginning of vertex 0)
// indices[1] refers to vertices[3] (beginning of vertex 1)
// indices[2] refers to vertices[6] (beginning of vertex 2)
std::vector<int> indices = { 0, 3, 6 };
// Create the MeshInfo instance - this example uses the no-arg constructor
MeshInfo mesh; // meshid == 0; verts is given 3 rows, 0 cols; name == "INVALID"
// Append the vertices to the mesh.
mesh.AddVerts(vertices, indices);
AddVerts() [2/2]
void HF::Geometry::MeshInfo::AddVerts (const std::vector< std::array< float, 3 >> & verts)
Append a list of verts onto the end of the mesh. This will cause the array to be resized.
// Prepare the vertices
std::array<float, 3> vertex_0 = { 34.1, 63.9, 16.5 };
std::array<float, 3> vertex_1 = { 23.5, 85.7, 45.2 };
std::array<float, 3> vertex_2 = { 12.0, 24.6, 99.4 };
// Create a vector of vertices
std::vector<std::array<float, 3>> vertices(vertex_0, vertex_1, vertex_2);
// Create the MeshInfo instance - this example uses the no-arg constructor
MeshInfo mesh; // meshid == 0; verts is given 3 rows, 0 cols; name == "INVALID"
// Append the vertices to the mesh
mesh.AddVerts(vertices);
Definition at line 111 of file meshinfo.cpp.
References verts.
ConvertToOBJCoordinates()
void HF::Geometry::MeshInfo::ConvertToOBJCoordinates ()
Convert the internal coordinates of this mesh to OBJ coordinates
Definition at line 141 of file meshinfo.cpp.
References verts.
ConvertToRhinoCoordinates()
void HF::Geometry::MeshInfo::ConvertToRhinoCoordinates ()
Convert the internal coordinates of this mesh to rhino coordinates
// Prepare the vertices
std::array<float, 3> vertex_0 = { 34.1, 63.9, 16.5 };
std::array<float, 3> vertex_1 = { 23.5, 85.7, 45.2 };
std::array<float, 3> vertex_2 = { 12.0, 24.6, 99.4 };
// Create an array of vertices
std::vector<std::array<float, 3>> vertices(vertex_0, vertex_1, vertex_2);
// Create the MeshInfo
MeshInfo mesh(vertices, 3451, "My Mesh");
// Convert the coordinates
mesh.ConvertToRhinoCoordinates();
Definition at line 130 of file meshinfo.cpp.
References verts.
GetMeshID()
int HF::Geometry::MeshInfo::GetMeshID () const
Return a copy of meshid
Returns
The member field meshid, by value
// Prepare the vertices
std::array<float, 3> vertex_0 = { 34.1, 63.9, 16.5 };
std::array<float, 3> vertex_1 = { 23.5, 85.7, 45.2 };
std::array<float, 3> vertex_2 = { 12.0, 24.6, 99.4 };
// Create an array of vertices
std::vector<std::array<float, 3>> vertices(vertex_0, vertex_1, vertex_2);
// Create the MeshInfo
MeshInfo mesh(vertices, 3451, "My Mesh");
// Use GetMeshID to do an ID match
int mesh_id = -1;
if ((mesh_id = mesh.GetMeshID()) == 3451) {
    std::cout << "Retrieved 'My Mesh' << std::endl;
}
Definition at line 173 of file meshinfo.cpp.
References meshid.
getRawIndices()
std::vector< int > HF::Geometry::MeshInfo::getRawIndices () const
Retrieve a copy of the underlying index buffer. Useful for copying into other buffers
Returns
A copy of the member field indices, the underlying index buffer (using std::copy)
// Prepare the vertices. Every three floats represents one vertex.
std::vector<float> vertices = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 };
                                // 0 1 2 3 4 5 6 7 8
// Prepare indices - each member in indices must be the index representing the initial coordinate within a vertex.
// indices[0] refers to vertices[0] (beginning of vertex 0)
// indices[1] refers to vertices[3] (beginning of vertex 1)
// indices[2] refers to vertices[6] (beginning of vertex 2)
std::vector<int> indices = { 0, 3, 6 };
// Create the mesh.
MeshInfo mesh(vertices, indices, 5901, "This Mesh");
// Retrieve a copy of mesh's index vector
std::vector<int> indices_copy_0 = mesh.getRawIndices();
std::vector<int> indices_copy_1 = mesh.getRawIndices();
// Uses std::vector<int>'s operator== to determine member equality
if (indices_copy_0 == indices_copy_1) {
    std::cout << "indices_copy_0 and indices_copy_1 share the same elements/permutation." << std::endl;
}
// This will demonstrate that indices_copy_0 and indices_copy_1 are different container instances
if (&indices_copy_0 != &indices_copy_1) {
    std::cout << "indices_copy_0 and indices_copy_1 are different container instances." << std::endl;
}
// Output: indices_copy_0 and indices_copy_1 share the same elements/permutation.
// indices_copy_0 and indices_copy_1 are different container instances.
Definition at line 182 of file meshinfo.cpp.
References indices.
getRawVertices()
std::vector< float > HF::Geometry::MeshInfo::getRawVertices () const
Retrieve a copy of the underlying vertex buffer. Helpful for filling other buffers
Returns
A copy of the member field verts, the underlying vertex buffer (using std::copy)
// Prepare the vertices. Every three floats represents one vertex.
std::vector<float> vertices = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 };
                                // 0 1 2 3 4 5 6 7 8
// Prepare indices - each member in indices must be the index representing the initial coordinate within a vertex.
// indices[0] refers to vertices[0] (beginning of vertex 0)
// indices[1] refers to vertices[3] (beginning of vertex 1)
// indices[2] refers to vertices[6] (beginning of vertex 2)
std::vector<int> indices = { 0, 3, 6 };
// Create the mesh.
MeshInfo mesh(vertices, indices, 5901, "This Mesh");
// Retrieve copies of mesh's vertices.
std::vector<float> vertices_copy_0 = mesh.getRawVertices();
std::vector<float> vertices_copy_1 = mesh.getRawVertices();
// Uses std::vector<float>'s operator== to determine member equality
if (vertices_copy_0 == vertices_copy_1) {
    std::cout << "vertices_copy_0 and vertices_copy_1 share the same elements/permutation." << std::endl;
}
// This will demonstrate that vertices_copy_0 and vertices_copy_1 are different container instances
if (&vertices_copy_0 != &vertices_copy_1) {
    std::cout << "vertices_copy_0 and vertices_copy_1 are different container instances." << std::endl;
}
// Output: vertices_copy_0 and vertices_copy_1 share the same elements/permutation.
// vertices_copy_0 and vertices_copy_1 are different container instances.
Definition at line 175 of file meshinfo.cpp.
References verts.
GetVertsAsArrays()
std::vector< std::array< float, 3 > > HF::Geometry::MeshInfo::GetVertsAsArrays () const
Retrieve vertices as a vector of arrays of float.
Returns
A vector of arrays of float
// Prepare the vertices. Every three floats represents one vertex.
std::vector<float> vertices = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 };
                                // 0 1 2 3 4 5 6 7 8
// Prepare indices - each member in indices must be the index representing the initial coordinate within a vertex.
// indices[0] refers to vertices[0] (beginning of vertex 0)
// indices[1] refers to vertices[3] (beginning of vertex 1)
// indices[2] refers to vertices[6] (beginning of vertex 2)
std::vector<int> indices = { 0, 3, 6 };
// Create the mesh.
MeshInfo mesh(vertices, indices, 5901, "This Mesh");
// Retrieve vertices as a vector of coordinates (x, y, z)
// Useful if your vertices were prepared from a one-dimensional container c, of float
// (such that c.size() % 3 == 0)
std::vector<std::array<float, 3>> vert_container = mesh.GetVertsAsArrays();
Definition at line 189 of file meshinfo.cpp.
References indices, and NumTris().
NumTris()
int HF::Geometry::MeshInfo::NumTris () const
Get the total number of triangles in the given mesh
Returns
numVerts/3
// Prepare the vertices
std::array<float, 3> vertex_0 = { 34.1, 63.9, 16.5 };
std::array<float, 3> vertex_1 = { 23.5, 85.7, 45.2 };
std::array<float, 3> vertex_2 = { 12.0, 24.6, 99.4 };
// Create an array of vertices
std::vector<std::array<float, 3>> vertices(vertex_0, vertex_1, vertex_2);
// Create the MeshInfo
MeshInfo mesh(vertices, 3451, "My Mesh");
int tri_count = 0;
if ((tri_count = mesh.NumTri()) == 0) {
    std::cout << "This mesh has no triangles." << std::endl;
} else {
    std::cout << "Triangle count: " << tri_count << std::endl;
}
// Output is: 'Triangle count: 1'
// Note that (mesh.NumVerts() / 3 && mesh.NumTris()) will always be true,
// since three vertices compose a single triangle.
Definition at line 128 of file meshinfo.cpp.
References indices.
Referenced by GetVertsAsArrays().
NumVerts()
int HF::Geometry::MeshInfo::NumVerts () const
Get the number of vertices stored in this mesh info
Returns
Total number of stored vertices
// Prepare the vertices
std::array<float, 3> vertex_0 = { 34.1, 63.9, 16.5 };
std::array<float, 3> vertex_1 = { 23.5, 85.7, 45.2 };
std::array<float, 3> vertex_2 = { 12.0, 24.6, 99.4 };
// Create an array of vertices
std::vector<std::array<float, 3>> vertices(vertex_0, vertex_1, vertex_2);
// Create the MeshInfo
MeshInfo mesh(vertices, 3451, "My Mesh");
int vert_count = 0;
if ((vert_count = mesh.NumVerts()) == 0) {
    std::cout << "This mesh has no vertices." << std::endl;
} else {
    std::cout << "Vertex count: " << std::endl;
}
// Output is: 'Vertex count: 3'
Definition at line 126 of file meshinfo.cpp.
References verts.
Referenced by operator==(), and operator[]().
operator==()
bool HF::Geometry::MeshInfo::operator== (const MeshInfo & M2) const
Compare the vertices of two MeshInfo objects
Parameters
M2 The desired MeshInfo to compare
Returns
True if all vertices are equal within a certain tolerance, false otherwise
// Prepare the vertices. Every three floats represents one vertex.
std::vector<float> vertices_0 = { 11.0, 22.0, 33.0, 44.0, 55.0, 66.0, 77.0, 88.0, 99.0 };
                                // 0 1 2 3 4 5 6 7 8
std::vector<float> vertices_1 = { 11.0, 22.0, 33.0, 44.0, 55.0, 66.0, 77.0, 88.0, 99.0 };
                                // 0 1 2 3 4 5 6 7 8
// indices[0] refers to vertices[0] (beginning of vertex 0)
// indices[1] refers to vertices[3] (beginning of vertex 1)
// indices[2] refers to vertices[6] (beginning of vertex 2)
std::vector<int> indices_0 = { 0, 3, 6 };
std::vector<int> indices_1 = { 0, 3, 6 };
MeshInfo mesh_0(vertices_0, indices_0, 5901, "This Mesh");
MeshInfo mesh_1(vertices_1, indices_0, 4790, "That Mesh");
bool equivalent = mesh_0 == mesh_1; // returns true
// operator== will determine if two MeshInfo are equal if
// the Euclidean distance between each matching element in mesh_0 and mesh_1
// is within 0.001. This means that for all i between vertices_0 and vertices_1 --
// each x, y, z within
// vertices_0[i] and vertices_1[i]
// must be within 0.001 to be considered equivalent.
// Of course, this also means that if
// mesh_0.NumVerts() != mesh_1.NumVerts(),
// mesh_0 and mesh_1 are not equivalent at all.
Definition at line 219 of file meshinfo.cpp.
References HF::Geometry::arrayDist(), and NumVerts().
operator[]()
std::array< float, 3 > HF::Geometry::MeshInfo::operator[] (int i) const
Get vertex at a specific index in the mesh
Parameters
i Index of the desired vertex
Returns
An array of floats representing the x, y, and z coordinates
// Prepare the vertices. Every three floats represents one vertex.
std::vector<float> vertices_0 = { 11.0, 22.0, 33.0, 44.0, 55.0, 66.0, 77.0, 88.0, 99.0 };
                                // 0 1 2 3 4 5 6 7 8
                                // 0 1 2
// indices[0] refers to vertices[0] (beginning of vertex 0)
// indices[1] refers to vertices[3] (beginning of vertex 1)
// indices[2] refers to vertices[6] (beginning of vertex 2)
std::vector<int> indices_0 = { 0, 3, 6 };
// Create the mesh
MeshInfo mesh(vertices_0, indices_0, 5901, "This Mesh");
// Retrieve the desired vertex
int index = 1;
// vertex consists of { 44.0, 55.0, 66.0 },
// which is the second triplet of coordinates within vertices_0.
std::vector<std::array<float, 3>> vertex = mesh[index];
Definition at line 206 of file meshinfo.cpp.
References NumVerts(), and verts.
PerformRotation()
void HF::Geometry::MeshInfo::PerformRotation (float rx, float ry, float rz)
Rotate this mesh by x, y, z rotations in degrees (pitch, yaw, roll)
Parameters
rx Determines the pitch angle
ry Determines the yaw angle
rz Determines the roll angle
Definition at line 153 of file meshinfo.cpp.
References verts.
SetMeshID()
void HF::Geometry::MeshInfo::SetMeshID (int new_id)
Assigns the value of new_id to meshid
Parameters
new_id The desired id to assign to member field meshid
// Prepare the vertices. Every three floats represents one vertex.
std::vector<float> vertices = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 };
                                // 0 1 2 3 4 5 6 7 8
// Prepare indices - each member in indices must be the index representing the initial coordinate within a vertex.
// indices[0] refers to vertices[0] (beginning of vertex 0)
// indices[1] refers to vertices[3] (beginning of vertex 1)
// indices[2] refers to vertices[6] (beginning of vertex 2)
std::vector<int> indices = { 0, 3, 6 };
// Create the mesh.
MeshInfo mesh(vertices, indices, 5901, "This Mesh");
// Prepare a new mesh ID.
int new_mesh_id = 9999;
// Assign new_mesh_id to mesh.
mesh.SetMeshID(new_mesh_id);
// Test for value equality. Will return true.
if (new_mesh_id == mesh.GetMeshID()) {
    std::cout << "ID assignment successful." << std::endl;
}
Definition at line 204 of file meshinfo.cpp.
References meshid.
SetVert()
void HF::Geometry::MeshInfo::SetVert (int index, float x, float y, float z) [inline], [private]
Set the specific coordinates at index to x, y, and z.
Parameters
index Position in the array to assign the coordinate
x X coordinate
y Y coordinate
z Z coordinate
// TODO: this is a private member function of MeshInfo, but it is not used by any other member function within MeshInfo.
Definition at line 34 of file meshinfo.cpp.
References verts.
VectorsToBuffers()
void HF::Geometry::MeshInfo::VectorsToBuffers (const std::vector< std::array< float, 3 >> & vertices) [private]
Insert an unindexed list of vertices into the triangle and vertex buffers using hashing.
Parameters
vertices An ordered list of vertices; every 3 vertices form a triangle in the mesh
// TODO: this is a private member function of MeshInfo, but it is not used by any other member function with MeshInfo.
Definition at line 80 of file meshinfo.cpp.
References HF::Geometry::IndexRawVertices(), indices, and verts.
Referenced by MeshInfo().
Member Data Documentation
indices
Eigen::Matrix3X<int> HF::Geometry::MeshInfo::indices [private]
A Matrix of triangle indices for this mesh ///<.
Definition at line 79 of file meshinfo.h.
Referenced by getRawIndices(), GetVertsAsArrays(), MeshInfo(), NumTris(), and VectorsToBuffers().
meshid
int HF::Geometry::MeshInfo::meshid [private]
Unique ID of this mesh in the Db ///<.
Definition at line 77 of file meshinfo.h.
Referenced by GetMeshID(), MeshInfo(), and SetMeshID().
name
std::string HF::Geometry::MeshInfo::name = `` [private]
A name to help identify the mesh from other meshes ///<.
Definition at line 80 of file meshinfo.h.
Referenced by MeshInfo().
verts
Eigen::Matrix3X<float> HF::Geometry::MeshInfo::verts [private]
A Matrix of vertices for this mesh ///<.
Definition at line 78 of file meshinfo.h.
Referenced by AddVerts(), ConvertToOBJCoordinates(), ConvertToRhinoCoordinates(), getRawVertices(), MeshInfo(), NumVerts(), operator[](), PerformRotation(), SetVert(), and VectorsToBuffers().
The documentation for this class was generated from the following files:
Cpp/objloader/src/meshinfo.h
Cpp/objloader/src/meshinfo.cpp