HF::AnalysisMethods::GraphGeneratorPrivate Class Reference
Contains the private implementation of the GraphGenerator to insulate the clients from the implementation.
#include <graph_generator_private.h>
Public Member Functions
GraphGeneratorPrivate (GraphGenerator &GG)
Construct a graphgeneratorprivate with the settings of GG.
HF::SpatialStructures::Graph BuildNetwork ()
Conduct a breadth first search of traversable space.
Private Member Functions
bool WalkableCheck (const SpatialStructures::Node &position)
Determine if a node is above a valid floor.
void Graphdirecs (const SpatialStructures::Node &parent, const std::vector< std::pair< int, int >> &directions, std::vector< SpatialStructures::Node > &out_children)
Calculate positions for every direction pair in directions, then deposit in out children
bool CheckStart (v3 &start)
Push point to the ground if there is ground beneath it.
void GeneratePotentialChildren (const HF::SpatialStructures::Node &parent, const std::vector< std::pair< int, int >> &directions, std::vector< HF::SpatialStructures::Node > &out_children)
Populate out_children with a potential child position for every direction in directions.
void CrawlGeom (UniqueQueue &todo)
Begin breadth first search to populate the graph with with nodes and edges.
void CrawlGeomParallel (UniqueQueue &todo)
A parallel version of CrawlGeom.
void ComputerParent (const HF::SpatialStructures::Node &parent, const std::vector< std::pair< int, int >> &directions, std::vector< HF::SpatialStructures::Edge > &out_relations)
Generate edges and children for parent in relations.
bool CheckRay (HF::SpatialStructures::Node &position, const v3 &direction, HIT_FLAG flag=HIT_FLAG::BOTH)
Cast a ray and overwrite position with the result.
bool CheckRay (v3 &position, const v3 &direction, HIT_FLAG flag=HIT_FLAG::BOTH)
Cast a ray and overwrite position with the point of intersection.
bool OcclusionCheck (const SpatialStructures::Node &parent, const SpatialStructures::Node &child)
Check if there is an obstruction between parent and child.
bool CheckFloor (const HF::SpatialStructures::Node &parent, HF::SpatialStructures::Node &child)
Offset child to the floor, then check if it abides by upstep and downstep limits.
bool isUpSlope (const HF::SpatialStructures::Node &n1, const HF::SpatialStructures::Node &n2)
Determine if the graph can traverse the slope from n1 to n2.
void GetChildren (const HF::SpatialStructures::Node &parent, const std::vector< SpatialStructures::Node > &possible_children, std::vector< HF::SpatialStructures::Edge > &out_children)
Create all possible edges from parent to possible_children.
std::vector< HF::SpatialStructures::Node > CheckChildren (const HF::SpatialStructures::Node &parent, std::vector< HF::SpatialStructures::Node > Children)
Offset all children to the ground, then check if traversing from parent would require a step outside of step height limits.
bool IsConnected (const HF::SpatialStructures::Node &parent, const HF::SpatialStructures::Node &child)
float RayDist (const HF::SpatialStructures::Node &p1, const v3 &direction, HIT_FLAG flag=HIT_FLAG::BOTH)
Get the distance between the node and where the ray hits. If the ray doesn't hit, return 0.
HF::SpatialStructures::STEP CheckConnection (const HF::SpatialStructures::Node &parent, const HF::SpatialStructures::Node &child)
Check if parent can traverse to child.
Private Attributes
HF::SpatialStructures::Graph G
An internal graph that is iterated upon as the program is executed.
HF::AnalysisMethods::GraphGenerator & GG
The underlying graph generator to hold all the settings.
Detailed Description
Contains the private implementation of the GraphGenerator to insulate the clients from the implementation.
Todo
Todo Combine this with the graphgenerator public and create a single class.
Definition at line 22 of file graph_generator_private.h.
Constructor & Destructor Documentation
GraphGeneratorPrivate()
HF::AnalysisMethods::GraphGeneratorPrivate::GraphGeneratorPrivate (GraphGenerator & GG)
Construct a graphgeneratorprivate with the settings of GG.
Parameters
GG GraphGenerator containing settings to use when BuildNetwork is called.
Definition at line 69 of file graph_generator_private.cpp.
Member Function Documentation
BuildNetwork()
Graph HF::AnalysisMethods::GraphGeneratorPrivate::BuildNetwork ()
Conduct a breadth first search of traversable space.
Returns
The Graph generated using the settings from GG.
See also
GraphGenerator::BuildNetwork
Definition at line 72 of file graph_generator_private.cpp.
References CheckStart(), HF::AnalysisMethods::GraphGenerator::core_count, CrawlGeom(), CrawlGeomParallel(), G, GG, HF::AnalysisMethods::UniqueQueue::push(), HF::SpatialStructures::roundhf(), and HF::AnalysisMethods::GraphGenerator::start.
Referenced by HF::AnalysisMethods::GraphGenerator::BuildNetwork().
CheckChildren()
vector< Node > HF::AnalysisMethods::GraphGeneratorPrivate::CheckChildren (const HF::SpatialStructures::Node & parent, std::vector< HF::SpatialStructures::Node > Children) [private]
Offset all children to the ground, then check if traversing from parent would require a step outside of step height limits.
Parameters
parent Parent of all children in children.
children Child nodes to check.
Returns
All children that are above a valid floor and can be traversed to by parent without requiring a step outside of step height limits.
Todo
Todo Why is Children not const?
Definition at line 190 of file graph_generator_private.cpp.
References CheckRay(), HF::AnalysisMethods::down, HF::AnalysisMethods::GraphGenerator::downstep, GG, and HF::AnalysisMethods::GraphGenerator::upstep.
Referenced by GetChildren().
CheckConnection()
STEP HF::AnalysisMethods::GraphGeneratorPrivate::CheckConnection (const HF::SpatialStructures::Node & parent, const HF::SpatialStructures::Node & child) [private]
Check if parent can traverse to child.
Parameters
parent Parent of child.
child Child generated from parent.
Returns
The type of STEP from parent to child.
Specifically, this function checks for a direct line of sight. If the line of sight check succeeds, then it checks to see if the slope between parent and child is within the defined limits. If not, then it will offset the child node upward by upstep if it's higher than the parent, or downward by downstep if it's lower than parent and try the occlusion check again.
See also
STEP for details on each type of step.
Definition at line 209 of file graph_generator_private.cpp.
References HF::SpatialStructures::DOWN, HF::AnalysisMethods::GraphGenerator::downstep, GG, isUpSlope(), HF::SpatialStructures::NONE, HF::SpatialStructures::NOT_CONNECTED, OcclusionCheck(), HF::SpatialStructures::OVER, HF::SpatialStructures::UP, and HF::AnalysisMethods::GraphGenerator::upstep.
Referenced by GetChildren().
CheckFloor()
bool HF::AnalysisMethods::GraphGeneratorPrivate::CheckFloor (const HF::SpatialStructures::Node & parent, HF::SpatialStructures::Node & child) [inline], [private]
Offset child to the floor, then check if it abides by upstep and downstep limits.
Parameters
parent Parent of child.
child Child to check. Is moved to the floor if a floor is beneath it.
Returns
True if the child has a floor beneath it, and when offset it doesn't exceed the maximum upstep or downstep when compared to parent.
Deprecated
Deprecated CheckChildren performs the same function, but works on an array of nodes.
Definition at line 143 of file graph_generator_private.cpp.
References CheckRay(), HF::AnalysisMethods::down, HF::AnalysisMethods::GraphGenerator::downstep, HF::AnalysisMethods::FLOORS, GG, HF::AnalysisMethods::GraphGenerator::upstep, and HF::SpatialStructures::Node::z.
CheckRay() [1/2]
bool HF::AnalysisMethods::GraphGeneratorPrivate::CheckRay (HF::SpatialStructures::Node & position, const v3 & direction, HIT_FLAG flag = HIT_FLAG::BOTH) [private]
Cast a ray and overwrite position with the result.
Parameters
position Node to use as the origin. On Hit, this node's position will be overridden
direction Direction to fire the ray in
flag The type of geometry to intersect
Returns
True if the ray intersected any geometry. False otherwise.
Postcondition
If true is returned, position contains the point where the casted ray intersected geometry.
Definition at line 431 of file graph_generator_private.cpp.
References HF::AnalysisMethods::BOTH, HF::RayTracer::EmbreeRayTracer::FireRay(), HF::AnalysisMethods::FLOORS, GG, HF::AnalysisMethods::OBSTACLES, HF::AnalysisMethods::GraphGenerator::ray_tracer, and HF::AnalysisMethods::GraphGenerator::walkable_surfaces.
Referenced by CheckChildren(), CheckFloor(), and CheckStart().
CheckRay() [2/2]
bool HF::AnalysisMethods::GraphGeneratorPrivate::CheckRay (v3 & position, const v3 & direction, HIT_FLAG flag = HIT_FLAG::BOTH) [private]
Cast a ray and overwrite position with the point of intersection.
Parameters
position Node to use as the origin. On intersection, this node's position will be overridden with the point of intersection.
direction Direction to cast the ray in.
flag The type of geometry to collide with. See HIT_FLAG for more details.
Returns
True on hit, false otherwise.
Postcondition
If true is returned, position contains the point where the casted ray intersected geometry.
Exceptions
std::exception if HIT_FLAG isn't a valid value.
Definition at line 415 of file graph_generator_private.cpp.
References HF::AnalysisMethods::BOTH, HF::RayTracer::EmbreeRayTracer::FireRay(), HF::AnalysisMethods::FLOORS, GG, HF::AnalysisMethods::OBSTACLES, and HF::AnalysisMethods::GraphGenerator::ray_tracer.
CheckStart()
bool HF::AnalysisMethods::GraphGeneratorPrivate::CheckStart (v3 & start) [private]
Push point to the ground if there is ground beneath it.
Parameters
start Start point to check and modify.
Returns
Returns true if CheckRay(start, down) is true, false otherwise
Postcondition
If true is returned, the start point is placed directly on top of the geometry below it. If false, the start point is unmodified.
Todo
Todo Is this needed? This is identical to CheckRay.
Definition at line 105 of file graph_generator_private.cpp.
References CheckRay(), and HF::AnalysisMethods::down.
Referenced by BuildNetwork().
ComputerParent()
void HF::AnalysisMethods::GraphGeneratorPrivate::ComputerParent (const HF::SpatialStructures::Node & parent, const std::vector< std::pair< int, int >> & directions, std::vector< HF::SpatialStructures::Edge > & out_relations) [inline], [private]
Generate edges and children for parent in relations.
Parameters
parent Parent node to generate children from.
directions Directions to generate children in.
out_relations Output parameter for relations.
Postcondition
out_relation contains all valid edges between parent and its children.
See also
GeneratePotentialChildren for info on how directions are used to generate children.
Definition at line 464 of file graph_generator_private.cpp.
References GeneratePotentialChildren(), and GetChildren().
Referenced by CrawlGeom(), and CrawlGeomParallel().
CrawlGeom()
void HF::AnalysisMethods::GraphGeneratorPrivate::CrawlGeom (UniqueQueue & todo) [private]
Begin breadth first search to populate the graph with with nodes and edges.
Parameters
todo Todo list to hold unchecked nodes. Must atleast contain a single start point.
Precondition
todo contains the starting point for the graph.
Todo
Todo Extract the set logic for directions to another function.
See also
CrawlGeomParallel for a parallel version.
Definition at line 271 of file graph_generator_private.cpp.
References HF::SpatialStructures::Graph::addEdge(), ComputerParent(), HF::AnalysisMethods::UniqueQueue::empty(), G, GG, HF::AnalysisMethods::GraphGenerator::max_nodes, HF::AnalysisMethods::GraphGenerator::max_step_connection, HF::AnalysisMethods::permutations(), HF::AnalysisMethods::UniqueQueue::pop(), and HF::AnalysisMethods::UniqueQueue::push().
Referenced by BuildNetwork().
CrawlGeomParallel()
void HF::AnalysisMethods::GraphGeneratorPrivate::CrawlGeomParallel (UniqueQueue & todo) [private]
A parallel version of CrawlGeom.
Parameters
todo Todo list to use for execution. Must atleast contain a single start point.
Precondition
todo contains the start point for the graph.
Todo
Todo Extract the set logic for directions to another function.
See also
CrawlGeom for a serial version.
Definition at line 316 of file graph_generator_private.cpp.
References HF::SpatialStructures::Graph::addEdge(), ComputerParent(), HF::AnalysisMethods::UniqueQueue::empty(), G, GG, HF::AnalysisMethods::GraphGenerator::max_nodes, HF::AnalysisMethods::GraphGenerator::max_step_connection, HF::AnalysisMethods::permutations(), HF::AnalysisMethods::UniqueQueue::pop(), HF::AnalysisMethods::UniqueQueue::popMany(), HF::AnalysisMethods::UniqueQueue::push(), and HF::AnalysisMethods::UniqueQueue::size().
Referenced by BuildNetwork().
GeneratePotentialChildren()
void HF::AnalysisMethods::GraphGeneratorPrivate::GeneratePotentialChildren (const HF::SpatialStructures::Node & parent, const std::vector< std::pair< int, int >> & directions, std::vector< HF::SpatialStructures::Node > & out_children) [inline], [private]
Populate out_children with a potential child position for every direction in directions.
Parameters
parent Parent to generate children for.
directions X,Y pairs to use for generating children. I.E. A pair of {1,2}would create a child at {parent.x + 1*spacing.x, parent.y + 2*spacing.y, parent.z + spacing.z}.
out_children Output parameter for children.
Postcondition
out_children is filled with children generated from parent and directions.
Todo
Todo Potential speed gain here by using indexing instead of emplace_back.
Definition at line 109 of file graph_generator_private.cpp.
References GG, HF::SpatialStructures::roundhf(), and HF::AnalysisMethods::GraphGenerator::spacing.
Referenced by ComputerParent().
GetChildren()
void HF::AnalysisMethods::GraphGeneratorPrivate::GetChildren (const HF::SpatialStructures::Node & parent, const std::vector< SpatialStructures::Node > & possible_children, std::vector< HF::SpatialStructures::Edge > & out_children) [private]
Create all possible edges from parent to possible_children.
Parameters
parent Parent node used to generate contents of possible_children.
possible_children Possible children for parent. Usually generated from GeneratePotentialChildren.
out_children An output array for valid edges in after they've been evaluated.
All children are offset to the ground using CheckChildren, then a connection to parent is checked for using CheckConnection. If CheckChildren or CheckConnection is not successful for a child node, then it will not have an edge created in out_children.
Postcondition
out_children contains a set of all valid edges between parent and the children in possible_children.
Definition at line 172 of file graph_generator_private.cpp.
References CheckChildren(), CheckConnection(), HF::SpatialStructures::Node::distanceTo(), and HF::SpatialStructures::NOT_CONNECTED.
Referenced by ComputerParent().
Graphdirecs()
void HF::AnalysisMethods::GraphGeneratorPrivate::Graphdirecs (const SpatialStructures::Node & parent, const std::vector< std::pair< int, int >> & directions, std::vector< SpatialStructures::Node > & out_children) [private]
Calculate positions for every direction pair in directions, then deposit in out children
Parameters
parent The parent node
directions A reference to a direction pair (coordinates)
out_children A reference to a vector of Node where children will be deposited.
Deprecated
Deprecated From old codebase. Replaced with permutations.
IsConnected()
bool HF::AnalysisMethods::GraphGeneratorPrivate::IsConnected (const HF::SpatialStructures::Node & parent, const HF::SpatialStructures::Node & child) [private]
Deprecated
Deprecated Never used or implemented. In the Python code this would have cast a ray between parent and child then compared distance between the ray's intersection point with the distance between parent and child to see if there was a clear line of sight. Succeeded by OcclusionCheck.
isUpSlope()
bool HF::AnalysisMethods::GraphGeneratorPrivate::isUpSlope (const HF::SpatialStructures::Node & n1, const HF::SpatialStructures::Node & n2) [private]
Determine if the graph can traverse the slope from n1 to n2.
Parameters
n1 Node that's being traversed from.
n2 Node that's being traversed to.
Returns
True if the slope between n1 and n2 is within the limits in our settings. False otherwise.
Todo
Todo Rename this function to SlopeCheck, or SlopeCalc like the function it's based on in the original python code.
Definition at line 159 of file graph_generator_private.cpp.
References HF::AnalysisMethods::GraphGenerator::downslope, GG, HF::AnalysisMethods::GraphGenerator::upslope, HF::SpatialStructures::Node::x, HF::SpatialStructures::Node::y, and HF::SpatialStructures::Node::z.
Referenced by CheckConnection().
OcclusionCheck()
bool HF::AnalysisMethods::GraphGeneratorPrivate::OcclusionCheck (const SpatialStructures::Node & parent, const SpatialStructures::Node & child) [inline], [private]
Check if there is an obstruction between parent and child.
Parameters
parent Parent node to cast the ray from.
child Child node to cast the ray to.
Returns
True if there is an obstacle blocking line of sight between between parent and child.
This function casts an occlusion ray from parent to child with a maximum distance equal to the distance between both nodes.
Definition at line 127 of file graph_generator_private.cpp.
References HF::SpatialStructures::Node::directionTo(), HF::SpatialStructures::Node::distanceTo(), HF::RayTracer::EmbreeRayTracer::FireOcclusionRay(), GG, HF::AnalysisMethods::GraphGenerator::ray_tracer, HF::SpatialStructures::Node::x, HF::SpatialStructures::Node::y, and HF::SpatialStructures::Node::z.
Referenced by CheckConnection().
RayDist()
float HF::AnalysisMethods::GraphGeneratorPrivate::RayDist (const HF::SpatialStructures::Node & p1, const v3 & direction, HIT_FLAG flag = HIT_FLAG::BOTH) [private]
Get the distance between the node and where the ray hits. If the ray doesn't hit, return 0.
Parameters
p1 The desired node to assess
direction The direction of the ray
flag Ray collision status, 1 = FLOORS, 2 = OBSTACLES, 3 = BOTH (the default)
Returns
Distance between the node and the ray collision -- 0.0f if ray does not hit
Deprecated
Deprecated Not needed. This function was only used for checking if a ray was within a certain distance of something, however the raytracer's maximum distance parameter removes the need to check distance at all.
WalkableCheck()
bool HF::AnalysisMethods::GraphGeneratorPrivate::WalkableCheck (const SpatialStructures::Node & position) [inline], [private]
Determine if a node is above a valid floor.
Parameters
position Node to check.
Returns
True if the node is above a valid floor, false othewise.
Identical to CheckRay, but without any side effects. (the value of position won't change).
Definition at line 61 of file graph_generator_private.cpp.
References HF::AnalysisMethods::down, and HF::AnalysisMethods::FLOORS.
Member Data Documentation
G
HF::SpatialStructures::Graph HF::AnalysisMethods::GraphGeneratorPrivate::G [private]
An internal graph that is iterated upon as the program is executed.
Definition at line 25 of file graph_generator_private.h.
Referenced by BuildNetwork(), CrawlGeom(), and CrawlGeomParallel().
GG
HF::AnalysisMethods::GraphGenerator& HF::AnalysisMethods::GraphGeneratorPrivate::GG [private]
The underlying graph generator to hold all the settings.
Definition at line 26 of file graph_generator_private.h.
Referenced by BuildNetwork(), CheckChildren(), CheckConnection(), CheckFloor(), CheckRay(), CrawlGeom(), CrawlGeomParallel(), GeneratePotentialChildren(), isUpSlope(), and OcclusionCheck().
The documentation for this class was generated from the following files:
Cpp/analysismethods/src/graph_generator_private.h
Cpp/analysismethods/src/graph_generator_private.cpp