HF::SpatialStructures::Graph Class Reference
A Graph of nodes connected by edges that supports both integers and HF::SpatialStructures::Node.
#include <graph.h>
Public Member Functions
Graph (const std::vector< std::vector< int >> &edges, const std::vector< std::vector< float >> &distances, const std::vector< Node > &Nodes)
Construct a graph from a list of nodes, edges, and distances.
Graph ()
Construct an empty graph.
bool HasEdge (const std::array< float, 3 > &parent, const std::array< float, 3 > &child, bool undirected=false) const
Determine if the graph has an edge from parent to child.
bool HasEdge (const Node &parent, const Node &child, const bool undirected=false) const
Determine if the graph has an edge from parent to child.
bool HasEdge (int parent, int child, bool undirected=false) const
std::vector< Node > Nodes () const
Get a list of nodes from the graph sorted by ID.
std::vector< Edge > GetUndirectedEdges (const Node &N) const
Get a list of all edges to and from node N.
std::vector< EdgeSet > GetEdges () const
Get every in the given graph as IDs.
std::vector< float > AggregateGraph (COST_AGGREGATE agg_type, bool directed=true) const
Summarize the costs of every outgoing edge for every node in the graph.
const std::vector< Edge > operator[] (const Node &n) const
Get a list of all edges from Node n.
void addEdge (const Node &parent, const Node &child, float score=1.0f)
Add a new edge to the graph from parent to child.
void addEdge (int parent_id, int child_id, float score)
Add a new edge to the graph from parent to child.
bool hasKey (const Node &n) const
Determine if n exists in the graph.
std::vector< std::array< float, 3 > > NodesAsFloat3 () const
Get a list of nodes as float arrays.
int size () const
Determine how many nodes are in the graph.
int getID (const Node &node) const
Retrieve the ID for node in this graph.
void Compress ()
Compress the graph to a CSR and enable the usage of several functions.
CSRPtrs GetCSRPointers ()
Obtain the size of and pointers to the 3 arrays that comprise this graph's CSR. graph if it isn't compressed already
Node NodeFromID (int id) const
Retrieve the node that corresponds to id.
void Clear ()
Clear all nodes and edges from the graph.
void GenerateCrossSlope ()
Calculate cross slope for the given graph
void GenerateEnergy ()
Calculate energy for the given graph
Private Member Functions
int getOrAssignID (const Node &input_node)
Get the unique ID for this x, y, z position, assigning it an new one if it doesn't already exist
int getOrAssignID (int input_int)
Add an ID to the graph if it doesn't exist already.
bool checkForEdge (int parent, int child) const
Determine if an edge between parent and child exists in the graph.
void UpdateIDs (int new_id)
Add an empty node for this new id
Private Attributes
std::vector< Node > ordered_nodes
A list of nodes contained by the graph.
std::vector< int > id_to_nodes
Maps ids to indexes in ordered_nodes.
robin_hood::unordered_map< Node, int > idmap
Maps a list of X,Y,Z positions to ids.
Eigen::SparseMatrix< float, 1 > edge_matrix
The underlying CSR containing edge nformation.
int next_id = 0
The id for the next unique node.
std::vector< Eigen::Triplet< float > > triplets
Edges to be converted to a CSR when Graph::Compress() is called.
bool needs_compression = true
If true, the CSR is inaccurate and requires compression.
Detailed Description
A Graph of nodes connected by edges that supports both integers and HF::SpatialStructures::Node.
Internally, this object uses Eigen (https://eigen.tuxfamily.org/dox/group__TutorialSparse.html) to store and maintain a CSR matrix.
Invariant
Every node in the graph will have a Unique ID with no repeats
Definition at line 96 of file graph.h.
Constructor & Destructor Documentation
Graph() [1/2]
HF::SpatialStructures::Graph::Graph (const std::vector< std::vector< int >> & edges, const std::vector< std::vector< float >> & distances, const std::vector< Node > & Nodes)
Construct a graph from a list of nodes, edges, and distances.
Parameters
edges Ordered array of arrays of edges for each node in nodes.
distances Ordered array of distance from parent to child for each edge in edges.
Nodes Ordered array of nodes to act as a parent to all children in it's array in edges.
Preallocates the matrix it in element by element and compresses it.
Precondition
1) The size of all input arrays must match: (edges.size() == nodes.size() && nodes.size() == distances.size())
2) For the node at nodes[i], edges[i] should contain an array for the id of all nodes that nodes[i] has an edge from and, and distances[i] should contain an array of the the distance from nodes[i] to one of the nodes it has an edge to in edges[i].
Note
After constructing a graph with this constructor, it will not be able to be modified. Use the empty constructor and use addEdge if you want to modify the graph after construction. This may change in the future.
Remarks
This constructor can offer `slightly higher performance and memory consumption` than constructing a graph using Graph::addEdge in a loop according to official eigen documentation, however it may not be feasible for certain situations where the entire graph isn't known before the constructor is called. The implementation is based on the algorithm from Eigen's documentation under the section Filling a Sparse Matrix https://eigen.tuxfamily.org/dox/group__TutorialSparse.html.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
Definition at line 326 of file graph.cpp.
Graph() [2/2]
HF::SpatialStructures::Graph::Graph () [inline]
Construct an empty graph.
Remarks
This can be used to create a new graph to later be filled with edges/nodes by calling Graph::addEdge() then calling Graph::Compress(). Implementation is based on the Eigen documentation for Filling a CSR: https://eigen.tuxfamily.org/dox/group__TutorialSparse.html.
See also
Graph::addEdge() for details on adding edges.
Graph::Compress() for details on compressing the graph.
// be sure to #include "graph.h"
HF::SpatialStructures::Graph graph; // This represents an order-zero graph (null graph)
                                        // It lacks vertices and edges.
Definition at line 228 of file graph.h.
Member Function Documentation
addEdge() [1/2]
void HF::SpatialStructures::Graph::addEdge (const Node & parent, const Node & child, float score = 1.0f)
Add a new edge to the graph from parent to child.
Parameters
parent Parent node of the edge.
child Child node of the edge.
score Cost of traversing from aprent to child.
If the parent or child node do not have an ID. An ID will be assigned automatically.
Warning
This will not work if the graph wasn't created from the empty constructor since it has no internal edge list to add to.
Remarks
This adds a new element to the triplet list so next time Compress is called, the value is added to the graph.
Todo
Todo How should this signal that the graph can't have edges added to it? Or how do we add edges to an existing graph quickly without adding to its edge list?
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Create a pair of nodes
HF::SpatialStructures::Node n_parent(4.0f, 5.0f, 6.0f);
HF::SpatialStructures::Node n_child(7.0f, 8.0f, 9.0f);
graph.addEdge(n_parent, n_child); // default score is 1.0f
Definition at line 224 of file graph.cpp.
Referenced by AddEdgeFromNodeIDs(), AddEdgeFromNodes(), HF::AnalysisMethods::GraphGeneratorPrivate::CrawlGeom(), and HF::AnalysisMethods::GraphGeneratorPrivate::CrawlGeomParallel().
addEdge() [2/2]
void HF::SpatialStructures::Graph::addEdge (int parent_id, int child_id, float score)
Add a new edge to the graph from parent to child.
Parameters
parent Parent node of the edge.
child Child node of the edge.
score Cost of traversing from aprent to child.
If the parent or child ids don't exist in the dictionary, they will be added.
Warning
This will not work if the graph wasn't created from the empty constructor since it has no internal edge list to add to.
Remarks
This adds a new element to the triplet list so next time Compress is called, the value is added to the graph.
Todo
Todo How should this signal that the graph can't have edges added to it? Or how do we add edges to an existing graph quickly without adding to its edge list?
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
int parent = 1;
int child = 2;
graph.addEdge(parent, child, 1.0f);
graph.Compress();
Definition at line 237 of file graph.cpp.
AggregateGraph()
std::vector< float > HF::SpatialStructures::Graph::AggregateGraph (COST_AGGREGATE agg_type, bool directed = true) const
Summarize the costs of every outgoing edge for every node in the graph.
Parameters
agg_type Type of aggregation to use.
directed If true, include both incoming and outgoing edges for calculating a node's score.
Returns
An ordered list of scores for agg_type on each node in the graph.
Remarks
Useful for getting scores from the VisibilityGraph.
Exceptions
std::out_of_range if agg_type doesn't match any value of COST_AGGREGATE.
Std::exception if the graph isn't compressed.
Time Complexity
If undirected: O(k) where k is the total number of edges in the graph.
If directed: O(n) where n is the total number of nodes in the graph.
See also
COST_AGGREGATE to see a list of supported aggregation types.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// graph must be compressed, or a exception will be thrown
HF::SpatialStructures::COST_AGGREGATE aggregate = HF::SpatialStructures::COST_AGGREGATE::AVERAGE; // aggregate == 1 in this case
// directed parameter may be true or false
std::vector<float> aggregate_graph = graph.AggregateGraph(aggregate, true);
Definition at line 156 of file graph.cpp.
References HF::SpatialStructures::Aggregate().
Referenced by AggregateCosts().
checkForEdge()
bool HF::SpatialStructures::Graph::checkForEdge (int parent, int child) const [private]
Determine if an edge between parent and child exists in the graph.
Iterates through every row in the parent's column to find child. If child is not found in this column, false is returned. If child can be found in this column, then true is returned.
Time Complexity
O(k) where k is the number of edges from parent.
        
        // Iterate through parent's row to see if it has child.
        for (SparseMatrix<float, 1>::InnerIterator it(edge_matrix, parent); it; ++it)
            if (it.col() == child) return true;
        
        // If we've gotten to this point, then the child doesn't exist in parent's row
        return false;
Definition at line 256 of file graph.cpp.
Clear()
void HF::SpatialStructures::Graph::Clear ()
Clear all nodes and edges from the graph.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// If we want to remove all nodes and edges from graph, we may do so with Clear:
graph.Clear(); // edge_matrix is zeroed out, buffer is squeezed,
                                    // triplets are also cleared, and
                                    // needs_compression == true
Definition at line 415 of file graph.cpp.
Referenced by ClearGraph().
Compress()
void HF::SpatialStructures::Graph::Compress ()
Compress the graph to a CSR and enable the usage of several functions.
This won't do anything if called on an already compressed graph. The graph is `compressed` by resizing the edge matrix to the maximum ID of any node in triplets, then calling setFromTriplets().
Note
This function actually doesn't actually reduce memory usage since it keeps the edge list in order to allow for modifications to the graph. In the future, it may be beneficial allow for the user to pass in a boolean that would delete the triplet array if true.
Remarks
This method of constructing the CSR is based on Eigen's documentation for Filling a sparse matrix https://eigen.tuxfamily.org/dox/group__TutorialSparse.html.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Create a pair of nodes
HF::SpatialStructures::Node n_parent(4.0f, 5.0f, 6.0f);
HF::SpatialStructures::Node n_child(7.0f, 8.0f, 9.0f);
graph.addEdge(n_parent, n_child); // default score is 1.0f
// In order to use GetEdges, or AggregateGraph, we must compress our graph instance
graph.Compress(); // GetEdges and AggregateGraph are now usable
Definition at line 395 of file graph.cpp.
Referenced by Compress().
GenerateCrossSlope()
void HF::SpatialStructures::Graph::GenerateCrossSlope ()
Calculate cross slope for the given graph
Deprecated
Deprecated Not Implemented.
// TODO example - code commented out in graph.cpp
GenerateEnergy()
void HF::SpatialStructures::Graph::GenerateEnergy ()
Calculate energy for the given graph
Deprecated
Deprecated Not Implemented.
// TODO example - code commented out in graph.cpp
GetCSRPointers()
CSRPtrs HF::SpatialStructures::Graph::GetCSRPointers ()
Obtain the size of and pointers to the 3 arrays that comprise this graph's CSR. graph if it isn't compressed already
Returns
Pointers and sizes of the arrays that comprise the CSR. If the CSR cannot be constructed due to factors such as an empty input array, then the CSRPtrs contain null values for it's pointers.
This will automatically call Compress if it hasn't been called already.
Remarks
This can be useful for reconstructing or mapping to the CSR without interacting with eigen at all. Numpy can directly make map the arrays returned by this function to it's own CSR implementation.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Create a pair of nodes
HF::SpatialStructures::Node n_parent(4.0f, 5.0f, 6.0f);
HF::SpatialStructures::Node n_child(7.0f, 8.0f, 9.0f);
graph.addEdge(n_parent, n_child); // default score is 1.0f
// Graph will be compressed automatically be GetCSRPointers
CSRPtrs returned_csr = graph.GetCSRPointers();
See also
CSRPtrs.AreValid() for checking if the return value represents a valid CSR.
Definition at line 32 of file graph.cpp.
References Compress().
Referenced by GetCSRPointers().
GetEdges()
std::vector< EdgeSet > HF::SpatialStructures::Graph::GetEdges () const
Get every in the given graph as IDs.
Returns
An array of edgesets for every node in the graph (Graph in the form of IDs).
Exceptions
std::exception if the graph hasn't been compressed. compressed.
Time Complexity
O(k) where k is the number of edges in the graph.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// graph must be compressed, or a exception will be thrown
// To brief, an EdgeSet has the following layout: struct EdgeSet { int parent;
// std::vector<IntEdge> children; };
//
// An IntEdge has the following layout: struct IntEdge { int child; float
// weight; };
// A std::vector<EdgeSet> is a Graph, in the form of IDs.
std::vector<HF::SpatialStructures::EdgeSet> edge_set = graph.GetEdges();
Definition at line 87 of file graph.cpp.
Referenced by HF::Pathfinding::BoostGraph::BoostGraph().
getID()
int HF::SpatialStructures::Graph::getID (const Node & node) const
Retrieve the ID for node in this graph.
Returns
The ID assigned to this node. -1 if it was not yet added to the graph
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
HF::SpatialStructures::Node other_node(55.0f, 66.1f, 15.5f, 9510); // Let's construct a Node we know is not in graph.
bool has_key = graph.hasKey(other_node); // other_node does not exist in graph, so has_key == false;
int ID = graph.getID(other_node); // ID will assigned -1, because other_node is not a part of graph.
// Likewise, if we pass a Node instance that indeed exists...
// Retrieve the nodes from the graph, or use the original instance of
// std::vector<Node> passed to Graph upon instantiation
std::vector<HF::SpatialStructures::Node> get_nodes = graph.Nodes();
// nodes[index] yields an instance of Node that we can pass to hasKey. Any node
// that exists with graph can be passed to this member function to determine if
// the graph has the node's key, or not.
int index = 2; // we assume for this example that index 2 is valid.
HF::SpatialStructures::Node good_node = get_nodes[index];
ID = graph.getID(good_node); // ID > -1, i.e. it is a Node instance that exists within this Graph.
Definition at line 24 of file graph.cpp.
Referenced by GetNodeID().
getOrAssignID() [1/2]
int HF::SpatialStructures::Graph::getOrAssignID (const Node & input_node) [private]
Get the unique ID for this x, y, z position, assigning it an new one if it doesn't already exist
If the node has not yet been seen by the graph, next_id will be assigned to it and incremented, then the node node will and its new id will be added to idmap. If the node has already been assigned an ID, then the ID will be returned directly from idmap.
Parameters
input_node Node to retrieve and potentially assign a new ID for.
Returns
The ID of input_node.
// definition of Graph::addEdge(const Node& parent, const Node& child, float score)
        needs_compression = true;
        int parent_id = getOrAssignID(parent);
        int child_id = getOrAssignID(child);
        triplets.emplace_back(
            Eigen::Triplet<float>(parent_id, child_id, score)
        );
Definition at line 288 of file graph.cpp.
getOrAssignID() [2/2]
int HF::SpatialStructures::Graph::getOrAssignID (int input_int) [private]
Add an ID to the graph if it doesn't exist already.
// definition of Graph::addEdge(int parent_id, int child_id, float score)
        // This will require that the graph is recompressed
        needs_compression = true;
        // If the parent or child id is larger than next_id, set next_id to parent or child ID.
        next_id = std::max(child_id, std::max(parent_id, next_id));
        // Store these Ids in the hashmap if they don't exist already.
        getOrAssignID(child_id);
        getOrAssignID(parent_id);
        // Add this to the list of triplets.
        triplets.emplace_back(Eigen::Triplet<float>(parent_id, child_id, score));
Definition at line 313 of file graph.cpp.
GetUndirectedEdges()
vector< Edge > HF::SpatialStructures::Graph::GetUndirectedEdges (const Node & N) const
Get a list of all edges to and from node N.
Parameters
N The Node to get edges from and to.
Returns
A list of edges to and from node N or an empty array if is not in the graph.
Time Complexity
O(k) where k is the number of edges in the graph since it needs to iterate through every edge in the graph to find the edges to this node.
See also
operator[] to get a list of directed edges only containing edges from N.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Retrieve the nodes from the graph, or use the original instance of
// std::vector<HF::SpatialStructures::Node> passed to Graph upon instantiation
std::vector<HF::SpatialStructures::Node> get_nodes = graph.Nodes();
// nodes[index] yields an instance of Node that we can pass to
// GetUndirectedEdges. Any node that exists with graph can be passed to this
// member function to retrieve a vector of undirected edges.
int index = 2;
std::vector<HF::SpatialStructures::Edge> undirected_edges = graph.GetUndirectedEdges(get_nodes[index]);
Definition at line 59 of file graph.cpp.
HasEdge() [1/3]
bool HF::SpatialStructures::Graph::HasEdge (const Node & parent, const Node & child, const bool undirected = false) const
Determine if the graph has an edge from parent to child.
Parameters
parent Parent of the edge to check for.
child Child of the edge to check for.
undirected If true, look for an edge from child to parent as well.
Returns
True if an edge between parentand child exists (also child and parent if undirected is true).
Remarks
Gets the IDs of both nodes, then calls the integer overload.
Exceptions
std::exception if the graph is uncompressed.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// last argument can be true/false for undirected/directed graph respectively
bool has_edge = graph.HasEdge(node_1, node_2, true);
Definition at line 272 of file graph.cpp.
HasEdge() [2/3]
bool HF::SpatialStructures::Graph::HasEdge (const std::array< float, 3 > & parent, const std::array< float, 3 > & child, bool undirected = false) const
Determine if the graph has an edge from parent to child.
Parameters
parent Parent of the edge to check for.
child Child of the edge to check for.
undirected If true, look for an edge from child to parent as well.
Returns
True if an edge between parent and child exists (also child and parent if undirected is true).
Remarks
Converts parent and child to Node then calls the node overload.
Exceptions
std::exception if the matrix is uncompressed.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Prepare {x, y, z} coordinates (positions)
auto parent_pos = node_1.getArray(); // (2.0, 3.0, 4.0)
auto child_pos = node_2.getArray(); // (11.0, 22.0, 140.0)
// last argument can be true/false for undirected/directed graph respectively
bool has_edge = graph.HasEdge(parent_pos, child_pos, true);
Definition at line 367 of file graph.cpp.
HasEdge() [3/3]
bool HF::SpatialStructures::Graph::HasEdge (int parent, int child, bool undirected = false) const
Definition at line 268 of file graph.cpp.
hasKey()
bool HF::SpatialStructures::Graph::hasKey (const Node & n) const
Determine if n exists in the graph.
Parameters
n Node to look for.
Returns
True if the node exists, false otherwise.
Performs a single hash to check if n exists in the hashmap.
Time Complexity
O(1) since it's a single hash function.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
HF::SpatialStructures::Node other_node(55.0f, 66.1f, 15.5f, 9510); // Let's construct a Node we know is not in graph.
bool has_key = graph.hasKey(other_node); // other_node does not exist in graph, so has_key == false;
// Likewise, if we pass a Node instance that indeed exists...
// Retrieve the nodes from the graph, or use the original instance of
// std::vector<Node> passed to Graph upon instantiation
std::vector<HF::SpatialStructures::Node> get_nodes = graph.Nodes();
// nodes[index] yields an instance of Node that we can pass to hasKey. Any node
// that exists with graph can be passed to this member function to determine if
// the graph has the node's key, or not.
int index = 2;
HF::SpatialStructures::Node good_node = get_nodes[index];
has_key = graph.hasKey(good_node); // now has_key is true
Definition at line 374 of file graph.cpp.
NodeFromID()
Node HF::SpatialStructures::Graph::NodeFromID (int id) const
Retrieve the node that corresponds to id.
Parameters
id The ID of the node to get.
Returns
The node corresponding to id, by value.
Exceptions
std::out_of_range id didn't belong to any node in the graph.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Let's retrieve node_1.
int desired_node_id = 2;
HF::SpatialStructures::Node node_from_id = graph.NodeFromID(desired_node_id);
// Note that NodeFromID ceases to work if the id argument provided does not
// exist as an ID among the nodes within graph
Definition at line 53 of file graph.cpp.
Nodes()
std::vector< Node > HF::SpatialStructures::Graph::Nodes () const
Get a list of nodes from the graph sorted by ID.
Returns
A sorted vector of nodes.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Nodes() returns a copy of the ordered_nodes field
std::vector<HF::SpatialStructures::Node> nodes_from_graph = graph.Nodes();
Definition at line 55 of file graph.cpp.
Referenced by HF::Pathfinding::BoostGraph::BoostGraph(), GenerateGraph(), and GetAllNodesFromGraph().
NodesAsFloat3()
std::vector< std::array< float, 3 > > HF::SpatialStructures::Graph::NodesAsFloat3 () const
Get a list of nodes as float arrays.
Returns
An array of float arrays containing the position of every node in the graph in order.
Remarks
May be useful for to functions that take arrays instead of nodes.
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// A container of std::array<float, 3> is constructed and populated within
// NodesAsFloat3, and returned. Each array of 3 floats represents a Node's
// position within the Cartesian coordinate system. { x, y, z }
std::vector<std::array<float, 3>> nodes_as_floats = graph.NodesAsFloat3();
// The two loops below will yield the same output
for (auto n : graph.Nodes()) {
    std::cout << "(" << n.x << "," << n.y << "," << n.z << ")" << std::endl;
}
for (auto a : nodes_as_floats) {
    std::cout << a << std::endl;
}
Definition at line 376 of file graph.cpp.
operator[]()
const std::vector< Edge > HF::SpatialStructures::Graph::operator[] (const Node & n) const
Get a list of all edges from Node n.
Parameters
n Parent of all edges to retrieve.
Returns
An array of edges from node n.
Exceptions
std::outofrange n does not exist in the graph.
Todo
Todo Should this just return an empty list instead of throwing?
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Retrieve the nodes from the graph, or use the original instance of
// std::vector<Node> passed to Graph upon instantiation
std::vector<HF::SpatialStructures::Node> get_nodes = graph.Nodes();
// nodes[index] yields an instance of Node that we can pass to
// GetUndirectedEdges. Any node that exists with graph can be passed to this
// member function to retrieve a vector of edges.
int index = 2;
HF::SpatialStructures::Node node = get_nodes[index];
// Note that if node does not exist within graph, that an exception will be thrown.
std::vector<HF::SpatialStructures::Edge> undirected_edges = graph[node];
// See a (node)->(child_node_0, child_node_1, ... child_node_n)
std::cout << node.getArray() << "->";
for (auto e : undirected_edges) {
    std::cout << e.child.getArray() << ", ";
}
std::cout << std::endl;
Definition at line 207 of file graph.cpp.
size()
int HF::SpatialStructures::Graph::size () const
Determine how many nodes are in the graph.
Returns
The number of nodes in the graph.
Size is directly returned from id_to_nodes.size().
// be sure to #include "graph.h"
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f, 4);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f, 6);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
// Note: graph is compressed upon instantiation
HF::SpatialStructures::Graph graph(edges, distances, nodes);
int id_count = graph.size(); // We retrieve the size of the node id count within graph (3)
Definition at line 22 of file graph.cpp.
Referenced by HF::Pathfinding::BoostGraph::BoostGraph().
UpdateIDs()
void HF::SpatialStructures::Graph::UpdateIDs (int new_id) [private]
Add an empty node for this new id
Deprecated
Deprecated Never Implemented.
Member Data Documentation
edge_matrix
Eigen::SparseMatrix<float, 1> HF::SpatialStructures::Graph::edge_matrix [private]
The underlying CSR containing edge nformation.
Definition at line 101 of file graph.h.
id_to_nodes
std::vector<int> HF::SpatialStructures::Graph::id_to_nodes [private]
Maps ids to indexes in ordered_nodes.
Definition at line 99 of file graph.h.
idmap
robin_hood::unordered_map<Node, int> HF::SpatialStructures::Graph::idmap [private]
Maps a list of X,Y,Z positions to ids.
Definition at line 100 of file graph.h.
needs_compression
bool HF::SpatialStructures::Graph::needs_compression = true [private]
If true, the CSR is inaccurate and requires compression.
Definition at line 104 of file graph.h.
next_id
int HF::SpatialStructures::Graph::next_id = 0 [private]
The id for the next unique node.
Definition at line 102 of file graph.h.
ordered_nodes
std::vector<Node> HF::SpatialStructures::Graph::ordered_nodes [private]
A list of nodes contained by the graph.
Definition at line 98 of file graph.h.
triplets
std::vector<Eigen::Triplet<float> > HF::SpatialStructures::Graph::triplets [private]
Edges to be converted to a CSR when Graph::Compress() is called.
Definition at line 103 of file graph.h.
The documentation for this class was generated from the following files:
Cpp/spatialstructures/src/graph.h
Cpp/spatialstructures/src/graph.cpp