HF::SpatialStructures::Path Struct Reference
A point in space with an ID
#include <path.h>
Public Member Functions
Path::Path ()
Default constructor, empty block
Path::Path (const std::vector< PathMember > pm)
Construct a path from an ordered list of path members
void AddNode (int node, float cost)
Constructs a PathMember and appends it to the underlying members vector
bool empty () const
Determines if the underlying members vector is empty, or not
int size () const
Retrieves the length of the underlying members vector (PathMember count)
void Reverse ()
Invokes std::reverse to reverse the contents of the underlying members vector, using iterators
bool operator== (const Path &p2) const
Determines if all PathMember in p1 and p2's underlying PathMember vector are equivalent, or not, see operator== for PathMember
PathMember operator[] (int i) const
Retrieve a PathMember from the underlying PathMember vector, by value
PathMember * GetPMPointer ()
Return the pointer to the underlying path member vector
Public Attributes
std::vector< PathMember > members
The underlying vector of PathMember.
Detailed Description
A point in space with an ID
Definition at line 82 of file path.h.
Member Function Documentation
AddNode()
void HF::SpatialStructures::Path::AddNode (int node, float cost)
Constructs a PathMember and appends it to the underlying members vector
Parameters
node The identifier for the PathMember
cost The cost (weight) for the PathMember
// be sure to #include "path.h"
// Create the PathMembers
HF::SpatialStructures::PathMember p0 = { 3.14f, 3 };
HF::SpatialStructures::PathMember p1 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p2 = { 1.64f, 1 };
HF::SpatialStructures::PathMember p3 = { 9.35, 7 };
// Create the container of PathMembers
std::vector<HF::SpatialStructures::PathMember> members{ p0, p1, p2, p3 };
// Create the path, using the container of PathMembers
HF::SpatialStructures::Path path(members);
int node_id = 278;
float cost = 8.92f;
path.AddNode(node_id, cost); // A PathMember is constructed within AddNode from node_id and cost
                                // and is then appended to the underlying members vector (via push_back)
Definition at line 12 of file path.cpp.
References members.
Referenced by ConstructShortestPathFromPred().
empty()
bool HF::SpatialStructures::Path::empty () const
Determines if the underlying members vector is empty, or not
Returns
True if the underyling members vector is empty, false otherwise
// be sure to #include "path.h"
HF::SpatialStructures::Path path;
// There are no PathMembers in path's members container.
// if empty() returns true, that means the underlying members vector is of size 0 (no members)
// otherwise, empty returns false. In this case, path.empty() returns true.
std::string result = path.empty() ? "is empty" : "has at least one member";
std::cout << "The Path object " << result << std::endl;
Definition at line 16 of file path.cpp.
References members.
Referenced by CreatePath().
GetPMPointer()
PathMember * HF::SpatialStructures::Path::GetPMPointer ()
Return the pointer to the underlying path member vector
// be sure to #include "path.h"
// Create the PathMembers
HF::SpatialStructures::PathMember p0 = { 3.14f, 3 };
HF::SpatialStructures::PathMember p1 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p2 = { 1.64f, 1 };
HF::SpatialStructures::PathMember p3 = { 9.35f, 7 };
// Create the container of PathMembers
std::vector<HF::SpatialStructures::PathMember> members{p0, p1, p2, p3};
HF::SpatialStructures::Path path(members); // Create the Path object, path
HF::SpatialStructures::PathMember *ptr = path.GetPMPointer();
// You now have a pointer to the underlying buffer of the members vector with in a PathMember.
HF::SpatialStructures::PathMember *curr = ptr;
HF::SpatialStructures::PathMember *finish = ptr + path.size();
while (curr != finish) {
    std::cout << "Cost: " << curr->cost << " "
              << "Node: " << curr->node << std::endl;
    ++curr;
}
Definition at line 49 of file path.cpp.
References members.
Referenced by CreatePath(), GetPathInfo(), and HF::Pathfinding::InsertPathsIntoArray().
operator==()
bool HF::SpatialStructures::Path::operator== (const Path & p2) const
Determines if all PathMember in p1 and p2's underlying PathMember vector are equivalent, or not, see operator== for PathMember
Parameters
p2 The Path to compare against p1 (or rather, the elements of their PathMember vectors)
Returns
True, if all PathMember elements in p2 are equal to all PathMember elements in p1, false otherwise
// be sure to #include "path.h"
HF::SpatialStructures::PathMember p0 = { 3.14f, 3 }; // Create all the PathMember objects
HF::SpatialStructures::PathMember p1 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p2 = { 3.14f, 3 };
HF::SpatialStructures::PathMember p3 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p4 = { 1.1f, 9 };
HF::SpatialStructures::PathMember p5 = { 123.0f, 10 };
std::vector<HF::SpatialStructures::PathMember> members_0{p0, p1}; // Create the HF::SpatialStructures::PathMember vectors
std::vector<HF::SpatialStructures::PathMember> members_1{p2, p3};
std::vector<HF::SpatialStructures::PathMember> members_2{p4, p5};
std::vector<HF::SpatialStructures::PathMember> members_3{p1, p0};
HF::SpatialStructures::Path path_0(members_0); // Create the Path objects
HF::SpatialStructures::Path path_1(members_1);
HF::SpatialStructures::Path path_2(members_2);
HF::SpatialStructures::Path path_3(members_3);
bool same_values_same_order = path_0 == path_1;
bool totally_different = path_0 == path_2;
bool same_values_different_order = path_0 == path_3;
// path_0 and path_1 share the same PathMember values, with an identical permutation,
// so they are equivalent.
// path_0 and path_2 are not equivalent, because they have completely different PathMember
// values.
// path_0 and path_3 are not equivalent, because although they have PathMember objects of
// the same values, the order in which path_0 and path_3 have their member vectors arranged
// are different.
Definition at line 28 of file path.cpp.
References size().
operator[]()
PathMember HF::SpatialStructures::Path::operator[] (int i) const
Retrieve a PathMember from the underlying PathMember vector, by value
Parameters
i The index for the desired PathMember element within members
Returns
A PathMember within the members vector, at index i, by value
// be sure to #include "path.h"
// Create the PathMembers
HF::SpatialStructures::PathMember p0 = { 3.14f, 3 };
HF::SpatialStructures::PathMember p1 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p2 = { 1.64f, 1 };
HF::SpatialStructures::PathMember p3 = { 9.35f, 7 };
// Create the container of PathMembers
std::vector<HF::SpatialStructures::PathMember> members{p0, p1, p2, p3};
HF::SpatialStructures::Path path(members); // Create the Path object, path
const int desired_index = 2;
HF::SpatialStructures::PathMember result = path[desired_index]; // a copy of the element at desired_index
                                                                // within the internal members vector
                                                                // is assigned to result
Definition at line 41 of file path.cpp.
References members.
Path::Path() [1/2]
HF::SpatialStructures::Path::Path::Path () [inline]
Default constructor, empty block
// be sure to #include "path.h"
HF::SpatialStructures::Path path;
Definition at line 97 of file path.h.
References Path::Path().
Referenced by Path::Path().
Path::Path() [2/2]
HF::SpatialStructures::Path::Path::Path (const std::vector< PathMember > pm)
Construct a path from an ordered list of path members
// be sure to #include "path.h"
// Create the PathMembers
HF::SpatialStructures::PathMember p0 = { 3.14f, 3 };
HF::SpatialStructures::PathMember p1 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p2 = { 1.64f, 1 };
HF::SpatialStructures::PathMember p3 = { 9.35, 7 };
// Create the container of PathMembers
std::vector<HF::SpatialStructures::PathMember> members{p0, p1, p2, p3};
// Create the path, using the container of PathMembers
HF::SpatialStructures::Path path(members);
References Path::Path().
Reverse()
void HF::SpatialStructures::Path::Reverse ()
Invokes std::reverse to reverse the contents of the underlying members vector, using iterators
// be sure to #include "path.h"
// Create the PathMembers
HF::SpatialStructures::PathMember p0 = { 3.14f, 3 };
HF::SpatialStructures::PathMember p1 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p2 = { 1.64f, 1 };
HF::SpatialStructures::PathMember p3 = { 9.35f, 7 };
// Create the container of PathMembers
std::vector<HF::SpatialStructures::PathMember> members{p0, p1, p2, p3};
HF::SpatialStructures::Path path(members); // Create the Path object, path
path.AddNode(278, 3.14f); // Append one more PathMember to path
path.Reverse(); // The order of the PathMembers within members is now that of
                            // p3, p2, p1, p0
Definition at line 24 of file path.cpp.
References members.
Referenced by ConstructShortestPathFromPred().
size()
int HF::SpatialStructures::Path::size () const
Retrieves the length of the underlying members vector (PathMember count)
Returns
The value returned by members.size() - the current PathMember count
// be sure to #include "path.h"
// Create the PathMembers
HF::SpatialStructures::PathMember p0 = { 3.14f, 3 };
HF::SpatialStructures::PathMember p1 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p2 = { 1.64f, 1 };
HF::SpatialStructures::PathMember p3 = { 9.35f, 7 };
// Create the container of PathMembers
std::vector<HF::SpatialStructures::PathMember> members{p0, p1, p2, p3};
HF::SpatialStructures::Path path(members); // Create the Path object, path
path.AddNode(278, 3.14f); // Add one more PathMember to path
std::string result = path.size() >= 5 ? "at least 5 members" : "under 5 members";
std::cout << "The Path object has " << result << std::endl;
Definition at line 20 of file path.cpp.
References members.
Referenced by ConstructShortestPathFromPred(), CreatePath(), GetPathInfo(), HF::Pathfinding::InsertPathsIntoArray(), std::operator<<(), and operator==().
Member Data Documentation
members
std::vector<PathMember> HF::SpatialStructures::Path::members
The underlying vector of PathMember.
Definition at line 84 of file path.h.
Referenced by AddNode(), empty(), GetPMPointer(), operator[](), Reverse(), and size().
The documentation for this struct was generated from the following files:
Cpp/spatialstructures/src/path.h
Cpp/spatialstructures/src/path.cpp