HF::Pathfinding::BoostGraph Class Reference
A graph usable with the BoostGraphLibrary.
#include <boost_graph.h>
Public Member Functions
BoostGraph (const HF::SpatialStructures::Graph &graph)
Create a boost graph from a HF::SpatialStructures::Graph.
~BoostGraph ()
Explicit Destructor required for BoostGraphDeleter to work in path_finder.h.
Public Attributes
graph_t g
The underlying graph in boost.
std::vector< vertex_descriptor > p
Vertex array preallocated to the number of nodes in the graph.
std::vector< double > d
Distance array preallocated to the number of nodes in the graph.
Detailed Description
A graph usable with the BoostGraphLibrary.
Contains a CSR in boost created from a graph in HumanFactors. This is necessary for using any of the BoostGraphLibrary functions.
Remarks
None of the memebers of this class should need to be modified after the class is created. This is intended to be a pseudo-wrapper to make the HF::SpatialStructures::Graph usable with boost. You can read more about the boost graph libary in the official boost documentation: https://www.boost.org/doc/libs/1_73_0/libs/graph/doc/quick_tour.html
Boost's graphs can be difficult to use due to the extensive use of templates. This limits their usage outside of the HF::Pathfinder, so there aren't any functions to interact with the boost graph after creation.
See also
HF::SpatialStructures::Graph for a graph that's better supported in HumanFactors.
graph_t for info about the graph in boost this class holds.
Definition at line 165 of file boost_graph.h.
Constructor & Destructor Documentation
BoostGraph()
HF::Pathfinding::BoostGraph::BoostGraph (const HF::SpatialStructures::Graph & graph)
Create a boost graph from a HF::SpatialStructures::Graph.
Parameters
graph Graph to create a graph in boost from.
Every edge and node in the graph is used to create a graph in Boost. This will also allocate space equal to the number of nodes in g for this class's p and d arrays for use in FindPath as an optimization.
Invariant
This class will always carry a valid boost graph.
// be sure to #include "boost_graph.h", #include "node.h", #include "graph.h",
// and #include <vector>
// In order to create a BoostGraph, we must first create a Graph instance first.
// We must prepare the nodes, their edges, and the weights (distances) of each edge.
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Passing Graph graph to BoostGraph bg, by reference
HF::Pathfinding::BoostGraph bg(graph);
Definition at line 20 of file boost_graph.cpp.
References d, g, HF::SpatialStructures::Graph::GetEdges(), HF::SpatialStructures::Graph::Nodes(), p, HF::SpatialStructures::Graph::size(), and HF::Pathfinding::Edge_Cost::weight.
 BoostGraph()
HF::Pathfinding::BoostGraph::~BoostGraph () [default]
Explicit Destructor required for BoostGraphDeleter to work in path_finder.h.
Calls the default destruction behavior.
Warning
Do not modify this function! This class is still using the default destructor, but unique pointer requires the destructor to be declared.
// be sure to #include "boost_graph.h", #include "node.h", #include "graph.h",
// and #include <vector>
// In order to create a BoostGraph, we must first create a Graph instance first.
// We must prepare the nodes, their edges, and the weights (distances) of each edge.
// Create the nodes
HF::SpatialStructures::Node node_0(1.0f, 1.0f, 2.0f);
HF::SpatialStructures::Node node_1(2.0f, 3.0f, 4.0f, 5);
HF::SpatialStructures::Node node_2(11.0f, 22.0f, 140.0f);
// Create a container (vector) of nodes
std::vector<HF::SpatialStructures::Node> nodes = { node_0, node_1, node_2 };
// Create matrices for edges and distances, edges.size() == distances().size()
std::vector<std::vector<int>> edges = { { 1, 2 }, { 2 }, { 1 } };
std::vector<std::vector<float>> distances = { { 1.0f, 2.5f }, { 54.0f }, { 39.0f } };
// Now you can create a Graph - note that nodes, edges, and distances are passed
// by reference
HF::SpatialStructures::Graph graph(edges, distances, nodes);
// Begin scope
{
    // Create a BoostGraph bg, from a Graph graph (passing g by reference)
    HF::Pathfinding::BoostGraph bg(graph);
}
// End scope
// When bg goes out of scope, BoostGraph::~BoostGraph is called An explicit call
// to BoostGraph::~BoostGraph is also made when invoking operator delete on a
// (BoostGraph *)
Member Data Documentation
d
std::vector<double> HF::Pathfinding::BoostGraph::d
Distance array preallocated to the number of nodes in the graph.
Definition at line 169 of file boost_graph.h.
Referenced by BoostGraph().
g
graph_t HF::Pathfinding::BoostGraph::g
The underlying graph in boost.
Definition at line 167 of file boost_graph.h.
Referenced by BoostGraph(), HF::Pathfinding::FindPath(), HF::Pathfinding::FindPaths(), and HF::Pathfinding::InsertPathsIntoArray().
p
std::vector<vertex_descriptor> HF::Pathfinding::BoostGraph::p
Vertex array preallocated to the number of nodes in the graph.
Definition at line 168 of file boost_graph.h.
Referenced by BoostGraph().
The documentation for this class was generated from the following files:
Cpp/pathfinding/src/boost_graph.h
Cpp/pathfinding/src/boost_graph.cpp