HF::RayTracer::EmbreeRayTracer Class Reference
A wrapper for Intel's Embree Library.
#include <embree_raytracer.h>
Public Member Functions
EmbreeRayTracer ()
Create an EmbreeRayTracer with no arguments
EmbreeRayTracer (std::vector< HF::Geometry::MeshInfo > &MI)
Create a new EmbreeRayTracer and add a single mesh to the scene.
EmbreeRayTracer (const std::vector< std::array< float, 3 >> &geometry)
Create a new Raytracer and generate its BVH from a flat array of vertices.
bool FireRay (std::array< float, 3 > &origin, const std::array< float, 3 > &dir, float distance=-1, int mesh_id=-1)
Cast a ray and overwrite the origin with the hitpoint if it intersects any geometry.
bool FireRay (float &x, float &y, float &z, float dx, float dy, float dz, float distance=-1, int mesh_id=-1)
Cast a single ray and get the hitpoint. x , y ,and z are overridden with the hitpoint on a successful hit.
std::vector< bool > FireRays (std::vector< std::array< float, 3 >> &origins, std::vector< std::array< float, 3 >> &directions, bool use_parallel=true, float max_distance=-1, int mesh_id=-1)
Fire multiple rays and recieve hitpoints in return.
HitStruct Intersect (float x, float y, float z, float dx, float dy, float dz, float max_distance=-1, int mesh_id=-1)
Cast a ray and store all relevant information in a HitStruct.
bool FireOcclusionRay (const std::array< float, 3 > &origin, const std::array< float, 3 > &direction, float max_dist=-1)
Cast an occlusion ray using arrays as input.
std::vector< bool > FireOcclusionRays (const std::vector< std::array< float, 3 >> &origins, const std::vector< std::array< float, 3 >> &directions, float max_distance=-1, bool use_parallel=true)
Cast multiple occlusion rays in parallel.
bool FireOcclusionRay (float x, float y, float z, float dx, float dy, float dz, float distance=-1, int mesh_id=-1)
Cast a single occlusion ray.
void FireRequests (std::vector< FullRayRequest > &requests, bool parallel=true)
Fire a vector of ray requests.
void FireOcclusionRequests (std::vector< FullRayRequest > &requests, bool parallel=true)
Fire a vector of occlusion ray requests.
bool InsertNewMesh (std::vector< std::array< float, 3 >> &Mesh, int ID, bool Commit=false)
Add a new mesh to this raytracer's BVH with the specified ID.
bool EmbreeRayTracer::InsertNewMesh (HF::Geometry::MeshInfo &Mesh, bool Commit)
Add a new mesh to the BVH with the specified ID. If False, then the addition failed, or the ID was already taken.
bool InsertNewMesh (std::vector< HF::Geometry::MeshInfo > &Meshes, bool Commit=true)
Add several new meshes to the BVH.
template<typename N , typename V >
bool FireAnyRay (const N &node, const V &direction, float &out_distance, int &out_meshid, float max_distance=-1.0f)
Template for firing rays using array-like containers for the direction and origin.
template<typename N , typename V >
bool FireAnyOcclusionRay (const N &origin, const V &direction, float max_distance=-1.0f, int mesh_id=-1)
Template for firing rays using array-like containers for the direction and origin. Similar to FireAnyRay.
void operator= (const EmbreeRayTracer &ERT2)
Increment reference counters to prevent destruction when a copy is made.
~EmbreeRayTracer ()
Custom destructor to ensure cleanup of embree resources.
Private Attributes
RTCDevice device
All objects in Embree are created from this. https://www.embree.org/api.html#device-object.
RTCScene scene
Container for a set of geometries, and the BVH. https://www.embree.org/api.html#scene-object.
RTCIntersectContext context
Context to fire rays within.
Triangle * triangles
Triangle buffer. Is used in multiple places, but contents are dumped.
Vertex * Vertices
Vertex buffer. Is used in multiple places but contents are dumped.
std::vector< RTCGeometry > geometry
Detailed Description
A wrapper for Intel's Embree Library.
Provides several functions to quickly and simply perform ray intersections using Embree. This class will automatically dispose of Embree buffers when destroyed, incrementing Embree's reference counters on copy, and decrementing them on deletion. This class also provides methods for adding geometry to Embree's geometry buffers.
Todo
Todo Could use a constructor overload for a single instance of meshinfo for conveience.
Many functions support MeshID but don't actually check for it.
Definition at line 73 of file embree_raytracer.h.
Constructor & Destructor Documentation
EmbreeRayTracer() [1/3]
HF::RayTracer::EmbreeRayTracer::EmbreeRayTracer () [inline]
Create an EmbreeRayTracer with no arguments
// Requires #include "embree_raytracer.h", #include "objloader.h"
// For brevity
using HF::RayTracer::EmbreeRayTracer;
// Create the EmbreeRayTracer, no arguments
EmbreeRayTracer ert;
Definition at line 101 of file embree_raytracer.h.
EmbreeRayTracer() [2/3]
HF::RayTracer::EmbreeRayTracer::EmbreeRayTracer (std::vector< HF::Geometry::MeshInfo > & MI)
Create a new EmbreeRayTracer and add a single mesh to the scene.
Parameters
MI The mesh to use for scene construction.
Exceptions
Exception Thrown if MI contains no vertices.
Todo
Todo This function calls throw; which is meant to only be used to rethrow previously thrown exceptions. This should be throwing HF::Exceptions::InvalidOBJ
// Requires #include "embree_raytracer.h", #include "objloader.h"
// For brevity
using HF::Geometry::MeshInfo;
using HF::RayTracer::EmbreeRayTracer;
// Prepare the obj file path
std::string teapot_path = "teapot.obj";
std::vector<MeshInfo> geom = HF::Geometry::LoadMeshObjects(teapot_path, HF::Geometry::ONLY_FILE);
// Create the EmbreeRayTracer
auto ert = EmbreeRayTracer(geom);
Definition at line 458 of file embree_raytracer.cpp.
References context, device, InsertNewMesh(), and scene.
EmbreeRayTracer() [3/3]
HF::RayTracer::EmbreeRayTracer::EmbreeRayTracer (const std::vector< std::array< float, 3 >> & geometry)
Create a new Raytracer and generate its BVH from a flat array of vertices.
Parameters
geometry A vector of float arrays representing geometry. Every 3 arrays should form a single triangle of the mesh
Use of this function is discouraged since it is slower and less memory efficent than building from an array of triangle indices and an array of vertices. Internally a hashmap is used to assign an ID to every vertex in order to generate the index array.
Exceptions
std::exception Embree's geometry buffers could not be initialized.
// Requires #include "embree_raytracer.h", #include "objloader.h"
// Create a container of coordinates
std::vector<std::array<float, 3>> directions = {
    {0, 0, 1},
    {0, 1, 0},
    {1, 0, 0},
    {-1, 0, 0},
    {0, -1, 0},
    {0, 0, -1},
};
// Create the EmbreeRayTracer
auto ert = HF::RayTracer::EmbreeRayTracer(directions);
Definition at line 226 of file embree_raytracer.cpp.
References context, device, geometry, scene, triangles, HF::RayTracer::vectorsToBuffers(), and Vertices.
 EmbreeRayTracer()
HF::RayTracer::EmbreeRayTracer::~EmbreeRayTracer ()
Custom destructor to ensure cleanup of embree resources.
// Requires #include "embree_raytracer.h", #include "objloader.h"
// For brevity
using HF::Geometry::MeshInfo;
using HF::RayTracer::EmbreeRayTracer;
// Prepare the obj file path
std::string teapot_path = "teapot.obj";
std::vector<MeshInfo> geom = HF::Geometry::LoadMeshObjects(teapot_path, HF::Geometry::ONLY_FILE);
// Begin scope
{
    // Create the EmbreeRayTracer
    auto ert = EmbreeRayTracer(geom);
    // Use ert within this scope
}
// end scope - destructor called at end of scope
Definition at line 667 of file embree_raytracer.cpp.
References device, and scene.
Member Function Documentation
EmbreeRayTracer::InsertNewMesh()
bool HF::RayTracer::EmbreeRayTracer::EmbreeRayTracer::InsertNewMesh (HF::Geometry::MeshInfo & Mesh, bool Commit)
Add a new mesh to the BVH with the specified ID. If False, then the addition failed, or the ID was already taken.
Parameters
Mesh A vector of 3d points composing the mesh
ID the id of the mesh
Commit Whether or not to commit changes yet. This is slow, so only do this when you're done adding meshes.
Returns
True if successful
Exceptions
std::exception RTC failed to allocate vertex and or index buffers.
// Requires #include "embree_raytracer.h", #include "objloader.h"
// Create a container of coordinates
std::vector<std::array<float, 3>> directions = {
    {0, 0, 1},
    {0, 1, 0},
    {1, 0, 0}
};
// Create the EmbreeRayTracer
auto ert = HF::RayTracer::EmbreeRayTracer(directions);
// Prepare coordinates to create a mesh
std::vector<std::array<float, 3>> mesh_coords = {
    {-1, 0, 0},
    {0, -1, 0},
    {0, 0, -1}
};
// Create a mesh
const int id = 325;
const std::string mesh_name = "my mesh";
HF::Geometry::MeshInfo mesh(mesh_coords, id, mesh_name);
// Determine if mesh insertion successful
if (ert.InsertNewMesh(mesh, false)) {
    std::cout << "Mesh insertion okay" << std::endl;
}
else {
    std::cout << "Mesh insertion error" << std::endl;
}
>>>Mesh insertion okay
FireAnyOcclusionRay()
template<typename N , typename V >
bool HF::RayTracer::EmbreeRayTracer::FireAnyOcclusionRay (const N & origin, const V & direction, float max_distance = -1.0f, int mesh_id = -1) [inline]
Template for firing rays using array-like containers for the direction and origin. Similar to FireAnyRay.
Parameters
node A point in space. Must atleast have [0], [1], and [2] defined.
direction Direction to fire the ray in. Same constraints as node, but can be a different type.
max_distance Maximum distance the ray can travel.
Returns
true if the ray connected with anything, false otherwise.
Like the other occlusion functions, this is much faster than its counterparts at the cost of only being able to return true if the ray intersects any geometry, and false if it doesn't.
Note
C++ 2020's Concepts would be a good way to explain how to use this whenever they get implemented.
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
// Fire a ray straight down
bool res = ert.FireAnyOcclusionRay(
    std::array<float, 3>{0, 0, 1},
    std::array<float, 3>{0, 0, -1}
);
// Print Results
if (res) std::cerr << "True" << std::endl;
else std::cerr << "False" << std::endl;
// Fire a ray straight up
res = ert.FireAnyOcclusionRay(
    std::array<float, 3>{0, 0, 1},
    std::array<float, 3>{0, 0, 1}
);
// Print Results
if (res) std::cerr << "True" << std::endl;
else std::cerr << "False" << std::endl;
>>> True
>>> False
Definition at line 1030 of file embree_raytracer.h.
References FireOcclusionRay().
Referenced by HF::AnalysisMethods::VisibilityGraph::HeightCheck(), and HF::AnalysisMethods::VisibilityGraph::IsOcclusionBetween().
FireAnyRay()
template<typename N , typename V >
bool HF::RayTracer::EmbreeRayTracer::FireAnyRay (const N & node, const V & direction, float & out_distance, int & out_meshid, float max_distance = -1.0f) [inline]
Template for firing rays using array-like containers for the direction and origin.
Parameters
node A point in space. Must atleast have [0], [1], and [2] defined
direction Direction to fire the ray in. Same constraints as node, but can be a different type
out_distance distance from the ray to the hit (if any)
out_meshid ID of the mesh hit(if any)
max_distance Maximum distance the ray can travel. And intersections beyond this distance will be ignored. Will consider all intersections regardless of distance if set to -1.
Returns
True if the ray intersected any geometry, false otherwise.
This is preferrable to use over the other ray functions in many circumstances since the use of templates ensures no unnecessary conversions are performed.
Note
C++ 2020's Concepts would be a good way to explain how to use this whenever they get implemented.
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create a new raytracer from a basic 10x10 plane centered on the origin.
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
// Create origin/direction arrays
std::array<float, 3> origin{ 0, 0, 1 };
std::array<float, 3> direction{ 0, 0, -1 };
bool res = false; float out_dist = -1; int out_id = -1;
// Fire a ray straight down
res = ert.FireAnyRay(origin, direction, out_dist, out_id);
// Print its distance if it connected
if (res) std::cerr << out_dist << std::endl;
else std::cerr << "Miss" << std::endl;
// Fire a ray straight up
res = ert.FireAnyRay(origin, origin, out_dist, out_id);
// Print its distance if it connected
if (res) std::cerr << out_dist << std::endl;
else std::cerr << "Miss" << std::endl;
>>>(0, 0, 0)
>>>Miss
Definition at line 946 of file embree_raytracer.h.
References Intersect().
Referenced by FireRaysDistance(), and FireSingleRayDistance().
FireOcclusionRay() [1/2]
bool HF::RayTracer::EmbreeRayTracer::FireOcclusionRay (const std::array< float, 3 > & origin, const std::array< float, 3 > & direction, float max_dist = -1)
Cast an occlusion ray using arrays as input.
Parameters
origin Start point of the ray.
direction Direction of the ray.
max_dist Maximum distance of the ray. Any hits beyond this distance will not be counted. If negative, count all hits regardless of distance.
Returns
True if The ray intersected any geometry, False otherwise.
Occulsion rays are faster than the other ray functions, but can only tell if a ray intersected any geometry or it didn't. use the other functions for information such as distance, hitpoint, or meshid.
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
// Fire a ray straight down
bool res = ert.FireOcclusionRay(
    std::array<float, 3>{ 0, 0, 1 },
    std::array<float, 3>{ 0, 0, -1 }
);
// Print Result
if (res) std::cerr << "True" << std::endl;
else std::cerr << "False" << std::endl;
// Fire a ray straight up
res = ert.FireOcclusionRay(
    std::array<float, 3>{ 0, 0, 1 },
    std::array<float, 3>{ 0, 0, 1 }
);
// Print Result.
if (res) std::cerr << "True" << std::endl;
else std::cerr << "False" << std::endl;
>>> True
>>> False
Definition at line 389 of file embree_raytracer.cpp.
Referenced by FireAnyOcclusionRay(), FireOcclusionRays(), and HF::AnalysisMethods::GraphGeneratorPrivate::OcclusionCheck().
FireOcclusionRay() [2/2]
bool HF::RayTracer::EmbreeRayTracer::FireOcclusionRay (float x, float y, float z, float dx, float dy, float dz, float distance = -1, int mesh_id = -1)
Cast a single occlusion ray.
Parameters
x x component of the ray's origin.
y y component of the ray's origin.
z z component of the ray's origin.
dx x component of the ray's direction.
dy y component of the ray's direction.
dz z component of the ray's direction.
distance Maximum distance of the ray. Any hits beyond this distance will not be counted. If negative, count all hits regardless of distance.
mesh_id (NOT IMPLEMENTED) The id of the only mesh for this ray to collide with. -1 for all.
Returns
True if the ray intersected any geometry. False otherwise.
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
// Fire a ray straight down
bool res = ert.FireOcclusionRay(0, 0, 1, 0, 0, -1);
// Print Results
if (res) std::cerr << "True" << std::endl;
else std::cerr << "False" << std::endl;
// Fire a ray straight up
res = ert.FireOcclusionRay(0, 0, 1, 0, 0, 1);
// Print results
if (res) std::cerr << "True" << std::endl;
else std::cerr << "False" << std::endl;
>>> True
>>> False
Definition at line 518 of file embree_raytracer.cpp.
References context, and scene.
FireOcclusionRays()
std::vector< bool > HF::RayTracer::EmbreeRayTracer::FireOcclusionRays (const std::vector< std::array< float, 3 >> & origins, const std::vector< std::array< float, 3 >> & directions, float max_distance = -1, bool use_parallel = true)
Cast multiple occlusion rays in parallel.
Parameters
origins A list of origins. If only one is supplied then it will be fired for every direction in directions.
directions A list of directions. If only one is supplied then it will be fired for every origin in origins
max_distance Maximum distance the ray can travel
parallel Whether or not to fire the rays in parallel.
Returns
An ordered array of bools where every true indicates a hit and every false indicates a miss.
Can be fired in 3 configurations:
Equal amount of directions/origins: Fire a ray for every pair of origin/direction in order. i.e. (origin[0], direction[0]), (origin[1], direction[1])
One direction, multiple origins: Fire a ray in the given direction from each origin point in origins.
One origin, multiple directions: Fire a ray from the origin point in each direction in directions.
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
// Create an array of directions all containing {0,0,-1}
std::vector<std::array<float, 3>> directions(10, std::array<float, 3>{0, 0, -1});
// Create an array of origins with the first 5 values being above the plane and
// the last five values being under it.
std::vector<std::array<float, 3>> origins(10);
for (int i = 0; i < 5; i++) origins[i] = std::array<float, 3>{ 0.0f, 0.0f, 1.0f };
for (int i = 5; i < 10; i++) origins[i] = std::array<float, 3>{ 0.0f, 0.0f, -1.0f };
// Cast every occlusion ray
std::vector<bool> results = ert.FireOcclusionRays(origins, directions);
// Iterate through all results to print them
std::cout << "[";
for (int i = 0; i < 10; i++) {
    // Print true if the ray intersected, false otherwise
    if (results[i]) std::cout << "True";
    else std::cout << "False";
    // Add a comma if it's not the last member
    if (i != 9) std::cout << ", ";
}
std::cout << "]" << std::endl;
>>> [True, True, True, True, True, False, False, False, False, False]
Definition at line 397 of file embree_raytracer.cpp.
References FireOcclusionRay().
Referenced by FireOcclusionRays().
FireOcclusionRequests()
void HF::RayTracer::EmbreeRayTracer::FireOcclusionRequests (std::vector< FullRayRequest > & requests, bool parallel = true)
Fire a vector of occlusion ray requests.
Parameters
requests A list of requests to fire. Each request will be updated with hitpoints if successful.
parallel If true, fire rays in parallel
Deprecated
Deprecated Never used. Holdover from the previous codebase.
FireRay() [1/2]
bool HF::RayTracer::EmbreeRayTracer::FireRay (float & x, float & y, float & z, float dx, float dy, float dz, float distance = -1, int mesh_id = -1)
Cast a single ray and get the hitpoint. x , y ,and z are overridden with the hitpoint on a successful hit.
Parameters
x x component of the ray's origin.
y y component of the ray's origin.
z z component of the ray's origin.
dx x component of the ray's direction.
dy y component of the ray's direction.
dz z component of the ray's direction.
distance Any intersections beyond this distance are ignored. Set to -1 count any hit regardless of distance.
mesh_id (UNUSED) The id of the only mesh for this ray to collide with. Any geometry wihtout this ID is ignored
Returns
true if the ray hit, false otherwise
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
bool res;
// Fire a ray straight down directly at the plane
float x = 0; float y = 0; float z = 1;
res = ert.FireRay(x, y, z, 0, 0, -1);
// Print output
if (res) std::cerr << "(" << x << ", " << y << ", " << z << ")" << std::endl;
else std::cerr << "Miss" << std::endl;
// Fire a ray straight up
x = 0; y = 0; z = 1;
res = ert.FireRay(x, y, z, 0, 0, 1);
// Print output
if (res) std::cerr << "(" << x << ", " << y << ", " << z << ")" << std::endl;
else std::cerr << "Miss" << std::endl;
>>>(0, 0, 0)
>>>Miss
Definition at line 270 of file embree_raytracer.cpp.
References HF::RayTracer::CheckState(), context, device, and scene.
FireRay() [2/2]
bool HF::RayTracer::EmbreeRayTracer::FireRay (std::array< float, 3 > & origin, const std::array< float, 3 > & dir, float distance = -1, int mesh_id = -1)
Cast a ray and overwrite the origin with the hitpoint if it intersects any geometry.
Parameters
dir Direction to fire the ray in.
origin Start point of the ray. Updated to contain the hitpoint if successful.
distance Any hits beyond this distance are ignored. Set to -1 to count all intersections regardless of distance.
mesh_id (UNUSED) The id of the only mesh for this ray to collide with. -1 for all
Returns
True if the ray intersected some geometry and the origin is updated with the hit point. False otherwise.
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const std::vector<float> plane_vertices{
            -10.0f, 10.0f, 0.0f,
            -10.0f, -10.0f, 0.0f,
            10.0f, 10.0f, 0.0f,
            10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
// Fire a ray straight down
std::array<float, 3> origin{ 0,0,1 };
bool res = ert.FireRay(
    origin,
    std::array<float, 3>{0, 0, -1}
);
// Print Results
if (res) std::cerr << "(" << origin[0] << ", " << origin[1] << ", " << origin[2] << ")" << std::endl;
else std::cerr << "Miss" << std::endl;
// Fire a ray straight up
origin = std::array<float, 3>{ 0, 0, 1 };
res = ert.FireRay(
    origin,
    std::array<float, 3>{0, 0, 1}
);
// Print Results
if (res) std::cerr << "(" << origin[0] << ", " << origin[1] << ", " << origin[2] << ")" << std::endl;
else std::cerr << "Miss" << std::endl;
>>>(0,0,0)
>>>Miss
Definition at line 261 of file embree_raytracer.cpp.
Referenced by HF::AnalysisMethods::GraphGeneratorPrivate::CheckRay(), FireRay(), and FireRays().
FireRays()
std::vector< bool > HF::RayTracer::EmbreeRayTracer::FireRays (std::vector< std::array< float, 3 >> & origins, std::vector< std::array< float, 3 >> & directions, bool use_parallel = true, float max_distance = -1, int mesh_id = -1)
Fire multiple rays and recieve hitpoints in return.
Parameters
origins An array of x,y,z coordinates to fire rays from.
directions An array of x,y,z directions to fire in.
use_parallel Cast rays in parallel if true, if not fire in serial. All available cores will be used.
max_distance Maximum distance the ray can travel. Any intersections beyond this distance will be ignored. If set to 1, all intersections will be counted regardless of distance.
mesh_id (UNUSED) Only intersect with the mesh of this ID
Returns
A vector of Vector3D for the hitpoint of each ray fired. If a ray didn't hit, its point will be invalid, checkable using Vector3D.IsValid().
Can be fired in 3 configurations:
Equal amount of directions/origins: Fire a ray for every pair of origin/direction in order. i.e. (origin[0], direction[0]), (origin[1], direction[1])
One direction, multiple origins: Fire a ray in the given direction from each origin point in origins.
One origin, multiple directions: Fire a ray from the origin point in each direction in directions.
Exceptions
System.ArgumentException Length of directions and origins did not match any of the valid cases.
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create plane
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
// Create an array of directions all containing {0,0,-1}
std::vector<std::array<float, 3>> directions(10, std::array<float, 3>{ 0, 0, -1 });
// Create an array of origin points moving further to the left with each point
std::vector<std::array<float, 3>> origins(10);
for (int i = 0; i < 10; i++) origins[i] = std::array<float, 3>{static_cast<float>(2 * i), 0, 1};
// Fire every ray.
auto results = ert.FireRays(origins, directions);
// Print results
std::cout << "[";
for (int i = 0; i < 10; i++) {
    if (results[i])
        std::cout << "(" << origins[i][0] << ", " << origins[i][1] << ", " << origins[i][2] << ")";
    else
        std::cout << "Miss";
    if (i != 9) std::cout << ", ";
}
std::cout << "]" << std::endl;
>>> [(0, 0, 0), (1.99, 0, 0), (3.98, 0, 0), (5.97, 0, 0), (7.96, 0, 0), (9.95, 0, 0), Miss, Miss, Miss, Miss]
Definition at line 305 of file embree_raytracer.cpp.
References FireRay().
Referenced by FireMultipleDirectionsOneOrigin(), FireMultipleOriginsOneDirection(), and FireMultipleRays().
FireRequests()
void HF::RayTracer::EmbreeRayTracer::FireRequests (std::vector< FullRayRequest > & requests, bool parallel = true)
Fire a vector of ray requests.
Parameters
requests A list of requests to fire. These requests will be updated with the results of each shot.
parallel If true will fire rays in parallel.
Deprecated
Deprecated Never used. Holdover from the previous codebase.
Definition at line 534 of file embree_raytracer.cpp.
References context, HF::RayTracer::Fire8Rays(), and scene.
Referenced by HF::AnalysisMethods::ViewAnalysis::SphericalViewAnalysisFromRayRequests().
InsertNewMesh() [1/2]
bool HF::RayTracer::EmbreeRayTracer::InsertNewMesh (std::vector< HF::Geometry::MeshInfo > & Meshes, bool Commit = true)
Add several new meshes to the BVH.
Parameters
Meshes A vector of meshinfo to each be added as a seperate mesh.
Commit Whether or not to commit changes to the scene after all meshes in Meshes have been added.
Returns
True.
// Requires #include "embree_raytracer.h", #include "objloader.h"
// For brevity
using HF::Geometry::MeshInfo;
using HF::RayTracer::EmbreeRayTracer;
// Prepare the obj file path
std::string teapot_path = "teapot.obj";
std::vector<MeshInfo> geom = HF::Geometry::LoadMeshObjects(teapot_path, HF::Geometry::ONLY_FILE);
// Create the EmbreeRayTracer
auto ert = EmbreeRayTracer(geom);
// Prepare coordinates to create a mesh
std::vector<std::array<float, 3>> mesh_coords_0 = {
    {0, 0, 1},
    {0, 1, 0},
    {1, 0, 0}
};
std::vector<std::array<float, 3>> mesh_coords_1 = {
    {-1, 0, 0},
    {0, -1, 0},
    {0, 0, -1}
};
// Prepare mesh IDs and names
const int mesh_id_0 = 241;
const int mesh_id_1 = 363;
const std::string mesh_name_0 = "this mesh";
const std::string mesh_name_1 = "that mesh";
// Create each MeshInfo
MeshInfo mesh_0(mesh_coords_0, mesh_id_0, mesh_name_0);
MeshInfo mesh_1(mesh_coords_1, mesh_id_1, mesh_name_1);
// Create a container of MeshInfo
std::vector<MeshInfo> mesh_vec = { mesh_0, mesh_1 };
// Determine if mesh insertion successful
if (ert.InsertNewMesh(mesh_vec, false)) {
    std::cout << "Mesh insertion okay" << std::endl;
}
else {
    std::cout << "Mesh insertion error" << std::endl;
}
Definition at line 644 of file embree_raytracer.cpp.
References InsertNewMesh(), and scene.
InsertNewMesh() [2/2]
bool HF::RayTracer::EmbreeRayTracer::InsertNewMesh (std::vector< std::array< float, 3 >> & Mesh, int ID, bool Commit = false)
Add a new mesh to this raytracer's BVH with the specified ID.
Parameters
Mesh A vector of 3d points composing the mesh
ID the id of the mesh
Commit Whether or not to commit changes yet. This is slow, so only do this when you're done adding meshes.
Returns
True if the mesh was added successfully, false if the addition failed or the ID was already taken.
Exceptions
std::exception Embree failed to allocate vertex and or index buffers.
// Requires #include "embree_raytracer.h", #include "objloader.h"
// Create a container of coordinates
std::vector<std::array<float, 3>> directions = {
    {0, 0, 1},
    {0, 1, 0},
    {1, 0, 0},
    {-1, 0, 0},
    {0, -1, 0},
    {0, 0, -1},
};
// Create the EmbreeRayTracer
auto ert = HF::RayTracer::EmbreeRayTracer(directions);
// Prepare the mesh ID
const int id = 214;
// Insert the mesh, Commit parameter defaults to false
bool status = ert.InsertNewMesh(directions, id);
// Retrieve status
std::string result = status ? "status okay" : "status not okay";
std::cout << result << std::endl;
>>>status okay
Definition at line 548 of file embree_raytracer.cpp.
References device, geometry, scene, triangles, HF::RayTracer::vectorsToBuffers(), and Vertices.
Referenced by EmbreeRayTracer(), and InsertNewMesh().
Intersect()
HitStruct HF::RayTracer::EmbreeRayTracer::Intersect (float x, float y, float z, float dx, float dy, float dz, float max_distance = -1, int mesh_id = -1)
Cast a ray and store all relevant information in a HitStruct.
Parameters
x x component of the ray's origin.
y y component of the ray's origin.
z z component of the ray's origin.
dx x component of the ray's direction.
dy y component of the ray's direction.
dz z component of the ray's direction.
max_distance Maximum distance the ray can travel. Any intersections beyond this distance will be ignored. If set to -1, all intersections will be counted regardless of distance.
mesh_id (UNIMPLEMENTED) the id of the only mesh for this ray to collide with. Any geometry wihtout this ID is ignored.
Returns
A HitStruct containing information about the intersection if any occurred.
Example
// Requires #include "embree_raytracer.h", #include "meshinfo.h"
// for brevity
using HF::RayTracer::EmbreeRayTracer;
using HF::Geometry::MeshInfo;
// Create Plane
const std::vector<float> plane_vertices{
    -10.0f, 10.0f, 0.0f,
    -10.0f, -10.0f, 0.0f,
    10.0f, 10.0f, 0.0f,
    10.0f, -10.0f, 0.0f,
};
const std::vector<int> plane_indices{ 3, 1, 0, 2, 3, 0 };
// Create RayTracer
EmbreeRayTracer ert(std::vector<MeshInfo>{MeshInfo(plane_vertices, plane_indices, 0, " ")});
HitStruct res;
// Fire a ray straight down
res = ert.Intersect(0, 0, 1, 0, 0, -1);
// Print distance if it connected
if (res.DidHit()) std::cerr << res.distance << std::endl;
else std::cerr << "Miss" << std::endl;
// Fire a ray straight up
res = ert.Intersect(0, 0, 1, 0, 0, 1);
//Print distance if it connected
if (res.DidHit()) std::cerr << res.distance << std::endl;
else std::cerr << "Miss" << std::endl;
>>>1
>>>Miss
Definition at line 368 of file embree_raytracer.cpp.
References context, and scene.
Referenced by FireAnyRay().
operator=()
void HF::RayTracer::EmbreeRayTracer::operator= (const EmbreeRayTracer & ERT2)
Increment reference counters to prevent destruction when a copy is made.
Parameters
ERT2 Reference to EmbreeRayTracer, the right-hand side of the = statement
// Requires #include "embree_raytracer.h"
// Create a container of coordinates
std::vector<std::array<float, 3>> directions = {
    {0, 0, 1},
    {0, 1, 0},
    {1, 0, 0},
    {-1, 0, 0},
    {0, -1, 0},
    {0, 0, -1},
};
// Create the EmbreeRayTracer
HF::RayTracer::EmbreeRayTracer ert_0(directions);
// Create an EmbreeRayTracer, no arguments
HF::RayTracer::EmbreeRayTracer ert_1;
// If and when ert_0 goes out of scope,
// data within ert_0 will be retained inside of ert_1.
ert_1 = ert_0;
Definition at line 656 of file embree_raytracer.cpp.
References context, device, geometry, and scene.
Member Data Documentation
context
RTCIntersectContext HF::RayTracer::EmbreeRayTracer::context [private]
Context to fire rays within.
Definition at line 79 of file embree_raytracer.h.
Referenced by EmbreeRayTracer(), FireOcclusionRay(), FireRay(), FireRequests(), Intersect(), and operator=().
device
RTCDevice HF::RayTracer::EmbreeRayTracer::device [private]
All objects in Embree are created from this. https://www.embree.org/api.html#device-object.
Definition at line 75 of file embree_raytracer.h.
Referenced by EmbreeRayTracer(), FireRay(), InsertNewMesh(), operator=(), and ~EmbreeRayTracer().
geometry
std::vector<RTCGeometry> HF::RayTracer::EmbreeRayTracer::geometry [private]
Definition at line 85 of file embree_raytracer.h.
Referenced by EmbreeRayTracer(), InsertNewMesh(), and operator=().
scene
RTCScene HF::RayTracer::EmbreeRayTracer::scene [private]
Container for a set of geometries, and the BVH. https://www.embree.org/api.html#scene-object.
Definition at line 77 of file embree_raytracer.h.
Referenced by EmbreeRayTracer(), FireOcclusionRay(), FireRay(), FireRequests(), InsertNewMesh(), Intersect(), operator=(), and ~EmbreeRayTracer().
triangles
Triangle* HF::RayTracer::EmbreeRayTracer::triangles [private]
Triangle buffer. Is used in multiple places, but contents are dumped.
Definition at line 81 of file embree_raytracer.h.
Referenced by EmbreeRayTracer(), and InsertNewMesh().
Vertices
Vertex* HF::RayTracer::EmbreeRayTracer::Vertices [private]
Vertex buffer. Is used in multiple places but contents are dumped.
Definition at line 83 of file embree_raytracer.h.
Referenced by EmbreeRayTracer(), and InsertNewMesh().
The documentation for this class was generated from the following files:
Cpp/raytracer/src/embree_raytracer.h
Cpp/raytracer/src/embree_raytracer.cpp