Cpp/objloader/src/meshinfo.h File Reference
Contains definitions for the MeshInfo class.
#include <Dense>
#include <array>
Classes
struct HF::nanoGeom::Mesh
struct std::hash< std::array< T, 3 > >
Template specialization of std::hash for using std::array<numeric_type, 3>.
struct HF::Geometry::array_and_size< ptr_type >
A simple type to hold the size and data pointer of an array.
class HF::Geometry::MeshInfo< numeric_type >
A collection of vertices and indices representing geometry.
Namespaces
 HF
Perform human scale analysis on 3D environments.
 HF::nanoGeom
 HF::Geometry
Manipulate and load geometry from disk.
Macros
#define HF_MESHINFO
Functions
template<typename SizeT >
void std::array_hash_combine_impl (SizeT &seed, SizeT value)
Combine the hash of value into seed.
template<typename T >
HF::Geometry::MeshInfo () -> MeshInfo< float >
Detailed Description
Contains definitions for the MeshInfo class.
Author
TBA
Date
16 Jun 2020
Class Documentation
struct HF::nanoGeom::Mesh
Definition at line 19 of file meshinfo.h.
Class Members
unsigned int *
faces
[xyz] * 3(triangle) * num_faces
double *
facevarying_binormals
[xyz] * 3(triangle) * num_faces
double *
facevarying_normals
[xyz] * num_vertices
double *
facevarying_tangents
[xyz] * 3(triangle) * num_faces
double *
facevarying_uvs
[xyz] * 3(triangle) * num_faces
double *
facevarying_vertex_colors
[xyz] * 3(triangle) * num_faces
unsigned int *
material_ids
triangle x num_faces
size_t
num_faces
size_t
num_vertices
double *
vertices
Macro Definition Documentation
HF_MESHINFO
#define HF_MESHINFO
Definition at line 9 of file meshinfo.h.
Function Documentation
array_hash_combine_impl()
template<typename SizeT >
void std::array_hash_combine_impl (SizeT & seed, SizeT value) [inline]
Combine the hash of value into seed.
Combine hashes for multiple floats.
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
// be sure to #include "meshinfo.h"
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Definition at line 52 of file meshinfo.h.
References std::array_hash_combine_impl().
Referenced by std::array_hash_combine_impl(), std::hash< std::array< float, 3 > >::operator()(), and std::hash< std::array< T, 3 > >::operator()().