Cpp/pathfinding/src/path_finder.h File Reference
Contains definition for the BoostGraphDeleter structure.
#include <memory>
#include <vector>
#include <string>
#include <cassert>
#include <iostream>
Classes
struct HF::Pathfinding::BoostGraphDeleter
Deleter for the BoostGraph.
struct HF::Pathfinding::DistanceAndPredecessor
Holds and maintains a distance and predecessor matrix.
Namespaces
namespace HF
Perform human scale analysis on 3D environments.
namespace HF::SpatialStructures
Contains standard fundamental data structures for representing space used throughout HumanFactors.
namespace HF::Pathfinding
Algorithms to find the shortest path between nodes in a HF::SpatialStructures::Graph.
Functions
std::unique_ptr< BoostGraph, BoostGraphDeleter > HF::Pathfinding::CreateBoostGraph (const HF::SpatialStructures::Graph &g, const std::string &cost_type=``)
Create a new boost graph from a HF::SpatialStructures:Graph.
Path HF::Pathfinding::FindPath (BoostGraph *bg, int start_id, int end_id)
Find a path between points A and B using Dijkstra's Shortest Path algorithm.
vector< Path > HF::Pathfinding::FindPaths (BoostGraph *bg, const std::vector< int > &start_points, const std::vector< int > &end_points)
Find a path from every id in start_ids to the matching end node in end_ids.
std::vector< HF::SpatialStructures::Path > HF::Pathfinding::FindAllPaths (BoostGraph *bg)
Find a path from every node to every node (NOTE: Not implemented yet.)
void HF::Pathfinding::InsertPathsIntoArray (const BoostGraph *bg, const std::vector< int > &start_points, const std::vector< int > &end_points, HF::SpatialStructures::Path **out_paths, HF::SpatialStructures::PathMember **out_path_members, int *out_sizes)
A special version of FindPaths optimized for the C_Interface.
DistanceAndPredecessor HF::Pathfinding::GenerateDistanceAndPred (const BoostGraph &bg)
Generate the distance and predecessor matricies for a specific boost graph.
void HF::Pathfinding::InsertAllToAllPathsIntoArray (BoostGraph *bg, HF::SpatialStructures::Path **out_paths, HF::SpatialStructures::PathMember **out_path_members, int *out_sizes)
A special version of FindPaths optimized for the C_Interface, such that all paths possible from each node to every other node are generated.
std::ostream & operator<< (std::ostream &os, HF::Pathfinding::DistanceAndPredecessor &dist_pred)
An overload to print HF::Pathfinding::DistanceAndPredecessor when passed to cout .
Detailed Description
Contains definition for the BoostGraphDeleter structure.
Author
TBA
Date
17 Jun 2020
Definition in file path_finder.h.
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, HF::Pathfinding::DistanceAndPredecessor & dist_pred) [inline]
An overload to print HF::Pathfinding::DistanceAndPredecessor when passed to cout .
Definition at line 621 of file path_finder.h.
References HF::Pathfinding::DistanceAndPredecessor::GetRowOfDist(), HF::Pathfinding::DistanceAndPredecessor::GetRowOfPred(), HF::Pathfinding::DistanceAndPredecessor::size, and nlohmann::to_string().