Cpp/tests/src/AnalysisMethods.cpp File Reference
#include `gtest/gtest.h`
#include <array>
#include <graph_generator.h>
#include <unique_queue.h>
#include <embree_raytracer.h>
#include <objloader.h>
#include <meshinfo.h>
#include <graph.h>
#include <edge.h>
#include <node.h>
#include <Constants.h>
#include <analysis_C.h>
#include `performance_testing.h`
Namespaces
 HF
Perform human scale analysis on 3D environments.
 CInterfaceTests
Functions
EmbreeRayTracer CreateRTWithPlane ()
Create a new raytracer from a basic 10x10 plane centered on the origin.
void HF::CheckForDuplicates (const HF::SpatialStructures::Graph &g, float precision=0.0001f)
HF::TEST (_GraphGenerator, GraphGeneratorParallel)
HF::TEST (_GraphGenerator, DuplicateNodes2)
HF::TEST (_GraphGenerator, DuplicateNodes)
HF::TEST (_GraphGenerator, GraphGeneratorSingle)
HF::TEST (_GraphGenerator, DuplicateNodes_Weston)
HF::TEST (_GraphGenerator, DuplicateNodes_2B)
HF::TEST (_UniqueQueue, BlockRepeats)
HF::TEST (_UniqueQueue, Size)
HF::TEST (_UniqueQueue, Empty)
CInterfaceTests::TEST (_AnalysisCInterface, GenerateGraph)
TEST (Performance, GraphGenerator)
Evaluates how quickly the graph generator can create nodes on a flat plane.
TEST (Performance, attrs)
Function Documentation
CreateRTWithPlane()
EmbreeRayTracer CreateRTWithPlane () [inline]
Create a new raytracer from a basic 10x10 plane centered on the origin.
Definition at line 25 of file AnalysisMethods.cpp.
Referenced by TEST().
TEST() [1/2]
TEST (Performance , attrs)
Definition at line 478 of file AnalysisMethods.cpp.
References CreateRTWithPlane(), and nlohmann::to_string().
TEST() [2/2]
TEST (Performance , GraphGenerator)
Evaluates how quickly the graph generator can create nodes on a flat plane.
namespace CInterfaceTests { TEST(_CInterfaceUtils, ConvertRawFloatArrayToPoints) { Requires include `cinterface_utils.h`
    float raw_array[] = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 };
    const int size = 9;

    std::vector<std::array<float, 3>> points = ConvertRawFloatArrayToPoints(raw_array, size);
}

TEST(_CInterfaceUtils, ConvertRawIntArrayToPoints) {
 Requires include `cinterface_utils.h`
    int raw_array[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 };
    const int size = 9;

    std::vector<std::array<int, 3>> points = ConvertRawIntArrayToPoints(raw_array, size);
}

TEST(_CInterfaceUtils, DestroyFloatVector) {
 Requires include `cinterface_utils.h`
    std::vector<float>* vec = new std::vector<float>{ 3, 6, 9 };
operator delete called on vec within DestroyFloatVector if (DestroyFloatVector(vec)) { std::cout << `DestroyFloatVector was successful` << std::endl; vec = nullptr; } else { std::cout << `DestroyFloatVector unsuccessful` << std::endl; } }
TEST(_CInterfaceUtils, DeleteRawPtr) { Requires include `cinterface_utils.h`
    std::vector<int>* vec = new std::vector<int>{ 6, 3, 1, 0, 5, 0 };

    DeleteRawPtr<std::vector<int>>(vec);
At this point here, we assume DeleteRawPtr was successful. We set vec to nullptr to eliminate a dangling pointer. if (vec) { vec = nullptr; } }
}
/*!
Definition at line 422 of file AnalysisMethods.cpp.
References CreateRTWithPlane(), and PrintTrials().