Cpp/spatialstructures/src/node.h File Reference
Contains definitions for the Node structure.
#include <array>
#include <ostream>
Classes
struct HF::SpatialStructures::Node
A point in space with an ID.
struct std::hash< HF::SpatialStructures::Node >
Hash this node by combining the hashes of all of it's position elements.
Namespaces
 HF
Perform human scale analysis on 3D environments.
 HF::SpatialStructures
Contains standard fundamental data structures for representing space used throughout HumanFactors.
Macros
#define HF_NODE
Enumerations
enum HF::SpatialStructures::NODE_TYPE { HF::SpatialStructures::GRAPH = 0,
HF::SpatialStructures::POI = 1,
HF::SpatialStructures::OTHER = 2
 }
The type of node this is.
Functions
template<typename SizeT >
void std::hash_combine_impl (SizeT &seed, SizeT value) noexcept
combine value into the hash value of seed
ostream & std::operator<< (ostream &os, const HF::SpatialStructures::Node n)
Create a string containing the x,y,z position of this node.
ostream & std::operator<< (ostream &os, const std::array< float, 3 > n)
Create a string containing the x,y,z positions of this array.
Detailed Description
Contains definitions for the Node structure.
Author
TBA
Date
06 Jun 2020
Macro Definition Documentation
HF_NODE
#define HF_NODE
Definition at line 11 of file node.h.
Function Documentation
hash_combine_impl()
template<typename SizeT >
void std::hash_combine_impl (SizeT & seed, SizeT value) [inline], [noexcept]
combine value into the hash value of seed
Definition at line 414 of file node.h.
References std::hash_combine_impl().
Referenced by std::hash_combine_impl(), and std::hash< HF::SpatialStructures::Node >::operator()().
operator<<() [1/2]
ostream& std::operator<< (ostream & os, const HF::SpatialStructures::Node n) [inline]
Create a string containing the x,y,z position of this node.
Definition at line 433 of file node.h.
References HF::SpatialStructures::Node::x, HF::SpatialStructures::Node::y, and HF::SpatialStructures::Node::z.
operator<<() [2/2]
ostream& std::operator<< (ostream & os, const std::array< float, 3 > n) [inline]
Create a string containing the x,y,z positions of this array.
Definition at line 439 of file node.h.