Cpp/tests/src/VisibilityGraph.cpp File Reference
#include `gtest/gtest.h`
#include <array>
#include <embree_raytracer.h>
#include <objloader.h>
#include <meshinfo.h>
#include <graph.h>
#include <edge.h>
#include <node.h>
#include <visibility_graph.h>
#include <string>
#include <visibility_graph_C.h>
Typedefs
using MeshInfo = HF::Geometry::MeshInfo< float >
Functions
EmbreeRayTracer CreatePlaneTracer ()
TEST (_VisibilityGraph, NodesOnFlatPlaneAllConnect)
TEST (_VisibilityGraph, ParallelNodesOnFlatPlaneAllConnect)
TEST (_VisibilityGraph, NodesOnFlatPlaneWithWallDontConnect)
TEST (_VisibilityGraph, GroupConstructsValidGraph)
TEST (C_VisibilityGraph, GroupConstructsValidGraph)
TEST (_visibilityGraph, AllToAll)
The following are tests for the code samples for HF::VisibilityGraph.
TEST (_visibilityGraph, GroupToGroup)
TEST (_visibilityGraph, AllToAllUndirected)
Variables
const std::string plane_path = `plane.obj`
const std::string walled_plane_path = `plane_walled.obj`
Typedef Documentation
MeshInfo
using MeshInfo = HF::Geometry::MeshInfo<float>
Definition at line 19 of file VisibilityGraph.cpp.
Function Documentation
CreatePlaneTracer()
EmbreeRayTracer CreatePlaneTracer ()
Definition at line 27 of file VisibilityGraph.cpp.
References HF::Geometry::LoadMeshObjects(), HF::Geometry::ONLY_FILE, and plane_path.
Referenced by TEST().
TEST() [1/8]
TEST (_visibilityGraph , AllToAll)
The following are tests for the code samples for HF::VisibilityGraph.
Definition at line 182 of file VisibilityGraph.cpp.
References HF::VisibilityGraph::AllToAll(), HF::Geometry::LoadMeshObjects(), and plane_path.
TEST() [2/8]
TEST (_visibilityGraph , AllToAllUndirected)
Definition at line 260 of file VisibilityGraph.cpp.
References HF::VisibilityGraph::AllToAllUndirected(), HF::Geometry::LoadMeshObjects(), and plane_path.
TEST() [3/8]
TEST (_VisibilityGraph , GroupConstructsValidGraph)
Definition at line 85 of file VisibilityGraph.cpp.
References HF::SpatialStructures::COUNT, CreatePlaneTracer(), and HF::VisibilityGraph::GroupToGroup().
TEST() [4/8]
TEST (_visibilityGraph , GroupToGroup)
Definition at line 216 of file VisibilityGraph.cpp.
References HF::VisibilityGraph::GroupToGroup(), HF::Geometry::LoadMeshObjects(), and plane_path.
TEST() [5/8]
TEST (_VisibilityGraph , NodesOnFlatPlaneAllConnect)
Definition at line 31 of file VisibilityGraph.cpp.
References HF::VisibilityGraph::AllToAll(), HF::Geometry::LoadMeshObjects(), HF::Geometry::ONLY_FILE, and plane_path.
TEST() [6/8]
TEST (_VisibilityGraph , NodesOnFlatPlaneWithWallDontConnect)
Definition at line 65 of file VisibilityGraph.cpp.
References HF::VisibilityGraph::AllToAll(), HF::Geometry::LoadMeshObjects(), HF::Geometry::ONLY_FILE, and walled_plane_path.
TEST() [7/8]
TEST (_VisibilityGraph , ParallelNodesOnFlatPlaneAllConnect)
Definition at line 47 of file VisibilityGraph.cpp.
References HF::VisibilityGraph::AllToAllUndirected(), HF::Geometry::LoadMeshObjects(), HF::Geometry::ONLY_FILE, and plane_path.
TEST() [8/8]
TEST (C_VisibilityGraph , GroupConstructsValidGraph)
Definition at line 117 of file VisibilityGraph.cpp.
References CreatePlaneTracer(), CreateVisibilityGraphGroupToGroup(), and HF::SpatialStructures::SUM.
Variable Documentation
plane_path
const std::string plane_path = `plane.obj`
Definition at line 22 of file VisibilityGraph.cpp.
Referenced by CreatePlaneTracer(), and TEST().
walled_plane_path
const std::string walled_plane_path = `plane_walled.obj`
Definition at line 25 of file VisibilityGraph.cpp.
Referenced by TEST().