Cpp/tests/src/ViewAnalysis.cpp File Reference
#include `gtest/gtest.h`
#include <array>
#include <string>
#include <numeric>
#include <graph_generator.h>
#include <embree_raytracer.h>
#include <view_analysis.h>
#include <objloader.h>
#include <meshinfo.h>
#include <graph.h>
#include <edge.h>
#include <node.h>
#include <view_analysis_C.h>
#include <raytracer_C.h>
#include <objloader_C.h>
#include <HFExceptions.h>
#include <Constants.h>
Typedefs
using MeshInfo = HF::Geometry::MeshInfo< float >
Functions
TEST (_ViewAnalysis, SphericalViewAnalysis)
TEST (_ViewAnalysis, SphericalViewAnalysis_LoadedMesh)
TEST (_ViewAnalysis, AllRaysHit)
TEST (_ViewAnalysis, FibbonacciGeneratesRightAmtOfRays)
TEST (_ViewAnalysis, AggregateDoesntReturnInfinite)
TEST (_ViewAnalysis, FibbonacciDistributePoints)
TEST (_ViewAnalysis, AggregateAverage)
TEST (_ViewAnalysis, ViewAnalysisAggregate)
TEST (_ViewAnalysis, ViewAnalysisAggregate_MIN)
TEST (C_ViewAnalysisCInterface, SphericalViewAnalysisAggregate)
TEST (C_ViewAnalysisCInterface, SphericalViewAnalysisAggregateFlat)
TEST (C_ViewAnalysisCInterface, SphericalDistribute)
TEST (C_ViewAnalysisCInterface, SphericalViewAnalysisNoAggregateFlat)
TEST (C_ViewAnalysisCInterface, SphericalViewAnalysisNoAggregate)
Variables
std::string big_teapot_path = `big_teapot.obj`
Typedef Documentation
MeshInfo
using MeshInfo = HF::Geometry::MeshInfo<float>
Definition at line 27 of file ViewAnalysis.cpp.
Function Documentation
TEST() [1/14]
TEST (_ViewAnalysis , AggregateAverage)
Definition at line 308 of file ViewAnalysis.cpp.
References HF::ViewAnalysis::Aggregate(), AVERAGE, COUNT, MAX, MIN, and SUM.
TEST() [2/14]
TEST (_ViewAnalysis , AggregateDoesntReturnInfinite)
Definition at line 266 of file ViewAnalysis.cpp.
References HF::ViewAnalysis::AVERAGE, big_teapot_path, HF::Geometry::LoadMeshObjects(), and HF::ViewAnalysis::SphericalRayshootWithAnyRTForDistance().
TEST() [3/14]
TEST (_ViewAnalysis , AllRaysHit)
Todo
Todo fix this to actually test if all rays hit
Definition at line 244 of file ViewAnalysis.cpp.
References big_teapot_path, HF::Geometry::LoadMeshObjects(), HF::ViewAnalysis::SphericalRayshootWithAnyRTForDistance(), and HF::ViewAnalysis::SUM.
TEST() [4/14]
TEST (_ViewAnalysis , FibbonacciDistributePoints)
Definition at line 284 of file ViewAnalysis.cpp.
References HF::ViewAnalysis::FibbonacciDistributePoints().
TEST() [5/14]
TEST (_ViewAnalysis , FibbonacciGeneratesRightAmtOfRays)
Definition at line 262 of file ViewAnalysis.cpp.
References HF::ViewAnalysis::FibbonacciDistributePoints().
TEST() [6/14]
TEST (_ViewAnalysis , SphericalViewAnalysis)
Definition at line 35 of file ViewAnalysis.cpp.
References HF::ViewAnalysis::SphericalViewAnalysis().
TEST() [7/14]
TEST (_ViewAnalysis , SphericalViewAnalysis_LoadedMesh)
Definition at line 135 of file ViewAnalysis.cpp.
References CreateRaytracer(), DestroyRayTracer(), LoadOBJ(), HF::Geometry::ONLY_FILE, and HF::ViewAnalysis::SphericalViewAnalysis().
TEST() [8/14]
TEST (_ViewAnalysis , ViewAnalysisAggregate)
Definition at line 359 of file ViewAnalysis.cpp.
References HF::ViewAnalysis::SphericalRayshootWithAnyRTForDistance(), and SUM.
TEST() [9/14]
TEST (_ViewAnalysis , ViewAnalysisAggregate_MIN)
Definition at line 406 of file ViewAnalysis.cpp.
References HF::Geometry::LoadMeshObjects(), MIN, and HF::ViewAnalysis::SphericalRayshootWithAnyRTForDistance().
TEST() [10/14]
TEST (C_ViewAnalysisCInterface , SphericalDistribute)
Definition at line 585 of file ViewAnalysis.cpp.
References DestroyFloatVector(), HF::Exceptions::OK, and SphericalDistribute().
TEST() [11/14]
TEST (C_ViewAnalysisCInterface , SphericalViewAnalysisAggregate)
Definition at line 438 of file ViewAnalysis.cpp.
References AVERAGE, CreateRaytracer(), DestroyFloatVector(), DestroyMeshInfo(), DestroyRayTracer(), HF::Exceptions::OK, SphereicalViewAnalysisAggregate(), and StoreMesh().
TEST() [12/14]
TEST (C_ViewAnalysisCInterface , SphericalViewAnalysisAggregateFlat)
Definition at line 512 of file ViewAnalysis.cpp.
References AVERAGE, CreateRaytracer(), DestroyFloatVector(), DestroyMeshInfo(), DestroyRayTracer(), HF::Exceptions::OK, SphereicalViewAnalysisAggregateFlat(), and StoreMesh().
TEST() [13/14]
TEST (C_ViewAnalysisCInterface , SphericalViewAnalysisNoAggregate)
Definition at line 694 of file ViewAnalysis.cpp.
References AVERAGE, CreateRaytracer(), DestroyMeshInfo(), DestroyRayResultVector(), DestroyRayTracer(), RayResult::distance, RayResult::meshid, HF::Exceptions::OK, SphericalViewAnalysisNoAggregate(), and StoreMesh().
TEST() [14/14]
TEST (C_ViewAnalysisCInterface , SphericalViewAnalysisNoAggregateFlat)
Definition at line 616 of file ViewAnalysis.cpp.
References AVERAGE, CreateRaytracer(), DestroyMeshInfo(), DestroyRayResultVector(), DestroyRayTracer(), RayResult::distance, RayResult::meshid, HF::Exceptions::OK, SphericalViewAnalysisNoAggregateFlat(), and StoreMesh().
Variable Documentation
big_teapot_path
std::string big_teapot_path = `big_teapot.obj`
Definition at line 33 of file ViewAnalysis.cpp.
Referenced by TEST().