HF Namespace Reference
Perform human scale analysis on 3D environments.
Namespaces
 Exceptions
Custom exceptions and error codes used interally by HumanFactors.
 Geometry
Manipulate and load geometry from disk.
 GraphGenerator
Generate a graph of accessible space from a given start point.
 nanoGeom
 Pathfinding
Algorithms to find the shortest path between nodes in a HF::SpatialStructures::Graph.
 RayTracer
Cast rays to determine if and where they intersect geometry.
 SpatialStructures
Contains standard fundamental data structures for representing space used throughout HumanFactors.
 ViewAnalysis
Analyze space from the perspective of observers within a 3D environment.
 VisibilityGraph
Evaluate visibility between points in a set of locations.
Functions
void CheckForDuplicates (const HF::SpatialStructures::Graph &g, float precision=0.0001f)
TEST (_GraphGenerator, GraphGeneratorParallel)
TEST (_GraphGenerator, DuplicateNodes2)
TEST (_GraphGenerator, DuplicateNodes)
TEST (_GraphGenerator, GraphGeneratorSingle)
TEST (_GraphGenerator, DuplicateNodes_Weston)
TEST (_GraphGenerator, DuplicateNodes_2B)
TEST (_UniqueQueue, BlockRepeats)
TEST (_UniqueQueue, Size)
TEST (_UniqueQueue, Empty)
void CheckForDuplicatesNano (const HF::SpatialStructures::Graph &g, float precision=0.0001f, bool insta_fail=false)
TEST (_GraphAlgorithm, BasicGenerator)
TEST (_GraphAlgorithm, Energy_Blob)
TEST (_GraphAlgorithm, Energy_BlobNanoRT)
TEST (_GraphAlgorithm, NanoRTVisibilityGraphTC)
TEST (_GraphAlgorithm, VsEmbree_blob)
Detailed Description
Perform human scale analysis on 3D environments.
Remarks
This is the base namespace for the HumanFactors package. All future modules should remain in this namespace and this should act as a jump page for all major sections of documentation.
Function Documentation
CheckForDuplicates()
void HF::CheckForDuplicates (const HF::SpatialStructures::Graph & g, float precision = 0.0001f)
Definition at line 39 of file AnalysisMethods.cpp.
References HF::SpatialStructures::Graph::Nodes(), and HF::SpatialStructures::Graph::size().
Referenced by TEST().
CheckForDuplicatesNano()
void HF::CheckForDuplicatesNano (const HF::SpatialStructures::Graph & g, float precision = 0.0001f, bool insta_fail = false)
Definition at line 19 of file GraphAlgorithms.cpp.
References HF::SpatialStructures::Graph::Nodes(), and HF::SpatialStructures::Graph::size().
Referenced by TEST().
TEST() [1/14]
HF::TEST (_GraphAlgorithm , BasicGenerator)
Definition at line 71 of file GraphAlgorithms.cpp.
References HF::Geometry::LoadMeshObjects().
TEST() [2/14]
HF::TEST (_GraphAlgorithm , Energy_Blob)
Definition at line 119 of file GraphAlgorithms.cpp.
References HF::Geometry::LoadMeshObjects().
TEST() [3/14]
HF::TEST (_GraphAlgorithm , Energy_BlobNanoRT)
Definition at line 150 of file GraphAlgorithms.cpp.
References HF::Geometry::LoadMeshObjects().
TEST() [4/14]
HF::TEST (_GraphAlgorithm , NanoRTVisibilityGraphTC)
Definition at line 182 of file GraphAlgorithms.cpp.
References HF::GraphGenerator::GraphGenerator::BuildNetwork(), CheckForDuplicatesNano(), HF::SpatialStructures::Graph::Compress(), and HF::Geometry::LoadMeshObjects().
TEST() [5/14]
HF::TEST (_GraphAlgorithm , VsEmbree_blob)
Definition at line 228 of file GraphAlgorithms.cpp.
References HF::GraphGenerator::GraphGenerator::BuildNetwork(), CheckForDuplicatesNano(), HF::SpatialStructures::Graph::Compress(), and HF::Geometry::LoadMeshObjects().
TEST() [6/14]
HF::TEST (_GraphGenerator , DuplicateNodes)
Definition at line 150 of file AnalysisMethods.cpp.
References CheckForDuplicates(), and HF::Geometry::LoadMeshObjects().
TEST() [7/14]
HF::TEST (_GraphGenerator , DuplicateNodes2)
Definition at line 111 of file AnalysisMethods.cpp.
References HF::Geometry::LoadMeshObjects().
TEST() [8/14]
HF::TEST (_GraphGenerator , DuplicateNodes_2B)
Definition at line 270 of file AnalysisMethods.cpp.
References CheckForDuplicates(), HF::GraphGenerator::default_ground_offset, HF::GraphGenerator::default_spacing_precision, HF::GraphGenerator::default_z_precision, and HF::Geometry::LoadMeshObjects().
TEST() [9/14]
HF::TEST (_GraphGenerator , DuplicateNodes_Weston)
Definition at line 238 of file AnalysisMethods.cpp.
References CheckForDuplicates(), HF::GraphGenerator::default_ground_offset, HF::GraphGenerator::default_spacing_precision, HF::GraphGenerator::default_z_precision, and HF::Geometry::LoadMeshObjects().
TEST() [10/14]
HF::TEST (_GraphGenerator , GraphGeneratorParallel)
Definition at line 89 of file AnalysisMethods.cpp.
References CheckForDuplicates(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [11/14]
HF::TEST (_GraphGenerator , GraphGeneratorSingle)
Definition at line 174 of file AnalysisMethods.cpp.
References CheckForDuplicates(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [12/14]
HF::TEST (_UniqueQueue , BlockRepeats)
Definition at line 301 of file AnalysisMethods.cpp.
References HF::GraphGenerator::UniqueQueue::push().
TEST() [13/14]
HF::TEST (_UniqueQueue , Empty)
Definition at line 314 of file AnalysisMethods.cpp.
References HF::GraphGenerator::UniqueQueue::empty(), and HF::GraphGenerator::UniqueQueue::push().
TEST() [14/14]
HF::TEST (_UniqueQueue , Size)
Definition at line 308 of file AnalysisMethods.cpp.
References HF::GraphGenerator::UniqueQueue::push(), and HF::GraphGenerator::UniqueQueue::size().