Cpp/tests/src/SpatialStructures.cpp File Reference
#include `gtest/gtest.h`
#include <robin_hood.h>
#include <graph.h>
#include <node.h>
#include <edge.h>
#include <constants.h>
#include <HFExceptions.h>
#include <spatialstructures_C.h>
#include `path.h`
Namespaces
 GraphTests
 NodeTests
 NodeExampleTests
The following are tests for the code samples for HF::SpatialStructures::Node.
 EdgeExampleTests
The following are tests for the code samples for HF::SpatialStructures::Edge.
 PathExampleTests
The following are tests for the code samples for HF::SpatialStructures::Path.
 GraphExampleTests
The following are tests for the code samples for HF::SpatialStructures::Graph.
 GraphExampleTests::ConstantsExampleTests
The following are tests for the code samples for HF::SpatialStructures::Constants.
 ConstantsExampleTests
 CInterfaceTests
Functions
GraphTests::TEST (_Graph, Creation)
GraphTests::TEST (_Graph, AddNodeTest)
GraphTests::TEST (_Graph, HasKeyFailTest)
GraphTests::TEST (_Graph, GetUndirectedEdges)
GraphTests::TEST (_Graph, GetUndirectedEdgesMulti)
GraphTests::TEST (_Graph, HasEdgeTrue)
GraphTests::TEST (_Graph, HasEdgeFalse)
GraphTests::TEST (_Graph, HasEdgeMulti)
Graph GraphTests::CreateTestAggregateGraph ()
GraphTests::TEST (_Graph, AggregateCosts_Sum)
GraphTests::TEST (_Graph, AggregateCosts_Average)
GraphTests::TEST (_Graph, AggregateCosts_Count)
GraphTests::TEST (_Graph, AggregateCosts_Undirected_Sum)
GraphTests::TEST (_Graph, AggregateCosts_Undirected_Average)
GraphTests::TEST (_Graph, AggregateCosts_Undirected_Count)
GraphTests::TEST (_Graph, AggregateCostsMulti)
GraphTests::TEST (_Graph, GetCostTypes)
GraphTests::TEST (_Graph, SizeEqualsNumberOfNodes)
GraphTests::TEST (_Graph, SizeEqualsNumberOfInts)
GraphTests::TEST (_Graph, GroupInsert)
bool GraphTests::Contains (const std::vector< int > &domain, int target)
GraphTests::TEST (_Graph, GetEdges)
TEST (_Graph, AddEdgeToNewCost)
TEST (_Graph, MultipleNewCostDoesntAffectDefault)
TEST (_Graph, GetSubGraphMulti)
void CompareVectorsOfEdgeSets (const vector< EdgeSet > &E1, const vector< EdgeSet > &E2)
TEST (_Graph, AddMultipleEdgeSetsToNewCost)
TEST (_Graph, DefaultNameChange)
TEST (_Graph, ClearMulti)
TEST (_Graph, AlternateCSR)
std::vector< int > GetIds (const Graph &G, const std::vector< Node > &nodes)
Graph CreateNodeAttributeGraph ()
float StringToFloat (const std::string &str_to_convert)
std::vector< float > ConvertStringsToFloat (const std::vector< std::string > &strings)
TEST (_Graph, AttrToParams_INCOMING)
TEST (_Graph, AttrToParams_OUTGOING)
TEST (_Graph, AttrToParams_BOTH)
TEST (C_Graph, AttrToParams)
TEST (_Rounding, addition_error)
NodeTests::TEST (_Node, Distance)
NodeTests::TEST (_Node, Equality)
NodeTests::TEST (_Node, RoundingAndEquality)
NodeExampleTests::TEST (_Node, DefaultConstructor)
NodeExampleTests::TEST (_Node, ParamConstructorNoID)
NodeExampleTests::TEST (_Node, ParamConstructorArray)
NodeExampleTests::TEST (_node, ParamConstructorArrayTypeID)
NodeExampleTests::TEST (_node, DistanceTo)
NodeExampleTests::TEST (_node, AngleTo)
NodeExampleTests::TEST (_node, DirectionTo)
NodeExampleTests::TEST (_node, GetArray)
NodeExampleTests::TEST (_node, OperatorIndexByRef)
NodeExampleTests::TEST (_node, OperatorIndexByVal)
NodeExampleTests::TEST (_node, OperatorEquality)
NodeExampleTests::TEST (_node, OperatorAssignment)
NodeExampleTests::TEST (_node, OperatorNEquality)
NodeExampleTests::TEST (_node, OperatorMinus)
NodeExampleTests::TEST (_node, OperatorPlus)
NodeExampleTests::TEST (_node, OperatorMultiply)
NodeExampleTests::TEST (_node, OperatorLessThanConst)
NodeExampleTests::TEST (_node, OperatorLessThan)
NodeExampleTests::TEST (_node, OperatorGreaterThanConst)
EdgeExampleTests::TEST (_edge, EdgeConstructor)
PathExampleTests::TEST (_pathMember, OperatorEquality)
PathExampleTests::TEST (_pathMember, OperatorNEquality)
PathExampleTests::TEST (_path, NoArgConstructor)
PathExampleTests::TEST (_path, ParamConstructor)
PathExampleTests::TEST (_path, AddNode)
PathExampleTests::TEST (_path, Empty)
PathExampleTests::TEST (_path, Size)
PathExampleTests::TEST (_path, Reverse)
PathExampleTests::TEST (_path, OperatorEquality)
PathExampleTests::TEST (_path, OperatorIndex)
PathExampleTests::TEST (_path, GetPMPointer)
PathExampleTests::TEST (_path, OperatorLessThanLessThan)
GraphExampleTests::TEST (_csrptrs, AreValid)
GraphExampleTests::TEST (_graph, ParamConstructor)
GraphExampleTests::TEST (_graph, NoArgConstructor)
GraphExampleTests::TEST (_graph, HasEdge_Array)
GraphExampleTests::TEST (_graph, HasEdge_Node)
GraphExampleTests::TEST (_graph, HasEdge_Int)
GraphExampleTests::TEST (_graph, Nodes)
GraphExampleTests::TEST (_graph, GetUndirectedEdges)
GraphExampleTests::TEST (_graph, GetEdges)
GraphExampleTests::TEST (_graph, AggregateGraph)
GraphExampleTests::TEST (_graph, OperatorIndex)
GraphExampleTests::TEST (_graph, AddEdge_Node)
GraphExampleTests::TEST (_graph, AddEdge_Int)
GraphExampleTests::TEST (_graph, HasKey)
GraphExampleTests::TEST (_graph, NodesAsFloat3)
GraphExampleTests::TEST (_graph, Size)
GraphExampleTests::TEST (_graph, GetID)
GraphExampleTests::TEST (_graph, Compress)
GraphExampleTests::TEST (_graph, GetCSRPointers)
GraphExampleTests::TEST (_graph, NodeFromID)
GraphExampleTests::TEST (_graph, Clear)
GraphExampleTests::ConstantsExampleTests::TEST (_functions, RoundHF)
GraphExampleTests::TEST (_graph, AddNodeAttribute)
GraphExampleTests::TEST (_graph, AddNodeAttributes)
GraphExampleTests::TEST (_graph, GetNodeAttributes)
GraphExampleTests::TEST (_graph, ClearNodeAttributes)
GraphExampleTests::TEST (_graph, GetEdgesCostName)
ConstantsExampleTests::TEST (_functions, RoundHF)
CInterfaceTests::TEST (_graphCInterface, AddNodeAttributes)
CInterfaceTests::TEST (_graphCInterface, GetNodeAttributes)
CInterfaceTests::TEST (_graphCInterface, DeleteScoreArray)
CInterfaceTests::TEST (_graphCInterface, ClearAttributeType)
CInterfaceTests::TEST (_NodeCInterface, GetAllNodesFromGraph)
CInterfaceTests::TEST (_NodeCInterface, GetSizeOfNodeVector)
CInterfaceTests::TEST (_NodeCInterface, AggregateCosts)
CInterfaceTests::TEST (_NodeCInterface, CreateGraph)
CInterfaceTests::TEST (_NodeCInterface, AddEdgeFromNodes)
CInterfaceTests::TEST (_NodeCInterface, AddEdgeFromNodeIDs)
CInterfaceTests::TEST (_NodeCInterface, GetCSRPointers)
CInterfaceTests::TEST (_NodeCInterface, GetNodeID)
CInterfaceTests::TEST (_NodeCInterface, Compress)
CInterfaceTests::TEST (_NodeCInterface, ClearGraph)
CInterfaceTests::TEST (_NodeCInterface, DestroyNodes)
CInterfaceTests::TEST (_NodeCInterface, DestroyEdges)
CInterfaceTests::TEST (_NodeCInterface, DestroyGraph)
Variables
const string test_attribute = `test_attr`
const vector< Node > test_param_nodes
Function Documentation
CompareVectorsOfEdgeSets()
void CompareVectorsOfEdgeSets (const vector< EdgeSet > & E1, const vector< EdgeSet > & E2) [inline]
Definition at line 435 of file SpatialStructures.cpp.
Referenced by TEST().
ConvertStringsToFloat()
std::vector<float> ConvertStringsToFloat (const std::vector< std::string > & strings) [inline]
Definition at line 592 of file SpatialStructures.cpp.
References StringToFloat().
Referenced by TEST().
CreateNodeAttributeGraph()
Graph CreateNodeAttributeGraph ()
[EX_AttrsToStrings]
[EX_AttrsToStrings]
Definition at line 549 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddNodeAttribute(), HF::SpatialStructures::Graph::Compress(), HF::SpatialStructures::Graph::getID(), and test_attribute.
Referenced by TEST().
GetIds()
std::vector<int> GetIds (const Graph & G, const std::vector< Node > & nodes)
Definition at line 541 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::getID().
Referenced by TEST().
StringToFloat()
float StringToFloat (const std::string & str_to_convert) [inline]
Definition at line 582 of file SpatialStructures.cpp.
Referenced by ConvertStringsToFloat().
TEST() [1/12]
TEST (_Graph , AddEdgeToNewCost)
Definition at line 349 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetEdges().
TEST() [2/12]
TEST (_Graph , AddMultipleEdgeSetsToNewCost)
Definition at line 442 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::AddEdges(), CompareVectorsOfEdgeSets(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetEdges().
TEST() [3/12]
TEST (_Graph , AlternateCSR)
Definition at line 505 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::AddEdges(), HF::SpatialStructures::Graph::Compress(), HF::SpatialStructures::CSRPtrs::data, HF::SpatialStructures::Graph::GetCSRPointers(), and HF::SpatialStructures::CSRPtrs::nnz.
TEST() [4/12]
TEST (_Graph , AttrToParams_BOTH)
Definition at line 640 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::AttrToCost(), HF::SpatialStructures::BOTH, ConvertStringsToFloat(), CreateNodeAttributeGraph(), HF::SpatialStructures::Graph::GetCost(), GetIds(), HF::SpatialStructures::Graph::GetNodeAttributes(), test_attribute, and test_param_nodes.
TEST() [5/12]
TEST (_Graph , AttrToParams_INCOMING)
[EX_AttrsToStrings2]
[EX_AttrsToStrings2]
Definition at line 601 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::AttrToCost(), ConvertStringsToFloat(), CreateNodeAttributeGraph(), HF::SpatialStructures::Graph::GetCost(), GetIds(), HF::SpatialStructures::Graph::GetNodeAttributes(), HF::SpatialStructures::INCOMING, test_attribute, and test_param_nodes.
TEST() [6/12]
TEST (_Graph , AttrToParams_OUTGOING)
Definition at line 624 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::AttrToCost(), ConvertStringsToFloat(), CreateNodeAttributeGraph(), HF::SpatialStructures::Graph::GetCost(), GetIds(), HF::SpatialStructures::Graph::GetNodeAttributes(), HF::SpatialStructures::OUTGOING, test_attribute, and test_param_nodes.
TEST() [7/12]
TEST (_Graph , ClearMulti)
Definition at line 487 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Clear(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::HasEdge().
TEST() [8/12]
TEST (_Graph , DefaultNameChange)
Definition at line 466 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::HasEdge().
TEST() [9/12]
TEST (_Graph , GetSubGraphMulti)
Definition at line 406 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::AddEdges(), HF::SpatialStructures::Graph::Compress(), HF::SpatialStructures::Graph::GetEdges(), and HF::SpatialStructures::Graph::GetSubgraph().
TEST() [10/12]
TEST (_Graph , MultipleNewCostDoesntAffectDefault)
Definition at line 376 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::AddEdges(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetEdges().
TEST() [11/12]
TEST (_Rounding , addition_error)
Definition at line 674 of file SpatialStructures.cpp.
TEST() [12/12]
TEST (C_Graph , AttrToParams)
Definition at line 656 of file SpatialStructures.cpp.
References HF::SpatialStructures::BOTH, ConvertStringsToFloat(), CreateNodeAttributeGraph(), HF::SpatialStructures::Graph::GetCost(), GetIds(), HF::SpatialStructures::Graph::GetNodeAttributes(), GraphAttrsToCosts(), test_attribute, and test_param_nodes.
Variable Documentation
test_attribute
const string test_attribute = `test_attr`
Definition at line 536 of file SpatialStructures.cpp.
Referenced by CreateNodeAttributeGraph(), and TEST().
test_param_nodes
const vector<Node> test_param_nodes
Initial value:
= {
        {1,1,1}, {2,2,2}, {3,3,3},{4,4,4}, {5,5,5}
}
Definition at line 537 of file SpatialStructures.cpp.
Referenced by TEST().