std Namespace Reference
STL namespace.
Classes
class allocator
STL class.
class array
STL class.
class atomic
STL class.
class atomic_ref
STL class.
class auto_ptr
STL class.
class bad_alloc
STL class.
class bad_cast
STL class.
class bad_exception
STL class.
class bad_typeid
STL class.
class basic_fstream
STL class.
class basic_ifstream
STL class.
class basic_ios
STL class.
class basic_iostream
STL class.
class basic_istream
STL class.
class basic_istringstream
STL class.
class basic_ofstream
STL class.
class basic_ostream
STL class.
class basic_ostringstream
STL class.
class basic_string
STL class.
class basic_string_view
STL class.
class basic_stringstream
STL class.
class bitset
STL class.
class complex
STL class.
class deque
STL class.
class domain_error
STL class.
class error_category
STL class.
class error_code
STL class.
class error_condition
STL class.
class exception
STL class.
class forward_list
STL class.
class fstream
STL class.
struct hash< HF::SpatialStructures::Node >
Hash this node by combining the hashes of all of it's position elements.
struct hash< nlohmann::json >
hash value for JSON objects
struct hash< std::array< float, 3 > >
struct hash< std::array< T, 3 > >
Template specialization of std::hash for using std::array<numeric_type, 3>.
class ifstream
STL class.
class invalid_argument
STL class.
class ios
STL class.
class ios_base
STL class.
class istream
STL class.
class istringstream
STL class.
class jthread
STL class.
class length_error
STL class.
struct less<::nlohmann::detail::value_t >
specialization for std::less<value_t>
class list
STL class.
class lock_guard
STL class.
class logic_error
STL class.
class map
STL class.
class multimap
STL class.
class multiset
STL class.
class mutex
STL class.
class ofstream
STL class.
class ostream
STL class.
class ostringstream
STL class.
class out_of_range
STL class.
class overflow_error
STL class.
class priority_queue
STL class.
class queue
STL class.
class range_error
STL class.
class recursive_mutex
STL class.
class recursive_timed_mutex
STL class.
class runtime_error
STL class.
class set
STL class.
class shared_lock
STL class.
class shared_mutex
STL class.
class shared_ptr
STL class.
class shared_timed_mutex
STL class.
class smart_ptr
STL class.
class span
STL class.
class stack
STL class.
class string
STL class.
class string_view
STL class.
class stringstream
STL class.
class system_error
STL class.
class thread
STL class.
class timed_mutex
STL class.
class tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >
class tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >
class u16string
STL class.
class u16string_view
STL class.
class u32string
STL class.
class u32string_view
STL class.
class u8string
STL class.
class u8string_view
STL class.
class underflow_error
STL class.
class unique_lock
STL class.
class unique_ptr
STL class.
class unordered_map
STL class.
class unordered_multimap
STL class.
class unordered_multiset
STL class.
class unordered_set
STL class.
class valarray
STL class.
class vector
STL class.
class weak_ptr
STL class.
class wfstream
STL class.
class wifstream
STL class.
class wios
STL class.
class wistream
STL class.
class wistringstream
STL class.
class wofstream
STL class.
class wostream
STL class.
class wostringstream
STL class.
class wstring
STL class.
class wstring_view
STL class.
class wstringstream
STL class.
Functions
template<typename SizeT >
void array_hash_combine_impl (SizeT &seed, SizeT value)
Combine the hash of value into seed.
template<> void swap< nlohmann::json > (nlohmann::json &j1, nlohmann::json &j2) noexcept(is_nothrow_move_constructible< nlohmann::json >::value &&is_nothrow_move_assignable< nlohmann::json >::value)
exchanges the values of two JSON objects
template<typename SizeT >
void hash_combine_impl (SizeT &seed, SizeT value) noexcept
combine value into the hash value of seed
ostream & operator<< (ostream &os, const HF::SpatialStructures::Node n)
Create a string containing the x,y,z position of this node.
ostream & operator<< (ostream &os, const std::array< float, 3 > n)
Create a string containing the x,y,z positions of this array.
ostream & operator<< (ostream &os, const HF::SpatialStructures::Path p)
String representation of all the members contained by path p.
Detailed Description
STL namespace.
Hashing code for nodes.
Class Documentation
class std::tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >
template<std::size_t N, typename IteratorType>
class std::tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >
Definition at line 3987 of file json.hpp.
Class Members
typedef decltype(get< N >(declval< ::iteration_proxy_value< IteratorType > >()))
type
Function Documentation
array_hash_combine_impl()
template<typename SizeT >
void std::array_hash_combine_impl (SizeT & seed, SizeT value) [inline]
Combine the hash of value into seed.
Combine hashes for multiple floats.
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
// be sure to #include "meshinfo.h"
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Template Parameters
SizeT Integral type, such as size_t (implementation defined)
std::size_t seed_in = 0;
std::size_t value_in = VALUE_USER_DEFINED; // user-defined value for seed
// seed_in is passed by reference
std::array_hash_combine_impl<size_t>(seed_in, value_in);
// seed_in has now been given a value by array_hash_combine_impl
Definition at line 52 of file meshinfo.h.
Referenced by std::hash< std::array< float, 3 > >::operator()(), and std::hash< std::array< T, 3 > >::operator()().
hash_combine_impl()
template<typename SizeT >
void std::hash_combine_impl (SizeT & seed, SizeT value) [inline], [noexcept]
combine value into the hash value of seed
Definition at line 414 of file node.h.
Referenced by std::hash< HF::SpatialStructures::Node >::operator()().
operator<<() [1/3]
ostream & std::operator<< (ostream & os, const HF::SpatialStructures::Node n) [inline]
Create a string containing the x,y,z position of this node.
Definition at line 433 of file node.h.
References HF::SpatialStructures::Node::x, HF::SpatialStructures::Node::y, and HF::SpatialStructures::Node::z.
operator<<() [2/3]
ostream & std::operator<< (ostream & os, const HF::SpatialStructures::Path p) [inline]
String representation of all the members contained by path p.
// be sure to #include "path.h"
// Create the PathMembers
HF::SpatialStructures::PathMember p0 = { 3.14f, 3 };
HF::SpatialStructures::PathMember p1 = { 2.78f, 2 };
HF::SpatialStructures::PathMember p2 = { 1.64f, 1 };
HF::SpatialStructures::PathMember p3 = { 9.35f, 7 };
// Create the container of PathMembers
std::vector<HF::SpatialStructures::PathMember> members{p0, p1, p2, p3};
HF::SpatialStructures::Path path(members); // Create the Path object, path
std::cout << path << std::endl; // Output path to an ostream, like cout
// Output is: (3) -3.14-> (2) -2.78-> (1) -1.64-> (7) -9.35->
Definition at line 344 of file path.h.
References HF::SpatialStructures::Path::size().
operator<<() [3/3]
ostream & std::operator<< (ostream & os, const std::array< float, 3 > n) [inline]
Create a string containing the x,y,z positions of this array.
Definition at line 439 of file node.h.
swap< nlohmann::json >()
template<>
void std::swap< nlohmann::json > (nlohmann::json & j1, nlohmann::json & j2) [inline], [noexcept]
exchanges the values of two JSON objects
Since
version 1.0.0
Definition at line 25227 of file json.hpp.