Cpp/tests/src/PathFinding.cpp File Reference
#include `gtest/gtest.h`
#include <memory>
#include <boost/graph/dijkstra_shortest_paths.hpp>
#include <boost/graph/breadth_first_search.hpp>
#include <boost/graph/dijkstra_shortest_paths_no_color_map.hpp>
#include <boost/exception/exception.hpp>
#include <path_finder.h>
#include <boost_graph.h>
#include <graph.h>
#include <node.h>
#include <edge.h>
#include <path.h>
#include <HFExceptions.h>
#include `pathfinder_C.h`
#include `cost_algorithms.h`
#include `spatialstructures_C.h`
Namespaces
 CInterfaceTests
Functions
TEST (_Pathfinding, BoostGraphCreation)
TEST (_Pathfinding, SinglePath)
TEST (_Pathfinding, MultiplePaths)
Path QuickConstructPath (int start, int end, const std::vector< int > &pred, const std::vector< float > &distances)
TEST (_Pathfinding, DistanceAndPredecessorMatrices)
TEST (C_Pathfinder, DistanceAndPredecessorMatrices_C)
TEST (_boostGraph, Constructor)
The following are tests for the code samples for HF::SpatialStructures::Pathfinding.
TEST (_boostGraph, ConstructorCostName)
TEST (_boostGraph, Destructor)
TEST (_boostGraphDeleter, OperatorFunction)
TEST (_pathFinding, CreateBoostGraph)
TEST (_pathFinding, CreateBoostGraphCostName)
TEST (_pathFinding, FindPath)
TEST (_pathFinding, FindPaths)
TEST (_pathFinding, InsertAllToAllPathsIntoArray)
CInterfaceTests::TEST (C_Pathfinder, CreatePath)
CInterfaceTests::TEST (C_Pathfinder, CreatePaths)
CInterfaceTests::TEST (C_Pathfinder, CreatePathCostType)
CInterfaceTests::TEST (C_Pathfinder, CreatePathsCostType)
CInterfaceTests::TEST (C_Pathfinder, GetPathInfo)
CInterfaceTests::TEST (C_Pathfinder, DestroyPath)
CInterfaceTests::TEST (C_Pathfinder, CreateAllToAllPaths)
Function Documentation
QuickConstructPath()
Path QuickConstructPath (int start, int end, const std::vector< int > & pred, const std::vector< float > & distances) [inline]
Definition at line 98 of file PathFinding.cpp.
References HF::SpatialStructures::Path::AddNode(), and HF::SpatialStructures::Path::Reverse().
Referenced by TEST().
TEST() [1/14]
TEST (_boostGraph , Constructor)
The following are tests for the code samples for HF::SpatialStructures::Pathfinding.
Definition at line 254 of file PathFinding.cpp.
TEST() [2/14]
TEST (_boostGraph , ConstructorCostName)
Definition at line 279 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddEdges(), HF::SpatialStructures::CostAlgorithms::CalculateEnergyExpenditure(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetSubgraph().
TEST() [3/14]
TEST (_boostGraph , Destructor)
Definition at line 316 of file PathFinding.cpp.
TEST() [4/14]
TEST (_boostGraphDeleter , OperatorFunction)
Definition at line 349 of file PathFinding.cpp.
TEST() [5/14]
TEST (_Pathfinding , BoostGraphCreation)
Definition at line 26 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::Pathfinding::BoostGraph::g.
TEST() [6/14]
TEST (_pathFinding , CreateBoostGraph)
Definition at line 406 of file PathFinding.cpp.
References HF::Pathfinding::CreateBoostGraph().
TEST() [7/14]
TEST (_pathFinding , CreateBoostGraphCostName)
Definition at line 437 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddEdges(), HF::SpatialStructures::CostAlgorithms::CalculateEnergyExpenditure(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), and HF::SpatialStructures::Graph::GetSubgraph().
TEST() [8/14]
TEST (_Pathfinding , DistanceAndPredecessorMatrices)
Ensures taht no runtime errors occur and the array if of the correct length. [EX_DistPred]
[EX_DistPred]
[EX_DistPred_2]
[EX_DistPred_2]
Definition at line 131 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), HF::Pathfinding::FindPath(), HF::Pathfinding::GenerateDistanceAndPred(), QuickConstructPath(), and HF::SpatialStructures::Graph::size().
TEST() [9/14]
TEST (_pathFinding , FindPath)
Definition at line 475 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), HF::Pathfinding::FindPath(), and HF::SpatialStructures::Path::members.
TEST() [10/14]
TEST (_pathFinding , FindPaths)
Definition at line 500 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), and HF::Pathfinding::FindPaths().
TEST() [11/14]
TEST (_pathFinding , InsertAllToAllPathsIntoArray)
Definition at line 540 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), HF::Pathfinding::InsertAllToAllPathsIntoArray(), HF::SpatialStructures::Path::members, and HF::SpatialStructures::Graph::Nodes().
TEST() [12/14]
TEST (_Pathfinding , MultiplePaths)
Definition at line 64 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::Pathfinding::FindPaths().
TEST() [13/14]
TEST (_Pathfinding , SinglePath)
Definition at line 39 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::Pathfinding::FindPath().
TEST() [14/14]
TEST (C_Pathfinder , DistanceAndPredecessorMatrices_C)
[EX_DistPred_C]
[EX_DistPred_C]
[EX_DistPred_C_2]
[EX_DistPred_C_2]
Definition at line 183 of file PathFinding.cpp.
References AddEdgeFromNodes(), CalculateDistanceAndPredecessor(), Compress(), HF::Pathfinding::CreateBoostGraph(), CreateGraph(), DestroyFloatVector(), DestroyIntVector(), HF::Pathfinding::GenerateDistanceAndPred(), HF::Exceptions::OK, and HF::SpatialStructures::Graph::size().