Cpp/tests/src/performance.cpp File Reference
#include `gtest/gtest.h`
#include `performance_testing.h`
#include <embree_raytracer.h>
#include <objloader.h>
#include <meshinfo.h>
#include <view_analysis.h>
#include <graph.h>
#include <vector>
#include <array>
#include <ostream>
#include <fstream>
#include <graph_generator.h>
Classes
struct ModelAndStart
struct GraphGeneratorSettings
Typedefs
using MeshInfo = HF::Geometry::MeshInfo< float >
Functions
template<typename T >
int count_hits (vector< HitStruct< T >> &results)
void PrintDirections (const std::vector< std::array< float, 3 >> directions)
void WriteToCSV (std::ofstream &file, const std::vector< string > &strings_to_write)
TEST (Performance, CustomTriangleIntersection)
TEST (Performance, GraphGenerator_PrecisevsStandard)
Class Documentation
struct GraphGeneratorSettings
Definition at line 191 of file performance.cpp.
Class Members
float
DownSlope
float
DownStep
array< float, 3 >
spacing
float
UpSlope
float
UpStep
Typedef Documentation
MeshInfo
using MeshInfo = HF::Geometry::MeshInfo<float>
Definition at line 19 of file performance.cpp.
Function Documentation
count_hits()
template<typename T >
int count_hits (vector< HitStruct< T >> & results) [inline]
Definition at line 27 of file performance.cpp.
Referenced by TEST().
PrintDirections()
void PrintDirections (const std::vector< std::array< float, 3 >> directions)
Definition at line 36 of file performance.cpp.
TEST() [1/2]
TEST (Performance , CustomTriangleIntersection)
Definition at line 77 of file performance.cpp.
References count_hits(), HF::ViewAnalysis::FibbonacciDistributePoints(), StopWatch::GetDuration(), StopWatch::StartClock(), StopWatch::StopClock(), nlohmann::to_string(), and WriteToCSV().
TEST() [2/2]
TEST (Performance , GraphGenerator_PrecisevsStandard)
10000, 10000, 10000,
Definition at line 200 of file performance.cpp.
References HF::GraphGenerator::GraphGenerator::BuildNetwork(), StopWatch::GetDuration(), StopWatch::StartClock(), StopWatch::StopClock(), nlohmann::to_string(), and WriteToCSV().
WriteToCSV()
void WriteToCSV (std::ofstream & file, const std::vector< string > & strings_to_write) [inline]
Definition at line 69 of file performance.cpp.
Referenced by TEST().