CostAlgorithmsTests Namespace Reference
Functions
TEST (_CostAlgorithms, CalculateCrossSlopeSubgraph)
TEST (_CostAlgorithms, CalculateCrossSlopeAll)
TEST (_CostAlgorithms, to_radians)
TEST (_CostAlgorithms, to_degrees)
TEST (_CostAlgorithms, euclidean_distance)
TEST (_CostAlgorithms, dot_product)
TEST (_CostAlgorithms, is_perpendicular)
TEST (_CostAlgorithms, GetPerpendicularEdges)
Function Documentation
TEST() [1/8]
CostAlgorithmsTests::TEST (_CostAlgorithms , CalculateCrossSlopeAll)
Definition at line 47 of file CostAlgorithms.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::CostAlgorithms::CalculateCrossSlope(), and HF::SpatialStructures::Graph::Compress().
TEST() [2/8]
CostAlgorithmsTests::TEST (_CostAlgorithms , CalculateCrossSlopeSubgraph)
Definition at line 12 of file CostAlgorithms.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::CostAlgorithms::CalculateCrossSlope(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetSubgraph().
TEST() [3/8]
CostAlgorithmsTests::TEST (_CostAlgorithms , dot_product)
Definition at line 188 of file CostAlgorithms.cpp.
References HF::SpatialStructures::CostAlgorithms::dot_product().
TEST() [4/8]
CostAlgorithmsTests::TEST (_CostAlgorithms , euclidean_distance)
Definition at line 172 of file CostAlgorithms.cpp.
References HF::SpatialStructures::CostAlgorithms::euclidean_distance().
TEST() [5/8]
CostAlgorithmsTests::TEST (_CostAlgorithms , GetPerpendicularEdges)
Definition at line 224 of file CostAlgorithms.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::SpatialStructures::CostAlgorithms::GetPerpendicularEdges(), and HF::SpatialStructures::Graph::GetSubgraph().
TEST() [6/8]
CostAlgorithmsTests::TEST (_CostAlgorithms , is_perpendicular)
Definition at line 206 of file CostAlgorithms.cpp.
References HF::SpatialStructures::CostAlgorithms::is_perpendicular().
TEST() [7/8]
CostAlgorithmsTests::TEST (_CostAlgorithms , to_degrees)
Definition at line 154 of file CostAlgorithms.cpp.
References HF::SpatialStructures::CostAlgorithms::to_degrees().
TEST() [8/8]
CostAlgorithmsTests::TEST (_CostAlgorithms , to_radians)
Definition at line 144 of file CostAlgorithms.cpp.
References HF::SpatialStructures::CostAlgorithms::to_radians().