HF::nanoGeom Namespace Reference
Classes
struct Mesh
Functions
bool LoadObj (Mesh &mesh, const char *filename)
bool nanoRT_RayCast (nanort::BVHAccel< double > &accel, nanort::TriangleIntersector< double, nanort::TriangleIntersection< double > > &triangle_intersector, nanort::Ray< double > &ray, nanort::TriangleIntersection< double > &isect)
nanort::BVHAccel< double > nanoRT_BVH (Mesh &mesh)
nanort::BVHAccel< double > nanoRT_BVH (Mesh mesh)
bool nanoRT_Intersect (Mesh &mesh, nanort::BVHAccel< double > &accel, nanoRT_Data &intersector)
template<typename T >
nanort::BVHAccel< T > nanoRT_BVH (unsigned int *indices, T *vertices, int num_vertices, int num_indices)
Class Documentation
struct HF::nanoGeom::Mesh
Definition at line 19 of file meshinfo.h.
Class Members
unsigned int *
faces
[xyz] * 3(triangle) * num_faces
double *
facevarying_binormals
[xyz] * 3(triangle) * num_faces
double *
facevarying_normals
[xyz] * num_vertices
double *
facevarying_tangents
[xyz] * 3(triangle) * num_faces
double *
facevarying_uvs
[xyz] * 3(triangle) * num_faces
double *
facevarying_vertex_colors
[xyz] * 3(triangle) * num_faces
unsigned int *
material_ids
triangle x num_faces
size_t
num_faces
size_t
num_vertices
double *
vertices
Function Documentation
LoadObj()
bool HF::nanoGeom::LoadObj (Mesh & mesh, const char * filename)
Definition at line 29 of file objloader.cpp.
References HF::nanoGeom::Mesh::faces, HF::nanoGeom::Mesh::num_faces, HF::nanoGeom::Mesh::num_vertices, and HF::nanoGeom::Mesh::vertices.
Referenced by TEST().
nanoRT_BVH() [1/3]
nanort::BVHAccel<double> HF::nanoGeom::nanoRT_BVH (Mesh & mesh)
Definition at line 72 of file nanort_raytracer.cpp.
References nanort::BVHAccel< T >::Build(), nanort::BVHBuildOptions< T >::cache_bbox, HF::nanoGeom::Mesh::faces, HF::nanoGeom::Mesh::num_faces, and HF::nanoGeom::Mesh::vertices.
Referenced by nanoRT_BVH(), and TEST().
nanoRT_BVH() [2/3]
nanort::BVHAccel< double > HF::nanoGeom::nanoRT_BVH (Mesh mesh)
Definition at line 94 of file nanort_raytracer.cpp.
References HF::nanoGeom::Mesh::faces, nanoRT_BVH(), HF::nanoGeom::Mesh::num_faces, HF::nanoGeom::Mesh::num_vertices, and HF::nanoGeom::Mesh::vertices.
nanoRT_BVH() [3/3]
template<typename T >
nanort::BVHAccel<T> HF::nanoGeom::nanoRT_BVH (unsigned int * indices, T * vertices, int num_vertices, int num_indices) [inline]
Definition at line 112 of file ray_data.h.
References nanort::BVHAccel< T >::Build(), and nanort::BVHBuildOptions< T >::cache_bbox.
nanoRT_Intersect()
bool HF::nanoGeom::nanoRT_Intersect (Mesh & mesh, nanort::BVHAccel< double > & accel, nanoRT_Data & intersector)
Definition at line 98 of file nanort_raytracer.cpp.
References nanort::Ray< T >::dir, nanoRT_Data::hit, nanort::Ray< T >::org, nanoRT_Data::point, nanoRT_Data::ray, nanort::TriangleIntersection< T >::t, and nanort::BVHAccel< T >::Traverse().
Referenced by TEST().
nanoRT_RayCast()
bool HF::nanoGeom::nanoRT_RayCast (nanort::BVHAccel< double > & accel, nanort::TriangleIntersector< double, nanort::TriangleIntersection< double > > & triangle_intersector, nanort::Ray< double > & ray, nanort::TriangleIntersection< double > & isect)
Definition at line 47 of file nanort_raytracer.cpp.
References nanort::BVHAccel< T >::Traverse().