CInterfaceTests Namespace Reference
Functions
TEST (_analysis_cinterface, GenerateGraph)
TEST (_AnalysisCInterface, GenerateGraph)
TEST (_CostAlgorithmsCInterface, CalculateAndStoreCrossSlope)
TEST (_CostAlgorithmsCInterface, CalculateAndStoreEnergyExpenditureWithEnergyBlob)
TEST (_CostAlgorithms, CalculateEnergyExpenditureSubgraph)
TEST (_CostAlgorithms, CalculateEnergyExpenditureAll)
TEST (_CostAlgorithms, CalculateEnergyExpenditureWithEnergyBlob)
TEST (C_OBJLoader, LoadOBJ)
TEST (C_OBJLoader, StoreMesh)
TEST (C_OBJLoader, RotateMesh)
TEST (C_OBJLoader, GetVertsAndTris)
TEST (C_OBJLoader, GetMeshID)
TEST (C_OBJLoader, GetName)
TEST (_objloader_cinterface, LoadOBJ)
TEST (_objloader_CInterface, StoreMesh)
TEST (_objloader_CInterface, RotateMesh)
TEST (_objloader_CInterface, DestroyMeshInfo)
TEST (_pathfinder_cinterface, CreatePath)
TEST (_pathfinder_cinterface, CreatePaths)
TEST (_pathfinder_cinterface, GetPathInfo)
TEST (_pathfinder_cinterface, DestroyPath)
TEST (_pathfinder_cinterface, CreateAllToAllPaths)
TEST (_pathfinder_cinterface, CalculateDistanceAndPredecessor)
TEST (C_Pathfinder, CreatePath)
TEST (C_Pathfinder, CreatePaths)
TEST (C_Pathfinder, CreatePathCostType)
TEST (C_Pathfinder, CreatePathsCostType)
TEST (C_Pathfinder, GetPathInfo)
TEST (C_Pathfinder, DestroyPath)
TEST (C_Pathfinder, CreateAllToAllPaths)
TEST (_graphCInterface, AddNodeAttributes)
TEST (_graphCInterface, GetNodeAttributes)
TEST (_graphCInterface, DeleteScoreArray)
TEST (_graphCInterface, ClearAttributeType)
TEST (_NodeCInterface, GetAllNodesFromGraph)
TEST (_NodeCInterface, GetSizeOfNodeVector)
TEST (_NodeCInterface, AggregateCosts)
TEST (_NodeCInterface, CreateGraph)
TEST (_NodeCInterface, AddEdgeFromNodes)
TEST (_NodeCInterface, AddEdgeFromNodeIDs)
TEST (_NodeCInterface, GetCSRPointers)
TEST (_NodeCInterface, GetNodeID)
TEST (_NodeCInterface, Compress)
TEST (_NodeCInterface, ClearGraph)
TEST (_NodeCInterface, DestroyNodes)
TEST (_NodeCInterface, DestroyEdges)
TEST (_NodeCInterface, DestroyGraph)
TEST (_spatialstructures_cinterface, AlgorithmCostTitle)
TEST (_spatialstructures_cinterface, GetAllNodesFromGraph)
TEST (_spatialstructures_cinterface, GetEdgesForNode)
TEST (_spatialstructures_cinterface, GetSizeOfNodeVector)
TEST (_spatialstructures_cinterface, GetSizeOfEdgeVector)
TEST (_spatialstructures_cinterface, GetEdgeCost)
TEST (_spatialstructures_cinterface, AggregateCosts)
TEST (_spatialstructures_cinterface, CreateGraph)
TEST (_spatialstructures_cinterface, AddEdgeFromNodes)
TEST (_spatialstructures_cinterface, AddEdgeFromNodeIDs)
TEST (_spatialstructures_cinterface, GetCSRPointers)
TEST (_spatialstructures_cinterface, GetNodeID)
TEST (_spatialstructures_cinterface, Compress)
TEST (_spatialstructures_cinterface, ClearGraph)
TEST (_spatialstructures_cinterface, DestroyNodes)
TEST (_spatialstructures_cinterface, DestroyEdges)
TEST (_spatialstructures_cinterface, DestroyGraph)
TEST (_spatialstructures_cinterface, CalculateAndStoreCrossSlope)
TEST (_spatialstructures_cinterface, CalculateAndStoreEnergyExpenditure)
TEST (_spatialstructures_cinterface, AddNodeAttributes)
TEST (_spatialstructures_cinterface, GetNodeAttributes)
TEST (_spatialstructures_cinterface, DeleteScoreArray)
TEST (_spatialstructures_cinterface, ClearAttributeType)
TEST (_spatialstructures_cinterface, GetSizeOfGraph)
TEST (_view_analysis_cinterface, SphereicalViewAnalysisAggregate)
TEST (_view_analysis_cinterface, SphereicalViewAnalysisAggregateFlat)
TEST (_view_analysis_cinterface, SphericalViewAnalysisNoAggregate)
TEST (_view_analysis_cinterface, SphericalViewAnalysisNoAggregateFlat)
TEST (_view_analysis_cinterface, SphericalDistribute)
TEST (_visibility_graph_cinterface, CreateVisibilityGraphAllToAll)
TEST (_visibility_graph_cinterface, CreateVisibilityGraphAllToAllUndirected)
TEST (_visibility_graph_cinterface, CreateVisibilityGraphGroupToGroup)
Variables
int mesh_indices [] = { 0, 1, 2 }
const int mesh_num_indices = 3
float mesh_vertices [] = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 }
const int mesh_num_vertices = 9
std::string mesh_name = `This mesh`
const int mesh_id = 0
Function Documentation
TEST() [1/79]
CInterfaceTests::TEST (_analysis_cinterface , GenerateGraph)
[snippet_analysis_cinterface_GenerateGraph_setup_0]
[snippet_analysis_cinterface_GenerateGraph_setup_0]
[snippet_analysis_cinterface_GenerateGraph]
[snippet_analysis_cinterface_GenerateGraph]
[snippet_analysis_cinterface_GenerateGraph_compress]
[snippet_analysis_cinterface_GenerateGraph_compress]
[snippet_analysis_cinterface_GenerateGraph_GetNodes]
[snippet_analysis_cinterface_GenerateGraph_GetNodes]
[snippet_analysis_cinterface_GenerateGraph_output]
[snippet_analysis_cinterface_GenerateGraph_output]
[snippet_analysis_cinterface_GenerateGraph_destroy]
Memory resource cleanup.
[snippet_analysis_cinterface_GenerateGraph_destroy]
Definition at line 20 of file analysis_C_cinterface.cpp.
References Compress(), CreateRaytracer(), DestroyGraph(), DestroyMeshInfo(), DestroyNodes(), DestroyRayTracer(), GenerateGraph(), GetAllNodesFromGraph(), GetSizeOfNodeVector(), and LoadOBJ().
TEST() [2/79]
CInterfaceTests::TEST (_AnalysisCInterface , GenerateGraph)
Definition at line 324 of file AnalysisMethods.cpp.
References GenerateGraph().
TEST() [3/79]
CInterfaceTests::TEST (_CostAlgorithms , CalculateEnergyExpenditureAll)
Definition at line 375 of file CostAlgorithms.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::CostAlgorithms::CalculateEnergyExpenditure(), and HF::SpatialStructures::Graph::Compress().
TEST() [4/79]
CInterfaceTests::TEST (_CostAlgorithms , CalculateEnergyExpenditureSubgraph)
Definition at line 341 of file CostAlgorithms.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::CostAlgorithms::CalculateEnergyExpenditure(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetSubgraph().
TEST() [5/79]
CInterfaceTests::TEST (_CostAlgorithms , CalculateEnergyExpenditureWithEnergyBlob)
Definition at line 410 of file CostAlgorithms.cpp.
TEST() [6/79]
CInterfaceTests::TEST (_CostAlgorithmsCInterface , CalculateAndStoreCrossSlope)
Definition at line 268 of file CostAlgorithms.cpp.
References HF::SpatialStructures::Graph::addEdge(), CalculateAndStoreCrossSlope(), and HF::SpatialStructures::Graph::Compress().
TEST() [7/79]
CInterfaceTests::TEST (_CostAlgorithmsCInterface , CalculateAndStoreEnergyExpenditureWithEnergyBlob)
Definition at line 338 of file CostAlgorithms.cpp.
TEST() [8/79]
CInterfaceTests::TEST (_graphCInterface , AddNodeAttributes)
Definition at line 1987 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), AddNodeAttributes(), HF::SpatialStructures::Graph::GetNodeAttributes(), and HF::SpatialStructures::Graph::size().
TEST() [9/79]
CInterfaceTests::TEST (_graphCInterface , ClearAttributeType)
Definition at line 2098 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), AddNodeAttributes(), ClearAttributeType(), HF::SpatialStructures::Graph::GetNodeAttributes(), HF::Exceptions::OK, and HF::SpatialStructures::Graph::size().
TEST() [10/79]
CInterfaceTests::TEST (_graphCInterface , DeleteScoreArray)
Definition at line 2077 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), AddNodeAttributes(), DeleteScoreArray(), GetNodeAttributes(), and HF::SpatialStructures::Graph::size().
TEST() [11/79]
CInterfaceTests::TEST (_graphCInterface , GetNodeAttributes)
Definition at line 2008 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), AddNodeAttributes(), DeleteScoreArray(), GetNodeAttributes(), and HF::SpatialStructures::Graph::size().
TEST() [12/79]
CInterfaceTests::TEST (_NodeCInterface , AddEdgeFromNodeIDs)
Definition at line 2246 of file SpatialStructures.cpp.
References AddEdgeFromNodeIDs(), CreateGraph(), and DestroyGraph().
TEST() [13/79]
CInterfaceTests::TEST (_NodeCInterface , AddEdgeFromNodes)
Definition at line 2223 of file SpatialStructures.cpp.
References AddEdgeFromNodes(), CreateGraph(), and DestroyGraph().
TEST() [14/79]
CInterfaceTests::TEST (_NodeCInterface , AggregateCosts)
Definition at line 2171 of file SpatialStructures.cpp.
References AddEdgeFromNodes(), AggregateCosts(), CreateGraph(), and DestroyGraph().
TEST() [15/79]
CInterfaceTests::TEST (_NodeCInterface , ClearGraph)
Definition at line 2378 of file SpatialStructures.cpp.
References AddEdgeFromNodes(), ClearGraph(), CreateGraph(), and DestroyGraph().
TEST() [16/79]
CInterfaceTests::TEST (_NodeCInterface , Compress)
Definition at line 2344 of file SpatialStructures.cpp.
References AddEdgeFromNodes(), Compress(), CreateGraph(), and DestroyGraph().
TEST() [17/79]
CInterfaceTests::TEST (_NodeCInterface , CreateGraph)
Definition at line 2204 of file SpatialStructures.cpp.
References CreateGraph(), and DestroyGraph().
TEST() [18/79]
CInterfaceTests::TEST (_NodeCInterface , DestroyEdges)
Definition at line 2418 of file SpatialStructures.cpp.
References DestroyEdges().
TEST() [19/79]
CInterfaceTests::TEST (_NodeCInterface , DestroyGraph)
Definition at line 2436 of file SpatialStructures.cpp.
References CreateGraph(), and DestroyGraph().
TEST() [20/79]
CInterfaceTests::TEST (_NodeCInterface , DestroyNodes)
Definition at line 2403 of file SpatialStructures.cpp.
References DestroyNodes().
TEST() [21/79]
CInterfaceTests::TEST (_NodeCInterface , GetAllNodesFromGraph)
Definition at line 2123 of file SpatialStructures.cpp.
References AddEdgeFromNodes(), CreateGraph(), DestroyGraph(), and GetAllNodesFromGraph().
TEST() [22/79]
CInterfaceTests::TEST (_NodeCInterface , GetCSRPointers)
Definition at line 2269 of file SpatialStructures.cpp.
References AddEdgeFromNodes(), HF::SpatialStructures::CSRPtrs::cols, Compress(), CreateGraph(), HF::SpatialStructures::CSRPtrs::data, DestroyGraph(), GetCSRPointers(), HF::SpatialStructures::CSRPtrs::inner_indices, HF::SpatialStructures::CSRPtrs::nnz, HF::SpatialStructures::CSRPtrs::outer_indices, and HF::SpatialStructures::CSRPtrs::rows.
TEST() [23/79]
CInterfaceTests::TEST (_NodeCInterface , GetNodeID)
Definition at line 2316 of file SpatialStructures.cpp.
References AddEdgeFromNodes(), CreateGraph(), DestroyGraph(), and GetNodeID().
TEST() [24/79]
CInterfaceTests::TEST (_NodeCInterface , GetSizeOfNodeVector)
Definition at line 2155 of file SpatialStructures.cpp.
References DestroyNodes(), and GetSizeOfNodeVector().
TEST() [25/79]
CInterfaceTests::TEST (_objloader_CInterface , DestroyMeshInfo)
[snippet_DestroyMeshInfo]
[snippet_DestroyMeshInfo]
Definition at line 256 of file objloader_cinterface.cpp.
References DestroyMeshInfo(), and LoadOBJ().
TEST() [26/79]
CInterfaceTests::TEST (_objloader_cinterface , LoadOBJ)
Definition at line 17 of file objloader_cinterface.cpp.
References DestroyMeshInfo(), and LoadOBJ().
TEST() [27/79]
CInterfaceTests::TEST (_objloader_CInterface , RotateMesh)
[snippet_RotateMesh]
[snippet_RotateMesh]
Definition at line 172 of file objloader_cinterface.cpp.
References DestroyMeshInfo(), mesh_id, mesh_indices, mesh_name, mesh_vertices, RotateMesh(), and StoreMesh().
TEST() [28/79]
CInterfaceTests::TEST (_objloader_CInterface , StoreMesh)
[snippet_StoreMesh_setup]
[snippet_StoreMesh_setup]
[snippet_StoreMesh_call]
[snippet_StoreMesh_call]
Definition at line 87 of file objloader_cinterface.cpp.
References DestroyMeshInfo(), mesh_id, mesh_indices, mesh_name, mesh_vertices, and StoreMesh().
TEST() [29/79]
CInterfaceTests::TEST (_pathfinder_cinterface , CalculateDistanceAndPredecessor)
[EX_DistPred_C]
[EX_DistPred_C]
[EX_DistPred_C_2]
[EX_DistPred_C_2]
Definition at line 310 of file pathfinder_C_cinterface.cpp.
References AddEdgeFromNodes(), CalculateDistanceAndPredecessor(), Compress(), HF::Pathfinding::CreateBoostGraph(), CreateGraph(), DestroyFloatVector(), DestroyIntVector(), HF::Pathfinding::GenerateDistanceAndPred(), and HF::Exceptions::OK.
TEST() [30/79]
CInterfaceTests::TEST (_pathfinder_cinterface , CreateAllToAllPaths)
[snippet_CreateAllToAllPaths]
[snippet_CreateAllToAllPaths]
Definition at line 304 of file pathfinder_C_cinterface.cpp.
TEST() [31/79]
CInterfaceTests::TEST (_pathfinder_cinterface , CreatePath)
[snippet_CreatePath]
[snippet_CreatePath]
Definition at line 35 of file pathfinder_C_cinterface.cpp.
References Compress(), CreatePath(), CreateRaytracer(), DestroyGraph(), DestroyMeshInfo(), DestroyNodes(), DestroyPath(), DestroyRayTracer(), GenerateGraph(), GetAllNodesFromGraph(), GetSizeOfNodeVector(), LoadOBJ(), and HF::SpatialStructures::Path::members.
TEST() [32/79]
CInterfaceTests::TEST (_pathfinder_cinterface , CreatePaths)
[snippet_CreatePaths]
[snippet_CreatePaths]
Definition at line 286 of file pathfinder_C_cinterface.cpp.
TEST() [33/79]
CInterfaceTests::TEST (_pathfinder_cinterface , DestroyPath)
[snippet_DestroyPath]
[snippet_DestroyPath]
Definition at line 298 of file pathfinder_C_cinterface.cpp.
TEST() [34/79]
CInterfaceTests::TEST (_pathfinder_cinterface , GetPathInfo)
[snippet_GetPathInfo]
[snippet_GetPathInfo]
Definition at line 292 of file pathfinder_C_cinterface.cpp.
TEST() [35/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , AddEdgeFromNodeIDs)
[snippet_spatialstructuresC_AddEdgeFromNodeIDs]
[snippet_spatialstructuresC_AddEdgeFromNodeIDs]
Definition at line 304 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodeIDs(), CreateGraph(), and DestroyGraph().
TEST() [36/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , AddEdgeFromNodes)
[snippet_spatialstructuresC_AddEdgeFromNodes]
[snippet_spatialstructuresC_AddEdgeFromNodes]
Definition at line 256 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), CreateGraph(), and DestroyGraph().
TEST() [37/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , AddNodeAttributes)
[snippet_spatialstructuresC_AddNodeAttributes]
[snippet_spatialstructuresC_AddNodeAttributes]
Definition at line 806 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodeIDs(), AddNodeAttributes(), CreateGraph(), DestroyGraph(), and HF::SpatialStructures::Graph::size().
TEST() [38/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , AggregateCosts)
[snippet_spatialstructuresC_AggregateCosts]
[snippet_spatialstructuresC_AggregateCosts]
Definition at line 142 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), AggregateCosts(), CreateGraph(), DestroyFloatVector(), and DestroyGraph().
TEST() [39/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , AlgorithmCostTitle)
[snippet_spatialstructuresC_AlgorithmCostTitle]
[snippet_spatialstructuresC_AlgorithmCostTitle]
Definition at line 18 of file spatialstructures_C_cinterface.cpp.
References AlgorithmCostTitle(), and CROSS_SLOPE.
TEST() [40/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , CalculateAndStoreCrossSlope)
[snippet_spatialstructuresC_CalculateAndStoreCrossSlope]
[snippet_spatialstructuresC_CalculateAndStoreCrossSlope]
Definition at line 678 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), AlgorithmCostTitle(), CalculateAndStoreCrossSlope(), Compress(), CreateGraph(), CROSS_SLOPE, and DestroyGraph().
TEST() [41/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , CalculateAndStoreEnergyExpenditure)
[snippet_spatialstructuresC_CalculateAndStoreEnergyExpenditure]
[snippet_spatialstructuresC_CalculateAndStoreEnergyExpenditure]
Definition at line 742 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), AlgorithmCostTitle(), CalculateAndStoreEnergyExpenditure(), Compress(), CreateGraph(), CROSS_SLOPE, and DestroyGraph().
TEST() [42/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , ClearAttributeType)
[snippet_spatialstructuresC_ClearAttributeType]
[snippet_spatialstructuresC_ClearAttributeType]
Definition at line 914 of file spatialstructures_C_cinterface.cpp.
References HF::SpatialStructures::Graph::addEdge(), AddNodeAttributes(), ClearAttributeType(), and HF::SpatialStructures::Graph::size().
TEST() [43/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , ClearGraph)
[snippet_spatialstructuresC_ClearGraph]
[snippet_spatialstructuresC_ClearGraph]
Definition at line 531 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), ClearGraph(), CreateGraph(), and DestroyGraph().
TEST() [44/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , Compress)
[snippet_spatialstructuresC_Compress]
[snippet_spatialstructuresC_Compress]
[snippet_spatialstructuresC_Compress]
Definition at line 472 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), Compress(), CreateGraph(), and DestroyGraph().
TEST() [45/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , CreateGraph)
[snippet_spatialstructuresC_CreateGraph]
[snippet_spatialstructuresC_CreateGraph]
Definition at line 215 of file spatialstructures_C_cinterface.cpp.
References CreateGraph(), and DestroyGraph().
TEST() [46/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , DeleteScoreArray)
[snippet_spatialstructuresC_DeleteScoreArray]
[snippet_spatialstructuresC_DeleteScoreArray]
Definition at line 908 of file spatialstructures_C_cinterface.cpp.
TEST() [47/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , DestroyEdges)
[snippet_spatialstructuresC_DestroyEdges]
[snippet_spatialstructuresC_DestroyEdges]
Definition at line 608 of file spatialstructures_C_cinterface.cpp.
References DestroyEdges().
TEST() [48/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , DestroyGraph)
[snippet_spatialstructuresC_DestroyGraph]
[snippet_spatialstructuresC_DestroyGraph]
Definition at line 640 of file spatialstructures_C_cinterface.cpp.
References CreateGraph(), and DestroyGraph().
TEST() [49/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , DestroyNodes)
[snippet_spatialstructuresC_DestroyNodes]
[snippet_spatialstructuresC_DestroyNodes]
Definition at line 579 of file spatialstructures_C_cinterface.cpp.
References DestroyNodes().
TEST() [50/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetAllNodesFromGraph)
[snippet_spatialstructuresC_GetAllNodesFromGraph]
[snippet_spatialstructuresC_GetAllNodesFromGraph]
Definition at line 31 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), CreateGraph(), DestroyGraph(), DestroyNodes(), and GetAllNodesFromGraph().
TEST() [51/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetCSRPointers)
[snippet_spatialstructuresC_GetCSRPointers]
[snippet_spatialstructuresC_GetCSRPointers]
Definition at line 348 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), HF::SpatialStructures::CSRPtrs::cols, Compress(), CreateGraph(), HF::SpatialStructures::CSRPtrs::data, DestroyGraph(), GetCSRPointers(), HF::SpatialStructures::CSRPtrs::inner_indices, HF::SpatialStructures::CSRPtrs::nnz, HF::SpatialStructures::CSRPtrs::outer_indices, and HF::SpatialStructures::CSRPtrs::rows.
TEST() [52/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetEdgeCost)
[snippet_spatialstructuresC_GetEdgeCost]
[snippet_spatialstructuresC_GetEdgeCost]
Definition at line 136 of file spatialstructures_C_cinterface.cpp.
TEST() [53/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetEdgesForNode)
[snippet_spatialstructuresC_GetEdgesForNode]
[snippet_spatialstructuresC_GetEdgesForNode]
Definition at line 90 of file spatialstructures_C_cinterface.cpp.
TEST() [54/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetNodeAttributes)
[snippet_spatialstructuresC_GetNodeAttributes]
[snippet_spatialstructuresC_GetNodeAttributes]
Definition at line 859 of file spatialstructures_C_cinterface.cpp.
References HF::SpatialStructures::Graph::addEdge(), AddNodeAttributes(), DeleteScoreArray(), GetNodeAttributes(), and HF::SpatialStructures::Graph::size().
TEST() [55/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetNodeID)
[snippet_spatialstructuresC_GetNodeID]
[snippet_spatialstructuresC_GetNodeID]
Definition at line 422 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), CreateGraph(), DestroyGraph(), and GetNodeID().
TEST() [56/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetSizeOfEdgeVector)
[snippet_spatialstructuresC_GetSizeOfEdgeVector]
[snippet_spatialstructuresC_GetSizeOfEdgeVector]
Definition at line 130 of file spatialstructures_C_cinterface.cpp.
TEST() [57/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetSizeOfGraph)
[snippet_spatialstructuresC_GetSizeOfGraph]
[snippet_spatialstructuresC_GetSizeOfGraph]
Definition at line 934 of file spatialstructures_C_cinterface.cpp.
References AddEdgeFromNodes(), CreateGraph(), DestroyGraph(), and GetSizeOfGraph().
TEST() [58/79]
CInterfaceTests::TEST (_spatialstructures_cinterface , GetSizeOfNodeVector)
[snippet_spatialstructuresC_GetSizeOfNodeVector]
[snippet_spatialstructuresC_GetSizeOfNodeVector]
Definition at line 96 of file spatialstructures_C_cinterface.cpp.
References DestroyNodes(), and GetSizeOfNodeVector().
TEST() [59/79]
CInterfaceTests::TEST (_view_analysis_cinterface , SphereicalViewAnalysisAggregate)
[snippet_view_analysis_SphereicalViewAnalysisAggregate_setup_0]
[snippet_view_analysis_SphereicalViewAnalysisAggregate_setup_0]
[snippet_view_analysis_SphereicalViewAnalysisAggregate_setup_1]
[snippet_view_analysis_SphereicalViewAnalysisAggregate_setup_1]
[snippet_view_analysis_SphereicalViewAnalysisAggregate]
[snippet_view_analysis_SphereicalViewAnalysisAggregate]
[snippet_view_analysis_SphereicalViewAnalysisAggregate_results]
[snippet_view_analysis_SphereicalViewAnalysisAggregate_results]
[snippet_view_analysis_SphereicalViewAnalysisAggregate_destroy]
[snippet_view_analysis_SphereicalViewAnalysisAggregate_destroy]
Definition at line 22 of file view_analysis_cinterface.cpp.
References AVERAGE, CreateRaytracer(), DestroyMeshInfo(), DestroyRayTracer(), LoadOBJ(), and SphereicalViewAnalysisAggregate().
TEST() [60/79]
CInterfaceTests::TEST (_view_analysis_cinterface , SphereicalViewAnalysisAggregateFlat)
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat_setup_0]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat_setup_0]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat_setup_1]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat_setup_1]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat_results]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat_results]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat_destroy]
[snippet_view_analysis_SphericalViewAnalysisAggregateFlat_destroy]
Definition at line 189 of file view_analysis_cinterface.cpp.
References AVERAGE, CreateRaytracer(), DestroyMeshInfo(), DestroyRayTracer(), LoadOBJ(), and SphereicalViewAnalysisAggregateFlat().
TEST() [61/79]
CInterfaceTests::TEST (_view_analysis_cinterface , SphericalDistribute)
[snippet_view_analysis_SphericalDistribute_setup]
[snippet_view_analysis_SphericalDistribute_setup]
[snippet_view_analysis_SphericalDistribute]
[snippet_view_analysis_SphericalDistribute]
[snippet_view_analysis_SphericalDistribute_output]
[snippet_view_analysis_SphericalDistribute_output]
[snippet_view_analysis_SphericalDistribute_destroy]
[snippet_view_analysis_SphericalDistribute_destroy]
Definition at line 671 of file view_analysis_cinterface.cpp.
References DestroyFloatVector(), and SphericalDistribute().
TEST() [62/79]
CInterfaceTests::TEST (_view_analysis_cinterface , SphericalViewAnalysisNoAggregate)
[snippet_view_analysis_SphericalViewAnalysisNoAggregate_setup_0]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate_setup_0]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate_setup_1]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate_setup_1]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate_results]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate_results]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate_destroy]
[snippet_view_analysis_SphericalViewAnalysisNoAggregate_destroy]
Definition at line 355 of file view_analysis_cinterface.cpp.
References CreateRaytracer(), DestroyMeshInfo(), DestroyRayTracer(), LoadOBJ(), and SphericalViewAnalysisNoAggregate().
TEST() [63/79]
CInterfaceTests::TEST (_view_analysis_cinterface , SphericalViewAnalysisNoAggregateFlat)
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat_setup_0]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat_setup_0]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat_setup_1]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat_setup_1]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat_results]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat_results]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat_destroy]
[snippet_view_analysis_SphericalViewAnalysisNoAggregateFlat_destroy]
Definition at line 513 of file view_analysis_cinterface.cpp.
References CreateRaytracer(), DestroyMeshInfo(), DestroyRayTracer(), LoadOBJ(), and SphericalViewAnalysisNoAggregateFlat().
TEST() [64/79]
CInterfaceTests::TEST (_visibility_graph_cinterface , CreateVisibilityGraphAllToAll)
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_setup]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_setup]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_call]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_call]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_compress]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_compress]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_output_0]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_output_0]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_output_1]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_output_1]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_destroy]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAll_destroy]
Definition at line 19 of file visibility_graph_cinterface.cpp.
References HF::SpatialStructures::CSRPtrs::cols, Compress(), CreateRaytracer(), CreateVisibilityGraphAllToAll(), HF::SpatialStructures::CSRPtrs::data, DestroyGraph(), DestroyMeshInfo(), DestroyRayTracer(), GetCSRPointers(), HF::SpatialStructures::CSRPtrs::inner_indices, LoadOBJ(), HF::SpatialStructures::CSRPtrs::nnz, HF::SpatialStructures::CSRPtrs::outer_indices, and HF::SpatialStructures::CSRPtrs::rows.
TEST() [65/79]
CInterfaceTests::TEST (_visibility_graph_cinterface , CreateVisibilityGraphAllToAllUndirected)
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_setup]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_setup]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_call]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_call]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_compress]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_compress]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_output_0]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_output_0]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_output_1]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_output_1]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_destroy]
[snippet_VisibilityGraph_CreateVisibilityGraphAllToAllUndirected_destroy]
Definition at line 222 of file visibility_graph_cinterface.cpp.
References HF::SpatialStructures::CSRPtrs::cols, Compress(), CreateRaytracer(), CreateVisibilityGraphAllToAllUndirected(), HF::SpatialStructures::CSRPtrs::data, DestroyGraph(), DestroyMeshInfo(), DestroyRayTracer(), GetCSRPointers(), HF::SpatialStructures::CSRPtrs::inner_indices, LoadOBJ(), HF::SpatialStructures::CSRPtrs::nnz, HF::SpatialStructures::CSRPtrs::outer_indices, and HF::SpatialStructures::CSRPtrs::rows.
TEST() [66/79]
CInterfaceTests::TEST (_visibility_graph_cinterface , CreateVisibilityGraphGroupToGroup)
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_setup]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_setup]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_call]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_call]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_compress]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_compress]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_output_0]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_output_0]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_output_1]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_output_1]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_destroy]
[snippet_VisibilityGraph_CreateVisibilityGraphGroupToGroup_destroy]
Definition at line 428 of file visibility_graph_cinterface.cpp.
References HF::SpatialStructures::CSRPtrs::cols, Compress(), CreateRaytracer(), CreateVisibilityGraphGroupToGroup(), HF::SpatialStructures::CSRPtrs::data, DestroyGraph(), DestroyMeshInfo(), DestroyRayTracer(), GetCSRPointers(), HF::SpatialStructures::CSRPtrs::inner_indices, LoadOBJ(), HF::SpatialStructures::CSRPtrs::nnz, HF::SpatialStructures::CSRPtrs::outer_indices, and HF::SpatialStructures::CSRPtrs::rows.
TEST() [67/79]
CInterfaceTests::TEST (C_OBJLoader , GetMeshID)
Definition at line 900 of file OBJLoader.cpp.
References DestroyMeshInfo(), GetMeshID(), mesh_id, mesh_indices, mesh_name, mesh_num_indices, mesh_num_vertices, mesh_vertices, HF::Exceptions::OK, and StoreMesh().
TEST() [68/79]
CInterfaceTests::TEST (C_OBJLoader , GetName)
Definition at line 918 of file OBJLoader.cpp.
References DestroyMeshInfo(), GetMeshName(), mesh_id, mesh_indices, mesh_name, mesh_num_indices, mesh_num_vertices, mesh_vertices, HF::Exceptions::OK, and StoreMesh().
TEST() [69/79]
CInterfaceTests::TEST (C_OBJLoader , GetVertsAndTris)
Definition at line 867 of file OBJLoader.cpp.
References DestroyMeshInfo(), GetVertsAndTris(), mesh_id, mesh_indices, mesh_name, mesh_num_indices, mesh_num_vertices, mesh_vertices, HF::Exceptions::OK, and StoreMesh().
TEST() [70/79]
CInterfaceTests::TEST (C_OBJLoader , LoadOBJ)
Definition at line 782 of file OBJLoader.cpp.
References HF::Geometry::BY_GROUP, DestroyMeshInfo(), DestroyMeshInfoPtrArray(), GetMeshID(), HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), LoadOBJ(), HF::Geometry::MeshInfo< numeric_type >::name, and HF::Exceptions::OK.
TEST() [71/79]
CInterfaceTests::TEST (C_OBJLoader , RotateMesh)
Definition at line 841 of file OBJLoader.cpp.
References DestroyMeshInfo(), HF::Geometry::MeshInfo< numeric_type >::GetIndexedVertices(), mesh_id, mesh_indices, mesh_name, mesh_num_indices, mesh_num_vertices, mesh_vertices, HF::Exceptions::OK, RotateMesh(), and StoreMesh().
TEST() [72/79]
CInterfaceTests::TEST (C_OBJLoader , StoreMesh)
Definition at line 826 of file OBJLoader.cpp.
References DestroyMeshInfo(), HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), mesh_id, mesh_indices, mesh_name, mesh_num_indices, mesh_num_vertices, mesh_vertices, HF::Geometry::MeshInfo< numeric_type >::name, HF::Exceptions::OK, and StoreMesh().
TEST() [73/79]
CInterfaceTests::TEST (C_Pathfinder , CreateAllToAllPaths)
[snippet_pathfinder_C_CreateAllToAllPaths]
[snippet_pathfinder_C_CreateAllToAllPaths]
[snippet_pathfinder_C_CreateAllToAllPaths_output] Path from 0 to 1 node ID : 0 cost 1 node ID : 1 cost 0
Total cost : 1
Path from 0 to 2 node ID : 0 cost 2 node ID : 2 cost 0
Total cost : 2
Path from 0 to 3 node ID : 0 cost 1 node ID : 1 cost 3 node ID : 3 cost 0
Total cost : 4
Path from 0 to 4 node ID : 0 cost 1 node ID : 1 cost 4 node ID : 4 cost 0
Total cost : 5
Path from 0 to 5 node ID : 0 cost 1 node ID : 1 cost 3 node ID : 3 cost 5 node ID : 5 cost 0
Total cost : 9
Path from 0 to 6 node ID : 0 cost 1 node ID : 1 cost 4 node ID : 4 cost 3 node ID : 6 cost 0
Total cost : 8
Path from 1 to 3 node ID : 1 cost 3 node ID : 3 cost 0
Total cost : 3
Path from 1 to 4 node ID : 1 cost 4 node ID : 4 cost 0
Total cost : 4
Path from 1 to 5 node ID : 1 cost 3 node ID : 3 cost 5 node ID : 5 cost 0
Total cost : 8
Path from 1 to 6 node ID : 1 cost 4 node ID : 4 cost 3 node ID : 6 cost 0
Total cost : 7
Path from 2 to 4 node ID : 2 cost 4 node ID : 4 cost 0
Total cost : 4
Path from 2 to 6 node ID : 2 cost 4 node ID : 4 cost 3 node ID : 6 cost 0
Total cost : 7
Path from 3 to 5 node ID : 3 cost 5 node ID : 5 cost 0
Total cost : 5
Path from 3 to 6 node ID : 3 cost 5 node ID : 5 cost 1 node ID : 6 cost 0
Total cost : 6
Path from 4 to 6 node ID : 4 cost 3 node ID : 6 cost 0
Total cost : 3
Path from 5 to 6 node ID : 5 cost 1 node ID : 6 cost 0
Total cost : 1
[snippet_pathfinder_C_CreateAllToAllPaths_output]
Definition at line 972 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), CreateAllToAllPaths(), HF::Pathfinding::CreateBoostGraph(), DestroyPath(), and HF::SpatialStructures::Graph::Nodes().
TEST() [74/79]
CInterfaceTests::TEST (C_Pathfinder , CreatePath)
Definition at line 697 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), CreatePath(), and DestroyPath().
TEST() [75/79]
CInterfaceTests::TEST (C_Pathfinder , CreatePathCostType)
[snippet_pathfinder_C_CreatePathCostType]
Use out_path, out_path_member
[snippet_pathfinder_C_CreatePathCostType]
Definition at line 778 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddEdges(), AlgorithmCostTitle(), HF::SpatialStructures::CostAlgorithms::CalculateEnergyExpenditure(), HF::SpatialStructures::Graph::Compress(), CreatePath(), CROSS_SLOPE, DestroyPath(), and HF::SpatialStructures::Graph::GetSubgraph().
TEST() [76/79]
CInterfaceTests::TEST (C_Pathfinder , CreatePaths)
[snippet_pathfinder_C_CreatePaths]
[snippet_pathfinder_C_CreatePaths]
Definition at line 728 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), CreatePaths(), and DestroyPath().
TEST() [77/79]
CInterfaceTests::TEST (C_Pathfinder , CreatePathsCostType)
[snippet_pathfinder_C_CreatePathsCostType]
[snippet_pathfinder_C_CreatePathsCostType]
Definition at line 834 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddEdges(), AlgorithmCostTitle(), HF::SpatialStructures::CostAlgorithms::CalculateEnergyExpenditure(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), CreatePaths(), CROSS_SLOPE, and DestroyPath().
TEST() [78/79]
CInterfaceTests::TEST (C_Pathfinder , DestroyPath)
[snippet_pathfinder_C_DestroyPath]
[snippet_pathfinder_C_DestroyPath]
Definition at line 940 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), CreatePath(), and DestroyPath().
TEST() [79/79]
CInterfaceTests::TEST (C_Pathfinder , GetPathInfo)
[snippet_pathfinder_C_GetPathInfo]
[snippet_pathfinder_C_GetPathInfo]
Definition at line 907 of file PathFinding.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::Pathfinding::CreateBoostGraph(), CreatePath(), DestroyPath(), and GetPathInfo().
Variable Documentation
mesh_id
const int CInterfaceTests::mesh_id = 0
Definition at line 780 of file OBJLoader.cpp.
Referenced by HF::RayTracer::RayRequest::didHit(), HF::RayTracer::DidIntersect(), HF::RayTracer::EmbreeRayTracer::Intersect(), HF::RayTracer::NanoRTRayTracer::Occluded(), HF::RayTracer::EmbreeRayTracer::Occluded(), HF::RayTracer::NanoRTRayTracer::PointIntersection(), HF::RayTracer::EmbreeRayTracer::PointIntersection(), HF::RayTracer::EmbreeRayTracer::PointIntersections(), TEST(), and TEST().
mesh_indices
int CInterfaceTests::mesh_indices[] = { 0, 1, 2 }
Definition at line 774 of file OBJLoader.cpp.
Referenced by GetVertsAndTris(), and TEST().
mesh_name
std::string CInterfaceTests::mesh_name = `This mesh`
Definition at line 779 of file OBJLoader.cpp.
Referenced by StoreMesh(), TEST(), and TEST().
mesh_num_indices
const int CInterfaceTests::mesh_num_indices = 3
Definition at line 775 of file OBJLoader.cpp.
Referenced by TEST().
mesh_num_vertices
const int CInterfaceTests::mesh_num_vertices = 9
Definition at line 777 of file OBJLoader.cpp.
Referenced by TEST().
mesh_vertices
float CInterfaceTests::mesh_vertices[] = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 }
Definition at line 776 of file OBJLoader.cpp.
Referenced by GetVertsAndTris(), and TEST().