GraphExampleTests Namespace Reference
The following are tests for the code samples for HF::SpatialStructures::Graph.
Namespaces
 ConstantsExampleTests
The following are tests for the code samples for HF::SpatialStructures::Constants.
Functions
TEST (_csrptrs, AreValid)
TEST (_graph, ParamConstructor)
TEST (_graph, NoArgConstructor)
TEST (_graph, HasEdge_Array)
TEST (_graph, HasEdge_Node)
TEST (_graph, HasEdge_Int)
TEST (_graph, Nodes)
TEST (_graph, GetUndirectedEdges)
TEST (_graph, GetEdges)
TEST (_graph, AggregateGraph)
TEST (_graph, OperatorIndex)
TEST (_graph, AddEdge_Node)
TEST (_graph, AddEdge_Int)
TEST (_graph, HasKey)
TEST (_graph, NodesAsFloat3)
TEST (_graph, Size)
TEST (_graph, GetID)
TEST (_graph, Compress)
TEST (_graph, GetCSRPointers)
TEST (_graph, NodeFromID)
TEST (_graph, Clear)
TEST (_graph, AddNodeAttribute)
TEST (_graph, AddNodeAttributes)
TEST (_graph, GetNodeAttributes)
TEST (_graph, ClearNodeAttributes)
TEST (_graph, GetEdgesCostName)
Detailed Description
The following are tests for the code samples for HF::SpatialStructures::Graph.
Function Documentation
TEST() [1/26]
GraphExampleTests::TEST (_csrptrs , AreValid)
Definition at line 1268 of file SpatialStructures.cpp.
References HF::SpatialStructures::CSRPtrs::AreValid().
TEST() [2/26]
GraphExampleTests::TEST (_graph , AddEdge_Int)
Definition at line 1579 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), and HF::SpatialStructures::Graph::Compress().
TEST() [3/26]
GraphExampleTests::TEST (_graph , AddEdge_Node)
Definition at line 1553 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge().
TEST() [4/26]
GraphExampleTests::TEST (_graph , AddNodeAttribute)
Definition at line 1864 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddNodeAttribute(), HF::SpatialStructures::Graph::GetNodeAttributes(), and HF::SpatialStructures::Graph::size().
TEST() [5/26]
GraphExampleTests::TEST (_graph , AddNodeAttributes)
Definition at line 1882 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddNodeAttributes(), HF::SpatialStructures::Graph::GetNodeAttributes(), and HF::SpatialStructures::Graph::size().
TEST() [6/26]
GraphExampleTests::TEST (_graph , AggregateGraph)
Definition at line 1487 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::AggregateGraph(), and HF::SpatialStructures::AVERAGE.
TEST() [7/26]
GraphExampleTests::TEST (_graph , Clear)
Definition at line 1821 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::Clear(), and HF::SpatialStructures::Graph::NodesAsFloat3().
TEST() [8/26]
GraphExampleTests::TEST (_graph , ClearNodeAttributes)
Definition at line 1934 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddNodeAttribute(), HF::SpatialStructures::Graph::ClearNodeAttributes(), and HF::SpatialStructures::Graph::GetNodeAttributes().
TEST() [9/26]
GraphExampleTests::TEST (_graph , Compress)
Definition at line 1737 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), and HF::SpatialStructures::Graph::Compress().
TEST() [10/26]
GraphExampleTests::TEST (_graph , GetCSRPointers)
Definition at line 1764 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), and HF::SpatialStructures::Graph::GetCSRPointers().
TEST() [11/26]
GraphExampleTests::TEST (_graph , GetEdges)
Definition at line 1444 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::GetEdges().
TEST() [12/26]
GraphExampleTests::TEST (_graph , GetEdgesCostName)
TODO test std::vector<EdgeSet> Graph::GetEdges(const string& cost_name);
Requires methods from #24, Multiple Costs for the Graph in order to properly test this.
(i.e. Adding edges to a graph with a desired cost type)
Definition at line 1958 of file SpatialStructures.cpp.
TEST() [13/26]
GraphExampleTests::TEST (_graph , GetID)
Definition at line 1698 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::getID(), HF::SpatialStructures::Graph::hasKey(), and HF::SpatialStructures::Graph::Nodes().
TEST() [14/26]
GraphExampleTests::TEST (_graph , GetNodeAttributes)
Definition at line 1900 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AddNodeAttribute(), HF::SpatialStructures::Graph::GetNodeAttributes(), and HF::SpatialStructures::Graph::size().
TEST() [15/26]
GraphExampleTests::TEST (_graph , GetUndirectedEdges)
Definition at line 1403 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::GetUndirectedEdges(), and HF::SpatialStructures::Graph::Nodes().
TEST() [16/26]
GraphExampleTests::TEST (_graph , HasEdge_Array)
Definition at line 1307 of file SpatialStructures.cpp.
References HF::SpatialStructures::Node::getArray(), and HF::SpatialStructures::Graph::HasEdge().
TEST() [17/26]
GraphExampleTests::TEST (_graph , HasEdge_Int)
Definition at line 1355 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::HasEdge().
TEST() [18/26]
GraphExampleTests::TEST (_graph , HasEdge_Node)
Definition at line 1333 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::HasEdge().
TEST() [19/26]
GraphExampleTests::TEST (_graph , HasKey)
Definition at line 1605 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::hasKey(), and HF::SpatialStructures::Graph::Nodes().
TEST() [20/26]
GraphExampleTests::TEST (_graph , NoArgConstructor)
Definition at line 1302 of file SpatialStructures.cpp.
TEST() [21/26]
GraphExampleTests::TEST (_graph , NodeFromID)
Definition at line 1793 of file SpatialStructures.cpp.
References HF::SpatialStructures::Node::id, and HF::SpatialStructures::Graph::NodeFromID().
TEST() [22/26]
GraphExampleTests::TEST (_graph , Nodes)
Definition at line 1377 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::Nodes().
TEST() [23/26]
GraphExampleTests::TEST (_graph , NodesAsFloat3)
Definition at line 1644 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::Nodes(), and HF::SpatialStructures::Graph::NodesAsFloat3().
TEST() [24/26]
GraphExampleTests::TEST (_graph , OperatorIndex)
Definition at line 1517 of file SpatialStructures.cpp.
References HF::SpatialStructures::Node::getArray(), and HF::SpatialStructures::Graph::Nodes().
TEST() [25/26]
GraphExampleTests::TEST (_graph , ParamConstructor)
Definition at line 1285 of file SpatialStructures.cpp.
TEST() [26/26]
GraphExampleTests::TEST (_graph , Size)
Definition at line 1676 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::size().