C_Interface Namespace Reference
Functions
MeshInfo< float > * ConstructExamplePlane ()
EmbreeRayTracer * ConstructTestRaytracer ()
TEST (C_EmbreeRayTracer, CreateRayTracer)
TEST (C_EmbreeRayTracer, AddMesh)
TEST (C_EmbreeRayTracer, NewMeshesCanBeIntersected)
TEST (C_EmbreeRayTracer, ConstructionWithMultipleMeshes)
TEST (C_EmbreeRayTracer, AdditionWithMultipleMeshes)
Function Documentation
ConstructExamplePlane()
MeshInfo<float>* C_Interface::ConstructExamplePlane ()
Definition at line 961 of file embree_raytracer.cpp.
References HF::Exceptions::OK, and StoreMesh().
Referenced by ConstructTestRaytracer(), and TEST().
ConstructTestRaytracer()
EmbreeRayTracer* C_Interface::ConstructTestRaytracer ()
Definition at line 988 of file embree_raytracer.cpp.
References ConstructExamplePlane(), CreateRaytracer(), DestroyMeshInfo(), and HF::Exceptions::OK.
Referenced by TEST().
TEST() [1/5]
C_Interface::TEST (C_EmbreeRayTracer , AdditionWithMultipleMeshes)
Definition at line 1088 of file embree_raytracer.cpp.
References AddMeshes(), HF::Geometry::BY_GROUP, ConstructTestRaytracer(), DestroyMeshInfo(), DestroyRayTracer(), FireRay(), and LoadOBJ().
TEST() [2/5]
C_Interface::TEST (C_EmbreeRayTracer , AddMesh)
Definition at line 1012 of file embree_raytracer.cpp.
References AddMesh(), ConstructExamplePlane(), ConstructTestRaytracer(), DestroyMeshInfo(), DestroyRayTracer(), and HF::Exceptions::OK.
TEST() [3/5]
C_Interface::TEST (C_EmbreeRayTracer , ConstructionWithMultipleMeshes)
Definition at line 1063 of file embree_raytracer.cpp.
References HF::Geometry::BY_GROUP, CreateRaytracerMultiMesh(), DestroyMeshInfo(), DestroyRayTracer(), FireRay(), and LoadOBJ().
TEST() [4/5]
C_Interface::TEST (C_EmbreeRayTracer , CreateRayTracer)
Definition at line 1003 of file embree_raytracer.cpp.
References ConstructTestRaytracer(), and DestroyRayTracer().
TEST() [5/5]
C_Interface::TEST (C_EmbreeRayTracer , NewMeshesCanBeIntersected)
Definition at line 1034 of file embree_raytracer.cpp.
References AddMesh(), ConstructExamplePlane(), ConstructTestRaytracer(), DestroyMeshInfo(), DestroyRayTracer(), and FireOcclusionRays().