GraphTests Namespace Reference
Functions
TEST (_Graph, Creation)
TEST (_Graph, AddNodeTest)
TEST (_Graph, HasKeyFailTest)
TEST (_Graph, GetUndirectedEdges)
TEST (_Graph, GetUndirectedEdgesMulti)
TEST (_Graph, HasEdgeTrue)
TEST (_Graph, HasEdgeFalse)
TEST (_Graph, HasEdgeMulti)
Graph CreateTestAggregateGraph ()
TEST (_Graph, AggregateCosts_Sum)
TEST (_Graph, AggregateCosts_Average)
TEST (_Graph, AggregateCosts_Count)
TEST (_Graph, AggregateCosts_Undirected_Sum)
TEST (_Graph, AggregateCosts_Undirected_Average)
TEST (_Graph, AggregateCosts_Undirected_Count)
TEST (_Graph, AggregateCostsMulti)
TEST (_Graph, GetCostTypes)
TEST (_Graph, SizeEqualsNumberOfNodes)
TEST (_Graph, SizeEqualsNumberOfInts)
TEST (_Graph, GroupInsert)
bool Contains (const std::vector< int > &domain, int target)
TEST (_Graph, GetEdges)
Function Documentation
Contains()
bool GraphTests::Contains (const std::vector< int > & domain, int target)
Definition at line 302 of file SpatialStructures.cpp.
Referenced by TEST().
CreateTestAggregateGraph()
Graph GraphTests::CreateTestAggregateGraph () [inline]
Definition at line 112 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), and HF::SpatialStructures::Graph::Compress().
Referenced by TEST().
TEST() [1/20]
GraphTests::TEST (_Graph , AddNodeTest)
Definition at line 22 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), and HF::SpatialStructures::Graph::hasKey().
TEST() [2/20]
GraphTests::TEST (_Graph , AggregateCosts_Average)
Definition at line 138 of file SpatialStructures.cpp.
References HF::SpatialStructures::AVERAGE, and CreateTestAggregateGraph().
TEST() [3/20]
GraphTests::TEST (_Graph , AggregateCosts_Count)
Definition at line 148 of file SpatialStructures.cpp.
References HF::SpatialStructures::COUNT, and CreateTestAggregateGraph().
TEST() [4/20]
GraphTests::TEST (_Graph , AggregateCosts_Sum)
Definition at line 127 of file SpatialStructures.cpp.
References CreateTestAggregateGraph(), and HF::SpatialStructures::SUM.
TEST() [5/20]
GraphTests::TEST (_Graph , AggregateCosts_Undirected_Average)
Definition at line 169 of file SpatialStructures.cpp.
References HF::SpatialStructures::AVERAGE, and CreateTestAggregateGraph().
TEST() [6/20]
GraphTests::TEST (_Graph , AggregateCosts_Undirected_Count)
Definition at line 179 of file SpatialStructures.cpp.
References HF::SpatialStructures::COUNT, and CreateTestAggregateGraph().
TEST() [7/20]
GraphTests::TEST (_Graph , AggregateCosts_Undirected_Sum)
Definition at line 158 of file SpatialStructures.cpp.
References CreateTestAggregateGraph(), and HF::SpatialStructures::SUM.
TEST() [8/20]
GraphTests::TEST (_Graph , AggregateCostsMulti)
Definition at line 188 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::AggregateGraph(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::SUM.
TEST() [9/20]
GraphTests::TEST (_Graph , Creation)
Definition at line 17 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::size().
TEST() [10/20]
GraphTests::TEST (_Graph , GetCostTypes)
Definition at line 202 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetCostTypes().
TEST() [11/20]
GraphTests::TEST (_Graph , GetEdges)
Definition at line 311 of file SpatialStructures.cpp.
References HF::SpatialStructures::IntEdge::child, Contains(), and HF::SpatialStructures::Graph::GetEdges().
TEST() [12/20]
GraphTests::TEST (_Graph , GetUndirectedEdges)
Definition at line 44 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetUndirectedEdges().
TEST() [13/20]
GraphTests::TEST (_Graph , GetUndirectedEdgesMulti)
Definition at line 57 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::GetUndirectedEdges().
TEST() [14/20]
GraphTests::TEST (_Graph , GroupInsert)
Definition at line 254 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::HasEdge(), and HF::SpatialStructures::Graph::hasKey().
TEST() [15/20]
GraphTests::TEST (_Graph , HasEdgeFalse)
Definition at line 85 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::HasEdge().
TEST() [16/20]
GraphTests::TEST (_Graph , HasEdgeMulti)
Definition at line 96 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::HasEdge().
TEST() [17/20]
GraphTests::TEST (_Graph , HasEdgeTrue)
Definition at line 74 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::HasEdge().
TEST() [18/20]
GraphTests::TEST (_Graph , HasKeyFailTest)
Definition at line 31 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), HF::SpatialStructures::Graph::hasKey(), and HF::SpatialStructures::Graph::size().
TEST() [19/20]
GraphTests::TEST (_Graph , SizeEqualsNumberOfInts)
Definition at line 243 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Compress(), and HF::SpatialStructures::Graph::size().
TEST() [20/20]
GraphTests::TEST (_Graph , SizeEqualsNumberOfNodes)
Definition at line 232 of file SpatialStructures.cpp.
References HF::SpatialStructures::Graph::addEdge(), HF::SpatialStructures::Graph::Nodes(), and HF::SpatialStructures::Graph::size().