NodeExampleTests Namespace Reference
The following are tests for the code samples for HF::SpatialStructures::Node.
Functions
TEST (_Node, DefaultConstructor)
TEST (_Node, ParamConstructorNoID)
TEST (_Node, ParamConstructorArray)
TEST (_node, ParamConstructorArrayTypeID)
TEST (_node, DistanceTo)
TEST (_node, AngleTo)
TEST (_node, DirectionTo)
TEST (_node, GetArray)
TEST (_node, OperatorIndexByRef)
TEST (_node, OperatorIndexByVal)
TEST (_node, OperatorEquality)
TEST (_node, OperatorAssignment)
TEST (_node, OperatorNEquality)
TEST (_node, OperatorMinus)
TEST (_node, OperatorPlus)
TEST (_node, OperatorMultiply)
TEST (_node, OperatorLessThanConst)
TEST (_node, OperatorLessThan)
TEST (_node, OperatorGreaterThanConst)
Detailed Description
The following are tests for the code samples for HF::SpatialStructures::Node.
Function Documentation
TEST() [1/19]
NodeExampleTests::TEST (_node , AngleTo)
TODO code sample: line 40 of node.cpp - 'This needs an actual angle formula'
Definition at line 828 of file SpatialStructures.cpp.
TEST() [2/19]
NodeExampleTests::TEST (_Node , DefaultConstructor)
Definition at line 796 of file SpatialStructures.cpp.
TEST() [3/19]
NodeExampleTests::TEST (_node , DirectionTo)
Definition at line 832 of file SpatialStructures.cpp.
References HF::SpatialStructures::Node::directionTo().
TEST() [4/19]
NodeExampleTests::TEST (_node , DistanceTo)
Definition at line 821 of file SpatialStructures.cpp.
References HF::SpatialStructures::Node::distanceTo(), and HF::SpatialStructures::CostAlgorithms::euclidean_distance().
TEST() [5/19]
NodeExampleTests::TEST (_node , GetArray)
Definition at line 839 of file SpatialStructures.cpp.
References HF::SpatialStructures::Node::getArray(), and HF::SpatialStructures::Node::x.
TEST() [6/19]
NodeExampleTests::TEST (_node , OperatorAssignment)
Definition at line 899 of file SpatialStructures.cpp.
TEST() [7/19]
NodeExampleTests::TEST (_node , OperatorEquality)
Definition at line 882 of file SpatialStructures.cpp.
TEST() [8/19]
NodeExampleTests::TEST (_node , OperatorGreaterThanConst)
Definition at line 1002 of file SpatialStructures.cpp.
TEST() [9/19]
NodeExampleTests::TEST (_node , OperatorIndexByRef)
Definition at line 858 of file SpatialStructures.cpp.
TEST() [10/19]
NodeExampleTests::TEST (_node , OperatorIndexByVal)
Definition at line 870 of file SpatialStructures.cpp.
TEST() [11/19]
NodeExampleTests::TEST (_node , OperatorLessThan)
Definition at line 980 of file SpatialStructures.cpp.
TEST() [12/19]
NodeExampleTests::TEST (_node , OperatorLessThanConst)
Definition at line 967 of file SpatialStructures.cpp.
TEST() [13/19]
NodeExampleTests::TEST (_node , OperatorMinus)
Definition at line 930 of file SpatialStructures.cpp.
TEST() [14/19]
NodeExampleTests::TEST (_node , OperatorMultiply)
Definition at line 955 of file SpatialStructures.cpp.
TEST() [15/19]
NodeExampleTests::TEST (_node , OperatorNEquality)
Definition at line 911 of file SpatialStructures.cpp.
TEST() [16/19]
NodeExampleTests::TEST (_node , OperatorPlus)
Definition at line 943 of file SpatialStructures.cpp.
TEST() [17/19]
NodeExampleTests::TEST (_Node , ParamConstructorArray)
Definition at line 811 of file SpatialStructures.cpp.
TEST() [18/19]
NodeExampleTests::TEST (_node , ParamConstructorArrayTypeID)
Definition at line 816 of file SpatialStructures.cpp.
References HF::SpatialStructures::GRAPH.
TEST() [19/19]
NodeExampleTests::TEST (_Node , ParamConstructorNoID)
Definition at line 807 of file SpatialStructures.cpp.