PathExampleTests Namespace Reference
The following are tests for the code samples for HF::SpatialStructures::Path.
Functions
TEST (_pathMember, OperatorEquality)
TEST (_pathMember, OperatorNEquality)
TEST (_path, NoArgConstructor)
TEST (_path, ParamConstructor)
TEST (_path, AddNode)
TEST (_path, Empty)
TEST (_path, Size)
TEST (_path, Reverse)
TEST (_path, OperatorEquality)
TEST (_path, OperatorIndex)
TEST (_path, GetPMPointer)
TEST (_path, OperatorLessThanLessThan)
Detailed Description
The following are tests for the code samples for HF::SpatialStructures::Path.
Function Documentation
TEST() [1/12]
PathExampleTests::TEST (_path , AddNode)
Definition at line 1090 of file SpatialStructures.cpp.
References HF::SpatialStructures::Path::AddNode().
TEST() [2/12]
PathExampleTests::TEST (_path , Empty)
Definition at line 1110 of file SpatialStructures.cpp.
References HF::SpatialStructures::Path::empty().
TEST() [3/12]
PathExampleTests::TEST (_path , GetPMPointer)
Definition at line 1220 of file SpatialStructures.cpp.
References HF::SpatialStructures::PathMember::cost, HF::SpatialStructures::Path::GetPMPointer(), HF::SpatialStructures::PathMember::node, and HF::SpatialStructures::Path::size().
TEST() [4/12]
PathExampleTests::TEST (_path , NoArgConstructor)
Definition at line 1072 of file SpatialStructures.cpp.
TEST() [5/12]
PathExampleTests::TEST (_path , OperatorEquality)
Definition at line 1159 of file SpatialStructures.cpp.
TEST() [6/12]
PathExampleTests::TEST (_path , OperatorIndex)
Definition at line 1200 of file SpatialStructures.cpp.
TEST() [7/12]
PathExampleTests::TEST (_path , OperatorLessThanLessThan)
Definition at line 1245 of file SpatialStructures.cpp.
TEST() [8/12]
PathExampleTests::TEST (_path , ParamConstructor)
Definition at line 1076 of file SpatialStructures.cpp.
TEST() [9/12]
PathExampleTests::TEST (_path , Reverse)
Definition at line 1140 of file SpatialStructures.cpp.
References HF::SpatialStructures::Path::AddNode(), and HF::SpatialStructures::Path::Reverse().
TEST() [10/12]
PathExampleTests::TEST (_path , Size)
Definition at line 1122 of file SpatialStructures.cpp.
References HF::SpatialStructures::Path::AddNode(), and HF::SpatialStructures::Path::size().
TEST() [11/12]
PathExampleTests::TEST (_pathMember , OperatorEquality)
Definition at line 1035 of file SpatialStructures.cpp.
TEST() [12/12]
PathExampleTests::TEST (_pathMember , OperatorNEquality)
Definition at line 1053 of file SpatialStructures.cpp.