nanort::real3< T > Class Template Reference
#include <nanort.h>
Public Member Functions
real3 ()
real3 (T x)
real3 (T xx, T yy, T zz)
real3 (const T *p)
T x () const
T y () const
T z () const
real3 operator* (T f) const
real3 operator- (const real3 &f2) const
real3 operator* (const real3 &f2) const
real3 operator+ (const real3 &f2) const
real3 & operator+= (const real3 &f2)
real3 operator/ (const real3 &f2) const
real3 operator- () const
T operator[] (int i) const
T & operator[] (int i)
Public Attributes
T v [3]
Detailed Description
template<typename T = float>
class nanort::real3< T >
Definition at line 322 of file nanort.h.
Constructor & Destructor Documentation
real3() [1/4]
template<typename T = float>
nanort::real3< T >::real3 () [inline]
Definition at line 324 of file nanort.h.
Referenced by nanort::real3< T >::operator*(), nanort::real3< T >::operator+(), nanort::real3< T >::operator-(), and nanort::real3< T >::operator/().
real3() [2/4]
template<typename T = float>
nanort::real3< T >::real3 (T x) [inline]
Definition at line 325 of file nanort.h.
References nanort::real3< T >::v, and nanort::real3< T >::x().
real3() [3/4]
template<typename T = float>
nanort::real3< T >::real3 (T xx, T yy, T zz) [inline]
Definition at line 330 of file nanort.h.
References nanort::real3< T >::v.
real3() [4/4]
template<typename T = float>
nanort::real3< T >::real3 (const T * p) [inline], [explicit]
Definition at line 335 of file nanort.h.
References nanort::real3< T >::v.
Member Function Documentation
operator*() [1/2]
template<typename T = float>
real3 nanort::real3< T >::operator* (const real3< T > & f2) const [inline]
Definition at line 349 of file nanort.h.
References nanort::real3< T >::real3(), nanort::real3< T >::x(), nanort::real3< T >::y(), and nanort::real3< T >::z().
operator*() [2/2]
template<typename T = float>
real3 nanort::real3< T >::operator* (T f) const [inline]
Definition at line 345 of file nanort.h.
References nanort::real3< T >::real3(), nanort::real3< T >::x(), nanort::real3< T >::y(), and nanort::real3< T >::z().
operator+()
template<typename T = float>
real3 nanort::real3< T >::operator+ (const real3< T > & f2) const [inline]
Definition at line 352 of file nanort.h.
References nanort::real3< T >::real3(), nanort::real3< T >::x(), nanort::real3< T >::y(), and nanort::real3< T >::z().
operator+=()
template<typename T = float>
real3 & nanort::real3< T >::operator+= (const real3< T > & f2) [inline]
Definition at line 355 of file nanort.h.
References nanort::real3< T >::v, nanort::real3< T >::x(), nanort::real3< T >::y(), and nanort::real3< T >::z().
operator-() [1/2]
template<typename T = float>
real3 nanort::real3< T >::operator- () const [inline]
Definition at line 364 of file nanort.h.
References nanort::real3< T >::real3(), nanort::real3< T >::x(), nanort::real3< T >::y(), and nanort::real3< T >::z().
operator-() [2/2]
template<typename T = float>
real3 nanort::real3< T >::operator- (const real3< T > & f2) const [inline]
Definition at line 346 of file nanort.h.
References nanort::real3< T >::real3(), nanort::real3< T >::x(), nanort::real3< T >::y(), and nanort::real3< T >::z().
operator/()
template<typename T = float>
real3 nanort::real3< T >::operator/ (const real3< T > & f2) const [inline]
Definition at line 361 of file nanort.h.
References nanort::real3< T >::real3(), nanort::real3< T >::x(), nanort::real3< T >::y(), and nanort::real3< T >::z().
operator[]() [1/2]
template<typename T = float>
T & nanort::real3< T >::operator[] (int i) [inline]
Definition at line 366 of file nanort.h.
References nanort::real3< T >::v.
operator[]() [2/2]
template<typename T = float>
T nanort::real3< T >::operator[] (int i) const [inline]
Definition at line 365 of file nanort.h.
References nanort::real3< T >::v.
x()
template<typename T = float>
T nanort::real3< T >::x () const [inline]
Definition at line 341 of file nanort.h.
References nanort::real3< T >::v.
Referenced by nanort::real3< T >::real3(), nanort::real3< T >::operator*(), nanort::operator*(), nanort::real3< T >::operator+(), nanort::real3< T >::operator+=(), nanort::real3< T >::operator-(), nanort::real3< T >::operator/(), nanort::vlength(), and nanort::vneg().
y()
template<typename T = float>
T nanort::real3< T >::y () const [inline]
Definition at line 342 of file nanort.h.
References nanort::real3< T >::v.
Referenced by nanort::real3< T >::operator*(), nanort::operator*(), nanort::real3< T >::operator+(), nanort::real3< T >::operator+=(), nanort::real3< T >::operator-(), nanort::real3< T >::operator/(), nanort::vlength(), and nanort::vneg().
z()
template<typename T = float>
T nanort::real3< T >::z () const [inline]
Definition at line 343 of file nanort.h.
References nanort::real3< T >::v.
Referenced by nanort::real3< T >::operator*(), nanort::operator*(), nanort::real3< T >::operator+(), nanort::real3< T >::operator+=(), nanort::real3< T >::operator-(), nanort::real3< T >::operator/(), nanort::vlength(), and nanort::vneg().
Member Data Documentation
v
template<typename T = float>
T nanort::real3< T >::v[3]
Definition at line 368 of file nanort.h.
Referenced by nanort::real3< T >::real3(), nanort::real3< T >::operator+=(), nanort::real3< T >::operator[](), nanort::vnormalize(), nanort::real3< T >::x(), nanort::real3< T >::y(), and nanort::real3< T >::z().
The documentation for this class was generated from the following file:
Cpp/raytracer/src/nanort.h