nanort::StackVector< T, stack_capacity > Class Template Reference
#include <nanort.h>
Public Member Functions
StackVector ()
StackVector (const StackVector< T, stack_capacity > &other)
StackVector< T, stack_capacity > & operator= (const StackVector< T, stack_capacity > &other)
T & operator[] (size_t i)
const T & operator[] (size_t i) const
Additional Inherited Members
Detailed Description
template<typename T, size_t stack_capacity>
class nanort::StackVector< T, stack_capacity >
Definition at line 287 of file nanort.h.
Constructor & Destructor Documentation
StackVector() [1/2]
template<typename T , size_t stack_capacity>
nanort::StackVector< T, stack_capacity >::StackVector () [inline]
Definition at line 291 of file nanort.h.
StackVector() [2/2]
template<typename T , size_t stack_capacity>
nanort::StackVector< T, stack_capacity >::StackVector (const StackVector< T, stack_capacity > & other) [inline]
Definition at line 299 of file nanort.h.
References nanort::StackContainer< std::vector< T, StackAllocator< T, stack_capacity > >, stack_capacity >::container().
Member Function Documentation
operator=()
template<typename T , size_t stack_capacity>
StackVector< T, stack_capacity > & nanort::StackVector< T, stack_capacity >::operator= (const StackVector< T, stack_capacity > & other) [inline]
Definition at line 305 of file nanort.h.
References nanort::StackContainer< std::vector< T, StackAllocator< T, stack_capacity > >, stack_capacity >::container().
operator[]() [1/2]
template<typename T , size_t stack_capacity>
T & nanort::StackVector< T, stack_capacity >::operator[] (size_t i) [inline]
Definition at line 313 of file nanort.h.
References nanort::StackContainer< std::vector< T, StackAllocator< T, stack_capacity > >, stack_capacity >::container().
operator[]() [2/2]
template<typename T , size_t stack_capacity>
const T & nanort::StackVector< T, stack_capacity >::operator[] (size_t i) const [inline]
Definition at line 314 of file nanort.h.
References nanort::StackContainer< std::vector< T, StackAllocator< T, stack_capacity > >, stack_capacity >::container().
The documentation for this class was generated from the following file:
Cpp/raytracer/src/nanort.h