HF::RayTracer::MultiRT Struct Reference
#include <MultiRT.h>
Public Types
enum RT_Type { NONE
, EMBREE
, NANO_RT
 }
using real_t = double
using real3 = std::array< real_t, 3 >
Public Member Functions
MultiRT ()
MultiRT (HF::RayTracer::EmbreeRayTracer *ert)
MultiRT (HF::RayTracer::NanoRTRayTracer *nrt)
bool Occluded (const real3 &origin, const real3 &direction, real_t distance)
HitStruct< real_t > Intersect (const real3 &origin, const real3 &direction)
Public Attributes
void * RayTracer
RT_Type type = RT_Type::NONE
Detailed Description
Definition at line 10 of file MultiRT.h.
Member Typedef Documentation
real3
using HF::RayTracer::MultiRT::real3 = std::array<real_t, 3>
Definition at line 12 of file MultiRT.h.
real_t
using HF::RayTracer::MultiRT::real_t = double
Definition at line 11 of file MultiRT.h.
Member Enumeration Documentation
RT_Type
enum HF::RayTracer::MultiRT::RT_Type
Enumerator
NONE
EMBREE
NANO_RT
Definition at line 14 of file MultiRT.h.
Constructor & Destructor Documentation
MultiRT() [1/3]
HF::RayTracer::MultiRT::MultiRT () [inline]
Definition at line 23 of file MultiRT.h.
MultiRT() [2/3]
HF::RayTracer::MultiRT::MultiRT (HF::RayTracer::EmbreeRayTracer * ert)
Definition at line 28 of file MultiRT.cpp.
References EMBREE, RayTracer, and type.
MultiRT() [3/3]
HF::RayTracer::MultiRT::MultiRT (HF::RayTracer::NanoRTRayTracer * nrt)
Definition at line 34 of file MultiRT.cpp.
References NANO_RT, RayTracer, and type.
Member Function Documentation
Intersect()
HitStruct< MultiRT::real_t > HF::RayTracer::MultiRT::Intersect (const real3 & origin, const real3 & direction)
Definition at line 40 of file MultiRT.cpp.
References EMBREE, Intersect(), NANO_RT, RayTracer, and type.
Referenced by HF::GraphGenerator::CheckRay(), and Intersect().
Occluded()
bool HF::RayTracer::MultiRT::Occluded (const real3 & origin, const real3 & direction, MultiRT::real_t distance)
Definition at line 49 of file MultiRT.cpp.
References EMBREE, NANO_RT, Occluded(), RayTracer, and type.
Referenced by Occluded(), and HF::GraphGenerator::OcclusionCheck().
Member Data Documentation
RayTracer
void* HF::RayTracer::MultiRT::RayTracer
Definition at line 20 of file MultiRT.h.
Referenced by MultiRT(), Intersect(), and Occluded().
type
RT_Type HF::RayTracer::MultiRT::type = RT_Type::NONE
Definition at line 21 of file MultiRT.h.
Referenced by MultiRT(), Intersect(), and Occluded().
The documentation for this struct was generated from the following files:
Cpp/raytracer/src/MultiRT.h
Cpp/raytracer/src/MultiRT.cpp