nlohmann::detail::json_sax_dom_parser< BasicJsonType > Class Template Reference
SAX implementation to create a JSON value from SAX events.
#include <json.hpp>
Public Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using binary_t = typename BasicJsonType::binary_t
Public Member Functions
json_sax_dom_parser (BasicJsonType &r, const bool allow_exceptions_=true)
json_sax_dom_parser (const json_sax_dom_parser &)=delete
json_sax_dom_parser (json_sax_dom_parser &&)=default
json_sax_dom_parser & operator= (const json_sax_dom_parser &)=delete
json_sax_dom_parser & operator= (json_sax_dom_parser &&)=default
~json_sax_dom_parser ()=default
bool null ()
bool boolean (bool val)
bool number_integer (number_integer_t val)
bool number_unsigned (number_unsigned_t val)
bool number_float (number_float_t val, const string_t &)
bool string (string_t &val)
bool binary (binary_t &val)
bool start_object (std::size_t len)
bool key (string_t &val)
bool end_object ()
bool start_array (std::size_t len)
bool end_array ()
template<class Exception >
bool parse_error (std::size_t, const std::string &, const Exception &ex)
constexpr bool is_errored () const
Private Member Functions
template<typename Value >
JSON_HEDLEY_RETURNS_NON_NULL BasicJsonType * handle_value (Value &&v)
Private Attributes
BasicJsonType & root
the parsed JSON value
std::vector< BasicJsonType * > ref_stack {}
stack to model hierarchy of values
BasicJsonType * object_element = nullptr
helper to hold the reference for the next object element
bool errored = false
whether a syntax error occurred
const bool allow_exceptions = true
whether to throw exceptions in case of errors
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::json_sax_dom_parser< BasicJsonType >
SAX implementation to create a JSON value from SAX events.
This class implements the json_sax interface and processes the SAX events to create a JSON value which makes it basically a DOM parser. The structure or hierarchy of the JSON value is managed by the stack ref_stack which contains a pointer to the respective array or object for each recursion depth.
After successful parsing, the value that is passed by reference to the constructor contains the parsed value.
Template Parameters
BasicJsonType the JSON type
Definition at line 5328 of file json.hpp.
Member Typedef Documentation
binary_t
template<typename BasicJsonType >
using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::binary_t = typename BasicJsonType::binary_t
Definition at line 5335 of file json.hpp.
number_float_t
template<typename BasicJsonType >
using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t
Definition at line 5333 of file json.hpp.
number_integer_t
template<typename BasicJsonType >
using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t
Definition at line 5331 of file json.hpp.
number_unsigned_t
template<typename BasicJsonType >
using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t
Definition at line 5332 of file json.hpp.
string_t
template<typename BasicJsonType >
using nlohmann::detail::json_sax_dom_parser< BasicJsonType >::string_t = typename BasicJsonType::string_t
Definition at line 5334 of file json.hpp.
Constructor & Destructor Documentation
json_sax_dom_parser() [1/3]
template<typename BasicJsonType >
nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (BasicJsonType & r, const bool allow_exceptions_ = true) [inline], [explicit]
Parameters
 in,out r reference to a JSON value that is manipulated while parsing
 in allow_exceptions_ whether parse errors yield exceptions
Definition at line 5342 of file json.hpp.
json_sax_dom_parser() [2/3]
template<typename BasicJsonType >
nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (const json_sax_dom_parser< BasicJsonType > &) [delete]
json_sax_dom_parser() [3/3]
template<typename BasicJsonType >
nlohmann::detail::json_sax_dom_parser< BasicJsonType >::json_sax_dom_parser (json_sax_dom_parser< BasicJsonType > &&) [default]
 json_sax_dom_parser()
template<typename BasicJsonType >
nlohmann::detail::json_sax_dom_parser< BasicJsonType >::~json_sax_dom_parser () [default]
Member Function Documentation
binary()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::binary (binary_t & val) [inline]
Definition at line 5389 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
boolean()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::boolean (bool val) [inline]
Definition at line 5359 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
end_array()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_array () [inline]
Definition at line 5434 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
end_object()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_object () [inline]
Definition at line 5415 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
handle_value()
template<typename BasicJsonType >
template<typename Value >
JSON_HEDLEY_RETURNS_NON_NULL BasicJsonType* nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value (Value && v) [inline], [private]
Invariant
If the ref stack is empty, then the passed value will be the new root.
If the ref stack contains a value, then it is an array or an object to which we can add elements
Definition at line 5467 of file json.hpp.
References JSON_ASSERT, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::object_element, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::root.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::binary(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::boolean(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::null(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_float(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_integer(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_unsigned(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object(), and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::string().
is_errored()
template<typename BasicJsonType >
constexpr bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored () const [inline], [constexpr]
Definition at line 5453 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::errored.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse().
key()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::key (string_t & val) [inline]
Definition at line 5408 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::object_element, and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack.
null()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::null () [inline]
Definition at line 5353 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_float()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_float (number_float_t val, const string_t &) [inline]
Definition at line 5377 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_integer()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_integer (number_integer_t val) [inline]
Definition at line 5365 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
number_unsigned()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::number_unsigned (number_unsigned_t val) [inline]
Definition at line 5371 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
operator=() [1/2]
template<typename BasicJsonType >
json_sax_dom_parser& nlohmann::detail::json_sax_dom_parser< BasicJsonType >::operator= (const json_sax_dom_parser< BasicJsonType > &) [delete]
operator=() [2/2]
template<typename BasicJsonType >
json_sax_dom_parser& nlohmann::detail::json_sax_dom_parser< BasicJsonType >::operator= (json_sax_dom_parser< BasicJsonType > &&) [default]
parse_error()
template<typename BasicJsonType >
template<class Exception >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error (std::size_t , const std::string & , const Exception & ex) [inline]
Definition at line 5441 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::allow_exceptions, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::errored, and JSON_THROW.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse().
start_array()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array (std::size_t len) [inline]
Definition at line 5421 of file json.hpp.
References nlohmann::detail::out_of_range::create(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and nlohmann::to_string().
start_object()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object (std::size_t len) [inline]
Definition at line 5395 of file json.hpp.
References nlohmann::detail::out_of_range::create(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack, and nlohmann::to_string().
string()
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::string (string_t & val) [inline]
Definition at line 5383 of file json.hpp.
References nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
Member Data Documentation
allow_exceptions
template<typename BasicJsonType >
const bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::allow_exceptions = true [private]
whether to throw exceptions in case of errors
Definition at line 5498 of file json.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error().
errored
template<typename BasicJsonType >
bool nlohmann::detail::json_sax_dom_parser< BasicJsonType >::errored = false [private]
whether a syntax error occurred
Definition at line 5496 of file json.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored(), and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error().
object_element
template<typename BasicJsonType >
BasicJsonType* nlohmann::detail::json_sax_dom_parser< BasicJsonType >::object_element = nullptr [private]
helper to hold the reference for the next object element
Definition at line 5494 of file json.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::key().
ref_stack
template<typename BasicJsonType >
std::vector<BasicJsonType*> nlohmann::detail::json_sax_dom_parser< BasicJsonType >::ref_stack {} [private]
stack to model hierarchy of values
Definition at line 5492 of file json.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_array(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::end_object(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::key(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_array(), and nlohmann::detail::json_sax_dom_parser< BasicJsonType >::start_object().
root
template<typename BasicJsonType >
BasicJsonType& nlohmann::detail::json_sax_dom_parser< BasicJsonType >::root [private]
the parsed JSON value
Definition at line 5490 of file json.hpp.
Referenced by nlohmann::detail::json_sax_dom_parser< BasicJsonType >::handle_value().
The documentation for this class was generated from the following file:
Cpp/spatialstructures/src/json.hpp