nlohmann::detail::iter_impl< BasicJsonType > Class Template Reference
a template for a bidirectional iterator for the basic_json class This class implements a both iterators (iterator and const_iterator) for the basic_json class.
#include <json.hpp>
Public Types
using iterator_category = std::bidirectional_iterator_tag
The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. The C++ Standard has never required user-defined iterators to derive from std::iterator. A user-defined iterator should provide publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators.
using value_type = typename BasicJsonType::value_type
the type of the values when the iterator is dereferenced
using difference_type = typename BasicJsonType::difference_type
a type to represent differences between iterators
using pointer = typename std::conditional< std::is_const< BasicJsonType >::value, typename BasicJsonType::const_pointer, typename BasicJsonType::pointer >::type
defines a pointer to the type iterated over (value_type)
using reference = typename std::conditional< std::is_const< BasicJsonType >::value, typename BasicJsonType::const_reference, typename BasicJsonType::reference >::type
defines a reference to the type iterated over (value_type)
Public Member Functions
iter_impl ()=default
default constructor
iter_impl (pointer object) noexcept
constructor for a given JSON instance
iter_impl (const iter_impl< const BasicJsonType > &other) noexcept
const copy constructor
iter_impl & operator= (const iter_impl< const BasicJsonType > &other) noexcept
converting assignment
iter_impl (const iter_impl< typename std::remove_const< BasicJsonType >::type > &other) noexcept
converting constructor
iter_impl & operator= (const iter_impl< typename std::remove_const< BasicJsonType >::type > &other) noexcept
converting assignment
reference operator* () const
return a reference to the value pointed to by the iterator
pointer operator-> () const
dereference the iterator
iter_impl const operator++ (int)
post-increment (it++)
iter_impl & operator++ ()
pre-increment (++it)
iter_impl const operator-- (int)
post-decrement (it--)
iter_impl & operator-- ()
pre-decrement (--it)
bool operator== (const iter_impl &other) const
comparison: equal
bool operator!= (const iter_impl &other) const
comparison: not equal
bool operator< (const iter_impl &other) const
comparison: smaller
bool operator<= (const iter_impl &other) const
comparison: less than or equal
bool operator> (const iter_impl &other) const
comparison: greater than
bool operator>= (const iter_impl &other) const
comparison: greater than or equal
iter_impl & operator+= (difference_type i)
add to iterator
iter_impl & operator-= (difference_type i)
subtract from iterator
iter_impl operator+ (difference_type i) const
add to iterator
iter_impl operator- (difference_type i) const
subtract from iterator
difference_type operator- (const iter_impl &other) const
return difference
reference operator[] (difference_type n) const
access to successor
const object_t::key_type & key () const
return the key of an object iterator
reference value () const
return the value of an iterator
Private Types
using object_t = typename BasicJsonType::object_t
using array_t = typename BasicJsonType::array_t
Private Member Functions
void set_begin () noexcept
set the iterator to the first value
void set_end () noexcept
set the iterator past the last value
Private Attributes
friend BasicJsonType
friend iteration_proxy< iter_impl >
friend iteration_proxy_value< iter_impl >
pointer m_object = nullptr
associated JSON instance
internal_iterator< typename std::remove_const< BasicJsonType >::type > m_it {}
the actual iterator of the associated instance
Friends
iter_impl operator+ (difference_type i, const iter_impl &it)
addition of distance and iterator
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::iter_impl< BasicJsonType >
a template for a bidirectional iterator for the basic_json class This class implements a both iterators (iterator and const_iterator) for the basic_json class.
Note
An iterator is called initialized when a pointer to a JSON value has been set (e.g., by a constructor or a copy assignment). If the iterator is default-constructed, it is uninitialized and most methods are undefined. The library uses assertions to detect calls on uninitialized iterators.** @requirement The class satisfies the following concept requirements:
 BidirectionalIterator: The iterator that can be moved can be moved in both directions (i.e. incremented and decremented).
Since
version 1.0.0, simplified in version 2.0.9, change to bidirectional iterators in version 3.0.0 (see https://github.com/nlohmann/json/issues/593)
Definition at line 10808 of file json.hpp.
Member Typedef Documentation
array_t
template<typename BasicJsonType >
using nlohmann::detail::iter_impl< BasicJsonType >::array_t = typename BasicJsonType::array_t [private]
Definition at line 10817 of file json.hpp.
difference_type
template<typename BasicJsonType >
using nlohmann::detail::iter_impl< BasicJsonType >::difference_type = typename BasicJsonType::difference_type
a type to represent differences between iterators
Definition at line 10834 of file json.hpp.
iterator_category
template<typename BasicJsonType >
using nlohmann::detail::iter_impl< BasicJsonType >::iterator_category = std::bidirectional_iterator_tag
The std::iterator class template (used as a base class to provide typedefs) is deprecated in C++17. The C++ Standard has never required user-defined iterators to derive from std::iterator. A user-defined iterator should provide publicly accessible typedefs named iterator_category, value_type, difference_type, pointer, and reference. Note that value_type is required to be non-const, even for constant iterators.
Definition at line 10829 of file json.hpp.
object_t
template<typename BasicJsonType >
using nlohmann::detail::iter_impl< BasicJsonType >::object_t = typename BasicJsonType::object_t [private]
Definition at line 10816 of file json.hpp.
pointer
template<typename BasicJsonType >
using nlohmann::detail::iter_impl< BasicJsonType >::pointer = typename std::conditional<std::is_const<BasicJsonType>::value, typename BasicJsonType::const_pointer, typename BasicJsonType::pointer>::type
defines a pointer to the type iterated over (value_type)
Definition at line 10836 of file json.hpp.
reference
template<typename BasicJsonType >
using nlohmann::detail::iter_impl< BasicJsonType >::reference = typename std::conditional<std::is_const<BasicJsonType>::value, typename BasicJsonType::const_reference, typename BasicJsonType::reference>::type
defines a reference to the type iterated over (value_type)
Definition at line 10840 of file json.hpp.
value_type
template<typename BasicJsonType >
using nlohmann::detail::iter_impl< BasicJsonType >::value_type = typename BasicJsonType::value_type
the type of the values when the iterator is dereferenced
Definition at line 10832 of file json.hpp.
Constructor & Destructor Documentation
iter_impl() [1/4]
template<typename BasicJsonType >
iter_impl< typename std::conditional< std::is_const< BasicJsonType >::value, typename std::remove_const< BasicJsonType >::type, const BasicJsonType >::type > () [default]
default constructor
allow basic_json to access private members
Definition at line 10811 of file json.hpp.
iter_impl() [2/4]
template<typename BasicJsonType >
nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (pointer object) [inline], [explicit], [noexcept]
constructor for a given JSON instance
Parameters
 in object pointer to a JSON object for this iterator
Precondition
object != nullptr
Postcondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 10854 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, JSON_ASSERT, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
iter_impl() [3/4]
template<typename BasicJsonType >
nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (const iter_impl< const BasicJsonType > & other) [inline], [noexcept]
const copy constructor
Note
The conventional copy constructor and copy assignment are implicitly defined. Combined with the following converting constructor and assignment, they support: (1) copy from iterator to iterator, (2) copy from const iterator to const iterator, and (3) conversion from iterator to const iterator. However conversion from const iterator to iterator is not defined.
Parameters
 in other const iterator to copy from
Note
This copy constructor had to be defined explicitly to circumvent a bug occurring on msvc v19.0 compiler (VS 2015) debug build. For more information refer to: https://github.com/nlohmann/json/issues/1608
Definition at line 10896 of file json.hpp.
iter_impl() [4/4]
template<typename BasicJsonType >
nlohmann::detail::iter_impl< BasicJsonType >::iter_impl (const iter_impl< typename std::remove_const< BasicJsonType >::type > & other) [inline], [noexcept]
converting constructor
Parameters
 in other non-const iterator to copy from
Note
It is not checked whether other is initialized.
Definition at line 10918 of file json.hpp.
Member Function Documentation
key()
template<typename BasicJsonType >
const object_t::key_type & nlohmann::detail::iter_impl< BasicJsonType >::key () const [inline]
return the key of an object iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11378 of file json.hpp.
References nlohmann::detail::invalid_iterator::create(), JSON_ASSERT, JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, and nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator.
operator!=()
template<typename BasicJsonType >
bool nlohmann::detail::iter_impl< BasicJsonType >::operator!= (const iter_impl< BasicJsonType > & other) const [inline]
comparison: not equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11192 of file json.hpp.
References nlohmann::detail::iter_impl< BasicJsonType >::operator==().
operator*()
template<typename BasicJsonType >
reference nlohmann::detail::iter_impl< BasicJsonType >::operator* () const [inline]
return a reference to the value pointed to by the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11008 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::is_begin(), JSON_ASSERT, JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::value().
operator+()
template<typename BasicJsonType >
iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator+ (difference_type i) const [inline]
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11293 of file json.hpp.
operator++() [1/2]
template<typename BasicJsonType >
iter_impl & nlohmann::detail::iter_impl< BasicJsonType >::operator++ () [inline]
pre-increment (++it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11090 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, JSON_ASSERT, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator++() [2/2]
template<typename BasicJsonType >
iter_impl const nlohmann::detail::iter_impl< BasicJsonType >::operator++ (int) [inline]
post-increment (it++)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11079 of file json.hpp.
operator+=()
template<typename BasicJsonType >
iter_impl & nlohmann::detail::iter_impl< BasicJsonType >::operator+= (difference_type i) [inline]
add to iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11255 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), JSON_ASSERT, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator-=().
operator-() [1/2]
template<typename BasicJsonType >
difference_type nlohmann::detail::iter_impl< BasicJsonType >::operator- (const iter_impl< BasicJsonType > & other) const [inline]
return difference
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11326 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), JSON_ASSERT, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator-() [2/2]
template<typename BasicJsonType >
iter_impl nlohmann::detail::iter_impl< BasicJsonType >::operator- (difference_type i) const [inline]
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11315 of file json.hpp.
operator--() [1/2]
template<typename BasicJsonType >
iter_impl & nlohmann::detail::iter_impl< BasicJsonType >::operator-- () [inline]
pre-decrement (--it)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11133 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, JSON_ASSERT, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator--() [2/2]
template<typename BasicJsonType >
iter_impl const nlohmann::detail::iter_impl< BasicJsonType >::operator-- (int) [inline]
post-decrement (it--)
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11122 of file json.hpp.
operator-=()
template<typename BasicJsonType >
iter_impl & nlohmann::detail::iter_impl< BasicJsonType >::operator-= (difference_type i) [inline]
subtract from iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11284 of file json.hpp.
References nlohmann::detail::iter_impl< BasicJsonType >::operator+=().
operator->()
template<typename BasicJsonType >
pointer nlohmann::detail::iter_impl< BasicJsonType >::operator-> () const [inline]
dereference the iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11045 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::is_begin(), JSON_ASSERT, JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
operator<()
template<typename BasicJsonType >
bool nlohmann::detail::iter_impl< BasicJsonType >::operator< (const iter_impl< BasicJsonType > & other) const [inline]
comparison: smaller
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11201 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), JSON_ASSERT, JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator>=().
operator<=()
template<typename BasicJsonType >
bool nlohmann::detail::iter_impl< BasicJsonType >::operator<= (const iter_impl< BasicJsonType > & other) const [inline]
comparison: less than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11228 of file json.hpp.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator>().
operator=() [1/2]
template<typename BasicJsonType >
iter_impl & nlohmann::detail::iter_impl< BasicJsonType >::operator= (const iter_impl< const BasicJsonType > & other) [inline], [noexcept]
converting assignment
Parameters
 in other const iterator to copy from
Returns
const/non-const iterator
Note
It is not checked whether other is initialized.
Definition at line 10906 of file json.hpp.
References nlohmann::detail::iter_impl< BasicJsonType >::m_it, and nlohmann::detail::iter_impl< BasicJsonType >::m_object.
operator=() [2/2]
template<typename BasicJsonType >
iter_impl & nlohmann::detail::iter_impl< BasicJsonType >::operator= (const iter_impl< typename std::remove_const< BasicJsonType >::type > & other) [inline], [noexcept]
converting assignment
Parameters
 in other non-const iterator to copy from
Returns
const/non-const iterator
Note
It is not checked whether other is initialized.
Definition at line 10928 of file json.hpp.
References nlohmann::detail::iter_impl< BasicJsonType >::m_it, and nlohmann::detail::iter_impl< BasicJsonType >::m_object.
operator==()
template<typename BasicJsonType >
bool nlohmann::detail::iter_impl< BasicJsonType >::operator== (const iter_impl< BasicJsonType > & other) const [inline]
comparison: equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11165 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), JSON_ASSERT, JSON_HEDLEY_UNLIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::operator!=().
operator>()
template<typename BasicJsonType >
bool nlohmann::detail::iter_impl< BasicJsonType >::operator> (const iter_impl< BasicJsonType > & other) const [inline]
comparison: greater than
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11237 of file json.hpp.
References nlohmann::detail::iter_impl< BasicJsonType >::operator<=().
operator>=()
template<typename BasicJsonType >
bool nlohmann::detail::iter_impl< BasicJsonType >::operator>= (const iter_impl< BasicJsonType > & other) const [inline]
comparison: greater than or equal
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11246 of file json.hpp.
References nlohmann::detail::iter_impl< BasicJsonType >::operator<().
operator[]()
template<typename BasicJsonType >
reference nlohmann::detail::iter_impl< BasicJsonType >::operator[] (difference_type n) const [inline]
access to successor
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11347 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, nlohmann::detail::invalid_iterator::create(), nlohmann::detail::primitive_iterator_t::get_value(), JSON_ASSERT, JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, and nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator.
set_begin()
template<typename BasicJsonType >
void nlohmann::detail::iter_impl< BasicJsonType >::set_begin () [inline], [private], [noexcept]
set the iterator to the first value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 10940 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, JSON_ASSERT, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::null, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator, nlohmann::detail::primitive_iterator_t::set_begin(), and nlohmann::detail::primitive_iterator_t::set_end().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::cbegin().
set_end()
template<typename BasicJsonType >
void nlohmann::detail::iter_impl< BasicJsonType >::set_end () [inline], [private], [noexcept]
set the iterator past the last value
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 10977 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::internal_iterator< BasicJsonType >::array_iterator, JSON_ASSERT, nlohmann::detail::iter_impl< BasicJsonType >::m_it, nlohmann::detail::iter_impl< BasicJsonType >::m_object, nlohmann::detail::object, nlohmann::detail::internal_iterator< BasicJsonType >::object_iterator, nlohmann::detail::internal_iterator< BasicJsonType >::primitive_iterator, and nlohmann::detail::primitive_iterator_t::set_end().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::cend(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end().
value()
template<typename BasicJsonType >
reference nlohmann::detail::iter_impl< BasicJsonType >::value () const [inline]
return the value of an iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11394 of file json.hpp.
References nlohmann::detail::iter_impl< BasicJsonType >::operator*().
Friends And Related Function Documentation
operator+
template<typename BasicJsonType >
iter_impl operator+ (difference_type i, const iter_impl< BasicJsonType > & it) [friend]
addition of distance and iterator
Precondition
The iterator is initialized; i.e. m_object != nullptr.
Definition at line 11304 of file json.hpp.
Member Data Documentation
BasicJsonType
template<typename BasicJsonType >
friend nlohmann::detail::iter_impl< BasicJsonType >::BasicJsonType [private]
Definition at line 10812 of file json.hpp.
iteration_proxy< iter_impl >
template<typename BasicJsonType >
friend nlohmann::detail::iter_impl< BasicJsonType >::iteration_proxy< iter_impl > [private]
Definition at line 10813 of file json.hpp.
iteration_proxy_value< iter_impl >
template<typename BasicJsonType >
friend nlohmann::detail::iter_impl< BasicJsonType >::iteration_proxy_value< iter_impl > [private]
Definition at line 10814 of file json.hpp.
m_it
template<typename BasicJsonType >
internal_iterator<typename std::remove_const<BasicJsonType>::type> nlohmann::detail::iter_impl< BasicJsonType >::m_it {} [private]
the actual iterator of the associated instance
Definition at line 11403 of file json.hpp.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::iter_impl(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert_iterator(), nlohmann::detail::iter_impl< BasicJsonType >::key(), nlohmann::detail::iter_impl< BasicJsonType >::operator*(), nlohmann::detail::iter_impl< BasicJsonType >::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator+=(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::iter_impl< BasicJsonType >::operator--(), nlohmann::detail::iter_impl< BasicJsonType >::operator->(), nlohmann::detail::iter_impl< BasicJsonType >::operator<(), nlohmann::detail::iter_impl< BasicJsonType >::operator=(), nlohmann::detail::iter_impl< BasicJsonType >::operator==(), nlohmann::detail::iter_impl< BasicJsonType >::operator[](), nlohmann::detail::iter_impl< BasicJsonType >::set_begin(), and nlohmann::detail::iter_impl< BasicJsonType >::set_end().
m_object
template<typename BasicJsonType >
pointer nlohmann::detail::iter_impl< BasicJsonType >::m_object = nullptr [private]
associated JSON instance
Definition at line 11401 of file json.hpp.
Referenced by nlohmann::detail::iter_impl< BasicJsonType >::iter_impl(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert(), nlohmann::detail::iter_impl< BasicJsonType >::key(), nlohmann::detail::iter_impl< BasicJsonType >::operator*(), nlohmann::detail::iter_impl< BasicJsonType >::operator++(), nlohmann::detail::iter_impl< BasicJsonType >::operator+=(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::iter_impl< BasicJsonType >::operator--(), nlohmann::detail::iter_impl< BasicJsonType >::operator->(), nlohmann::detail::iter_impl< BasicJsonType >::operator<(), nlohmann::detail::iter_impl< BasicJsonType >::operator=(), nlohmann::detail::iter_impl< BasicJsonType >::operator==(), nlohmann::detail::iter_impl< BasicJsonType >::operator[](), nlohmann::detail::iter_impl< BasicJsonType >::set_begin(), nlohmann::detail::iter_impl< BasicJsonType >::set_end(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::update().
The documentation for this class was generated from the following file:
Cpp/spatialstructures/src/json.hpp