nlohmann::detail::parser< BasicJsonType, InputAdapterType > Class Template Reference
syntax analysis
#include <json.hpp>
Public Member Functions
parser (InputAdapterType &&adapter, const parser_callback_t< BasicJsonType > cb=nullptr, const bool allow_exceptions_=true, const bool skip_comments=false)
a parser reading from an input adapter
void parse (const bool strict, BasicJsonType &result)
public parser interface
bool accept (const bool strict=true)
public accept interface
template<typename SAX >
bool sax_parse (SAX *sax, const bool strict=true)
Private Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using lexer_t = lexer< BasicJsonType, InputAdapterType >
using token_type = typename lexer_t::token_type
Private Member Functions
template<typename SAX >
bool sax_parse_internal (SAX *sax)
token_type get_token ()
get next token from lexer
std::string exception_message (const token_type expected, const std::string &context)
Private Attributes
const parser_callback_t< BasicJsonType > callback = nullptr
callback function
token_type last_token = token_type::uninitialized
the type of the last read token
lexer_t m_lexer
the lexer
const bool allow_exceptions = true
whether to throw exceptions in case of errors
Detailed Description
template<typename BasicJsonType, typename InputAdapterType>
class nlohmann::detail::parser< BasicJsonType, InputAdapterType >
syntax analysis
This class implements a recursive descent parser.
Definition at line 10163 of file json.hpp.
Member Typedef Documentation
lexer_t
template<typename BasicJsonType , typename InputAdapterType >
using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::lexer_t = lexer<BasicJsonType, InputAdapterType> [private]
Definition at line 10169 of file json.hpp.
number_float_t
template<typename BasicJsonType , typename InputAdapterType >
using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::number_float_t = typename BasicJsonType::number_float_t [private]
Definition at line 10167 of file json.hpp.
number_integer_t
template<typename BasicJsonType , typename InputAdapterType >
using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::number_integer_t = typename BasicJsonType::number_integer_t [private]
Definition at line 10165 of file json.hpp.
number_unsigned_t
template<typename BasicJsonType , typename InputAdapterType >
using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t [private]
Definition at line 10166 of file json.hpp.
string_t
template<typename BasicJsonType , typename InputAdapterType >
using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::string_t = typename BasicJsonType::string_t [private]
Definition at line 10168 of file json.hpp.
token_type
template<typename BasicJsonType , typename InputAdapterType >
using nlohmann::detail::parser< BasicJsonType, InputAdapterType >::token_type = typename lexer_t::token_type [private]
Definition at line 10170 of file json.hpp.
Constructor & Destructor Documentation
parser()
template<typename BasicJsonType , typename InputAdapterType >
nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parser (InputAdapterType && adapter, const parser_callback_t< BasicJsonType > cb = nullptr, const bool allow_exceptions_ = true, const bool skip_comments = false) [inline], [explicit]
a parser reading from an input adapter
Definition at line 10174 of file json.hpp.
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token().
Member Function Documentation
accept()
template<typename BasicJsonType , typename InputAdapterType >
bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::accept (const bool strict = true) [inline]
public accept interface
Parameters
 in strict whether to expect the last token to be EOF
Returns
whether the input is a proper JSON text
Definition at line 10257 of file json.hpp.
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::strict.
exception_message()
template<typename BasicJsonType , typename InputAdapterType >
std::string nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message (const token_type expected, const std::string & context) [inline], [private]
Definition at line 10572 of file json.hpp.
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::last_token, and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal().
get_token()
template<typename BasicJsonType , typename InputAdapterType >
token_type nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token () [inline], [private]
get next token from lexer
Definition at line 10567 of file json.hpp.
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::last_token, and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parser(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal().
parse()
template<typename BasicJsonType , typename InputAdapterType >
void nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse (const bool strict, BasicJsonType & result) [inline]
public parser interface
Parameters
 in strict whether to expect the last token to be EOF
 in,out result parsed JSON value
Exceptions
parse_error.101 in case of an unexpected token
parse_error.102 if to_unicode fails or surrogate error
parse_error.103 if to_unicode fails
Definition at line 10196 of file json.hpp.
References nlohmann::detail::parser< BasicJsonType, InputAdapterType >::allow_exceptions, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::callback, nlohmann::detail::parse_error::create(), nlohmann::detail::discarded, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), nlohmann::detail::json_sax_dom_parser< BasicJsonType >::is_errored(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::is_errored(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer, nlohmann::detail::json_sax_dom_parser< BasicJsonType >::parse_error(), nlohmann::detail::json_sax_dom_callback_parser< BasicJsonType >::parse_error(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal(), and nlohmann::detail::strict.
sax_parse()
template<typename BasicJsonType , typename InputAdapterType >
template<typename SAX >
bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse (SAX * sax, const bool strict = true) [inline]
Definition at line 10265 of file json.hpp.
References nlohmann::detail::parse_error::create(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal(), and nlohmann::detail::strict.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::accept().
sax_parse_internal()
template<typename BasicJsonType , typename InputAdapterType >
template<typename SAX >
bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal (SAX * sax) [inline], [private]
Definition at line 10285 of file json.hpp.
References nlohmann::detail::parse_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), JSON_ASSERT, JSON_HEDLEY_LIKELY, JSON_HEDLEY_UNLIKELY, nlohmann::detail::parser< BasicJsonType, InputAdapterType >::last_token, and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse().
Member Data Documentation
allow_exceptions
template<typename BasicJsonType , typename InputAdapterType >
const bool nlohmann::detail::parser< BasicJsonType, InputAdapterType >::allow_exceptions = true [private]
whether to throw exceptions in case of errors
Definition at line 10609 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse().
callback
template<typename BasicJsonType , typename InputAdapterType >
const parser_callback_t<BasicJsonType> nlohmann::detail::parser< BasicJsonType, InputAdapterType >::callback = nullptr [private]
callback function
Definition at line 10603 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse().
last_token
template<typename BasicJsonType , typename InputAdapterType >
token_type nlohmann::detail::parser< BasicJsonType, InputAdapterType >::last_token = token_type::uninitialized [private]
the type of the last read token
Definition at line 10605 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal().
m_lexer
template<typename BasicJsonType , typename InputAdapterType >
lexer_t nlohmann::detail::parser< BasicJsonType, InputAdapterType >::m_lexer [private]
the lexer
Definition at line 10607 of file json.hpp.
Referenced by nlohmann::detail::parser< BasicJsonType, InputAdapterType >::exception_message(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::get_token(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), and nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal().
The documentation for this class was generated from the following file:
Cpp/spatialstructures/src/json.hpp