nlohmann::detail::binary_writer< BasicJsonType, CharType > Class Template Reference
serialization to CBOR and MessagePack values
#include <json.hpp>
Public Member Functions
binary_writer (output_adapter_t< CharType > adapter)
create a binary writer
void write_bson (const BasicJsonType &j)
void write_cbor (const BasicJsonType &j)
void write_msgpack (const BasicJsonType &j)
void write_ubjson (const BasicJsonType &j, const bool use_count, const bool use_type, const bool add_prefix=true)
Static Public Member Functions
template<typename C = CharType, enable_if_t< std::is_signed< C >::value &&std::is_signed< char >::value > * = nullptr>
static constexpr CharType to_char_type (std::uint8_t x) noexcept
template<typename C = CharType, enable_if_t< std::is_signed< C >::value &&std::is_unsigned< char >::value > * = nullptr>
static CharType to_char_type (std::uint8_t x) noexcept
template<typename C = CharType, enable_if_t< std::is_unsigned< C >::value > * = nullptr>
static constexpr CharType to_char_type (std::uint8_t x) noexcept
template<typename InputCharType , typename C = CharType, enable_if_t< std::is_signed< C >::value &&std::is_signed< char >::value &&std::is_same< char, typename std::remove_cv< InputCharType >::type >::value > * = nullptr>
static constexpr CharType to_char_type (InputCharType x) noexcept
Private Types
using string_t = typename BasicJsonType::string_t
using binary_t = typename BasicJsonType::binary_t
using number_float_t = typename BasicJsonType::number_float_t
Private Member Functions
void write_bson_entry_header (const string_t &name, const std::uint8_t element_type)
Writes the given element_type and name to the output adapter.
void write_bson_boolean (const string_t &name, const bool value)
Writes a BSON element with key name and boolean value value.
void write_bson_double (const string_t &name, const double value)
Writes a BSON element with key name and double value value.
void write_bson_string (const string_t &name, const string_t &value)
Writes a BSON element with key name and string value value.
void write_bson_null (const string_t &name)
Writes a BSON element with key name and null value.
void write_bson_integer (const string_t &name, const std::int64_t value)
Writes a BSON element with key name and integer value.
void write_bson_unsigned (const string_t &name, const std::uint64_t value)
Writes a BSON element with key name and unsigned value.
void write_bson_object_entry (const string_t &name, const typename BasicJsonType::object_t &value)
Writes a BSON element with key name and object value.
void write_bson_array (const string_t &name, const typename BasicJsonType::array_t &value)
Writes a BSON element with key name and array value.
void write_bson_binary (const string_t &name, const binary_t &value)
Writes a BSON element with key name and binary value value.
void write_bson_element (const string_t &name, const BasicJsonType &j)
Serializes the JSON value j to BSON and associates it with the key name.
void write_bson_object (const typename BasicJsonType::object_t &value)
template<typename NumberType , typename std::enable_if< std::is_floating_point< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
template<typename NumberType , typename std::enable_if< std::is_unsigned< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
template<typename NumberType , typename std::enable_if< std::is_signed< NumberType >::value &&!std::is_floating_point< NumberType >::value, int >::type = 0>
void write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix)
CharType ubjson_prefix (const BasicJsonType &j) const noexcept
determine the type prefix of container values
template<typename NumberType , bool OutputIsLittleEndian = false>
void write_number (const NumberType n)
void write_compact_float (const number_float_t n, detail::input_format_t format)
Static Private Member Functions
static std::size_t calc_bson_entry_header_size (const string_t &name)
static std::size_t calc_bson_string_size (const string_t &value)
static std::size_t calc_bson_integer_size (const std::int64_t value)
static constexpr std::size_t calc_bson_unsigned_size (const std::uint64_t value) noexcept
static std::size_t calc_bson_array_size (const typename BasicJsonType::array_t &value)
static std::size_t calc_bson_binary_size (const typename BasicJsonType::binary_t &value)
static std::size_t calc_bson_element_size (const string_t &name, const BasicJsonType &j)
Calculates the size necessary to serialize the JSON value j with its name.
static std::size_t calc_bson_object_size (const typename BasicJsonType::object_t &value)
Calculates the size of the BSON serialization of the given JSON-object j.
static constexpr CharType get_cbor_float_prefix (float)
static constexpr CharType get_cbor_float_prefix (double)
static constexpr CharType get_msgpack_float_prefix (float)
static constexpr CharType get_msgpack_float_prefix (double)
static constexpr CharType get_ubjson_float_prefix (float)
static constexpr CharType get_ubjson_float_prefix (double)
Private Attributes
const bool is_little_endian = little_endianess()
whether we can assume little endianess
output_adapter_t< CharType > oa = nullptr
the output
Detailed Description
template<typename BasicJsonType, typename CharType>
class nlohmann::detail::binary_writer< BasicJsonType, CharType >
serialization to CBOR and MessagePack values
Definition at line 12752 of file json.hpp.
Member Typedef Documentation
binary_t
template<typename BasicJsonType , typename CharType >
using nlohmann::detail::binary_writer< BasicJsonType, CharType >::binary_t = typename BasicJsonType::binary_t [private]
Definition at line 12755 of file json.hpp.
number_float_t
template<typename BasicJsonType , typename CharType >
using nlohmann::detail::binary_writer< BasicJsonType, CharType >::number_float_t = typename BasicJsonType::number_float_t [private]
Definition at line 12756 of file json.hpp.
string_t
template<typename BasicJsonType , typename CharType >
using nlohmann::detail::binary_writer< BasicJsonType, CharType >::string_t = typename BasicJsonType::string_t [private]
Definition at line 12754 of file json.hpp.
Constructor & Destructor Documentation
binary_writer()
template<typename BasicJsonType , typename CharType >
nlohmann::detail::binary_writer< BasicJsonType, CharType >::binary_writer (output_adapter_t< CharType > adapter) [inline], [explicit]
create a binary writer
Parameters
 in adapter output adapter to write to
Definition at line 12764 of file json.hpp.
References JSON_ASSERT, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa.
Member Function Documentation
calc_bson_array_size()
template<typename BasicJsonType , typename CharType >
static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size (const typename BasicJsonType::array_t & value) [inline], [static], [private]
Returns
The size of the BSON-encoded array value
Definition at line 13776 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size(), nlohmann::to_string(), and nlohmann::detail::value.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array().
calc_bson_binary_size()
template<typename BasicJsonType , typename CharType >
static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_binary_size (const typename BasicJsonType::binary_t & value) [inline], [static], [private]
Returns
The size of the BSON-encoded binary array value
Definition at line 13791 of file json.hpp.
References nlohmann::detail::value.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
calc_bson_element_size()
template<typename BasicJsonType , typename CharType >
static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size (const string_t & name, const BasicJsonType & j) [inline], [static], [private]
Calculates the size necessary to serialize the JSON value j with its name.
Returns
The calculated size for the BSON document entry for j with the given name.
Definition at line 13833 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_binary_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_entry_header_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_integer_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_string_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_unsigned_size(), JSON_ASSERT, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size().
calc_bson_entry_header_size()
template<typename BasicJsonType , typename CharType >
static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_entry_header_size (const string_t & name) [inline], [static], [private]
Returns
The size of a BSON document entry header, including the id marker and the entry name size (and its null-terminator).
Definition at line 13629 of file json.hpp.
References nlohmann::detail::out_of_range::create(), JSON_HEDLEY_UNLIKELY, JSON_THROW, and nlohmann::to_string().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
calc_bson_integer_size()
template<typename BasicJsonType , typename CharType >
static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_integer_size (const std::int64_t value) [inline], [static], [private]
Returns
The size of the BSON-encoded integer value
Definition at line 13706 of file json.hpp.
References nlohmann::detail::value.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
calc_bson_object_size()
template<typename BasicJsonType , typename CharType >
static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size (const typename BasicJsonType::object_t & value) [inline], [static], [private]
Calculates the size of the BSON serialization of the given JSON-object j.
Parameters
 in j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 13927 of file json.hpp.
References nlohmann::detail::value.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
calc_bson_string_size()
template<typename BasicJsonType , typename CharType >
static std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_string_size (const string_t & value) [inline], [static], [private]
Returns
The size of the BSON-encoded string in value
Definition at line 13676 of file json.hpp.
References nlohmann::detail::value.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
calc_bson_unsigned_size()
template<typename BasicJsonType , typename CharType >
static constexpr std::size_t nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_unsigned_size (const std::uint64_t value) [inline], [static], [constexpr], [private], [noexcept]
Returns
The size of the BSON-encoded unsigned integer in j
Definition at line 13734 of file json.hpp.
References nlohmann::detail::value.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_element_size().
get_cbor_float_prefix() [1/2]
template<typename BasicJsonType , typename CharType >
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix (double) [inline], [static], [constexpr], [private]
Definition at line 13963 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
get_cbor_float_prefix() [2/2]
template<typename BasicJsonType , typename CharType >
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix (float) [inline], [static], [constexpr], [private]
Definition at line 13958 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_compact_float().
get_msgpack_float_prefix() [1/2]
template<typename BasicJsonType , typename CharType >
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix (double) [inline], [static], [constexpr], [private]
Definition at line 13977 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
get_msgpack_float_prefix() [2/2]
template<typename BasicJsonType , typename CharType >
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix (float) [inline], [static], [constexpr], [private]
Definition at line 13972 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_compact_float().
get_ubjson_float_prefix() [1/2]
template<typename BasicJsonType , typename CharType >
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix (double) [inline], [static], [constexpr], [private]
Definition at line 14214 of file json.hpp.
get_ubjson_float_prefix() [2/2]
template<typename BasicJsonType , typename CharType >
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix (float) [inline], [static], [constexpr], [private]
Definition at line 14209 of file json.hpp.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
to_char_type() [1/4]
template<typename BasicJsonType , typename CharType >
template<typename InputCharType , typename C = CharType, enable_if_t< std::is_signed< C >::value &&std::is_signed< char >::value &&std::is_same< char, typename std::remove_cv< InputCharType >::type >::value > * = nullptr>
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (InputCharType x) [inline], [static], [constexpr], [noexcept]
Definition at line 14307 of file json.hpp.
to_char_type() [2/4]
template<typename BasicJsonType , typename CharType >
template<typename C = CharType, enable_if_t< std::is_signed< C >::value &&std::is_signed< char >::value > * = nullptr>
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) [inline], [static], [constexpr], [noexcept]
Definition at line 14278 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
to_char_type() [3/4]
template<typename BasicJsonType , typename CharType >
template<typename C = CharType, enable_if_t< std::is_signed< C >::value &&std::is_unsigned< char >::value > * = nullptr>
static CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) [inline], [static], [noexcept]
Definition at line 14285 of file json.hpp.
to_char_type() [4/4]
template<typename BasicJsonType , typename CharType >
template<typename C = CharType, enable_if_t< std::is_unsigned< C >::value > * = nullptr>
static constexpr CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type (std::uint8_t x) [inline], [static], [constexpr], [noexcept]
Definition at line 14296 of file json.hpp.
ubjson_prefix()
template<typename BasicJsonType , typename CharType >
CharType nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix (const BasicJsonType & j) const [inline], [private], [noexcept]
determine the type prefix of container values
Definition at line 14129 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix(), nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
write_bson()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson (const BasicJsonType & j) [inline]
Parameters
 in j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 12773 of file json.hpp.
References nlohmann::detail::type_error::create(), JSON_THROW, nlohmann::detail::object, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
Referenced by nlohmann::basic_json::to_bson().
write_bson_array()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array (const string_t & name, const typename BasicJsonType::array_t & value) [inline], [private]
Writes a BSON element with key name and array value.
Definition at line 13799 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_array_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::to_string(), nlohmann::detail::value, nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_binary()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_binary (const string_t & name, const binary_t & value) [inline], [private]
Writes a BSON element with key name and binary value value.
Definition at line 13818 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::value, nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_boolean()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean (const string_t & name, const bool value) [inline], [private]
Writes a BSON element with key name and boolean value value.
Definition at line 13656 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::value, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_double()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_double (const string_t & name, const double value) [inline], [private]
Writes a BSON element with key name and double value value.
Definition at line 13666 of file json.hpp.
References nlohmann::detail::value, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_element()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element (const string_t & name, const BasicJsonType & j) [inline], [private]
Serializes the JSON value j to BSON and associates it with the key name.
Parameters
name The name to associate with the JSON entity j within the current BSON document
Returns
The size of the BSON entry
Definition at line 13881 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, JSON_ASSERT, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_binary(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_double(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_null(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
write_bson_entry_header()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header (const string_t & name, const std::uint8_t element_type) [inline], [private]
Writes the given element_type and name to the output adapter.
Definition at line 13644 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_binary(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_double(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_null(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned().
write_bson_integer()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_integer (const string_t & name, const std::int64_t value) [inline], [private]
Writes a BSON element with key name and integer value.
Definition at line 13716 of file json.hpp.
References nlohmann::detail::value, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_null()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_null (const string_t & name) [inline], [private]
Writes a BSON element with key name and null value.
Definition at line 13698 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_object()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object (const typename BasicJsonType::object_t & value) [inline], [private]
Parameters
 in j JSON value to serialize
Precondition
j.type() == value_t::object
Definition at line 13942 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_object_size(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::value, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry().
write_bson_object_entry()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object_entry (const string_t & name, const typename BasicJsonType::object_t & value) [inline], [private]
Writes a BSON element with key name and object value.
Definition at line 13766 of file json.hpp.
References nlohmann::detail::value, nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_string()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string (const string_t & name, const string_t & value) [inline], [private]
Writes a BSON element with key name and string value value.
Definition at line 13684 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::value, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_bson_unsigned()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned (const string_t & name, const std::uint64_t value) [inline], [private]
Writes a BSON element with key name and unsigned value.
Definition at line 13744 of file json.hpp.
References nlohmann::detail::out_of_range::create(), JSON_THROW, nlohmann::to_string(), nlohmann::detail::value, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_element().
write_cbor()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor (const BasicJsonType & j) [inline]
Parameters
 in j JSON value to serialize
Definition at line 12793 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::cbor, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_compact_float(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
Referenced by nlohmann::basic_json::to_cbor().
write_compact_float()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_compact_float (const number_float_t n, detail::input_format_t format) [inline], [private]
Definition at line 14251 of file json.hpp.
References nlohmann::detail::cbor, nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_cbor_float_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_msgpack_float_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack().
write_msgpack()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack (const BasicJsonType & j) [inline]
Parameters
 in j JSON value to serialize
Definition at line 13098 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::msgpack, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_compact_float(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
Referenced by nlohmann::basic_json::to_msgpack().
write_number()
template<typename BasicJsonType , typename CharType >
template<typename NumberType , bool OutputIsLittleEndian = false>
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number (const NumberType n) [inline], [private]
Definition at line 14235 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::is_little_endian, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_binary(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_compact_float(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
write_number_with_ubjson_prefix() [1/3]
template<typename BasicJsonType , typename CharType >
template<typename NumberType , typename std::enable_if< std::is_floating_point< NumberType >::value, int >::type = 0>
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) [inline], [private]
Definition at line 13989 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::get_ubjson_float_prefix(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
write_number_with_ubjson_prefix() [2/3]
template<typename BasicJsonType , typename CharType >
template<typename NumberType , typename std::enable_if< std::is_unsigned< NumberType >::value, int >::type = 0>
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) [inline], [private]
Definition at line 14002 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
write_number_with_ubjson_prefix() [3/3]
template<typename BasicJsonType , typename CharType >
template<typename NumberType , typename std::enable_if< std::is_signed< NumberType >::value &&!std::is_floating_point< NumberType >::value, int >::type = 0>
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix (const NumberType n, const bool add_prefix) [inline], [private]
Definition at line 14065 of file json.hpp.
References nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
write_ubjson()
template<typename BasicJsonType , typename CharType >
void nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson (const BasicJsonType & j, const bool use_count, const bool use_type, const bool add_prefix = true) [inline]
Parameters
 in j JSON value to serialize
 in use_count whether to use '#' prefixes (optimized format)
 in use_type whether to use '$' prefixes (optimized format)
 in add_prefix whether prefixes need to be used for this value
Definition at line 13422 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, JSON_ASSERT, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa, nlohmann::detail::object, nlohmann::detail::string, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix().
Referenced by nlohmann::basic_json::to_ubjson().
Member Data Documentation
is_little_endian
template<typename BasicJsonType , typename CharType >
const bool nlohmann::detail::binary_writer< BasicJsonType, CharType >::is_little_endian = little_endianess() [private]
whether we can assume little endianess
Definition at line 14314 of file json.hpp.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number().
oa
template<typename BasicJsonType , typename CharType >
output_adapter_t<CharType> nlohmann::detail::binary_writer< BasicJsonType, CharType >::oa = nullptr [private]
the output
Definition at line 14317 of file json.hpp.
Referenced by nlohmann::detail::binary_writer< BasicJsonType, CharType >::binary_writer(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_array(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_binary(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_boolean(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_entry_header(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_object(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_string(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_cbor(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_compact_float(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_msgpack(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_number_with_ubjson_prefix(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_ubjson().
The documentation for this class was generated from the following file:
Cpp/spatialstructures/src/json.hpp