nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX > Class Template Reference
deserialization of CBOR, MessagePack, and UBJSON values
#include <json.hpp>
Public Member Functions
binary_reader (InputAdapterType &&adapter)
create a binary reader
binary_reader (const binary_reader &)=delete
binary_reader (binary_reader &&)=default
binary_reader & operator= (const binary_reader &)=delete
binary_reader & operator= (binary_reader &&)=default
~binary_reader ()=default
bool sax_parse (const input_format_t format, json_sax_t *sax_, const bool strict=true, const cbor_tag_handler_t tag_handler=cbor_tag_handler_t::error)
Private Types
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using number_float_t = typename BasicJsonType::number_float_t
using string_t = typename BasicJsonType::string_t
using binary_t = typename BasicJsonType::binary_t
using json_sax_t = SAX
using char_type = typename InputAdapterType::char_type
using char_int_type = typename std::char_traits< char_type >::int_type
Private Member Functions
bool parse_bson_internal ()
Reads in a BSON-object and passes it to the SAX-parser.
bool get_bson_cstr (string_t &result)
Parses a C-style string from the BSON input.
template<typename NumberType >
bool get_bson_string (const NumberType len, string_t &result)
Parses a zero-terminated string of length len from the BSON input.
template<typename NumberType >
bool get_bson_binary (const NumberType len, binary_t &result)
Parses a byte array input of length len from the BSON input.
bool parse_bson_element_internal (const char_int_type element_type, const std::size_t element_type_parse_position)
Read a BSON document element of the given element_type.
bool parse_bson_element_list (const bool is_array)
Read a BSON element list (as specified in the BSON-spec)
bool parse_bson_array ()
Reads an array from the BSON input and passes it to the SAX-parser.
bool parse_cbor_internal (const bool get_char, const cbor_tag_handler_t tag_handler)
bool get_cbor_string (string_t &result)
reads a CBOR string
bool get_cbor_binary (binary_t &result)
reads a CBOR byte array
bool get_cbor_array (const std::size_t len, const cbor_tag_handler_t tag_handler)
bool get_cbor_object (const std::size_t len, const cbor_tag_handler_t tag_handler)
bool parse_msgpack_internal ()
bool get_msgpack_string (string_t &result)
reads a MessagePack string
bool get_msgpack_binary (binary_t &result)
reads a MessagePack byte array
bool get_msgpack_array (const std::size_t len)
bool get_msgpack_object (const std::size_t len)
bool parse_ubjson_internal (const bool get_char=true)
bool get_ubjson_string (string_t &result, const bool get_char=true)
reads a UBJSON string
bool get_ubjson_size_value (std::size_t &result)
bool get_ubjson_size_type (std::pair< std::size_t, char_int_type > &result)
determine the type and size for a container
bool get_ubjson_value (const char_int_type prefix)
bool get_ubjson_array ()
bool get_ubjson_object ()
bool get_ubjson_high_precision_number ()
char_int_type get ()
get next character from the input
char_int_type get_ignore_noop ()
template<typename NumberType , bool InputIsLittleEndian = false>
bool get_number (const input_format_t format, NumberType &result)
template<typename NumberType >
bool get_string (const input_format_t format, const NumberType len, string_t &result)
create a string by reading characters from the input
template<typename NumberType >
bool get_binary (const input_format_t format, const NumberType len, binary_t &result)
create a byte array by reading bytes from the input
bool unexpect_eof (const input_format_t format, const char *context) const
std::string get_token_string () const
std::string exception_message (const input_format_t format, const std::string &detail, const std::string &context) const
Private Attributes
InputAdapterType ia
input adapter
char_int_type current = std::char_traits<char_type>::eof()
the current character
std::size_t chars_read = 0
the number of characters read
const bool is_little_endian = little_endianess()
whether we can assume little endianess
json_sax_t * sax = nullptr
the SAX parser
Detailed Description
template<typename BasicJsonType, typename InputAdapterType, typename SAX = json_sax_dom_parser<BasicJsonType>>
class nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >
deserialization of CBOR, MessagePack, and UBJSON values
Definition at line 7695 of file json.hpp.
Member Typedef Documentation
binary_t
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
using nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::binary_t = typename BasicJsonType::binary_t [private]
Definition at line 7701 of file json.hpp.
char_int_type
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
using nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::char_int_type = typename std::char_traits<char_type>::int_type [private]
Definition at line 7704 of file json.hpp.
char_type
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
using nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::char_type = typename InputAdapterType::char_type [private]
Definition at line 7703 of file json.hpp.
json_sax_t
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
using nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::json_sax_t = SAX [private]
Definition at line 7702 of file json.hpp.
number_float_t
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
using nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::number_float_t = typename BasicJsonType::number_float_t [private]
Definition at line 7699 of file json.hpp.
number_integer_t
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
using nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::number_integer_t = typename BasicJsonType::number_integer_t [private]
Definition at line 7697 of file json.hpp.
number_unsigned_t
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
using nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::number_unsigned_t = typename BasicJsonType::number_unsigned_t [private]
Definition at line 7698 of file json.hpp.
string_t
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
using nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::string_t = typename BasicJsonType::string_t [private]
Definition at line 7700 of file json.hpp.
Constructor & Destructor Documentation
binary_reader() [1/3]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::binary_reader (InputAdapterType && adapter) [inline], [explicit]
create a binary reader
Parameters
 in adapter input adapter to read from
Definition at line 7712 of file json.hpp.
binary_reader() [2/3]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::binary_reader (const binary_reader< BasicJsonType, InputAdapterType, SAX > &) [delete]
binary_reader() [3/3]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::binary_reader (binary_reader< BasicJsonType, InputAdapterType, SAX > &&) [default]
 binary_reader()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::~binary_reader () [default]
Member Function Documentation
exception_message()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
std::string nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message (const input_format_t format, const std::string & detail, const std::string & context) const [inline], [private]
Parameters
 in format the current format
 in detail a detailed error message
 in context further context information
Returns
a message string to use in the parse_error exceptions
Definition at line 10050 of file json.hpp.
References nlohmann::detail::bson, nlohmann::detail::cbor, JSON_ASSERT, nlohmann::detail::msgpack, and nlohmann::detail::ubjson.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
get()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
char_int_type nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get () [inline], [private]
get next character from the input
This function provides the interface to the used input adapter. It does not throw in case the input reached EOF, but returns a -'ve valued std::char_traits<char_type>::eof() in that case.
Returns
character read from the input
Definition at line 9890 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::ia.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_cstr(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse().
get_binary()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
template<typename NumberType >
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_binary (const input_format_t format, const NumberType len, binary_t & result) [inline], [private]
create a byte array by reading bytes from the input
Template Parameters
NumberType the type of the number
Parameters
 in format the current format (for diagnostics)
 in len number of bytes to read
 out result byte array created by reading len bytes
Returns
whether byte array creation completed
Note
We can not reserve len bytes for the result, because len may be too large. Usually, unexpect_eof() detects the end of the input before we run out of memory.
Definition at line 10000 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_binary().
get_bson_binary()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
template<typename NumberType >
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_binary (const NumberType len, binary_t & result) [inline], [private]
Parses a byte array input of length len from the BSON input.
Parameters
 in len The length of the byte array to be read.
 in,out result A reference to the binary variable where the read array is to be stored.
Template Parameters
NumberType The type of the length len
Precondition
len >= 0
Returns
true if the byte array was successfully parsed
Definition at line 7870 of file json.hpp.
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal().
get_bson_cstr()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_cstr (string_t & result) [inline], [private]
Parses a C-style string from the BSON input.
Parameters
 in,out result A reference to the string variable where the read string is to be stored.
Returns
true if the \x00-byte indicating the end of the string was encountered before the EOF; false indicates an unexpected EOF.
Definition at line 7819 of file json.hpp.
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list().
get_bson_string()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
template<typename NumberType >
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string (const NumberType len, string_t & result) [inline], [private]
Parses a zero-terminated string of length len from the BSON input.
Parameters
 in len The length (including the zero-byte at the end) of the string to be read.
 in,out result A reference to the string variable where the read string is to be stored.
Template Parameters
NumberType The type of the length len
Precondition
len >= 1
Returns
true if the string was successfully parsed
Definition at line 7849 of file json.hpp.
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal().
get_cbor_array()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_array (const std::size_t len, const cbor_tag_handler_t tag_handler) [inline], [private]
Parameters
 in len the length of the array or std::size_t(-1) for an array of indefinite size
 in tag_handler how CBOR tags should be treated
Returns
whether array creation completed
Definition at line 8676 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal().
get_cbor_binary()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary (binary_t & result) [inline], [private]
reads a CBOR byte array
This function first reads starting bytes to determine the expected byte array length and then copies this number of bytes into the byte array. Additionally, CBOR's byte arrays with indefinite lengths are supported.
Parameters
 out result created byte array
Returns
whether byte array creation completed
Definition at line 8582 of file json.hpp.
References nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal().
get_cbor_object()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_object (const std::size_t len, const cbor_tag_handler_t tag_handler) [inline], [private]
Parameters
 in len the length of the object or std::size_t(-1) for an object of indefinite size
 in tag_handler how CBOR tags should be treated
Returns
whether object creation completed
Definition at line 8714 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::key, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal().
get_cbor_string()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string (string_t & result) [inline], [private]
reads a CBOR string
This function first reads starting bytes to determine the expected string length and then copies this number of bytes into a string. Additionally, CBOR's strings with indefinite lengths are supported.
Parameters
 out result created string
Returns
whether string creation completed
Definition at line 8487 of file json.hpp.
References nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal().
get_ignore_noop()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
char_int_type nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop () [inline], [private]
Returns
character read from the input after ignoring all 'N' entries
Definition at line 9899 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_ubjson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse().
get_msgpack_array()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_array (const std::size_t len) [inline], [private]
Parameters
 in len the length of the array
Returns
whether array creation completed
Definition at line 9340 of file json.hpp.
References JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal().
get_msgpack_binary()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_binary (binary_t & result) [inline], [private]
reads a MessagePack byte array
This function first reads starting bytes to determine the expected byte array length and then copies this number of bytes into a byte array.
Parameters
 out result created byte array
Returns
whether byte array creation completed
Definition at line 9229 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), and nlohmann::detail::msgpack.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal().
get_msgpack_object()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_object (const std::size_t len) [inline], [private]
Parameters
 in len the length of the object
Returns
whether object creation completed
Definition at line 9362 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::key, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal().
get_msgpack_string()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string (string_t & result) [inline], [private]
reads a MessagePack string
This function first reads starting bytes to determine the expected string length and then copies this number of bytes into a string.
Parameters
 out result created string
Returns
whether string creation completed
Definition at line 9147 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::msgpack, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_object(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal().
get_number()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
template<typename NumberType , bool InputIsLittleEndian = false>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number (const input_format_t format, NumberType & result) [inline], [private]
Definition at line 9924 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::is_little_endian, JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal().
get_string()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
template<typename NumberType >
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_string (const input_format_t format, const NumberType len, string_t & result) [inline], [private]
create a string by reading characters from the input
Template Parameters
NumberType the type of the number
Parameters
 in format the current format (for diagnostics)
 in len number of characters to read
 out result string created by reading len bytes
Returns
whether string creation completed
Note
We can not reserve len bytes for the result, because len may be too large. Usually, unexpect_eof() detects the end of the input before we run out of string memory.
Definition at line 9967 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string().
get_token_string()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
std::string nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string () const [inline], [private]
Returns
a string representation of the last read byte
Definition at line 10037 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse().
get_ubjson_array()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_array () [inline], [private]
Returns
whether array creation completed
Definition at line 9691 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_ubjson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value().
get_ubjson_high_precision_number()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number () [inline], [private]
Definition at line 9828 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), nlohmann::detail::input_adapter(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value().
get_ubjson_object()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object () [inline], [private]
Returns
whether object creation completed
Definition at line 9753 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::key, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_ubjson_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value().
get_ubjson_size_type()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type (std::pair< std::size_t, char_int_type > & result) [inline], [private]
determine the type and size for a container
In the optimized UBJSON format, a type and a size can be provided to allow for a more compact representation.
Parameters
 out result pair of the size and the type
Returns
whether pair creation completed
Definition at line 9549 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_array(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object().
get_ubjson_size_value()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value (std::size_t & result) [inline], [private]
Parameters
 out result determined size
Returns
whether size determination completed
Definition at line 9472 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, and nlohmann::detail::ubjson.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type().
get_ubjson_string()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string (string_t & result, const bool get_char = true) [inline], [private]
reads a UBJSON string
This function is either called after reading the 'S' byte explicitly indicating a string, or in case of an object key where the 'S' byte can be left out.
Parameters
 out result created string
 in get_char whether a new character should be retrieved from the input (true, default) or whether the last read character should be considered instead
Returns
whether string creation completed
Definition at line 9418 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value().
get_ubjson_value()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value (const char_int_type prefix) [inline], [private]
Parameters
prefix the previously read or set type prefix
Returns
whether value creation completed
Definition at line 9590 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, nlohmann::detail::ubjson, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_ubjson_internal().
operator=() [1/2]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
binary_reader & nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::operator= (binary_reader< BasicJsonType, InputAdapterType, SAX > &&) [default]
operator=() [2/2]
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
binary_reader & nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::operator= (const binary_reader< BasicJsonType, InputAdapterType, SAX > &) [delete]
parse_bson_array()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_array () [inline], [private]
Reads an array from the BSON input and passes it to the SAX-parser.
Returns
whether a valid BSON-array was passed to the SAX parser
Definition at line 8012 of file json.hpp.
References nlohmann::detail::bson, JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal().
parse_bson_element_internal()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal (const char_int_type element_type, const std::size_t element_type_parse_position) [inline], [private]
Read a BSON document element of the given element_type.
Parameters
 in element_type The BSON element type, c.f. http://bsonspec.org/spec.html
 in element_type_parse_position The position in the input stream, where the element_type was read.
Warning
Not all BSON element types are supported yet. An unsupported element_type will give rise to a parse_error.114: Unsupported BSON record type 0x...
Returns
whether a valid BSON-object/array was passed to the SAX parser
Definition at line 7896 of file json.hpp.
References nlohmann::detail::bson, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, and nlohmann::detail::value.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list().
parse_bson_element_list()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list (const bool is_array) [inline], [private]
Read a BSON element list (as specified in the BSON-spec)
The same binary layout is used for objects and arrays, hence it must be indicated with the argument is_array which one is expected (true --> array, false --> object).
Parameters
 in is_array Determines if the element list being read is to be treated as an object (is_array == false), or as an array (is_array == true).
Returns
whether a valid BSON-object/array was passed to the SAX parser
Definition at line 7974 of file json.hpp.
References nlohmann::detail::bson, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_cstr(), JSON_HEDLEY_UNLIKELY, nlohmann::detail::key, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_array(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_internal().
parse_bson_internal()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_internal () [inline], [private]
Reads in a BSON-object and passes it to the SAX-parser.
Returns
whether a valid BSON-value was passed to the SAX parser
Definition at line 7794 of file json.hpp.
References nlohmann::detail::bson, JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse().
parse_cbor_internal()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal (const bool get_char, const cbor_tag_handler_t tag_handler) [inline], [private]
Parameters
 in get_char whether a new character should be retrieved from the input (true) or whether the last read character should be considered instead (false)
 in tag_handler how CBOR tags should be treated
Returns
whether a valid CBOR value was passed to the SAX parser
Definition at line 8042 of file json.hpp.
References nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::error, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), nlohmann::detail::ignore, JSON_ASSERT, JSON_HEDLEY_UNLIKELY, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse().
parse_msgpack_internal()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal () [inline], [private]
Returns
whether a valid MessagePack value was passed to the SAX parser
Definition at line 8767 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), nlohmann::detail::msgpack, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_object(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse().
parse_ubjson_internal()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_ubjson_internal (const bool get_char = true) [inline], [private]
Parameters
 in get_char whether a new character should be retrieved from the input (true, default) or whether the last read character should be considered instead
Returns
whether a valid UBJSON value was passed to the SAX parser
Definition at line 9399 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value().
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse().
sax_parse()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse (const input_format_t format, json_sax_t * sax_, const bool strict = true, const cbor_tag_handler_t tag_handler = cbor_tag_handler_t::error) [inline]
Parameters
 in format the binary format to parse
 in sax_ a SAX event processor
 in strict whether to expect the input to be consumed completed
 in tag_handler how to treat CBOR tags
Returns
Definition at line 7733 of file json.hpp.
References nlohmann::detail::bson, nlohmann::detail::cbor, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), JSON_ASSERT, JSON_HEDLEY_UNLIKELY, nlohmann::detail::msgpack, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_ubjson_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax, nlohmann::detail::strict, and nlohmann::detail::ubjson.
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::from_bson(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::from_cbor(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::from_msgpack(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::from_ubjson(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::sax_parse().
unexpect_eof()
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof (const input_format_t format, const char * context) const [inline], [private]
Parameters
 in format the current format (for diagnostics)
 in context further context information (for diagnostics)
Returns
whether the last read character is not EOF
Definition at line 10024 of file json.hpp.
References nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read, nlohmann::detail::parse_error::create(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current, nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::exception_message(), JSON_HEDLEY_UNLIKELY, and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_cstr(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal().
Member Data Documentation
chars_read
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
std::size_t nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::chars_read = 0 [private]
the number of characters read
Definition at line 10089 of file json.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
current
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
char_int_type nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::current = std::char_traits<char_type>::eof() [private]
the current character
Definition at line 10086 of file json.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_cstr(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ignore_noop(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_token_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_ubjson_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
ia
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
InputAdapterType nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::ia [private]
input adapter
Definition at line 10083 of file json.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get().
is_little_endian
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
const bool nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::is_little_endian = little_endianess() [private]
whether we can assume little endianess
Definition at line 10092 of file json.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_number().
sax
template<typename BasicJsonType , typename InputAdapterType , typename SAX = json_sax_dom_parser<BasicJsonType>>
json_sax_t* nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax = nullptr [private]
the SAX parser
Definition at line 10095 of file json.hpp.
Referenced by nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_object(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_array(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_list(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
The documentation for this class was generated from the following file:
Cpp/spatialstructures/src/json.hpp