nlohmann::detail::serializer< BasicJsonType > Class Template Reference
#include <json.hpp>
Public Member Functions
serializer (output_adapter_t< char > s, const char ichar, error_handler_t error_handler_=error_handler_t::strict)
serializer (const serializer &)=delete
serializer & operator= (const serializer &)=delete
serializer (serializer &&)=delete
serializer & operator= (serializer &&)=delete
~serializer ()=default
void dump (const BasicJsonType &val, const bool pretty_print, const bool ensure_ascii, const unsigned int indent_step, const unsigned int current_indent=0)
internal implementation of the serialization function
Private Types
using string_t = typename BasicJsonType::string_t
using number_float_t = typename BasicJsonType::number_float_t
using number_integer_t = typename BasicJsonType::number_integer_t
using number_unsigned_t = typename BasicJsonType::number_unsigned_t
using binary_char_t = typename BasicJsonType::binary_t::value_type
Private Member Functions
void dump_escaped (const string_t &s, const bool ensure_ascii)
dump escaped string
unsigned int count_digits (number_unsigned_t x) noexcept
count digits
template<typename NumberType , detail::enable_if_t< std::is_same< NumberType, number_unsigned_t >::value||std::is_same< NumberType, number_integer_t >::value||std::is_same< NumberType, binary_char_t >::value, int > = 0>
void dump_integer (NumberType x)
dump an integer
void dump_float (number_float_t x)
dump a floating-point number
void dump_float (number_float_t x, std::true_type)
void dump_float (number_float_t x, std::false_type)
number_unsigned_t remove_sign (number_unsigned_t x)
number_unsigned_t remove_sign (number_integer_t x) noexcept
Static Private Member Functions
static std::uint8_t decode (std::uint8_t &state, std::uint32_t &codep, const std::uint8_t byte) noexcept
check whether a string is UTF-8 encoded
Private Attributes
output_adapter_t< char > o = nullptr
the output of the serializer
std::array< char, 64 > number_buffer {{}}
a (hopefully) large enough character buffer
const std::lconv * loc = nullptr
the locale
const char thousands_sep = '\0'
the locale's thousand separator character
const char decimal_point = '\0'
the locale's decimal point character
std::array< char, 512 > string_buffer {{}}
string buffer
const char indent_char
the indentation character
string_t indent_string
the indentation string
const error_handler_t error_handler
error_handler how to react on decoding errors
Static Private Attributes
static constexpr std::uint8_t UTF8_ACCEPT = 0
static constexpr std::uint8_t UTF8_REJECT = 1
Detailed Description
template<typename BasicJsonType>
class nlohmann::detail::serializer< BasicJsonType >
Definition at line 15477 of file json.hpp.
Member Typedef Documentation
binary_char_t
template<typename BasicJsonType >
using nlohmann::detail::serializer< BasicJsonType >::binary_char_t = typename BasicJsonType::binary_t::value_type [private]
Definition at line 15483 of file json.hpp.
number_float_t
template<typename BasicJsonType >
using nlohmann::detail::serializer< BasicJsonType >::number_float_t = typename BasicJsonType::number_float_t [private]
Definition at line 15480 of file json.hpp.
number_integer_t
template<typename BasicJsonType >
using nlohmann::detail::serializer< BasicJsonType >::number_integer_t = typename BasicJsonType::number_integer_t [private]
Definition at line 15481 of file json.hpp.
number_unsigned_t
template<typename BasicJsonType >
using nlohmann::detail::serializer< BasicJsonType >::number_unsigned_t = typename BasicJsonType::number_unsigned_t [private]
Definition at line 15482 of file json.hpp.
string_t
template<typename BasicJsonType >
using nlohmann::detail::serializer< BasicJsonType >::string_t = typename BasicJsonType::string_t [private]
Definition at line 15479 of file json.hpp.
Constructor & Destructor Documentation
serializer() [1/3]
template<typename BasicJsonType >
nlohmann::detail::serializer< BasicJsonType >::serializer (output_adapter_t< char > s, const char ichar, error_handler_t error_handler_ = error_handler_t::strict) [inline]
Parameters
 in s output stream to serialize to
 in ichar indentation character to use
 in error_handler_ how to react on decoding errors
Definition at line 15493 of file json.hpp.
serializer() [2/3]
template<typename BasicJsonType >
nlohmann::detail::serializer< BasicJsonType >::serializer (const serializer< BasicJsonType > &) [delete]
serializer() [3/3]
template<typename BasicJsonType >
nlohmann::detail::serializer< BasicJsonType >::serializer (serializer< BasicJsonType > &&) [delete]
 serializer()
template<typename BasicJsonType >
nlohmann::detail::serializer< BasicJsonType >::~serializer () [default]
Member Function Documentation
count_digits()
template<typename BasicJsonType >
unsigned int nlohmann::detail::serializer< BasicJsonType >::count_digits (number_unsigned_t x) [inline], [private], [noexcept]
count digits
Count the number of decimal (base 10) digits for an input unsigned integer.
Parameters
 in x unsigned integer number to count its digits
Returns
number of decimal digits
Definition at line 16073 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_integer().
decode()
template<typename BasicJsonType >
static std::uint8_t nlohmann::detail::serializer< BasicJsonType >::decode (std::uint8_t & state, std::uint32_t & codep, const std::uint8_t byte) [inline], [static], [private], [noexcept]
check whether a string is UTF-8 encoded
The function checks each byte of a string whether it is UTF-8 encoded. The result of the check is stored in the state parameter. The function must be called initially with state 0 (accept). State 1 means the string must be rejected, because the current byte is not allowed. If the string is completely processed, but the state is non-zero, the string ended prematurely; that is, the last byte indicated more bytes should have followed.
Parameters
 in,out state the state of the decoding
 in,out codep codepoint (valid only if resulting state is UTF8_ACCEPT)
 in byte next byte to decode
Returns
new state
Note
The function has been edited: a std::array is used.
Copyright
Copyright (c) 2008-2009 Bjoern Hoehrmann bjoern@hoehrmann.de
See also
 http://bjoern.hoehrmann.de/utf-8/decoder/dfa/
Definition at line 16298 of file json.hpp.
References JSON_ASSERT, and nlohmann::detail::serializer< BasicJsonType >::UTF8_ACCEPT.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
dump()
template<typename BasicJsonType >
void nlohmann::detail::serializer< BasicJsonType >::dump (const BasicJsonType & val, const bool pretty_print, const bool ensure_ascii, const unsigned int indent_step, const unsigned int current_indent = 0) [inline]
internal implementation of the serialization function
This function is called by the public member function dump and organizes the serialization internally. The indentation level is propagated as additional parameter. In case of arrays and objects, the function is called recursively.
strings and object keys are escaped using escape_string()
integer numbers are converted implicitly via operator<<
floating-point numbers are converted to a string using `%g` format
binary values are serialized as objects containing the subtype and the byte array
Parameters
 in val value to serialize
 in pretty_print whether the output shall be pretty-printed
 in ensure_ascii If ensure_ascii is true, all non-ASCII characters in the output are escaped with \uXXXX sequences, and the result consists of ASCII characters only.
 in indent_step the indent level
 in current_indent the current indent level (only used internally)
Definition at line 15533 of file json.hpp.
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::serializer< BasicJsonType >::dump(), nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), nlohmann::detail::serializer< BasicJsonType >::dump_float(), nlohmann::detail::serializer< BasicJsonType >::dump_integer(), nlohmann::detail::serializer< BasicJsonType >::indent_string, JSON_ASSERT, JSON_HEDLEY_UNLIKELY, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::serializer< BasicJsonType >::o, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump().
dump_escaped()
template<typename BasicJsonType >
void nlohmann::detail::serializer< BasicJsonType >::dump_escaped (const string_t & s, const bool ensure_ascii) [inline], [private]
dump escaped string
Escape a string by replacing certain special characters by a sequence of an escape character (backslash) and another character and other control characters by a sequence of `\u` followed by a four-digit hex representation. The escaped string is written to output stream o.
Parameters
 in s the string to escape
 in ensure_ascii whether to escape non-ASCII characters with \uXXXX sequences
@complexity Linear in the length of string s.
Definition at line 15817 of file json.hpp.
References nlohmann::detail::type_error::create(), nlohmann::detail::serializer< BasicJsonType >::decode(), nlohmann::detail::serializer< BasicJsonType >::error_handler, nlohmann::detail::ignore, JSON_ASSERT, JSON_HEDLEY_LIKELY, JSON_THROW, nlohmann::detail::serializer< BasicJsonType >::o, nlohmann::detail::replace, nlohmann::detail::strict, nlohmann::detail::serializer< BasicJsonType >::string_buffer, nlohmann::detail::binary_writer< BasicJsonType, CharType >::to_char_type(), nlohmann::detail::serializer< BasicJsonType >::UTF8_ACCEPT, and nlohmann::detail::serializer< BasicJsonType >::UTF8_REJECT.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump().
dump_float() [1/3]
template<typename BasicJsonType >
void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x) [inline], [private]
dump a floating-point number
Dump a given floating-point number to output stream o. Works internally with number_buffer.
Parameters
 in x floating-point number to dump
Definition at line 16199 of file json.hpp.
References nlohmann::detail::serializer< BasicJsonType >::dump_float(), and nlohmann::detail::serializer< BasicJsonType >::o.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump(), and nlohmann::detail::serializer< BasicJsonType >::dump_float().
dump_float() [2/3]
template<typename BasicJsonType >
void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x, std::false_type) [inline], [private]
Definition at line 16228 of file json.hpp.
References nlohmann::detail::serializer< BasicJsonType >::decimal_point, JSON_ASSERT, nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::serializer< BasicJsonType >::thousands_sep.
dump_float() [3/3]
template<typename BasicJsonType >
void nlohmann::detail::serializer< BasicJsonType >::dump_float (number_float_t x, std::true_type) [inline], [private]
Definition at line 16220 of file json.hpp.
References nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::to_chars().
dump_integer()
template<typename BasicJsonType >
template<typename NumberType , detail::enable_if_t< std::is_same< NumberType, number_unsigned_t >::value||std::is_same< NumberType, number_integer_t >::value||std::is_same< NumberType, binary_char_t >::value, int > = 0>
void nlohmann::detail::serializer< BasicJsonType >::dump_integer (NumberType x) [inline], [private]
dump an integer
Dump a given integer to output stream o. Works internally with number_buffer.
Parameters
 in x integer number (signed or unsigned) to dump
Template Parameters
NumberType either number_integer_t or number_unsigned_t
Definition at line 16113 of file json.hpp.
References nlohmann::detail::serializer< BasicJsonType >::count_digits(), JSON_ASSERT, nlohmann::detail::serializer< BasicJsonType >::number_buffer, nlohmann::detail::serializer< BasicJsonType >::o, and nlohmann::detail::serializer< BasicJsonType >::remove_sign().
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump().
operator=() [1/2]
template<typename BasicJsonType >
serializer & nlohmann::detail::serializer< BasicJsonType >::operator= (const serializer< BasicJsonType > &) [delete]
operator=() [2/2]
template<typename BasicJsonType >
serializer & nlohmann::detail::serializer< BasicJsonType >::operator= (serializer< BasicJsonType > &&) [delete]
remove_sign() [1/2]
template<typename BasicJsonType >
number_unsigned_t nlohmann::detail::serializer< BasicJsonType >::remove_sign (number_integer_t x) [inline], [private], [noexcept]
Definition at line 16352 of file json.hpp.
References JSON_ASSERT.
remove_sign() [2/2]
template<typename BasicJsonType >
number_unsigned_t nlohmann::detail::serializer< BasicJsonType >::remove_sign (number_unsigned_t x) [inline], [private]
Definition at line 16337 of file json.hpp.
References JSON_ASSERT.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_integer().
Member Data Documentation
decimal_point
template<typename BasicJsonType >
const char nlohmann::detail::serializer< BasicJsonType >::decimal_point = '\0' [private]
the locale's decimal point character
Definition at line 16370 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_float().
error_handler
template<typename BasicJsonType >
const error_handler_t nlohmann::detail::serializer< BasicJsonType >::error_handler [private]
error_handler how to react on decoding errors
Definition at line 16381 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
indent_char
template<typename BasicJsonType >
const char nlohmann::detail::serializer< BasicJsonType >::indent_char [private]
the indentation character
Definition at line 16376 of file json.hpp.
indent_string
template<typename BasicJsonType >
string_t nlohmann::detail::serializer< BasicJsonType >::indent_string [private]
the indentation string
Definition at line 16378 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump().
loc
template<typename BasicJsonType >
const std::lconv* nlohmann::detail::serializer< BasicJsonType >::loc = nullptr [private]
the locale
Definition at line 16366 of file json.hpp.
number_buffer
template<typename BasicJsonType >
std::array<char, 64> nlohmann::detail::serializer< BasicJsonType >::number_buffer {{}} [private]
a (hopefully) large enough character buffer
Definition at line 16363 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_float(), and nlohmann::detail::serializer< BasicJsonType >::dump_integer().
o
template<typename BasicJsonType >
output_adapter_t<char> nlohmann::detail::serializer< BasicJsonType >::o = nullptr [private]
the output of the serializer
Definition at line 16360 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump(), nlohmann::detail::serializer< BasicJsonType >::dump_escaped(), nlohmann::detail::serializer< BasicJsonType >::dump_float(), and nlohmann::detail::serializer< BasicJsonType >::dump_integer().
string_buffer
template<typename BasicJsonType >
std::array<char, 512> nlohmann::detail::serializer< BasicJsonType >::string_buffer {{}} [private]
string buffer
Definition at line 16373 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
thousands_sep
template<typename BasicJsonType >
const char nlohmann::detail::serializer< BasicJsonType >::thousands_sep = '\0' [private]
the locale's thousand separator character
Definition at line 16368 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_float().
UTF8_ACCEPT
template<typename BasicJsonType >
constexpr std::uint8_t nlohmann::detail::serializer< BasicJsonType >::UTF8_ACCEPT = 0 [static], [constexpr], [private]
Definition at line 15484 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::decode(), and nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
UTF8_REJECT
template<typename BasicJsonType >
constexpr std::uint8_t nlohmann::detail::serializer< BasicJsonType >::UTF8_REJECT = 1 [static], [constexpr], [private]
Definition at line 15485 of file json.hpp.
Referenced by nlohmann::detail::serializer< BasicJsonType >::dump_escaped().
The documentation for this class was generated from the following file:
Cpp/spatialstructures/src/json.hpp