StopWatch Struct Reference
#include <performance_testing.h>
Public Member Functions
StopWatch (bool auto_start=true)
Create a new clock and start it if auto_start is true.
void StartClock ()
Sets the start time of this trial to the current time.
long long StartToNow () const
Get the time from the start to now in milliseconds.
void StopClock ()
Set the end time of this stopwatch.
long long GetDuration () const
Get the duration from start to end.
Public Attributes
timepoint start {}
timepoint end {}
Detailed Description
Definition at line 19 of file performance_testing.h.
Constructor & Destructor Documentation
StopWatch()
StopWatch::StopWatch (bool auto_start = true) [inline]
Create a new clock and start it if auto_start is true.
Definition at line 25 of file performance_testing.h.
Member Function Documentation
GetDuration()
long long StopWatch::GetDuration () const [inline]
Get the duration from start to end.
Definition at line 46 of file performance_testing.h.
Referenced by TEST().
StartClock()
void StopWatch::StartClock () [inline]
Sets the start time of this trial to the current time.
Definition at line 31 of file performance_testing.h.
Referenced by TEST().
StartToNow()
long long StopWatch::StartToNow () const [inline]
Get the time from the start to now in milliseconds.
Definition at line 36 of file performance_testing.h.
StopClock()
void StopWatch::StopClock () [inline]
Set the end time of this stopwatch.
Definition at line 41 of file performance_testing.h.
Referenced by TEST().
Member Data Documentation
end
timepoint StopWatch::end {}
Definition at line 22 of file performance_testing.h.
start
timepoint StopWatch::start {}
Definition at line 21 of file performance_testing.h.
The documentation for this struct was generated from the following file:
Cpp/tests/src/performance_testing.h