Cpp/tests/src/nanort_raytracer.cpp File Reference
#include <gtest/gtest.h>
#include <string>
#include <objloader.h>
#include <meshinfo.h>
#include <embree_raytracer.h>
#include <robin_hood.h>
#include <cmath>
#include <iostream>
#include <fstream>
#include <view_analysis.h>
#include <HFExceptions.h>
#include <ray_data.h>
#include <objloader_C.h>
#include <raytracer_C.h>
#include `RayRequest.h`
#include `performance_testing.h`
Functions
TEST (_nanoRayTracer, MeshMatching)
TEST (_nanoRayTracer, Edge_Vert_Intersection)
TEST (_nanoRayTracer, NanoRayTracerBasic)
TEST (_nanoRayTracer, nanoRayTolerance)
TEST (_nanoRayTracer, nanoRayPerformance)
Function Documentation
TEST() [1/5]
TEST (_nanoRayTracer , Edge_Vert_Intersection)
Definition at line 74 of file nanort_raytracer.cpp.
References nanort::Ray< T >::dir, HF::nanoGeom::LoadObj(), HF::nanoGeom::nanoRT_BVH(), HF::nanoGeom::nanoRT_Intersect(), nanort::Ray< T >::org, nanoRT_Data::point, and nanoRT_Data::ray.
TEST() [2/5]
TEST (_nanoRayTracer , MeshMatching)
Definition at line 40 of file nanort_raytracer.cpp.
References HF::nanoGeom::Mesh::faces, HF::Geometry::LoadMeshObjects(), HF::nanoGeom::LoadObj(), HF::nanoGeom::Mesh::num_faces, HF::nanoGeom::Mesh::num_vertices, HF::Geometry::ONLY_FILE, and HF::nanoGeom::Mesh::vertices.
TEST() [3/5]
TEST (_nanoRayTracer , nanoRayPerformance)
Definition at line 178 of file nanort_raytracer.cpp.
References nanort::Ray< T >::dir, HF::nanoGeom::LoadObj(), HF::nanoGeom::nanoRT_BVH(), HF::nanoGeom::nanoRT_Intersect(), nanort::Ray< T >::org, nanoRT_Data::point, PrintTrials(), and nanoRT_Data::ray.
TEST() [4/5]
TEST (_nanoRayTracer , nanoRayTolerance)
Definition at line 131 of file nanort_raytracer.cpp.
References nanort::Ray< T >::dir, nanoRT_Data::hit, HF::nanoGeom::LoadObj(), HF::nanoGeom::nanoRT_BVH(), HF::nanoGeom::nanoRT_Intersect(), nanort::Ray< T >::org, nanoRT_Data::point, nanoRT_Data::ray, and nanort::TriangleIntersection< T >::t.
TEST() [5/5]
TEST (_nanoRayTracer , NanoRayTracerBasic)
Definition at line 107 of file nanort_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), and HF::RayTracer::NanoRTRayTracer::PointIntersection().