Cpp/tests/src/OBJLoader.cpp File Reference
#include <gtest/gtest.h>
#include <objloader.h>
#include <meshinfo.h>
#include <HFExceptions.h>
#include <string>
#include `objloader_C.h`
#include `performance_testing.h`
Namespaces
 CInterfaceTests
Macros
#define eigen_plain_assert
Typedefs
using MeshInfo = HF::Geometry::MeshInfo< float >
Functions
void PrintArray (std::array< float, 3 > in_array)
float arrayDist (const std::array< float, 3 > from, const std::array< float, 3 > &to)
void CompareMeshInfo (const MeshInfo &MI1, const MeshInfo &MI2, std::string label1=`MI1`, std::string label2=`MI2`)
void CompareVertArrays (const std::vector< std::array< float, 3 >> &vert_array1, const std::vector< std::array< float, 3 >> &vert_array2, std::string label1=`MI1`, std::string label2=`MI2`)
bool CompareVertArraysUnordered (const std::vector< std::array< float, 3 >> &vert_array1, const std::vector< std::array< float, 3 >> &vert_array2, std::string label1=`MI1`, std::string label2=`MI2`)
TEST (_OBJLoader, CorrectlyProducesOutput)
TEST (_OBJLoader, ThrowMissingFileOnMissingMesh)
TEST (_OBJLoader, VertexCountMatchesModel)
TEST (_OBJLoader, By_File)
TEST (_OBJLoader, By_Material)
TEST (_OBJLoader, Doubles)
TEST (_MeshInfo, ManualRotationEqualsPreset)
TEST (_MeshInfo, RotationToRhinoIsAccurate)
TEST (_MeshInfo, CopyConstructorWorks)
TEST (_MeshInfo, CreationIsDeterministic)
TEST (_MeshInfo, CanDisableRotationOnLoad)
TEST (_MeshInfo, RotationIsDeterministic)
TEST (_MeshInfo, RotationIsReversable)
TEST (_MeshInfo, CanReproduceInputArray)
TEST (_meshInfo, LoadMeshObjectsOne)
The following are tests for the code samples for HF::Geometry.
TEST (_meshInfo, LoadMeshObjectsMany)
TEST (_meshInfo, LoadRawVertices)
TEST (_meshInfo, ConstructorDefault)
end objloader.h
TEST (_meshInfo, ConstructorParamCoordsAsArray)
TEST (_meshInfo, ConstructorParamCoordsAsFloat)
TEST (_meshInfo, AddVertsAsArray)
TEST (_meshInfo, AddVertsAsFloatAndIndices)
TEST (_meshInfo, NumVerts)
TEST (_meshInfo, NumTris)
TEST (_meshInfo, ConvertToRhinoCoordinates)
TEST (_meshInfo, ConvertToOBJCoordinates)
TEST (_meshInfo, PerformRotation)
TEST (_meshInfo, GetMeshID)
TEST (_meshInfo, GetRawVertices)
TEST (_meshInfo, GetRawIndices)
TEST (_meshInfo, GetVertsAsArrays)
TEST (_meshInfo, SetMeshID)
TEST (_meshInfo, OperatorEquality)
TEST (_meshInfo, OperatorIndex)
TEST (_MeshInfo, CopyOperator)
CInterfaceTests::TEST (C_OBJLoader, LoadOBJ)
CInterfaceTests::TEST (C_OBJLoader, StoreMesh)
CInterfaceTests::TEST (C_OBJLoader, RotateMesh)
CInterfaceTests::TEST (C_OBJLoader, GetVertsAndTris)
CInterfaceTests::TEST (C_OBJLoader, GetMeshID)
CInterfaceTests::TEST (C_OBJLoader, GetName)
TEST (Performance, OBJLoader)
Tests how quickly the raytracer can load OBJ files.
Variables
const std::string obj_directiory = `../../Models/`
int CInterfaceTests::mesh_indices [] = { 0, 1, 2 }
const int CInterfaceTests::mesh_num_indices = 3
float CInterfaceTests::mesh_vertices [] = { 34.1, 63.9, 16.5, 23.5, 85.7, 45.2, 12.0, 24.6, 99.4 }
const int CInterfaceTests::mesh_num_vertices = 9
std::string CInterfaceTests::mesh_name = `This mesh`
const int CInterfaceTests::mesh_id = 0
Macro Definition Documentation
eigen_plain_assert
#define eigen_plain_assert
Definition at line 9 of file OBJLoader.cpp.
Typedef Documentation
MeshInfo
using MeshInfo = HF::Geometry::MeshInfo<float>
Definition at line 16 of file OBJLoader.cpp.
Function Documentation
arrayDist()
float arrayDist (const std::array< float, 3 > from, const std::array< float, 3 > & to) [inline]
Definition at line 23 of file OBJLoader.cpp.
Referenced by CompareMeshInfo(), CompareVertArrays(), and CompareVertArraysUnordered().
CompareMeshInfo()
void CompareMeshInfo (const MeshInfo & MI1, const MeshInfo & MI2, std::string label1 = `MI1`, std::string label2 = `MI2`)
Definition at line 27 of file OBJLoader.cpp.
References arrayDist(), HF::Geometry::MeshInfo< numeric_type >::NumVerts(), and PrintArray().
Referenced by TEST().
CompareVertArrays()
void CompareVertArrays (const std::vector< std::array< float, 3 >> & vert_array1, const std::vector< std::array< float, 3 >> & vert_array2, std::string label1 = `MI1`, std::string label2 = `MI2`)
Definition at line 52 of file OBJLoader.cpp.
References arrayDist(), and PrintArray().
Referenced by TEST().
CompareVertArraysUnordered()
bool CompareVertArraysUnordered (const std::vector< std::array< float, 3 >> & vert_array1, const std::vector< std::array< float, 3 >> & vert_array2, std::string label1 = `MI1`, std::string label2 = `MI2`)
Definition at line 79 of file OBJLoader.cpp.
References arrayDist().
Referenced by TEST().
PrintArray()
void PrintArray (std::array< float, 3 > in_array)
Definition at line 18 of file OBJLoader.cpp.
Referenced by CompareMeshInfo(), and CompareVertArrays().
TEST() [1/36]
TEST (_meshInfo , AddVertsAsArray)
Definition at line 376 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::AddVerts(), HF::Geometry::MeshInfo< numeric_type >::GetIndexedVertices(), HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), and HF::Geometry::MeshInfo< numeric_type >::GetUnindexedVertices().
TEST() [2/36]
TEST (_meshInfo , AddVertsAsFloatAndIndices)
Definition at line 402 of file OBJLoader.cpp.
TEST() [3/36]
TEST (_MeshInfo , CanDisableRotationOnLoad)
Definition at line 220 of file OBJLoader.cpp.
References HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [4/36]
TEST (_MeshInfo , CanReproduceInputArray)
Definition at line 249 of file OBJLoader.cpp.
References CompareVertArrays(), HF::Geometry::LoadMeshObjects(), HF::Geometry::LoadRawVertices(), and HF::Geometry::ONLY_FILE.
TEST() [5/36]
TEST (_meshInfo , ConstructorDefault)
end objloader.h
Definition at line 320 of file OBJLoader.cpp.
TEST() [6/36]
TEST (_meshInfo , ConstructorParamCoordsAsArray)
Definition at line 326 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), and HF::Geometry::MeshInfo< numeric_type >::GetUnindexedVertices().
TEST() [7/36]
TEST (_meshInfo , ConstructorParamCoordsAsFloat)
Definition at line 350 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), and HF::Geometry::MeshInfo< numeric_type >::GetUnindexedVertices().
TEST() [8/36]
TEST (_meshInfo , ConvertToOBJCoordinates)
Definition at line 500 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::ConvertToOBJCoordinates(), HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), and HF::Geometry::MeshInfo< numeric_type >::GetUnindexedVertices().
TEST() [9/36]
TEST (_meshInfo , ConvertToRhinoCoordinates)
Definition at line 474 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::ConvertToRhinoCoordinates(), HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), and HF::Geometry::MeshInfo< numeric_type >::GetUnindexedVertices().
TEST() [10/36]
TEST (_MeshInfo , CopyConstructorWorks)
Definition at line 198 of file OBJLoader.cpp.
References CompareMeshInfo(), HF::Geometry::MeshInfo< numeric_type >::ConvertToRhinoCoordinates(), HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [11/36]
TEST (_MeshInfo , CopyOperator)
Definition at line 767 of file OBJLoader.cpp.
TEST() [12/36]
TEST (_MeshInfo , CreationIsDeterministic)
Definition at line 212 of file OBJLoader.cpp.
References CompareMeshInfo(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [13/36]
TEST (_meshInfo , GetMeshID)
Definition at line 552 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), and CInterfaceTests::mesh_id.
TEST() [14/36]
TEST (_meshInfo , GetRawIndices)
Definition at line 618 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::getRawIndices().
TEST() [15/36]
TEST (_meshInfo , GetRawVertices)
Definition at line 573 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::GetIndexedVertices(), and HF::Geometry::MeshInfo< numeric_type >::NumTris().
TEST() [16/36]
TEST (_meshInfo , GetVertsAsArrays)
Definition at line 654 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), and HF::Geometry::MeshInfo< numeric_type >::GetUnindexedVertices().
TEST() [17/36]
TEST (_meshInfo , LoadMeshObjectsMany)
Definition at line 277 of file OBJLoader.cpp.
References HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [18/36]
TEST (_meshInfo , LoadMeshObjectsOne)
The following are tests for the code samples for HF::Geometry.
start objloader.h
Definition at line 263 of file OBJLoader.cpp.
References HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [19/36]
TEST (_meshInfo , LoadRawVertices)
Definition at line 302 of file OBJLoader.cpp.
References HF::Geometry::LoadRawVertices().
TEST() [20/36]
TEST (_MeshInfo , ManualRotationEqualsPreset)
Definition at line 177 of file OBJLoader.cpp.
References CompareMeshInfo(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [21/36]
TEST (_meshInfo , NumTris)
Definition at line 448 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::NumTris().
TEST() [22/36]
TEST (_meshInfo , NumVerts)
Definition at line 424 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::NumVerts().
TEST() [23/36]
TEST (_meshInfo , OperatorEquality)
Definition at line 706 of file OBJLoader.cpp.
TEST() [24/36]
TEST (_meshInfo , OperatorIndex)
Definition at line 741 of file OBJLoader.cpp.
TEST() [25/36]
TEST (_meshInfo , PerformRotation)
Definition at line 526 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), HF::Geometry::MeshInfo< numeric_type >::GetUnindexedVertices(), and HF::Geometry::MeshInfo< numeric_type >::PerformRotation().
TEST() [26/36]
TEST (_MeshInfo , RotationIsDeterministic)
Definition at line 227 of file OBJLoader.cpp.
References CompareMeshInfo(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [27/36]
TEST (_MeshInfo , RotationIsReversable)
Definition at line 237 of file OBJLoader.cpp.
References CompareMeshInfo(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [28/36]
TEST (_MeshInfo , RotationToRhinoIsAccurate)
Definition at line 188 of file OBJLoader.cpp.
References CompareMeshInfo(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [29/36]
TEST (_meshInfo , SetMeshID)
Definition at line 680 of file OBJLoader.cpp.
References HF::Geometry::MeshInfo< numeric_type >::GetMeshID(), and HF::Geometry::MeshInfo< numeric_type >::SetMeshID().
TEST() [30/36]
TEST (_OBJLoader , By_File)
Definition at line 154 of file OBJLoader.cpp.
References GetMeshID(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [31/36]
TEST (_OBJLoader , By_Material)
Definition at line 163 of file OBJLoader.cpp.
References GetMeshID(), HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [32/36]
TEST (_OBJLoader , CorrectlyProducesOutput)
Definition at line 112 of file OBJLoader.cpp.
References CompareVertArraysUnordered(), and HF::Geometry::LoadRawVertices().
TEST() [33/36]
TEST (_OBJLoader , Doubles)
Definition at line 172 of file OBJLoader.cpp.
TEST() [34/36]
TEST (_OBJLoader , ThrowMissingFileOnMissingMesh)
Definition at line 142 of file OBJLoader.cpp.
References HF::Geometry::BY_GROUP, and HF::Geometry::LoadMeshObjects().
TEST() [35/36]
TEST (_OBJLoader , VertexCountMatchesModel)
Definition at line 147 of file OBJLoader.cpp.
References HF::Geometry::LoadRawVertices().
TEST() [36/36]
TEST (Performance , OBJLoader)
Tests how quickly the raytracer can load OBJ files.
TEST(_OBJLoaderCInterface, DestroyMeshInfo) {
 Requires include `objloader_C.h`, include `meshinfo.h`
Prepare parameters for LoadOBJ
relative path begins where EXE file is located if file_path is not a path to a valid OBJ file, HF::Exceptions::FileNotFound is thrown std::string file_path = `big_teapot.obj`;
const int obj_length = file_path.size();
const float x_rot = 30; const float y_rot = 20; const float z_rot = 55;
std::vector<MeshInfo>* info = nullptr;
Call LoadOBJ if (LoadOBJ(file_path.c_str(), obj_length, x_rot, y_rot, z_rot, &info)) { std::cout << `LoadOBJ successful` << std::endl; } else { std::cout << `LoadOBJ unsuccessful` << std::endl; }
Release memory for info once finished with it DestroyMeshInfo(info); }
TEST(_Geometry, GetTestOBJPath) { std::vector<std::string> strings_to_test = { `teapot`, `plane`, `big teapot`, `energy blob`, `sibenik` };
Try to load these names. If a name isn't there is will throw. for (const auto& name : strings_to_test) HF::Geometry::LoadMeshObjects(HF::Geometry::GetTestOBJPath(name));
Try to load a name that doesn't exist. This should throw. try { HF::Geometry::GetTestOBJPath(`meshthatdoesntexist`);
And put an instant fail here in case we actually reach this ASSERT_TRUE(false); } catch (std::out_of_range& e) {
} } }
Definition at line 998 of file OBJLoader.cpp.
References HF::Geometry::GetTestOBJPath(), HF::Geometry::LoadRawVertices(), and PrintTrials().
Variable Documentation
obj_directiory
const std::string obj_directiory = `../../Models/`
Definition at line 14 of file OBJLoader.cpp.