Cpp/tests/src/embree_raytracer.cpp File Reference
#include <gtest/gtest.h>
#include <string>
#include <objloader.h>
#include <meshinfo.h>
#include <embree_raytracer.h>
#include <robin_hood.h>
#include <cmath>
#include <iostream>
#include <fstream>
#include <view_analysis.h>
#include <HFExceptions.h>
#include <objloader_C.h>
#include <raytracer_C.h>
#include `RayRequest.h`
#include `performance_testing.h`
Namespaces
 C_Interface
Functions
EmbreeRayTracer CreateRTWithPlane ()
Create a new raytracer from a basic 10x10 plane centered on the origin.
float Distance (const array< float, 3 > &p1, const array< float, 3 > &p2)
Calc distance between two arrays.
TEST (_Precision, RayTracerConnsistency)
TEST (_EmbreeRayTracer, HashAlgorithm)
TEST (_EmbreeRayTracer, Init)
TEST (_EmbreeRayTracer, Copy)
TEST (_EmbreeRayTracer, EmbreeGarbageCollectCorrect)
TEST (_EmbreeRayTracer, OcclusionRays)
TEST (_EmbreeRayTracer, StandardRays)
TEST (_EmbreeRayTracer, HitPointsAreAccurate)
TEST (_EmbreeRayTracer, RayTolerance)
TEST (_EmbreeRayTracer, EmbreeRayPerformance)
TEST (_EmbreeRayTracer, DeterministicResults)
TEST (_EmbreeRayTracer, PointIntersections)
TEST (_EmbreeRayTracer, Occlusions)
TEST (_EmbreeRayTracer, PointIntersection)
TEST (_EmbreeRayTracer, CastRayArrayOverload)
TEST (_EmbreeRayTracer, Intersect)
TEST (_EmbreeRayTracer, IntersectOutputArguments)
TEST (_EmbreeRayTracer, Occluded)
TEST (_EmbreeRayTracer, CastOcclusionRayArray)
TEST (_EmbreeRayTracer, OccludedSingle)
TEST (_EmbreeRayTracer, AddMesh)
TEST (_EmbreeRayTracer, InsertNewMeshOneMesh)
TEST (_EmbreeRayTracer, InsertNewMeshVecMesh)
TEST (_EmbreeRayTracer, OperatorAssignment)
TEST (_FullRayRequest, ConstructorArgs)
TEST (_FullRayRequest, DidHit)
TEST (Performance, EmbreeRaytracer)
How quickly the raytracer can cast rays directly at a simple plane.
MeshInfo< float > * C_Interface::ConstructExamplePlane ()
EmbreeRayTracer * C_Interface::ConstructTestRaytracer ()
C_Interface::TEST (C_EmbreeRayTracer, CreateRayTracer)
C_Interface::TEST (C_EmbreeRayTracer, AddMesh)
C_Interface::TEST (C_EmbreeRayTracer, NewMeshesCanBeIntersected)
C_Interface::TEST (C_EmbreeRayTracer, ConstructionWithMultipleMeshes)
C_Interface::TEST (C_EmbreeRayTracer, AdditionWithMultipleMeshes)
Function Documentation
CreateRTWithPlane()
EmbreeRayTracer CreateRTWithPlane () [inline]
Create a new raytracer from a basic 10x10 plane centered on the origin.
Definition at line 36 of file embree_raytracer.cpp.
Distance()
float Distance (const array< float, 3 > & p1, const array< float, 3 > & p2) [inline]
Calc distance between two arrays.
Definition at line 51 of file embree_raytracer.cpp.
Referenced by TEST().
TEST() [1/27]
TEST (_EmbreeRayTracer , AddMesh)
Definition at line 731 of file embree_raytracer.cpp.
TEST() [2/27]
TEST (_EmbreeRayTracer , CastOcclusionRayArray)
[EX_Occluded_Array]
[EX_Occluded_Array]
Definition at line 666 of file embree_raytracer.cpp.
References HF::RayTracer::EmbreeRayTracer::Occluded().
TEST() [3/27]
TEST (_EmbreeRayTracer , CastRayArrayOverload)
Definition at line 475 of file embree_raytracer.cpp.
References Distance(), and HF::RayTracer::EmbreeRayTracer::PointIntersection().
TEST() [4/27]
TEST (_EmbreeRayTracer , Copy)
Definition at line 110 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [5/27]
TEST (_EmbreeRayTracer , DeterministicResults)
Definition at line 299 of file embree_raytracer.cpp.
References Distance(), and HF::RayTracer::EmbreeRayTracer::PointIntersections().
TEST() [6/27]
TEST (_EmbreeRayTracer , EmbreeGarbageCollectCorrect)
Definition at line 120 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), HF::RayTracer::EmbreeRayTracer::Occluded(), and HF::Geometry::ONLY_FILE.
TEST() [7/27]
TEST (_EmbreeRayTracer , EmbreeRayPerformance)
Definition at line 255 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), HF::Geometry::ONLY_FILE, and PrintTrials().
TEST() [8/27]
TEST (_EmbreeRayTracer , HashAlgorithm)
Definition at line 90 of file embree_raytracer.cpp.
TEST() [9/27]
TEST (_EmbreeRayTracer , HitPointsAreAccurate)
Definition at line 180 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), HF::Geometry::ONLY_FILE, and plane_path.
TEST() [10/27]
TEST (_EmbreeRayTracer , Init)
Definition at line 103 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [11/27]
TEST (_EmbreeRayTracer , InsertNewMeshOneMesh)
Definition at line 757 of file embree_raytracer.cpp.
References CInterfaceTests::mesh_name.
TEST() [12/27]
TEST (_EmbreeRayTracer , InsertNewMeshVecMesh)
Definition at line 790 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), HF::Geometry::MeshInfo(), and HF::Geometry::ONLY_FILE.
TEST() [13/27]
TEST (_EmbreeRayTracer , Intersect)
[EX_Intersect]
[EX_Intersect]
Definition at line 561 of file embree_raytracer.cpp.
References HF::RayTracer::EmbreeRayTracer::Intersect().
TEST() [14/27]
TEST (_EmbreeRayTracer , IntersectOutputArguments)
Definition at line 595 of file embree_raytracer.cpp.
References HF::RayTracer::EmbreeRayTracer::IntersectOutputArguments().
TEST() [15/27]
TEST (_EmbreeRayTracer , Occluded)
Definition at line 632 of file embree_raytracer.cpp.
References HF::RayTracer::EmbreeRayTracer::Occluded().
TEST() [16/27]
TEST (_EmbreeRayTracer , OccludedSingle)
[EX_Occluded]
[EX_Occluded]
Definition at line 701 of file embree_raytracer.cpp.
References HF::RayTracer::EmbreeRayTracer::Occluded().
TEST() [17/27]
TEST (_EmbreeRayTracer , OcclusionRays)
Definition at line 140 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [18/27]
TEST (_EmbreeRayTracer , Occlusions)
Definition at line 401 of file embree_raytracer.cpp.
TEST() [19/27]
TEST (_EmbreeRayTracer , OperatorAssignment)
Definition at line 839 of file embree_raytracer.cpp.
TEST() [20/27]
TEST (_EmbreeRayTracer , PointIntersection)
Definition at line 442 of file embree_raytracer.cpp.
References Distance(), and HF::RayTracer::EmbreeRayTracer::PointIntersection().
TEST() [21/27]
TEST (_EmbreeRayTracer , PointIntersections)
Definition at line 356 of file embree_raytracer.cpp.
References Distance().
TEST() [22/27]
TEST (_EmbreeRayTracer , RayTolerance)
Definition at line 228 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), HF::Geometry::ONLY_FILE, and plane_path.
TEST() [23/27]
TEST (_EmbreeRayTracer , StandardRays)
Definition at line 159 of file embree_raytracer.cpp.
References HF::Geometry::LoadMeshObjects(), and HF::Geometry::ONLY_FILE.
TEST() [24/27]
TEST (_FullRayRequest , ConstructorArgs)
Definition at line 863 of file embree_raytracer.cpp.
TEST() [25/27]
TEST (_FullRayRequest , DidHit)
Definition at line 882 of file embree_raytracer.cpp.
References HF::RayTracer::RayRequest::didHit().
TEST() [26/27]
TEST (_Precision , RayTracerConnsistency)
Definition at line 59 of file embree_raytracer.cpp.
References HF::RayTracer::RayTriangleIntersection(), and HF::RayTracer::Vector3D::z.
TEST() [27/27]
TEST (Performance , EmbreeRaytracer)
How quickly the raytracer can cast rays directly at a simple plane.
Likely isn't truly indicative of the raytracer's performance, but provides a starting point for other more in depth performance tests. Variations on model complexity and ray direction are suggested.
Definition at line 917 of file embree_raytracer.cpp.
References HF::Geometry::GetTestOBJPath(), HF::Geometry::LoadMeshObjects(), HF::RayTracer::EmbreeRayTracer::PointIntersections(), and PrintTrials().