HumanFactors.Geometry.MeshInfo Class Reference
A collection of vertices and indices representing geometry.
Public Member Functions
int CalculatePresure ()
Calculates the amount of pressure this mesh should exert on the GC.
MeshInfo (int[] indices, float[] vertices, string name=``, int id=0)
Create an instance of MeshInfo from an array of vertices and triangle indices.
void RotateMesh (float xrot, float yrot, float zrot)
Rotate this mesh by the desired magnitude.
void RotateMesh (Vector3D rotation)
Rotate this mesh by the desired magnitude.
override String ToString ()
Public Attributes
int id = -1
ID of the mesh.
string name = ``
Name of the mesh.
DependentNativeArray< float > vertices
An array of all the coordinates for every vertex in the mesh.
DependentNativeArray< int > indices
An array of the indices for every triangle in the mesh.
Protected Member Functions
override bool ReleaseHandle ()
Manually delete this mesh in Unmanaged memory.
Detailed Description
A collection of vertices and indices representing geometry.
Stores a reference to mesh geometry in native memory. Internally, meshes are represented as a 3 by X matrix of vertices and a 3 by X matrix for indices. In the above image, the face list and vertex list are what's held in MeshInfo's Index and Vertex arrays respectively.
Invariant
Will always hold a valid mesh.
Constructor & Destructor Documentation
MeshInfo()
HumanFactors.Geometry.MeshInfo.MeshInfo (int[] indices, float[] vertices, string name = ``, int id = 0)
Create an instance of MeshInfo from an array of vertices and triangle indices.
Parameters
indices An array of indices for the triangles in the mesh. Each integer should correspond to 3 values in vertices , and every 3 integers should represent a complete triangle for the mesh.
vertices Vertices of the mesh. Each 3 floats represent the X,Y, and Z of a point in space
name The name of the mesh. Unused for now.
id The unique identifier for this mesh. If -1, this will automatically be set
Exceptions
HumanFactors.Exceptions.InvalidMeshException The input indices and vertices result in an invalid mesh.
Example
            // These vertices/indices are directly taken from the plane OBJ in example models.
            // Every 3 floats represent the x,y,z locations for a seperate vertex. It takes only
            // 4 vertices to make a plane.
            float[] vertices = {
                -20.079360961914062f, 0.0f, 18.940643310546875f,
                -20.079360961914062f, 0.0f, -18.842348098754883f,
                20.140586853027344f, 0.0f, 18.940643310546875f,
                20.140586853027344f, 0.0f, -18.842348098754883f
            };
            // Every 3 ints represent the indexes of vertices for a seperate triangle.
            int[] indices = {
                3, 1, 0,
                2, 3, 0
            };
            // Construct a new meshinfo instance with these elements
            HumanFactors.Geometry.MeshInfo Mesh = new HumanFactors.Geometry.MeshInfo(indices, vertices);
References HumanFactors.Geometry.MeshInfo.CalculatePresure(), and HumanFactors.NativeUtils.NativeObject.UpdatePressure().
Member Function Documentation
CalculatePresure()
int HumanFactors.Geometry.MeshInfo.CalculatePresure ()
Calculates the amount of pressure this mesh should exert on the GC.
Returns
The approximate size of this mesh in bytes.
Referenced by HumanFactors.Geometry.MeshInfo.MeshInfo().
ReleaseHandle()
override bool HumanFactors.Geometry.MeshInfo.ReleaseHandle () [protected]
Manually delete this mesh in Unmanaged memory.
Remarks
This is called automatically when the class is garbage collected, so don't worry about needing to manually call this. It may be advantageous to deallocate large meshes at specific times for specialized purposes where the garbage collector deleting a large mesh will cause noticable lag.
Returns
True if the handle is released successfully; otherwise, in the event of a catastrophic failure, false. In this case, it generates a releaseHandleFailed MDA Managed Debugging Assistant.
Warning
This deletes the mesh in unmanaged memory! Don't try to use this class again after calling this function!
RotateMesh() [1/2]
void HumanFactors.Geometry.MeshInfo.RotateMesh (float xrot, float yrot, float zrot)
Rotate this mesh by the desired magnitude.
Parameters
xrot Pitch to rotate by in degrees.
yrot Yaw to rotate by in degrees.
zrot Roll to rotate by in degrees.
Remarks
See the other overload for this function for use with CommonRotations.
Example
            // These vertices/indices are directly taken from the plane OBJ in example models.
            // Every 3 floats represent the x,y,z locations for a seperate vertex. It takes only
            // 4 vertices to make a plane.
            float[] vertices = {
                -20.079360961914062f, 0.0f, 18.940643310546875f,
                -20.079360961914062f, 0.0f, -18.842348098754883f,
                20.140586853027344f, 0.0f, 18.940643310546875f,
                20.140586853027344f, 0.0f, -18.842348098754883f
            };
            // Every 3 ints represent the indexes of vertices for a seperate triangle.
            int[] indices = {
                3, 1, 0,
                2, 3, 0
            };
            // Construct a new meshinfo instance with these elements
            HumanFactors.Geometry.MeshInfo Mesh = new HumanFactors.Geometry.MeshInfo(indices, vertices);
            // Rotate the mesh 90 degrees around the X axis
            Mesh.RotateMesh(90, 0, 0);
RotateMesh() [2/2]
void HumanFactors.Geometry.MeshInfo.RotateMesh (Vector3D rotation)
Rotate this mesh by the desired magnitude.
Parameters
rotation How far to rotate the mesh on the X,Y, and Z, axises in degrees.
See also
CommonRotations for commonly used rotations such as Yup to Zup.
Example
            // These vertices/indices are directly taken from the plane OBJ in example models.
            // Every 3 floats represent the x,y,z locations for a seperate vertex. It takes only
            // 4 vertices to make a plane.
            float[] vertices = {
                -20.079360961914062f, 0.0f, 18.940643310546875f,
                -20.079360961914062f, 0.0f, -18.842348098754883f,
                20.140586853027344f, 0.0f, 18.940643310546875f,
                20.140586853027344f, 0.0f, -18.842348098754883f
            };
            // Every 3 ints represent the indexes of vertices for a seperate triangle.
            int[] indices = {
                3, 1, 0,
                2, 3, 0
            };
            // Construct a new meshinfo instance with these elements
            HumanFactors.Geometry.MeshInfo Mesh = new HumanFactors.Geometry.MeshInfo(indices, vertices);
            // Rotate the mesh using a common rotation to convert it from yup to zup
            Mesh.RotateMesh(CommonRotations.Yup_To_Zup);
References HumanFactors.Geometry.MeshInfo.vertices.
The documentation for this class was generated from the following file:
src/Csharp/packages/geometry/src/MeshInfo.cs