HumanFactors.RayTracing.EmbreeBVH Class Reference
A Bounding Volume Hierarchy for the EmbreeRaytracer.
Public Member Functions
EmbreeBVH (MeshInfo MI, bool use_precise=false)
Generate a BVH for an instance of MeshInfo.
EmbreeBVH (MeshInfo[] MI)
Construct a BVH from an array of meshes.
void AddMesh (MeshInfo MI)
Add a new mesh to the BVH.
void AddMesh (MeshInfo[] MI)
Multiple new meshes to the BVH.
Protected Member Functions
override bool ReleaseHandle ()
Free the native memory managed by this class.
Additional Inherited Members
Detailed Description
A Bounding Volume Hierarchy for the EmbreeRaytracer.
Upon calling the constructor for this class, a Bounding Volume Hierarchy is generated for the RayTracing.EmbreeRaytracer. Without this structure, the raytracer cannot be used.
Remarks
A more detailed description of Embree's BVH is available in intel's paper: Embree: A Kernel Framework for Efficient CPU Ray Tracing http://cseweb.ucsd.edu/~ravir/274/15/papers/a143-wald.pdf.
See also
EmbreeRaytracer for functions to use this BVH for ray intersections.
Constructor & Destructor Documentation
EmbreeBVH() [1/2]
HumanFactors.RayTracing.EmbreeBVH.EmbreeBVH (MeshInfo MI, bool use_precise = false)
Generate a BVH for an instance of MeshInfo.
Parameters
MI Mesh to generate the BVH from.
use_precise Increase the accuracy of all ray intersections at the cost of performance.
Exceptions
Exception Embree failed to create a BVH for the given mesh.
Example
            // Load an OBJ from a filepath into a new meshinfo instance
            string good_mesh_path = "ExampleModels/plane.obj";
            MeshInfo Mesh = OBJLoader.LoadOBJ(good_mesh_path, CommonRotations.Yup_To_Zup);
            // Construct a BVH from the mesh
            EmbreeBVH BVH = new EmbreeBVH(Mesh);
EmbreeBVH() [2/2]
HumanFactors.RayTracing.EmbreeBVH.EmbreeBVH (MeshInfo[] MI)
Construct a BVH from an array of meshes.
\params MI Meshes to build the BVH from.
References HumanFactors.NativeUtils.NativeObject.pressure, and HumanFactors.NativeUtils.NativeObject.UpdatePressure().
Member Function Documentation
AddMesh() [1/2]
void HumanFactors.RayTracing.EmbreeBVH.AddMesh (MeshInfo MI)
Add a new mesh to the BVH.
Parameters
MI Meshinfo to add to this bvh. The ID of this MeshInfo will be updated if that ID is already occupied by another mesh in the BVH.
Example
Demonstrating that the BVH changes after the addition of new meshes.
            // Load a lot of submeshes from sponza
            var MeshInfos = OBJLoader.LoadOBJSubmeshes("ExampleModels/sponza.obj", GROUP_METHOD.BY_GROUP);
            var Plane = OBJLoader.LoadOBJ("ExampleModels/plane.obj");
            
            // Construct a BVH from the plane
            EmbreeBVH bvh = new EmbreeBVH(Plane);
           
            // Cast rays and print the results
            Debug.WriteLine("--- Just Plane---");
            Vector3D[] origins = { new Vector3D(1, 1, 1), new Vector3D(1, 1, 1) };
            Vector3D[] directions = { new Vector3D(0, 0, -1), new Vector3D(0, -1, 0) };
            bool[] results = EmbreeRaytracer.IntersectOccluded(bvh, origins, directions);
            string out_str = directions[0].ToString() + (results[0] ? "Intersected" : "Did not Intersect") + "\n";
            out_str += directions[1].ToString() + (results[1] ? "Intersected" : "Did not Intersect");
            Debug.WriteLine(out_str);
            
            // Add meshes to the BVH
            bvh.AddMesh(MeshInfos);
            // Cast rays again and see if the second ray connects
            Debug.WriteLine("--- After Addition---");
            bool[] post_addition_results = EmbreeRaytracer.IntersectOccluded(bvh, origins, directions);
            string post_addition_out_str = directions[0].ToString() + (post_addition_results[0] ? "Intersected" : "Did not Intersect") + "\n";
            post_addition_out_str += directions[1].ToString() + (post_addition_results[1] ? "Intersected" : "Did not Intersect");
            Debug.WriteLine(post_addition_out_str);
 --- Just Plane---
(0, 0, -1)Did not Intersect
(0, -1, 0)Intersected
--- After Addition---
(0, 0, -1)Intersected
(0, -1, 0)Intersected
References HumanFactors.NativeUtils.NativeObject.pressure, and HumanFactors.NativeUtils.NativeObject.UpdatePressure().
AddMesh() [2/2]
void HumanFactors.RayTracing.EmbreeBVH.AddMesh (MeshInfo[] MI)
Multiple new meshes to the BVH.
Parameters
MI Meshinfo to add to this bvh. The ID of this MeshInfo will be updated if that ID is already occupied by another mesh in the BVH.
Example
Demonstrating that the BVH changes after the addition of new meshes.
            // Load a lot of submeshes from sponza
            var MeshInfos = OBJLoader.LoadOBJSubmeshes("ExampleModels/sponza.obj", GROUP_METHOD.BY_GROUP);
            var Plane = OBJLoader.LoadOBJ("ExampleModels/plane.obj");
            
            // Construct a BVH from the plane
            EmbreeBVH bvh = new EmbreeBVH(Plane);
           
            // Cast rays and print the results
            Debug.WriteLine("--- Just Plane---");
            Vector3D[] origins = { new Vector3D(1, 1, 1), new Vector3D(1, 1, 1) };
            Vector3D[] directions = { new Vector3D(0, 0, -1), new Vector3D(0, -1, 0) };
            bool[] results = EmbreeRaytracer.IntersectOccluded(bvh, origins, directions);
            string out_str = directions[0].ToString() + (results[0] ? "Intersected" : "Did not Intersect") + "\n";
            out_str += directions[1].ToString() + (results[1] ? "Intersected" : "Did not Intersect");
            Debug.WriteLine(out_str);
            
            // Add meshes to the BVH
            bvh.AddMesh(MeshInfos);
            // Cast rays again and see if the second ray connects
            Debug.WriteLine("--- After Addition---");
            bool[] post_addition_results = EmbreeRaytracer.IntersectOccluded(bvh, origins, directions);
            string post_addition_out_str = directions[0].ToString() + (post_addition_results[0] ? "Intersected" : "Did not Intersect") + "\n";
            post_addition_out_str += directions[1].ToString() + (post_addition_results[1] ? "Intersected" : "Did not Intersect");
            Debug.WriteLine(post_addition_out_str);
 --- Just Plane---
(0, 0, -1)Did not Intersect
(0, -1, 0)Intersected
--- After Addition---
(0, 0, -1)Intersected
(0, -1, 0)Intersected
References HumanFactors.NativeUtils.NativeObject.pressure, and HumanFactors.NativeUtils.NativeObject.UpdatePressure().
ReleaseHandle()
override bool HumanFactors.RayTracing.EmbreeBVH.ReleaseHandle () [protected]
Free the native memory managed by this class.
Note
the garbage collector will handle this automatically
Warning
Do not attempt to use this class after freeing it!
Returns
True. This is guaranteed to execute properly.
The documentation for this class was generated from the following file:
src/Csharp/packages/raytracer/src/EmbreeBVH.cs