""" 
Determine which locations are visible from other locations.
============================================================


The visibility graph is generated by casting a ray between several
view points to check if they have a line of sight to eachother.
If two points can see each other, an edge is created between them.
This can be used to determine how visibile an observer is to others 
from a specific point in the environment and just how good that
visibility is. 
"""


# from .visibility_graph import VisibilityGraphAllToAll, VisibilityGraphUndirectedAllToAll, VisibilityGraphGroupToGroup
from .visibility_graph import *