HumanFactors.RayTracing.NativeMethods Class Reference
Static Package Functions
static IntPtr C_ConstructRaytracer (IntPtr mesh_info_ptr)
static Vector3D C_IntesectPoint (IntPtr rt_ptr, float x, float y, float z, float dx, float dy, float dz, float max_distance=-1)
static Vector3D[] C_IntersectPoints (IntPtr ert, IEnumerable< Vector3D > origins, IEnumerable< Vector3D > directions, float max_distance)
cs the intersect points.
static CVectorAndData C_IntersectRays (IntPtr ray_tracer, IEnumerable< Vector3D > origins, IEnumerable< Vector3D > directions, float max_distance)
static bool[] C_FireOcclusionRays (IntPtr rt_ptr, IEnumerable< Vector3D > origins, IEnumerable< Vector3D > directions, float max_distance)
static RayResult C_IntersectRay (IntPtr rt_ptr, Vector3D origin, Vector3D direction, float max_distance)
static void C_DestroyRayTracer (IntPtr rt_ptr)
static void C_DestroyRayResults (IntPtr ray_ptr)
Private Member Functions
static HF_STATUS CreateRaytracer (IntPtr mesh, ref IntPtr out_raytracer)
static HF_STATUS FireRay (IntPtr ert, ref float x, ref float y, ref float z, float dx, float dy, float dz, float max_distance, ref bool result)
static HF_STATUS FireSingleRayDistance (IntPtr ert, [In] float[] origin, [In] float[] direction, float max_distance, ref float out_distance, ref int out_meshid)
static HF_STATUS FireMultipleRays (IntPtr ert, [In, Out] float[] origins, float[] directions, int size, float max_distance, [MarshalAs(UnmanagedType.LPArray, ArraySubType=UnmanagedType.I1)][Out]bool[] result_array)
static HF_STATUS FireMultipleDirectionsOneOrigin (IntPtr bvh, [In] float[] origin, [In] float[] directions, int size, float max_distance, [MarshalAs(UnmanagedType.LPArray, ArraySubType=UnmanagedType.I1)][Out] bool[] result_array)
static HF_STATUS FireMultipleOriginsOneDirection (IntPtr bvh, [In] float[] origin, [In] float[] directions, int size, float max_distance, [MarshalAs(UnmanagedType.LPArray, ArraySubType=UnmanagedType.I1)][Out] bool[] result_array)
static HF_STATUS FireOcclusionRays (IntPtr bvh, [In] float[] origins, [In] float[] directions, int origin_size, int direction_size, float max_distance, [MarshalAs(UnmanagedType.LPArray, ArraySubType=UnmanagedType.I1)][Out] bool[] result_array)
static HF_STATUS DestroyRayTracer (IntPtr MeshPointer)
static HF_STATUS DestroyRayResultVector (IntPtr analysis)
static HF_STATUS FireRaysDistance (IntPtr ert, [In] float[] origins, int num_origins, [In] float[] directions, int num_directions, ref IntPtr out_results, ref IntPtr out_data)
Static Private Attributes
const string dllpath = NativeConstants.DLLPath
Detailed Description
Definition at line 17 of file RayTracerNative.cs.
Member Function Documentation
C_ConstructRaytracer()
static IntPtr HumanFactors.RayTracing.NativeMethods.C_ConstructRaytracer (IntPtr mesh_info_ptr) [static], [package]
Definition at line 21 of file RayTracerNative.cs.
References HumanFactors.RayTracing.NativeMethods.CreateRaytracer().
C_DestroyRayResults()
static void HumanFactors.RayTracing.NativeMethods.C_DestroyRayResults (IntPtr ray_ptr) [static], [package]
Referenced by HumanFactors.RayTracing.RayResults.ReleaseHandle().
C_DestroyRayTracer()
static void HumanFactors.RayTracing.NativeMethods.C_DestroyRayTracer (IntPtr rt_ptr) [static], [package]
Referenced by HumanFactors.RayTracing.EmbreeBVH.ReleaseHandle().
C_FireOcclusionRays()
static bool [] HumanFactors.RayTracing.NativeMethods.C_FireOcclusionRays (IntPtr rt_ptr, IEnumerable< Vector3D > origins, IEnumerable< Vector3D > directions, float max_distance) [static], [package]
Definition at line 120 of file RayTracerNative.cs.
References HumanFactors.RayTracing.NativeMethods.FireOcclusionRays(), and HumanFactors.NativeUtils.HelperFunctions.FlattenVectorArray().
C_IntersectPoints()
static Vector3D [] HumanFactors.RayTracing.NativeMethods.C_IntersectPoints (IntPtr ert, IEnumerable< Vector3D > origins, IEnumerable< Vector3D > directions, float max_distance) [static], [package]
cs the intersect points.
Parameters
ert The ert.
origins The origins.
directions The directions.
max_distance The maximum distance.
Returns
Exceptions
System.ArgumentException Arguments did not match one of the predefined cases!
System.Exception Multiple rays failed to fire
Definition at line 52 of file RayTracerNative.cs.
References HumanFactors.RayTracing.NativeMethods.FireMultipleDirectionsOneOrigin(), HumanFactors.RayTracing.NativeMethods.FireMultipleOriginsOneDirection(), HumanFactors.RayTracing.NativeMethods.FireMultipleRays(), and HumanFactors.NativeUtils.HelperFunctions.FloatArrayToVectorArray().
C_IntersectRay()
static RayResult HumanFactors.RayTracing.NativeMethods.C_IntersectRay (IntPtr rt_ptr, Vector3D origin, Vector3D direction, float max_distance) [static], [package]
Definition at line 147 of file RayTracerNative.cs.
References HumanFactors.RayTracing.NativeMethods.FireSingleRayDistance(), HumanFactors.Vector3D.x, HumanFactors.Vector3D.y, and HumanFactors.Vector3D.z.
C_IntersectRays()
static CVectorAndData HumanFactors.RayTracing.NativeMethods.C_IntersectRays (IntPtr ray_tracer, IEnumerable< Vector3D > origins, IEnumerable< Vector3D > directions, float max_distance) [static], [package]
Definition at line 89 of file RayTracerNative.cs.
References HumanFactors.RayTracing.NativeMethods.FireRaysDistance(), and HumanFactors.NativeUtils.HelperFunctions.FlattenVectorArray().
C_IntesectPoint()
static Vector3D HumanFactors.RayTracing.NativeMethods.C_IntesectPoint (IntPtr rt_ptr, float x, float y, float z, float dx, float dy, float dz, float max_distance = -1) [static], [package]
Definition at line 33 of file RayTracerNative.cs.
References HumanFactors.RayTracing.NativeMethods.FireRay().
CreateRaytracer()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.CreateRaytracer (IntPtr mesh, ref IntPtr out_raytracer) [private]
Referenced by HumanFactors.RayTracing.NativeMethods.C_ConstructRaytracer().
DestroyRayResultVector()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.DestroyRayResultVector (IntPtr analysis) [private]
DestroyRayTracer()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.DestroyRayTracer (IntPtr MeshPointer) [private]
FireMultipleDirectionsOneOrigin()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.FireMultipleDirectionsOneOrigin (IntPtr bvh, [In] float[] origin, [In] float[] directions, int size, float max_distance, [Out] bool[] result_array) [private]
Referenced by HumanFactors.RayTracing.NativeMethods.C_IntersectPoints().
FireMultipleOriginsOneDirection()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.FireMultipleOriginsOneDirection (IntPtr bvh, [In] float[] origin, [In] float[] directions, int size, float max_distance, [Out] bool[] result_array) [private]
Referenced by HumanFactors.RayTracing.NativeMethods.C_IntersectPoints().
FireMultipleRays()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.FireMultipleRays (IntPtr ert, [In, Out] float[] origins, float[] directions, int size, float max_distance, [Out] bool[] result_array) [private]
Referenced by HumanFactors.RayTracing.NativeMethods.C_IntersectPoints().
FireOcclusionRays()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.FireOcclusionRays (IntPtr bvh, [In] float[] origins, [In] float[] directions, int origin_size, int direction_size, float max_distance, [Out] bool[] result_array) [private]
Referenced by HumanFactors.RayTracing.NativeMethods.C_FireOcclusionRays().
FireRay()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.FireRay (IntPtr ert, ref float x, ref float y, ref float z, float dx, float dy, float dz, float max_distance, ref bool result) [private]
Referenced by HumanFactors.RayTracing.NativeMethods.C_IntesectPoint().
FireRaysDistance()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.FireRaysDistance (IntPtr ert, [In] float[] origins, int num_origins, [In] float[] directions, int num_directions, ref IntPtr out_results, ref IntPtr out_data) [private]
Referenced by HumanFactors.RayTracing.NativeMethods.C_IntersectRays().
FireSingleRayDistance()
static HF_STATUS HumanFactors.RayTracing.NativeMethods.FireSingleRayDistance (IntPtr ert, [In] float[] origin, [In] float[] direction, float max_distance, ref float out_distance, ref int out_meshid) [private]
Referenced by HumanFactors.RayTracing.NativeMethods.C_IntersectRay().
Member Data Documentation
dllpath
const string HumanFactors.RayTracing.NativeMethods.dllpath = NativeConstants.DLLPath [static], [private]
Definition at line 19 of file RayTracerNative.cs.
The documentation for this class was generated from the following file:
src/Csharp/packages/raytracer/src/RayTracerNative.cs