HumanFactors.SpatialStructures.Graph Class Reference
A graph representing connections between points in space.
Public Member Functions
Graph ()
Construct a new empty graph in unmanaged memory.
void AddEdge (Vector3D parent, Vector3D child, float cost, string cost_type=``)
Create a new edge between parent and child with cost.
void AddEdge (int parent_id, int child_id, float cost, string cost_type=``)
Create a new edge between parent and child with cost.
NodeList getNodes ()
Garray containing the graph's current nodes.
CSRInfo CompressToCSR (string cost_type=``)
Compress the graph into a CSR representation, and get pointers to it.
ManagedFloatArray AggregateEdgeCosts (GraphEdgeAggregation type, bool directed=true, string cost_type=``)
Summarize the edgecosts of every node in the graph.
float GetCost (int parent, int child, string cost_type=``)
Get the cost of traversing between parent and child
int GetNodeID (Vector3D node)
Gets the ID of a node in the graph.
void AddNodeAttribute (int id, string attribute, string score)
Define a node attribute for the node at id.
void AddNodeAttribute (string attribute, IEnumerable< int > ids, IEnumerable< string > scores)
Add attribute to all node in ids, with their respective score in scores.
string[] GetNodeAttributes (string attribute)
Get the score of every node for a given attribute.
void ClearNodeAttributes (string attribute)
Clear an attribute and all of its scores from the graph.
int NumNodes ()
Get the number of nodes in this graph.
Protected Member Functions
override bool ReleaseHandle ()
Free the native memory managed by this class.
Package Functions
Graph (IntPtr GraphPtr)
Wrap a graph that already exists in unmanaged memory.
Parameters
GraphPtr Pointer to the grpah in unmanaged memory
Private Attributes
CSRInfo CSRPointers
This graph's CSR pointers.
Additional Inherited Members
Detailed Description
A graph representing connections between points in space.
Every Node in the graph contains an X,Y,Z coordinate which can be used to represent a specific point in space. This graph internally is stored as a Sparse Matrix for space efficency. Nodes are stored in a hashmap containing X,Y, and Z coordinates, allowing for quick indexing of specific nodes by location alone. Access to this graph's internal CSR is available through Graph.CompressToCSR().
Cost Types
This Graph is capable of holding multiple cost types for any of it's edges. Each cost type has a distinct key as it's name, such as `CrossSlope` or `EnergyExpenditure`. Upon creation, the graph is assigned a default cost type, Distance which can be accessed explicitly by the key `Distance` or leaving the cost_type field blank. Alternate costs have corresponding edges in the default cost set, but different costs to traverse from the parent to the child node.
NodeAttributes
The graph is able to store an arbitrary amount of information about the nodes it contains as strings. Similar to alternate cost types, node attributes are each have a distinct key as their name, but instead of conatining information about edges in the graph, node attributes contain information about nodes. Unlike the cost algorithms in edgecosts, right now there is no functionality within HumanFactors that populates the node attributes of the graph with any kind of metric, however the methods to add and clear node attributes are made available so you are free to add your own node attributes.
Invariant
1) The CSR maintained by this graph will always be valid.
2) Every unique unique node in the graph will be assigned a unique id. A Node is considered unique if it has an X,Y,Z location that is not within 0.0001 units of any other node in the graph.
Note
The graph offers some basic functionality to add edges and nodes but it's main use is to provide access to the output of the GraphGenerator and VisibilityGraph. If adding edges or alternate cost types please make sure to read the documentation for these functions and that all preconditions are followed.
Todo
Todo Functions to access edges in the graph like numpy. Users shouldn't have to use unsafe functions to get the edges of a node from the CSR.
See also
CompressToCSR to get a CSR representation of the graph.
Definition at line 95 of file Graph.cs.
Constructor & Destructor Documentation
Graph() [1/2]
HumanFactors.SpatialStructures.Graph.Graph (IntPtr GraphPtr) [package]
Wrap a graph that already exists in unmanaged memory.
Parameters
GraphPtr Pointer to the grpah in unmanaged memory
Definition at line 102 of file Graph.cs.
Graph() [2/2]
HumanFactors.SpatialStructures.Graph.Graph ()
Construct a new empty graph in unmanaged memory.
Definition at line 105 of file Graph.cs.
Member Function Documentation
AddEdge() [1/2]
void HumanFactors.SpatialStructures.Graph.AddEdge (int parent_id, int child_id, float cost, string cost_type = ``)
Create a new edge between parent and child with cost.
Parameters
parent_id The ID of the parent node.
child_id The ID of the child node.
cost cost from parent to child.
cost_type The type of cost to add this edge to. If left blank will add the edge to the graph's default cost type.
Precondition
1) If adding edges to a new cost type, the graph must first be compressed by calling CompressToCSR()
2) If adding a cost to a type that isn't the default cost type, the edge must already exist in the default cost type.
3) If the graph has already been compressed and alternate costs exist, then both parent and child already exist in the graph.
Postcondition
1) If the ID of either parent or child does not exist in the graph then New IDs will be assigned to them.
2) Existing representations of the this graph's CSR will be invalidated.
3) If cost_type is not blank, and does not refer to the default cost type or any other cost that already exists in the graph, a new cost type will be created.
Exceptions
LogicError tried to add an alternate cost to the graph before it was compressed
InvalidCostOperation Tried to add an alternate cost that doesn't exist in the graph's default cost type.
Warning
1) If an edge between parent and child already exists, this will overwrite that edge.
2) Calling this function will invalidate any existing CSRPtrs returned from the graph. Make sure to call CompressToCSR again continuing to access it.
AddEdge() [2/2]
void HumanFactors.SpatialStructures.Graph.AddEdge (Vector3D parent, Vector3D child, float cost, string cost_type = ``)
Create a new edge between parent and child with cost.
Parameters
parent The X,Y,Z location for the parent node.
child x,y,z location for the child
cost cost for parent to child
cost_type The type of cost to add the edge to.
\Attention This overload is meant for debugging. There are many issues that can occur with adding integers to the graph that don't already have nodes assigned. Instead use the overload of this function deals with vector 3.
Precondition
1) If adding edges to a new cost type, the graph has been compressed by calling CompressToCSR().
2) If adding a cost to a type that isn't the default cost type, the edge must already exist in the default cost type.
3) If the graph has already been compressed and alternate costs exist, then both parent and child already exist in the graph.
Postcondition
1) If the ID of either parent or child does not exist in the graph then New IDs will be assigned to them.
2) Existing representations of the this graph's CSR will be invalidated.
3) If cost_type is not blank, and does not refer to the default cost type or any other cost that already exists in the graph, a new cost type will be created.
Exceptions
LogicError tried to add an alternate cost to the graph before it was compressed
InvalidCostOperation Tried to add an alternate cost that doesn't exist in the graph's default cost type.
Warning
1) If an edge between parent and child already exists, this will overwrite that edge.
2) Calling this function will invalidate any existing CSRPtrs returned from the graph. Make sure to call CompressToCSR again continuing to access it.
AddNodeAttribute() [1/2]
void HumanFactors.SpatialStructures.Graph.AddNodeAttribute (int id, string attribute, string score)
Define a node attribute for the node at id.
Parameters
id The ID of the node that will receive attribute.
attribute The name of the attribute to use.
score The score for attribute to store for this node.
Example
// Create a graph and add two edges to create nodes
Graph g = new Graph();
g.AddEdge(0, 1, 150);
g.AddEdge(0, 2, 100);
g.AddEdge(0, 3, 2);
// Add node attributes to the graph for the nodes
// we just created
g.AddNodeAttribute(2, "Attr", "200");
g.AddNodeAttribute(1, "Attr", "100");
g.AddNodeAttribute(0, "Attr", "0");
// Get scores for this attribute from the graph
var attr = g.GetNodeAttributes("Attr");
// Print results
foreach (var attribute in attr)
    Debug.WriteLine(attribute);
 >>> 0
>>> 100
>>> 200
Definition at line 335 of file Graph.cs.
AddNodeAttribute() [2/2]
void HumanFactors.SpatialStructures.Graph.AddNodeAttribute (string attribute, IEnumerable< int > ids, IEnumerable< string > scores)
Add attribute to all node in ids, with their respective score in scores.
Parameters
ids IDs of nodes to assign scores to for attribute
attribute Name of the attribute to assigns cores to for each node in ids
scores Ordered ids of scores to add to the node at the id in ids at the same index
Precondition
the length of ids and scores must match
Example
// Create a graph and add two edges to create nodes
Graph g = new Graph();
g.AddEdge(0, 1, 150);
g.AddEdge(0, 2, 100);
// Create arrays for ids and scores
int[] ids = { 0, 1, 2 };
string[] scores = { "0", "100", "200" };
// Add them to the graph
g.AddNodeAttribute("Attr", ids, scores);
// Get scores for this attribute from the graph
var attr = g.GetNodeAttributes("Attr");
foreach (var attribute in attr)
    Debug.WriteLine(attribute);
>>> 0
>>> 100
>>> 200
Definition at line 375 of file Graph.cs.
References HumanFactors.NativeUtils.NativeObject.Pointer.
AggregateEdgeCosts()
ManagedFloatArray HumanFactors.SpatialStructures.Graph.AggregateEdgeCosts (GraphEdgeAggregation type, bool directed = true, string cost_type = ``)
Summarize the edgecosts of every node in the graph.
Parameters
type The type of aggregation method to use.
directed Whether or not the graph is directed. If set to true then each nodes's score will only consider incomning edges. Otherwise, each node's score will consider both outgoing and incoming edges.
cost_type The type of cost to use for aggregating the edges.
Returns
An array of scores, in which each element corresponds to a node in the graph sorted by ID.
Precondition
If not left blank, cost_type must point to a valid cost in the graph.
Exceptions
KeyNotFoundException Cost specified didn't match the default cost, or any other cost type defined in the graph.
Warning
This will compress the graph if it is not compressed already. If any edges were added between lat call to CompressToCSR and now, then any active CSRPtrs will be invalidated.
Remarks
The order of the scores returned bythis function match the order of the scores returned from Graph.getNodes. This can be especially useful for summarizing the results of a VisibilityGraph.
Definition at line 242 of file Graph.cs.
References HumanFactors.SpatialStructures.NativeMethods.C_AggregateEdgeCosts(), HumanFactors.SpatialStructures.Graph.CompressToCSR(), HumanFactors.SpatialStructures.Graph.NumNodes(), and HumanFactors.NativeUtils.CVectorAndData.size.
ClearNodeAttributes()
void HumanFactors.SpatialStructures.Graph.ClearNodeAttributes (string attribute)
Clear an attribute and all of its scores from the graph.
Parameters
attribute The unique key of the attribute to clear from the graph.
Example
// Create a graph and add two edges to create nodes
Graph g = new Graph();
g.AddEdge(0, 1, 150);
g.AddEdge(0, 2, 100);
// Create arrays for ids and scores
int[] ids = { 0, 1, 2 };
string[] scores = { "0", "100", "200" };
// Add them to the graph
g.AddNodeAttribute("Attr", ids, scores);
// Now try to delete
g.ClearNodeAttributes("Attr");
// check that this is truly gone
var node_attrs = g.GetNodeAttributes("Attr");
Debug.WriteLine(node_attrs.size());
 >>> 0
Definition at line 444 of file Graph.cs.
References HumanFactors.SpatialStructures.NativeMethods.C_ClearAttributeType(), and HumanFactors.NativeUtils.NativeObject.Pointer.
CompressToCSR()
CSRInfo HumanFactors.SpatialStructures.Graph.CompressToCSR (string cost_type = ``)
Compress the graph into a CSR representation, and get pointers to it.
Parameters
cost_type Change the type of cost that's carried in the CSR's values array. If left blank, will use the graph's default cost type.
Remarks
The CSR pointers can be mapped to after retrieved from C++ using spans, or can be copied out of managed memory.
Exceptions
KeyNotFoundException cost_type is not blank, the name of the graph's default cost type, or the name of any already defined cost type in the graph.
See also
CSRPtrs for more info on the CSR type and how to access it.
Definition at line 207 of file Graph.cs.
References HumanFactors.SpatialStructures.NativeMethods.C_GetCSRPointers(), and HumanFactors.SpatialStructures.Graph.CSRPointers.
Referenced by HumanFactors.SpatialStructures.Graph.AggregateEdgeCosts().
GetCost()
float HumanFactors.SpatialStructures.Graph.GetCost (int parent, int child, string cost_type = ``)
Get the cost of traversing between parent and child
Parameters
parent Node that's being traversed from
child Node that's being traversed to
cost_type The cost type to retrieve. If blank, the graph's default cost will be used.
Returns
The cost of traversing from parent to child.
Precondition
1) cost_type must be the name of a cost that already exists in the graph, or blank.
2) The graph must first have been compressed using Graph.CompressToCSR().
Exceptions
LogicError The graph wasn't compressed before calling this function.
KeyNotFoundExeption The cost_type specified was not the default cost, blank, or the name of any cost that currently belongs to the graph.
Note
This is not a high performance function, since each index into the CSR requires an indexing operation. If multiple values are required, it is suggested to iterate through the pointers from Graph.CompressToCSR().
Definition at line 277 of file Graph.cs.
References HumanFactors.SpatialStructures.NativeMethods.C_GetEdgeCost(), and HumanFactors.NativeUtils.NativeObject.Pointer.
GetNodeAttributes()
string [] HumanFactors.SpatialStructures.Graph.GetNodeAttributes (string attribute)
Get the score of every node for a given attribute.
Parameters
attribute The unique name of the attribute type to get from the graph fopr every node
Returns
If an attribute with the name of attribute, type was found in the graph, then an array of scores for each node is returned in order of ID. For example, the score of the node with id 10 would be stored at index 10, id 12 stored at index 12, etc. Nodes without scores for attribute will have empty strings at their indexes.
If attribute didn't exist in the graph, then an empty array of strings will be returned.
// TODO example
Definition at line 410 of file Graph.cs.
References HumanFactors.SpatialStructures.NativeMethods.C_GetNodeAttributes(), HumanFactors.SpatialStructures.Graph.NumNodes(), and HumanFactors.NativeUtils.NativeObject.Pointer.
GetNodeID()
int HumanFactors.SpatialStructures.Graph.GetNodeID (Vector3D node)
Gets the ID of a node in the graph.
Parameters
node The X,Y,Z position of a node to get the ID for.
Returns
The ID of the node, or -1 if the node isn't in the graph.
Referenced by HumanFactors.Pathfinding.ShortestPath.DijkstraShortestPath().
getNodes()
NodeList HumanFactors.SpatialStructures.Graph.getNodes ()
Garray containing the graph's current nodes.
Returns
An array of the graph's current nodes ordered by ID.
NumNodes()
int HumanFactors.SpatialStructures.Graph.NumNodes ()
Get the number of nodes in this graph.
Returns
The number of currently defined nodes in this graph
Remarks
This is used multiple times internally to get the size of the graph without needing to get its nodes.
Referenced by HumanFactors.SpatialStructures.Graph.AggregateEdgeCosts(), HumanFactors.Pathfinding.ShortestPath.DijkstraAllToAll(), and HumanFactors.SpatialStructures.Graph.GetNodeAttributes().
ReleaseHandle()
override bool HumanFactors.SpatialStructures.Graph.ReleaseHandle () [protected]
Free the native memory managed by this class.
Note
the garbage collector will handle this automatically
Warning
Do not attempt to use this class after freeing it!
Returns
True. This is guaranteed to execute properly.
Definition at line 297 of file Graph.cs.
References HumanFactors.SpatialStructures.NativeMethods.C_DestroyGraph().
Member Data Documentation
CSRPointers
CSRInfo HumanFactors.SpatialStructures.Graph.CSRPointers [private]
This graph's CSR pointers.
Definition at line 98 of file Graph.cs.
Referenced by HumanFactors.SpatialStructures.Graph.CompressToCSR().
The documentation for this class was generated from the following file:
src/Csharp/packages/spatialstructures/src/Graph.cs