HumanFactors.ViewAnalysis.NativeMethods Class Reference
Static Package Functions
static CVectorAndData C_SphericalViewAnalysisAggregate (IntPtr ert, IEnumerable< Vector3D > nodes, int ray_count, float upward_fov, float downward_fov, float height, ViewAggregateType AT)
static CVectorAndData C_SphericalViewAnalysisNoAggregate (IntPtr ert, IEnumerable< Vector3D > nodes, int ray_count, float upward_fov, float downward_fov, float height)
static CVectorAndData SphericalDistribute (int num_rays, float up_fov, float down_fov)
static HF_STATUS C_DeleteResultVector (IntPtr ptr)
Private Member Functions
static HF_STATUS SphereicalViewAnalysisAggregateFlat (IntPtr ERT, [In] float[] node_ptr, int node_size, int max_rays, float upward_fov, float downward_fov, float height, ViewAggregateType AT, ref IntPtr out_scores, ref IntPtr out_scores_ptr, ref int out_scores_size)
static HF_STATUS SphericalViewAnalysisNoAggregateFlat (IntPtr ERT, [In] float[] node_ptr, int node_size, ref int max_rays, float upward_fov, float downward_fov, float height, ref IntPtr out_scores, ref IntPtr out_scores_ptr)
static HF_STATUS SphericalDistribute (ref int num_rays, ref IntPtr out_direction_vector, ref IntPtr out_direction_data, float upward_fov, float downward_fov)
static HF_STATUS DestroyRayResultVector (IntPtr vector_ptr)
Static Private Attributes
const string dll_path = NativeConstants.DLLPath
Detailed Description
Definition at line 14 of file ViewAnalysisNative.cs.
Member Function Documentation
C_DeleteResultVector()
static HF_STATUS HumanFactors.ViewAnalysis.NativeMethods.C_DeleteResultVector (IntPtr ptr) [static], [package]
C_SphericalViewAnalysisAggregate()
static CVectorAndData HumanFactors.ViewAnalysis.NativeMethods.C_SphericalViewAnalysisAggregate (IntPtr ert, IEnumerable< Vector3D > nodes, int ray_count, float upward_fov, float downward_fov, float height, ViewAggregateType AT) [static], [package]
Definition at line 19 of file ViewAnalysisNative.cs.
References HumanFactors.NativeUtils.CVectorAndData.data, HumanFactors.NativeUtils.HelperFunctions.FlattenVectorArray(), HumanFactors.NativeUtils.CVectorAndData.size, HumanFactors.ViewAnalysis.NativeMethods.SphereicalViewAnalysisAggregateFlat(), and HumanFactors.NativeUtils.CVectorAndData.vector.
C_SphericalViewAnalysisNoAggregate()
static CVectorAndData HumanFactors.ViewAnalysis.NativeMethods.C_SphericalViewAnalysisNoAggregate (IntPtr ert, IEnumerable< Vector3D > nodes, int ray_count, float upward_fov, float downward_fov, float height) [static], [package]
Definition at line 53 of file ViewAnalysisNative.cs.
References HumanFactors.NativeUtils.CVectorAndData.data, HumanFactors.NativeUtils.HelperFunctions.FlattenVectorArray(), HumanFactors.NativeUtils.CVectorAndData.size, HumanFactors.NativeUtils.CVectorAndData.size2, HumanFactors.ViewAnalysis.NativeMethods.SphericalViewAnalysisNoAggregateFlat(), and HumanFactors.NativeUtils.CVectorAndData.vector.
DestroyRayResultVector()
static HF_STATUS HumanFactors.ViewAnalysis.NativeMethods.DestroyRayResultVector (IntPtr vector_ptr) [private]
SphereicalViewAnalysisAggregateFlat()
static HF_STATUS HumanFactors.ViewAnalysis.NativeMethods.SphereicalViewAnalysisAggregateFlat (IntPtr ERT, [In] float[] node_ptr, int node_size, int max_rays, float upward_fov, float downward_fov, float height, ViewAggregateType AT, ref IntPtr out_scores, ref IntPtr out_scores_ptr, ref int out_scores_size) [private]
Referenced by HumanFactors.ViewAnalysis.NativeMethods.C_SphericalViewAnalysisAggregate().
SphericalDistribute() [1/2]
static CVectorAndData HumanFactors.ViewAnalysis.NativeMethods.SphericalDistribute (int num_rays, float up_fov, float down_fov) [static], [package]
Definition at line 87 of file ViewAnalysisNative.cs.
References HumanFactors.NativeUtils.CVectorAndData.data, HumanFactors.NativeUtils.CVectorAndData.size, HumanFactors.NativeUtils.CVectorAndData.size2, and HumanFactors.NativeUtils.CVectorAndData.vector.
SphericalDistribute() [2/2]
static HF_STATUS HumanFactors.ViewAnalysis.NativeMethods.SphericalDistribute (ref int num_rays, ref IntPtr out_direction_vector, ref IntPtr out_direction_data, float upward_fov, float downward_fov) [private]
SphericalViewAnalysisNoAggregateFlat()
static HF_STATUS HumanFactors.ViewAnalysis.NativeMethods.SphericalViewAnalysisNoAggregateFlat (IntPtr ERT, [In] float[] node_ptr, int node_size, ref int max_rays, float upward_fov, float downward_fov, float height, ref IntPtr out_scores, ref IntPtr out_scores_ptr) [private]
Referenced by HumanFactors.ViewAnalysis.NativeMethods.C_SphericalViewAnalysisNoAggregate().
Member Data Documentation
dll_path
const string HumanFactors.ViewAnalysis.NativeMethods.dll_path = NativeConstants.DLLPath [static], [private]
Definition at line 16 of file ViewAnalysisNative.cs.
The documentation for this class was generated from the following file:
src/Csharp/packages/viewanalysis/src/ViewAnalysisNative.cs