HumanFactors.Pathfinding.NativeMethods Class Reference
Static Package Functions
static CVectorAndData C_CreatePath (IntPtr graph_ptr, int start, int end, string cost_type)
Generate a path from start to end.
static CVectorAndData[] C_CreatePaths (IntPtr graph_ptr, IEnumerable< int > start, IEnumerable< int > end, string cost_type)
Generate a path from start to end.
static CVectorAndData[] C_AllToAllPaths (IntPtr graph_ptr, int graph_size, string cost_type)
static void C_DestroyPath (IntPtr path_ptr)
Destroy an existing path object.
Private Member Functions
static HF_STATUS DestroyPath (IntPtr path_ptr)
static HF_STATUS CreatePath (IntPtr graph_ptr, int start, int end, string cost_type, ref int out_size, ref IntPtr out_path, ref IntPtr out_data)
static HF_STATUS CreatePaths (IntPtr graph_ptr, [In] int[] start, [In] int[] end, string cost_type, [Out] IntPtr[] out_path_ptr_holder, [Out] IntPtr[] out_path_member_ptr_holder, [Out] int[] out_sizes, int num_paths)
static HF_STATUS CreateAllToAllPaths (IntPtr graph_ptr, string cost_type, [Out] IntPtr[] out_path_ptr_holder, [Out] IntPtr[] out_path_member_ptr_holder, [Out] int[] out_sizes, int num_paths)
Static Private Attributes
const string dll_path = NativeConstants.DLLPath
Detailed Description
Definition at line 17 of file PathfindingNative.cs.
Member Function Documentation
C_AllToAllPaths()
static CVectorAndData [] HumanFactors.Pathfinding.NativeMethods.C_AllToAllPaths (IntPtr graph_ptr, int graph_size, string cost_type) [static], [package]
Definition at line 115 of file PathfindingNative.cs.
References HumanFactors.Pathfinding.NativeMethods.CreateAllToAllPaths().
Referenced by HumanFactors.Pathfinding.ShortestPath.DijkstraAllToAll().
C_CreatePath()
static CVectorAndData HumanFactors.Pathfinding.NativeMethods.C_CreatePath (IntPtr graph_ptr, int start, int end, string cost_type) [static], [package]
Generate a path from start to end.
Returns
A CVectorAndData to the generated path.
Exceptions
System.IndexOutOfRangeException Start or end points were not in the graph
Definition at line 27 of file PathfindingNative.cs.
References HumanFactors.Pathfinding.NativeMethods.CreatePath(), HumanFactors.NativeUtils.CVectorAndData.data, HumanFactors.NativeUtils.CVectorAndData.size, and HumanFactors.NativeUtils.CVectorAndData.vector.
Referenced by HumanFactors.Pathfinding.ShortestPath.DijkstraShortestPath().
C_CreatePaths()
static CVectorAndData [] HumanFactors.Pathfinding.NativeMethods.C_CreatePaths (IntPtr graph_ptr, IEnumerable< int > start, IEnumerable< int > end, string cost_type) [static], [package]
Generate a path from start to end.
Returns
An array of CVectorAndData to the generated paths.
Exceptions
System.IndexOutOfRangeException Start or end points were not in the graph
Definition at line 67 of file PathfindingNative.cs.
References HumanFactors.Pathfinding.NativeMethods.CreatePaths().
Referenced by HumanFactors.Pathfinding.ShortestPath.DijkstraShortestPathMulti().
C_DestroyPath()
static void HumanFactors.Pathfinding.NativeMethods.C_DestroyPath (IntPtr path_ptr) [static], [package]
Destroy an existing path object.
Referenced by HumanFactors.Pathfinding.Path.ReleaseHandle().
CreateAllToAllPaths()
static HF_STATUS HumanFactors.Pathfinding.NativeMethods.CreateAllToAllPaths (IntPtr graph_ptr, string cost_type, [Out] IntPtr[] out_path_ptr_holder, [Out] IntPtr[] out_path_member_ptr_holder, [Out] int[] out_sizes, int num_paths) [private]
Referenced by HumanFactors.Pathfinding.NativeMethods.C_AllToAllPaths().
CreatePath()
static HF_STATUS HumanFactors.Pathfinding.NativeMethods.CreatePath (IntPtr graph_ptr, int start, int end, string cost_type, ref int out_size, ref IntPtr out_path, ref IntPtr out_data) [private]
Referenced by HumanFactors.Pathfinding.NativeMethods.C_CreatePath().
CreatePaths()
static HF_STATUS HumanFactors.Pathfinding.NativeMethods.CreatePaths (IntPtr graph_ptr, [In] int[] start, [In] int[] end, string cost_type, [Out] IntPtr[] out_path_ptr_holder, [Out] IntPtr[] out_path_member_ptr_holder, [Out] int[] out_sizes, int num_paths) [private]
Referenced by HumanFactors.Pathfinding.NativeMethods.C_CreatePaths().
DestroyPath()
static HF_STATUS HumanFactors.Pathfinding.NativeMethods.DestroyPath (IntPtr path_ptr) [private]
Member Data Documentation
dll_path
const string HumanFactors.Pathfinding.NativeMethods.dll_path = NativeConstants.DLLPath [static], [private]
Definition at line 19 of file PathfindingNative.cs.
The documentation for this class was generated from the following file:
src/Csharp/packages/pathfinding/src/PathfindingNative.cs