HumanFactors.Geometry.NativeMethods Class Reference
Native methods for the Geometry namespace
Package Functions
static HF_STATUS StoreMesh (ref IntPtr out_info, [In] int[] indices, int num_indices, [In] float[] vertices, int num_vertices, string name, int id)
static HF_STATUS DestroyMeshInfo (IntPtr MeshToDestroy)
static HF_STATUS RotateMesh (IntPtr Meshinfo, float xrot, float yrot, float zrot)
Static Package Functions
static IntPtr C_LoadOBJ (string obj_path, float xrot, float yrot, float zrot)
Attempt to load the OBJ at the given filepath. If a rotation is specifed, the obj will be rotated after it is loaded.
static IntPtr C_StoreMesh (IEnumerable< float > vertices, IEnumerable< int > indices, string name, int id)
Store a mesh in managed memory.
static void C_RotateMesh (IntPtr mesh, float xrot, float yrot, float zrot)
Rotate this mesh in C++
Private Member Functions
static HF_STATUS LoadOBJ (string obj_paths, int length, float yrot, float xrot, float zrot, ref IntPtr out_mesh_info)
Loads an OBJ file into meshinfo at the given instance
Static Private Attributes
const string dllpath = NativeConstants.DLLPath
Path to the HumanFactors dll copied from NativeConstants.
Detailed Description
Native methods for the Geometry namespace
Definition at line 19 of file GeometryNative.cs.
Member Function Documentation
C_LoadOBJ()
static IntPtr HumanFactors.Geometry.NativeMethods.C_LoadOBJ (string obj_path, float xrot, float yrot, float zrot) [static], [package]
Attempt to load the OBJ at the given filepath. If a rotation is specifed, the obj will be rotated after it is loaded.
Parameters
obj_path Filepath for the obj to load
xrot Degrees to rotate the mesh on the z axis.
yrot Degrees to rotate the mesh on the y axis.
zrot Degrees to rotate the mesh on the z axis.
Returns
A pointer to a valid instance of meshinfo from C++
Definition at line 36 of file GeometryNative.cs.
References HumanFactors.Geometry.NativeMethods.LoadOBJ().
Referenced by HumanFactors.Geometry.OBJLoader.LoadOBJ().
C_RotateMesh()
static void HumanFactors.Geometry.NativeMethods.C_RotateMesh (IntPtr mesh, float xrot, float yrot, float zrot) [static], [package]
Rotate this mesh in C++
C_StoreMesh()
static IntPtr HumanFactors.Geometry.NativeMethods.C_StoreMesh (IEnumerable< float > vertices, IEnumerable< int > indices, string name, int id) [static], [package]
Store a mesh in managed memory.
Returns
A pointer to the mesh in unmanaged memory
Exceptions
InvalidMeshException That did not represent a valid mesh
Definition at line 53 of file GeometryNative.cs.
References HumanFactors.Geometry.NativeMethods.StoreMesh().
DestroyMeshInfo()
static HF_STATUS HumanFactors.Geometry.NativeMethods.DestroyMeshInfo (IntPtr MeshToDestroy) [package]
Referenced by HumanFactors.Geometry.MeshInfo.ReleaseHandle().
LoadOBJ()
static HF_STATUS HumanFactors.Geometry.NativeMethods.LoadOBJ (string obj_paths, int length, float yrot, float xrot, float zrot, ref IntPtr out_mesh_info) [private]
Loads an OBJ file into meshinfo at the given instance
Referenced by HumanFactors.Geometry.NativeMethods.C_LoadOBJ().
RotateMesh()
static HF_STATUS HumanFactors.Geometry.NativeMethods.RotateMesh (IntPtr Meshinfo, float xrot, float yrot, float zrot) [package]
StoreMesh()
static HF_STATUS HumanFactors.Geometry.NativeMethods.StoreMesh (ref IntPtr out_info, [In] int[] indices, int num_indices, [In] float[] vertices, int num_vertices, string name, int id) [package]
Referenced by HumanFactors.Geometry.NativeMethods.C_StoreMesh().
Member Data Documentation
dllpath
const string HumanFactors.Geometry.NativeMethods.dllpath = NativeConstants.DLLPath [static], [private]
Path to the HumanFactors dll copied from NativeConstants.
Definition at line 25 of file GeometryNative.cs.
The documentation for this class was generated from the following file:
src/Csharp/packages/geometry/src/GeometryNative.cs