HumanFactors.NativeUtils.HelperFunctions Class Reference
Contains some functions useful for converting data for interop.
Static Public Member Functions
static float[] FlattenVectorArray (IEnumerable< Vector3D > vectors)
Convert a vector array into an array of floats.
static Vector3D[] FloatArrayToVectorArray (float[] float_array, bool[] result_array)
Convert a flat array of floats into a vector of points where result_array is true.
Static Package Functions
static void MarshalUnmananagedArray2Struct< T > (IntPtr unmanagedArray, int length, out T[] mangagedArray)
Copy an array of structs from unmanaged memory into managed memory
Detailed Description
Contains some functions useful for converting data for interop.
Remarks
These functions are frequently called internally in multiple HumanFactors namespaces.
Definition at line 88 of file NativeUtils.cs.
Member Function Documentation
FlattenVectorArray()
static float [] HumanFactors.NativeUtils.HelperFunctions.FlattenVectorArray (IEnumerable< Vector3D > vectors) [static]
Convert a vector array into an array of floats.
Parameters
vectors The array of vectors to convert
Returns
An array of floats 3x as big as the array of vectors.
Remarks
Useful for preparing for Pinvoke
Definition at line 120 of file NativeUtils.cs.
Referenced by HumanFactors.VisibilityGraph.NativeMethods.C_AllToAllVisibilityGraph(), HumanFactors.RayTracing.NativeMethods.C_FireOcclusionRays(), HumanFactors.VisibilityGraph.NativeMethods.C_GroupToGroupVisibilityGraph(), HumanFactors.RayTracing.NativeMethods.C_IntersectRays(), HumanFactors.ViewAnalysis.NativeMethods.C_SphericalViewAnalysisAggregate(), and HumanFactors.ViewAnalysis.NativeMethods.C_SphericalViewAnalysisNoAggregate().
FloatArrayToVectorArray()
static Vector3D [] HumanFactors.NativeUtils.HelperFunctions.FloatArrayToVectorArray (float[] float_array, bool[] result_array) [static]
Convert a flat array of floats into a vector of points where result_array is true.
Parameters
float_array The array of floats. Every 3 values should correspond to a single Vector3D
result_array Array of booleans where if false the Vector3D at this index will be set to null. Otherwise, it will be converted from the float array.
Returns
An array of Vector3D where every 3 floats in float_array is a single vector3D.
Remarks
This function is used frequently internally to handle results of ray intersections.
Exceptions
ArgumentException The number of elements in result_array is not equal to the number of elements in float_array / 3
Definition at line 154 of file NativeUtils.cs.
Referenced by HumanFactors.RayTracing.NativeMethods.C_IntersectPoints().
MarshalUnmananagedArray2Struct< T >()
static void HumanFactors.NativeUtils.HelperFunctions.MarshalUnmananagedArray2Struct< T > (IntPtr unmanagedArray, int length, out T[] mangagedArray) [static], [package]
Copy an array of structs from unmanaged memory into managed memory
Template Parameters
T The type of struct to copy
Parameters
unmanagedArray Pointer to the array in unmanaged memory.
length Number of elements in the unmanaged array.
mangagedArray An output parameter for the managed array to write to. This will be resized.
Returns
The new array of structs in managed memory.
Type Constraints
T : struct
Definition at line 96 of file NativeUtils.cs.
The documentation for this class was generated from the following file:
src/Csharp/packages/base/src/NativeUtils.cs