HumanFactors.SpatialStructures.NativeMethods Class Reference
Static Package Functions
static IntPtr C_CreateGraph ()
static void C_AddEdge (IntPtr graph_ptr, int parent_id, int child_id, float score, string cost_type)
static void C_AddEdge (IntPtr graph_ptr, Vector3D parent, Vector3D child, float cost, string cost_type)
static void C_DestroyGraph (IntPtr graph_ptr)
static int C_GetNodeID (IntPtr graph_ptr, float x, float y, float z)
static CSRInfo C_GetCSRPointers (IntPtr graph_ptr, string cost_type)
static CVectorAndData C_GetNodes (IntPtr graph_ptr)
static CVectorAndData C_AggregateEdgeCosts (IntPtr graph_ptr, bool directed, GraphEdgeAggregation agg_type, string cost_type)
static float C_GetEdgeCost (IntPtr graph_ptr, int parent, int child, string cost_type)
static void C_AddNodeAttributes (IntPtr graph_ptr, string attribute, int[] ids, string[] scores)
static unsafe string[] C_GetNodeAttributes (IntPtr graph_ptr, string attribute, int num_nodes)
static int C_GetGraphSize (IntPtr graph_ptr)
static void C_DestroyNodeVector (IntPtr node_ptr)
static void C_DestroyFloatVector (IntPtr float_vector)
static void C_CompressGraph (IntPtr graph)
static void C_CalculateAndStoreCrossSlope (IntPtr graph)
static void C_CalculateAndStoreEnergyExpenditure (IntPtr graph)
static void C_ClearAttributeType (IntPtr graph, string attribute_name)
Private Member Functions
static HF_STATUS GetNodes (IntPtr graph, ref IntPtr out_vector_ptr, ref IntPtr out_data_ptr)
static HF_STATUS GetSizeOfNodeVector (IntPtr node_vector, ref int out_size)
static HF_STATUS GetCSRPointers (IntPtr Graph, ref int out_nnz, ref int out_num_rows, ref int out_num_cols, ref IntPtr out_data_ptr, ref IntPtr out_inner_indices_ptr, ref IntPtr out_outer_indices_ptr, string cost_type)
static HF_STATUS Compress (IntPtr graph)
static HF_STATUS AggregateCosts (IntPtr graph, GraphEdgeAggregation agg, bool directed, string cost_type, ref IntPtr out_vector_ptr, ref IntPtr out_data_ptr)
static HF_STATUS GetNodeID (IntPtr graph, [In] float[] point, ref int out_id)
static HF_STATUS AddEdgeFromNodes (IntPtr Graph, [In] float[] parent, [In] float[] child, float score, string cost_type)
static HF_STATUS AddEdgeFromNodeIDs (IntPtr Graph, int parent, int child, float score, string cost_type)
static HF_STATUS AggregateCosts (IntPtr graph, int agg, bool directed, ref IntPtr out_vector_ptr, ref IntPtr out_float_ptr)
static HF_STATUS GetAllNodesFromGraph (IntPtr graph_ptr, ref IntPtr out_vector_ptr, ref IntPtr out_data_ptr)
static HF_STATUS CreateGraph ([In] float[] nodes, int num_nodes, ref IntPtr out_graph)
static HF_STATUS DestroyGraph (IntPtr graph_to_destroy)
static HF_STATUS DestroyNodes (IntPtr list_to_destroy)
static HF_STATUS DestroyFloatVector (IntPtr float_vector)
static HF_STATUS GetEdgeCost (IntPtr graph_ptr, int parent_id, int child_id, string cost_type, ref float out_float)
static HF_STATUS CalculateAndStoreCrossSlope (IntPtr graph_pointer)
static HF_STATUS CalculateAndStoreEnergyExpenditure (IntPtr graph_pointer)
static HF_STATUS AddNodeAttributes (IntPtr g, int[] ids, string attribute, string[] scores, int num_nodes)
static unsafe HF_STATUS DeleteScoreArray (IntPtr[] scores_to_delete, int num_char_arrays)
static HF_STATUS GetNodeAttributes (IntPtr g, string attribute, IntPtr[] out_scores, ref int out_score_size)
static HF_STATUS ClearAttributeType (IntPtr g, string attribute)
static HF_STATUS GetSizeOfGraph (IntPtr graph_ptr, ref int out_size)
Detailed Description
Definition at line 65 of file SpatialStructuresNative.cs.
Member Function Documentation
AddEdgeFromNodeIDs()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.AddEdgeFromNodeIDs (IntPtr Graph, int parent, int child, float score, string cost_type) [private]
AddEdgeFromNodes()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.AddEdgeFromNodes (IntPtr Graph, [In] float[] parent, [In] float[] child, float score, string cost_type) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_AddEdge().
AddNodeAttributes()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.AddNodeAttributes (IntPtr g, int[] ids, string attribute, string[] scores, int num_nodes) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_AddNodeAttributes().
AggregateCosts() [1/2]
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.AggregateCosts (IntPtr graph, GraphEdgeAggregation agg, bool directed, string cost_type, ref IntPtr out_vector_ptr, ref IntPtr out_data_ptr) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_AggregateEdgeCosts().
AggregateCosts() [2/2]
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.AggregateCosts (IntPtr graph, int agg, bool directed, ref IntPtr out_vector_ptr, ref IntPtr out_float_ptr) [private]
C_AddEdge() [1/2]
static void HumanFactors.SpatialStructures.NativeMethods.C_AddEdge (IntPtr graph_ptr, int parent_id, int child_id, float score, string cost_type) [static], [package]
C_AddEdge() [2/2]
static void HumanFactors.SpatialStructures.NativeMethods.C_AddEdge (IntPtr graph_ptr, Vector3D parent, Vector3D child, float cost, string cost_type) [static], [package]
Definition at line 82 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.AddEdgeFromNodes(), and HumanFactors.Vector3D.ToArray().
C_AddNodeAttributes()
static void HumanFactors.SpatialStructures.NativeMethods.C_AddNodeAttributes (IntPtr graph_ptr, string attribute, int[] ids, string[] scores) [static], [package]
Definition at line 207 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.AddNodeAttributes().
C_AggregateEdgeCosts()
static CVectorAndData HumanFactors.SpatialStructures.NativeMethods.C_AggregateEdgeCosts (IntPtr graph_ptr, bool directed, GraphEdgeAggregation agg_type, string cost_type) [static], [package]
Definition at line 160 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.AggregateCosts(), HumanFactors.NativeUtils.CVectorAndData.data, and HumanFactors.NativeUtils.CVectorAndData.vector.
Referenced by HumanFactors.SpatialStructures.Graph.AggregateEdgeCosts().
C_CalculateAndStoreCrossSlope()
static void HumanFactors.SpatialStructures.NativeMethods.C_CalculateAndStoreCrossSlope (IntPtr graph) [static], [package]
Referenced by HumanFactors.SpatialStructures.CostAlgorithms.CalculateAndStoreCrossSlope().
C_CalculateAndStoreEnergyExpenditure()
static void HumanFactors.SpatialStructures.NativeMethods.C_CalculateAndStoreEnergyExpenditure (IntPtr graph) [static], [package]
Referenced by HumanFactors.SpatialStructures.CostAlgorithms.CalculateAndStoreEnergyExpenditure().
C_ClearAttributeType()
static void HumanFactors.SpatialStructures.NativeMethods.C_ClearAttributeType (IntPtr graph, string attribute_name) [static], [package]
Referenced by HumanFactors.SpatialStructures.Graph.ClearNodeAttributes().
C_CompressGraph()
static void HumanFactors.SpatialStructures.NativeMethods.C_CompressGraph (IntPtr graph) [static], [package]
C_CreateGraph()
static IntPtr HumanFactors.SpatialStructures.NativeMethods.C_CreateGraph () [static], [package]
Definition at line 67 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.CreateGraph().
C_DestroyFloatVector()
static void HumanFactors.SpatialStructures.NativeMethods.C_DestroyFloatVector (IntPtr float_vector) [static], [package]
C_DestroyGraph()
static void HumanFactors.SpatialStructures.NativeMethods.C_DestroyGraph (IntPtr graph_ptr) [static], [package]
Referenced by HumanFactors.SpatialStructures.Graph.ReleaseHandle().
C_DestroyNodeVector()
static void HumanFactors.SpatialStructures.NativeMethods.C_DestroyNodeVector (IntPtr node_ptr) [static], [package]
Referenced by HumanFactors.SpatialStructures.NodeList.ReleaseHandle().
C_GetCSRPointers()
static CSRInfo HumanFactors.SpatialStructures.NativeMethods.C_GetCSRPointers (IntPtr graph_ptr, string cost_type) [static], [package]
Definition at line 115 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.GetCSRPointers().
Referenced by HumanFactors.SpatialStructures.Graph.CompressToCSR().
C_GetEdgeCost()
static float HumanFactors.SpatialStructures.NativeMethods.C_GetEdgeCost (IntPtr graph_ptr, int parent, int child, string cost_type) [static], [package]
Definition at line 187 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.GetEdgeCost().
Referenced by HumanFactors.SpatialStructures.Graph.GetCost().
C_GetGraphSize()
static int HumanFactors.SpatialStructures.NativeMethods.C_GetGraphSize (IntPtr graph_ptr) [static], [package]
Definition at line 241 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.GetSizeOfGraph().
C_GetNodeAttributes()
static unsafe string [] HumanFactors.SpatialStructures.NativeMethods.C_GetNodeAttributes (IntPtr graph_ptr, string attribute, int num_nodes) [static], [package]
Definition at line 215 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.DeleteScoreArray(), and HumanFactors.SpatialStructures.NativeMethods.GetNodeAttributes().
Referenced by HumanFactors.SpatialStructures.Graph.GetNodeAttributes().
C_GetNodeID()
static int HumanFactors.SpatialStructures.NativeMethods.C_GetNodeID (IntPtr graph_ptr, float x, float y, float z) [static], [package]
Definition at line 106 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.GetNodeID().
C_GetNodes()
static CVectorAndData HumanFactors.SpatialStructures.NativeMethods.C_GetNodes (IntPtr graph_ptr) [static], [package]
Definition at line 143 of file SpatialStructuresNative.cs.
References HumanFactors.SpatialStructures.NativeMethods.GetAllNodesFromGraph(), and HumanFactors.SpatialStructures.NativeMethods.GetSizeOfNodeVector().
CalculateAndStoreCrossSlope()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.CalculateAndStoreCrossSlope (IntPtr graph_pointer) [private]
CalculateAndStoreEnergyExpenditure()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.CalculateAndStoreEnergyExpenditure (IntPtr graph_pointer) [private]
ClearAttributeType()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.ClearAttributeType (IntPtr g, string attribute) [private]
Compress()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.Compress (IntPtr graph) [private]
CreateGraph()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.CreateGraph ([In] float[] nodes, int num_nodes, ref IntPtr out_graph) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_CreateGraph().
DeleteScoreArray()
static unsafe HF_STATUS HumanFactors.SpatialStructures.NativeMethods.DeleteScoreArray (IntPtr[] scores_to_delete, int num_char_arrays) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_GetNodeAttributes().
DestroyFloatVector()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.DestroyFloatVector (IntPtr float_vector) [private]
DestroyGraph()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.DestroyGraph (IntPtr graph_to_destroy) [private]
DestroyNodes()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.DestroyNodes (IntPtr list_to_destroy) [private]
GetAllNodesFromGraph()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.GetAllNodesFromGraph (IntPtr graph_ptr, ref IntPtr out_vector_ptr, ref IntPtr out_data_ptr) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_GetNodes().
GetCSRPointers()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.GetCSRPointers (IntPtr Graph, ref int out_nnz, ref int out_num_rows, ref int out_num_cols, ref IntPtr out_data_ptr, ref IntPtr out_inner_indices_ptr, ref IntPtr out_outer_indices_ptr, string cost_type) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_GetCSRPointers().
GetEdgeCost()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.GetEdgeCost (IntPtr graph_ptr, int parent_id, int child_id, string cost_type, ref float out_float) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_GetEdgeCost().
GetNodeAttributes()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.GetNodeAttributes (IntPtr g, string attribute, IntPtr[] out_scores, ref int out_score_size) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_GetNodeAttributes().
GetNodeID()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.GetNodeID (IntPtr graph, [In] float[] point, ref int out_id) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_GetNodeID().
GetNodes()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.GetNodes (IntPtr graph, ref IntPtr out_vector_ptr, ref IntPtr out_data_ptr) [private]
GetSizeOfGraph()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.GetSizeOfGraph (IntPtr graph_ptr, ref int out_size) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_GetGraphSize().
GetSizeOfNodeVector()
static HF_STATUS HumanFactors.SpatialStructures.NativeMethods.GetSizeOfNodeVector (IntPtr node_vector, ref int out_size) [private]
Referenced by HumanFactors.SpatialStructures.NativeMethods.C_GetNodes().
The documentation for this class was generated from the following file:
src/Csharp/packages/spatialstructures/src/SpatialStructuresNative.cs