HumanFactors.VisibilityGraph.NativeMethods Class Reference
Static Package Functions
static IntPtr C_AllToAllVisibilityGraph (IntPtr bvh, IEnumerable< Vector3D > nodes, float height, bool directed=false)
static IntPtr C_GroupToGroupVisibilityGraph (IntPtr bvh, IEnumerable< Vector3D > group_a, IEnumerable< Vector3D > group_b, float height)
Private Member Functions
static HF_STATUS CreateVisibilityGraphAllToAll (IntPtr ert, [In] float[] nodes, int num_nodes, ref IntPtr out_graph, float height)
static HF_STATUS CreateVisibilityGraphAllToAllUndirected (IntPtr ert, [In] float[] nodes, int num_nodes, ref IntPtr out_graph, float height)
static HF_STATUS CreateVisibilityGraphGroupToGroup (IntPtr ert, [In] float[] group_a, int size_a, [In] float[] group_b, int size_b, ref IntPtr out_graph, float height)
Static Private Attributes
const string dllpath = NativeConstants.DLLPath
Detailed Description
Definition at line 14 of file VisibilityGraphNative.cs.
Member Function Documentation
C_AllToAllVisibilityGraph()
static IntPtr HumanFactors.VisibilityGraph.NativeMethods.C_AllToAllVisibilityGraph (IntPtr bvh, IEnumerable< Vector3D > nodes, float height, bool directed = false) [static], [package]
Definition at line 18 of file VisibilityGraphNative.cs.
References HumanFactors.VisibilityGraph.NativeMethods.CreateVisibilityGraphAllToAll(), HumanFactors.VisibilityGraph.NativeMethods.CreateVisibilityGraphAllToAllUndirected(), and HumanFactors.NativeUtils.HelperFunctions.FlattenVectorArray().
Referenced by HumanFactors.VisibilityGraph.VisibilityGraph.GenerateAllToAll().
C_GroupToGroupVisibilityGraph()
static IntPtr HumanFactors.VisibilityGraph.NativeMethods.C_GroupToGroupVisibilityGraph (IntPtr bvh, IEnumerable< Vector3D > group_a, IEnumerable< Vector3D > group_b, float height) [static], [package]
Definition at line 33 of file VisibilityGraphNative.cs.
References HumanFactors.VisibilityGraph.NativeMethods.CreateVisibilityGraphGroupToGroup(), and HumanFactors.NativeUtils.HelperFunctions.FlattenVectorArray().
Referenced by HumanFactors.VisibilityGraph.VisibilityGraph.GenerateGroupToGroup().
CreateVisibilityGraphAllToAll()
static HF_STATUS HumanFactors.VisibilityGraph.NativeMethods.CreateVisibilityGraphAllToAll (IntPtr ert, [In] float[] nodes, int num_nodes, ref IntPtr out_graph, float height) [private]
Referenced by HumanFactors.VisibilityGraph.NativeMethods.C_AllToAllVisibilityGraph().
CreateVisibilityGraphAllToAllUndirected()
static HF_STATUS HumanFactors.VisibilityGraph.NativeMethods.CreateVisibilityGraphAllToAllUndirected (IntPtr ert, [In] float[] nodes, int num_nodes, ref IntPtr out_graph, float height) [private]
Referenced by HumanFactors.VisibilityGraph.NativeMethods.C_AllToAllVisibilityGraph().
CreateVisibilityGraphGroupToGroup()
static HF_STATUS HumanFactors.VisibilityGraph.NativeMethods.CreateVisibilityGraphGroupToGroup (IntPtr ert, [In] float[] group_a, int size_a, [In] float[] group_b, int size_b, ref IntPtr out_graph, float height) [private]
Referenced by HumanFactors.VisibilityGraph.NativeMethods.C_GroupToGroupVisibilityGraph().
Member Data Documentation
dllpath
const string HumanFactors.VisibilityGraph.NativeMethods.dllpath = NativeConstants.DLLPath [static], [private]
Definition at line 16 of file VisibilityGraphNative.cs.
The documentation for this class was generated from the following file:
src/Csharp/packages/visibilitygraph/src/VisibilityGraphNative.cs