HumanFactors.GraphGenerator.NativeMethods Class Reference
Static Package Functions
static IntPtr C_GenerateGraph (IntPtr bvh, Vector3D start_point, Vector3D spacing, int max_nodes=-1, float up_step=0.2f, float up_slope=20, float down_step=0.2f, float down_slope=20, int max_step_connections=1, int core_count=-1)
Private Member Functions
static HF_STATUS GenerateGraph (IntPtr ray_tracer, [In] float[] start_point, [In] float[] end_point, int MaxNodes, float UpStep, float UpSlope, float DownStep, float DownSlope, int max_step_connection, int core_count, ref IntPtr out_graph)
Static Private Attributes
const string dllpath = NativeConstants.DLLPath
Detailed Description
Definition at line 9 of file GraphGeneratorNative.cs.
Member Function Documentation
C_GenerateGraph()
static IntPtr HumanFactors.GraphGenerator.NativeMethods.C_GenerateGraph (IntPtr bvh, Vector3D start_point, Vector3D spacing, int max_nodes = -1, float up_step = 0.2f, float up_slope = 20, float down_step = 0.2f, float down_slope = 20, int max_step_connections = 1, int core_count = -1) [static], [package]
Definition at line 13 of file GraphGeneratorNative.cs.
References HumanFactors.GraphGenerator.NativeMethods.GenerateGraph(), and HumanFactors.Vector3D.ToArray().
Referenced by HumanFactors.GraphGenerator.GraphGenerator.GenerateGraph().
GenerateGraph()
static HF_STATUS HumanFactors.GraphGenerator.NativeMethods.GenerateGraph (IntPtr ray_tracer, [In] float[] start_point, [In] float[] end_point, int MaxNodes, float UpStep, float UpSlope, float DownStep, float DownSlope, int max_step_connection, int core_count, ref IntPtr out_graph) [private]
Referenced by HumanFactors.GraphGenerator.NativeMethods.C_GenerateGraph().
Member Data Documentation
dllpath
const string HumanFactors.GraphGenerator.NativeMethods.dllpath = NativeConstants.DLLPath [static], [private]
Definition at line 10 of file GraphGeneratorNative.cs.
The documentation for this class was generated from the following file:
src/Csharp/packages/graphgenerator/src/GraphGeneratorNative.cs