Humanfctors.Examples.OverallExamples Class Reference
Public Member Functions
void CompareOutputToExpected (string expected, string actual)
Compares two strings ignoring whitespace.
Graph GenerateExampleGraph ()
void GeneratePathsWithCostAlgorithms ()
void DijkstraShortestPathMulti ()
void DijkstraShortestPathMultiNodes ()
void GenerateAllToAll ()
void GetEdgeCostExample ()
Detailed Description
Definition at line 15 of file overall_examples.cs.
Member Function Documentation
CompareOutputToExpected()
void Humanfctors.Examples.OverallExamples.CompareOutputToExpected (string expected, string actual)
Compares two strings ignoring whitespace.
Definition at line 18 of file overall_examples.cs.
Referenced by Humanfctors.Examples.OverallExamples.DijkstraShortestPathMulti(), Humanfctors.Examples.OverallExamples.DijkstraShortestPathMultiNodes(), Humanfctors.Examples.OverallExamples.GenerateAllToAll(), and Humanfctors.Examples.OverallExamples.GeneratePathsWithCostAlgorithms().
DijkstraShortestPathMulti()
void Humanfctors.Examples.OverallExamples.DijkstraShortestPathMulti ()
[EX_MultiPathFinding]
[EX_MultiPathFinding]
Definition at line 128 of file overall_examples.cs.
References Humanfctors.Examples.OverallExamples.CompareOutputToExpected(), HumanFactors.Pathfinding.ShortestPath.DijkstraShortestPathMulti(), HumanFactors.SpatialStructures.CostAlgorithmNames.ENERGY_EXPENDITURE, and Humanfctors.Examples.OverallExamples.GenerateExampleGraph().
DijkstraShortestPathMultiNodes()
void Humanfctors.Examples.OverallExamples.DijkstraShortestPathMultiNodes ()
[EX_MultiPathFinding_Nodes]
[EX_MultiPathFinding_Nodes]
Definition at line 172 of file overall_examples.cs.
References Humanfctors.Examples.OverallExamples.CompareOutputToExpected(), HumanFactors.Pathfinding.ShortestPath.DijkstraShortestPathMulti(), HumanFactors.SpatialStructures.CostAlgorithmNames.ENERGY_EXPENDITURE, and Humanfctors.Examples.OverallExamples.GenerateExampleGraph().
GenerateAllToAll()
void Humanfctors.Examples.OverallExamples.GenerateAllToAll ()
[EX_Pathfinding_AllToAll]
[EX_Pathfinding_AllToAll]
Definition at line 230 of file overall_examples.cs.
References HumanFactors.SpatialStructures.Graph.AddEdge(), Humanfctors.Examples.OverallExamples.CompareOutputToExpected(), HumanFactors.SpatialStructures.Graph.CompressToCSR(), HumanFactors.Pathfinding.ShortestPath.DijkstraAllToAll(), and HumanFactors.SpatialStructures.Graph.NumNodes().
GenerateExampleGraph()
Graph Humanfctors.Examples.OverallExamples.GenerateExampleGraph ()
[EX_PathFinding_Graph]
[EX_PathFinding_Graph]
Definition at line 26 of file overall_examples.cs.
References HumanFactors.SpatialStructures.CostAlgorithms.CalculateAndStoreEnergyExpenditure(), HumanFactors.SpatialStructures.Graph.CompressToCSR(), HumanFactors.GraphGenerator.GraphGenerator.GenerateGraph(), and HumanFactors.Geometry.OBJLoader.LoadOBJ().
Referenced by Humanfctors.Examples.OverallExamples.DijkstraShortestPathMulti(), Humanfctors.Examples.OverallExamples.DijkstraShortestPathMultiNodes(), and Humanfctors.Examples.OverallExamples.GeneratePathsWithCostAlgorithms().
GeneratePathsWithCostAlgorithms()
void Humanfctors.Examples.OverallExamples.GeneratePathsWithCostAlgorithms ()
[EX_Pathfinding_Setup]
[EX_Pathfinding_Setup]
[EX_Pathfinding_IDS]
[EX_Pathfinding_IDS]
[EX_Pathfinding_Nodes]
[EX_Pathfinding_Nodes]
[EX_Pathfinding_Print]
[EX_Pathfinding_Print]
Definition at line 71 of file overall_examples.cs.
References Humanfctors.Examples.OverallExamples.CompareOutputToExpected(), HumanFactors.Pathfinding.ShortestPath.DijkstraShortestPath(), HumanFactors.SpatialStructures.CostAlgorithmNames.ENERGY_EXPENDITURE, Humanfctors.Examples.OverallExamples.GenerateExampleGraph(), and HumanFactors.NativeUtils.NativeArray< T >.ToString().
GetEdgeCostExample()
void Humanfctors.Examples.OverallExamples.GetEdgeCostExample ()
[Example_GetCost]
[Example_GetCost]
Definition at line 305 of file overall_examples.cs.
References HumanFactors.SpatialStructures.Graph.AddEdge(), HumanFactors.SpatialStructures.Graph.CompressToCSR(), and HumanFactors.SpatialStructures.Graph.GetCost().
The documentation for this class was generated from the following file:
src/Csharp/packages/base/overall_examples.cs