name: Documentation Tests for Doxygen

on:
    push: 
        branches:
            - main
    # pull_request:
    #     branches:    
    #         - dev_stage
    #         - main

jobs:

    doxygen:
        runs-on: windows-2019
        strategy:
            max-parallel: 0
            matrix:
                python-version: [3.8]

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - uses: actions/checkout@v2
          with: # for github push action
            #persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
            fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

        - name: Install windows documentation requirements
          run: |
            $url = "https://www.doxygen.nl/files/doxygen-1.9.5.windows.x64.bin.zip"
            Invoke-WebRequest -Uri $url -OutFile "C:\doxygen.zip"
            
            7z x "C:\doxygen.zip" -o"C:\windows\system32" -y

            doxygen --version`

            choco install graphviz -y

            #sudo apt-get install -y doxygen
            #sudo apt-get install -y graphviz
        
        - name: Build c++ documentation with doxygen
          run: |
            cd src
            doxygen Doxyfile
            ls 
            
        - name: Build c# documentation with doxygen
          run: |
            doxygen Doxyfile_Csharp
            doxygen Doxyfile_Public_CSharp

